### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by dupgit** [flux-framework/flux-sched#1025]
Hello,

[Typos](https://github.com/crate-ci/typos) has found typos in the code. I made a commit for each typo found (I have 53 commits). How do you want me to submit the commits ? I can do one pull request per commit or one pull request with all commits ? differently ?

Regards.

**Comment by jameshcorbett** [comment]
I'd say open a single PR with all the commits and let's take a look. 53 PRs would be too many I think.

**Comment by jameshcorbett** [comment]
Although just FYI this may be rendered unnecessary by #1021.

**Comment by jameshcorbett** [comment]
Closing this issue as PR #1028 was closed. Let me know if you'd like me to reopen.
