### ISSUE TITLE
Resource hoarding support

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-sched#105]
This is to propose resource hoarding support into `flux-sched`.

I want to create automatic tests where 1-node job requests are submitted back to back until the entire node resources within the Flux instance is filled up.

Given how resrc walks the resource tree, scheduling will be deterministic and thus easy to verify automatically. In addition, how quickly `schedsrv` can fill up all of the node resources with such unit jobs can be a good high-level metric for performance/scalability.

But one problem I face is a race: i.e., some earlier jobs can complete before later jobs are scheduled and then, these released nodes can be reused for scheduling these later jobs -- making thing potentially non-determininistic. 

To avoid the race, my tests currently use `sleep k` where k is sufficiently large. Since I won't know how large of the sleep amount will be needed for large scale testing, this scheme is fragile. I thought about other ways like using file IO to ensure earlier jobs don't complete before all of the jobs are scheduled and launched. But these can lead to pretty bad hacks. 

Instead, perhaps simple resource hoarding support within sched will beef up such testing. I can have `hoard=true` option to `schedsrv` module load, which then just simply doesn't release the resources even when a job completes. This way, sched will simply schedule all of the jobs to new nodes not being able to reuse the released node. 

If this support is there, I can use `sleep 0` as a way to quickly fill up the instance resources and stress test the system. Of course, this will only be used for a subset of automatic tests.

Any blind spot in this line of thoughts?

**Comment by lipari** [comment]
That seems ok to me - as a test-only option.  You might want to call it the `sched-once` option.  In any case, it would be easy to implement in schedsrv.c:

```
    case J_RUNNING:
        VERIFY (trans (J_COMPLETE, newstate, &(job->state))
                || trans (J_CANCELLED, newstate, &(job->state)));
        if (sched-once)
            break;
        q_move_to_cqueue (ctx, job);
        if ((resrc_tree_list_release (job->resrc_trees, job->lwj_id))) {
```

**Comment by dongahn** [comment]
OK. Thanks. I agree that `sched-once` sounds better. 

I think your code is on the right spot although I will have to test it to make sure nothing's broken with this option. Also, I will probably want to just not do `resrc_tree_list_release`under this option while still moving the job to the complete queue and generate resource event so that I to-be-added performance metric can measure all of the logic except for resource freeing. (Unless there is no side-effect, that is.)
