### ISSUE TITLE
config.h is missing from source code

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-sched#1050]
Problem: as noted in flux-framework/flux-accounting#365, `config.h` is not included in many of the cpp source modules. It's a good practice in autotools projects to include that right at the top of all (non-vendored) `.c` and `.cpp` source files, immediately following the copyright header, e.g.
```c
#if HAVE_CONFIG_H
#include "config.h"
#endif
```
One reason is that sometimes configure defines macros that affect how other header files are interpreted. That is why it needs to go first.

**Comment by trws** [comment]
As of now, the only thing ever set in that header in this project (except for a macro-based redefinition of malloc that tends to break things) is the GNU_SOURCE macro.  I don't mind adding an include back in for it everywhere, but it's not doing much.  Note that if this header is generating C, and is included in a C++ file, it *must* be wrapped in `extern "C"` to ensure correct linkage if it's possible for it to ever include a declaration of any kind.

**Comment by chu11** [comment]
I think an audit that `#include <flux/core.h>` is also within the `extern "C"` might be worthwhile while we're at it.  A cursory glance is we're doing it correctly in `flux-sched`, but I saw atleast one file in accounting that was missing it.

**Comment by chu11** [comment]
> Note that if this header is generating C, and is included in a C++ file, it must be wrapped in extern "C" to ensure correct linkage if it's possible for it to ever include a declaration of any kind.

I had to think about this.  Is it possible to include like a C declaration in the "config.h"?  I think in practice no, it's mostly just going to be #defines.  Although I suppose it isn't impossible for something to end up in there.

I would lean to "extern C" it just to be on the safe side ... and b/c someone (I assume @dongahn) already wrapped them in most of `flux-sched`.

**Comment by trws** [comment]
Yeah, it's the kind of thing where it *should* always be defines, but it could in principle include extra header files if something is under a different name on some systems or.. 🤷 it's one of those things where doing it doesn't really hurt, but not doing it could cause tricky to diagnose link issues down the line.
