### ISSUE TITLE
reapi ctx parameter is a struct, not an object

### ISSUE THREAD

**Issue by vsoch** [flux-framework/flux-sched#1064]
Per discussion in https://github.com/flux-framework/flux-sched/pull/1062#discussion_r1316805852 I think the "object" reference in the docstring just needs to be a struct. This is an easy fix and I'm just opening the issue here because I'm not sure it's in scope. We will probably chat later about adding it in that PR (or not).

https://github.com/flux-framework/flux-sched/blob/5ede1d4f8ef13a8b864017fa4f390847d88ffacc/resource/reapi/bindings/c/reapi_cli.h#L31

**Comment by trws** [comment]
Is this still a thing?

**Comment by vsoch** [comment]
I think I fixed this, so good to close.
