### ISSUE TITLE
build: configure errors on debian 11 system after cmake changes

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-sched#1066]
Problem: flux-sched `configure` fails on debian system with flux-core installed as a system package

flux-sched built here before, so the normal dependencies should be correct.   I installed the system cmake package which is 3.18.4.
```
 garlick@picl0:~/proj/flux-sched$ ./configure
-- VER 0.28.0-60-gcc781dd3
-- The CXX compiler identification is GNU 10.2.1
-- The C compiler identification is GNU 10.2.1
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/lib/ccache/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/lib/ccache/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Building flux-sched version 0.28.0-60-gcc781dd3
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- flux found in PATH and no specific FLUX_CORE_PREFIX specified, using /usr
-- Checking for module 'flux-core'
--   Found flux-core, version 0.54.0
-- Checking for module 'flux-hostlist'
--   Found flux-hostlist, version 0.54.0
-- Checking for module 'flux-idset'
--   Found flux-idset, version 0.54.0
-- Checking for module 'flux-optparse'
--   Found flux-optparse, version 0.54.0
-- Checking for module 'flux-pmi'
--   Found flux-pmi, version 0.54.0
-- Checking for module 'flux-schedutil'
--   Found flux-schedutil, version 0.54.0
-- Checking for module 'flux-taskmap'
--   Found flux-taskmap, version 0.54.0
-- flux core found and no specific prefix specified, using /usr
CMake Error at CMakeLists.txt:73 (find_package):
  find_package called with invalid argument "3.6...<4.0"


-- Checking for module 'yaml-cpp'
--   Found yaml-cpp, version 0.6.3
-- Checking for module 'libedit'
--   Found libedit, version 3.1
-- Checking for module 'libczmq>=3.0.0'
--   Found libczmq, version 4.2.1
-- Checking for module 'hwloc>=1.11.1'
--   Found hwloc, version 2.4.1
-- Checking for module 'jansson>=2.10'
--   Found jansson, version 2.13.1
-- Checking for module 'uuid'
--   Found uuid, version 2.36.1
-- Found Boost: /usr/lib/aarch64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake (found suitable version "1.74.0", minimum required is "1.50") found components: system filesystem graph regex 
-- Boost version: 1.74.0
CMake Error at CMakeLists.txt:122 (message):
  Python module yaml not found or version too low, need 3.10 got
Call Stack (most recent call first):
  CMakeLists.txt:165 (flux_find_python_module)


-- Configuring incomplete, errors occurred!
See also "/nfshome/garlick/proj/flux-sched/CMakeFiles/CMakeOutput.log".
```
Further tries yield shortened output:
```
 garlick@picl0:~/proj/flux-sched$ ./configure
-- VER 0.28.0-60-gcc781dd3
-- Building flux-sched version 0.28.0-60-gcc781dd3
CMake Error at CMakeLists.txt:73 (find_package):
  find_package called with invalid argument "3.6...<4.0"


-- Boost version: 1.74.0
CMake Error at CMakeLists.txt:122 (message):
  Python module yaml not found or version too low, need 3.10 got
Call Stack (most recent call first):
  CMakeLists.txt:165 (flux_find_python_module)


-- Configuring incomplete, errors occurred!
See also "/nfshome/garlick/proj/flux-sched/CMakeFiles/CMakeOutput.log".
```
See also: [CMakeOutput.log](https://github.com/flux-framework/flux-sched/files/12551535/CMakeOutput.log)

**Comment by grondo** [comment]
@trws any ideas here?

**Comment by trws** [comment]
Vanessa ran into a slightly similar issue last night, what version of cmake is this? I wonder if I'm accidentally using a newer language construct than what I set the cmake base requirement to, because it looks like an out of date cmake problem.

**Comment by trws** [comment]
And I just saw it's there, sorry, let me poke at this for a minute.

**Comment by trws** [comment]
Darn it, that's exactly what it is.  The version range check in find_package requires cmake version 3.19 or higher. I'll see what I can do about that, but the short version for now is using cmake 3.19 or higher should resolve it.

**Comment by grondo** [comment]
Hm, how did you get this to work on Debian 11 which has cmake 3.18.4? Or did we inadvertently drop support for that release? (Note that is the current release for raspbian running on our pi clusters)

**Comment by trws** [comment]
We never tested on Debian 11 in CI. I added support for Debian 12 in addition to our Ubuntu focal and Jammy containers, and since I was doing Bionic when I set the cmake stuff up, I just grabbed a binary cmake for basically all of them which is a newer version.  A debian 11 container using the same dockerfile as our bookworm container should work just fine, except for the python{,3}-yaml rename.  I remember testing with lower cmakes, but must not have after changing the version matching for python.  I think I can fix it so it will work with 3.18, but I have to think through how to get us the correct version constraint without the convenience syntax (haven't had to do it in a good while).

**Comment by trws** [comment]
It's that INTERFACE libraries didn't support source files to represent header-only libraries at one point, so it's failing on the way I set up yggdrasil.  That apparently is a 3.19 feature, the equivalent would be to swap the current add_library call with:

```cmake
add_library(yggdrasil INTERFACE)
target_include_directories(yggdrasil INTERFACE .)
```

Or at least something close to that.  It does make me wonder how worthwhile it is to support cmake < 3.20 though.  We're past that as default on RHEL8 at this point, for example.

**Comment by grondo** [comment]
Unfortunately the current version of raspbian is based on Debian 11 with cmake 3.18, so if we want to support pi clusters it might be nice to get that version working somehow. At least 3 of us core developers are using our rpi clusters for development...

**Comment by grondo** [comment]
> the equivalent would be to swap the current add_library call with:

Yes! That worked. I can build on raspbian now with the simple diff:
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 6c299b01..c37e0154 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -70,7 +70,7 @@ endif()
 if(DEFINED ENV{PYTHON})
   set(Python_EXECUTABLE $ENV{PYTHON} CACHE FILEPATH "")
 endif()
-find_package(Python 3.6...<4.0 COMPONENTS Interpreter Development REQUIRED) # 3.6 or higher
+find_package(Python 3.6 COMPONENTS Interpreter Development REQUIRED) # 3.6 or higher
 execute_process(
   COMMAND "${Python_EXECUTABLE}" -c "import sysconfig as sc; print(sc.get_path('purelib', vars={'base':'${CMAKE_INSTALL_PREFIX}'}))"
   OUTPUT_VARIABLE PYTHON_INSTALL_SITELIB
diff --git a/src/common/c++wrappers/CMakeLists.txt b/src/common/c++wrappers/CMakeLists.txt
index 2e0aec23..0bdf60d6 100644
--- a/src/common/c++wrappers/CMakeLists.txt
+++ b/src/common/c++wrappers/CMakeLists.txt
@@ -1,2 +1,3 @@
-add_library(cppwrappers INTERFACE eh_wrapper.hpp)
+add_library(cppwrappers INTERFACE)
+target_include_directories(cppwrappers INTERFACE .)
 add_subdirectory( test )
diff --git a/src/common/yggdrasil/CMakeLists.txt b/src/common/yggdrasil/CMakeLists.txt
index 17efca8a..e1a5757d 100644
--- a/src/common/yggdrasil/CMakeLists.txt
+++ b/src/common/yggdrasil/CMakeLists.txt
@@ -1,15 +1,3 @@
 # NOTE: despite the .cpp files this is a header-only library
-add_library(
-  yggdrasil
-  INTERFACE
-  util.hpp
-  tree_iterator.hpp
-  tree_iterator.cpp
-  size_holder.hpp
-  rbtree.hpp
-  rbtree.cpp
-  options.hpp
-  debug.hpp
-  bst.hpp
-  bst.cpp
-  )
+add_library( yggdrasil INTERFACE )
+target_include_directories(yggdrasil INTERFACE .)
```


Regarding the Python version, isn't checking for >= 3.6 sufficient, since there is no Python 4.0 and a quick google search indicates there likely never may be one....

**Comment by trws** [comment]
Yeah if that’s enough I’m good with it. Doing >3.6 should be sufficient too. I asked mainly because I was concerned we’d keep running into more, but just these two should be no problem. Might need a bit of a tweak for the yggdrasil stuff to get handled right by tooling still but that’s no problem.

**Comment by grondo** [comment]
Thanks @trws. Maybe I'll propose a PR with the above diff and you can suggest changes directly?

**Comment by trws** [comment]
That would be fantastic. If you haven’t had time, I’ll see if I can put it together when I get to the meeting this morning (being +8 hours offset, it might end up easier), will test it and see if I can add a 3.18 cmake into CI while I’m at it.

---
Sent from Workspace ONE Boxer<https://whatisworkspaceone.com/boxer>
On September 13, 2023 at 9:36:48 PM GMT+1, Mark Grondona ***@***.***> wrote:

Thanks @trws<https://urldefense.us/v3/__https://github.com/trws__;!!G2kpM7uM-TzIFchu!ygTd6mrlOSLCX9FNXwHQ6QcKo4x-kYvndtn_kKPtJ7klMKZ1aUGRvUNeZWpDXhR3ElJ1abm3vDtOYMo-MKEht3yO3Wo$>. Maybe I'll propose a PR with the above diff and you can suggest changes directly?
