### ISSUE TITLE
build: don't install grug2dot and resource-query

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-sched#1089]
Problem: I noticed when reviewing #1082 that these programs which were tagged `noinst` under automake are now being installed:
```
-rwxr-xr-x root/root     35392 2023-09-29 16:04 ./usr/bin/grug2dot
-rwxr-xr-x root/root    495480 2023-09-29 16:04 ./usr/bin/resource-query
```

**Comment by trws** [comment]
I'll take care of this in my dependency cleanup PR, will be up shortly.
