### ISSUE TITLE
Quick start container broken (module not found)

### ISSUE THREAD

**Issue by sgundry** [flux-framework/flux-sched#1099]
The first quick start step is broken: https://flux-framework.readthedocs.io/en/latest/tutorials/containers/flux-sched-container.html

 Running on Ubuntu 22.04:

```
$ docker run -ti fluxrm/flux-sched:latest
Oct 06 02:11:37.348654 broker.err[0]: rc1.0: flux-module: load sched-fluxion-resource: module not found in search path
Oct 06 02:11:37.349482 broker.err[0]: rc1.0: /etc/flux/rc1 Exited (rc=1) 4.8s
```

```
$ docker image ls | grep fluxrm
fluxrm/flux-sched                                         latest    0dd6172688fa   33 hours ago    2.13GB
```

Guessing a path issue: 
```
$ docker run -ti --entrypoint bash fluxrm/flux-sched:latest
 fluxuser@9112d7d31b1e:~$ flux module list
flux-module: flux_open: No such file or directory
```

**Comment by grondo** [comment]
Apparently 54ba3ac75951129a134b0234156f4c82c7b6fb01 did not fix this issue, and fluxion modules are still being installed to `/usr/lib/x86_64-linux-gnu/flux/moduls` even though the flux-core module dir is `/usr/lib/flux/modules`.

I may not have time to look at this until Monday.

In the meantime, a workaround is to export `FLUX_MODULE_PATH=/usr/lib/x86_64-linux-gnu/flux/` and ensure this gets passed into the docker container.

**Comment by grondo** [comment]
> In the meantime, a workaround is to export FLUX_MODULE_PATH=/usr/lib/x86_64-linux-gnu/flux/ and ensure this gets passed into the docker container.

Or, if you don't need the Fluxion scheduler, you can run with the `fluxrm/flux-core` docker image...

**Comment by grondo** [comment]
Ah, this must be because the `configure` wrapper script is being used here as `./configure --prefix=/usr`.

Not sure the correct fix at this point. Maybe always overriding `libdir` to flux-core's libdir is warranted.
