### ISSUE TITLE
scheduling throughput degrades linearly and needs further investigation

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-sched#111]
This is just to have a placeholder to further investigate job scheduling and launching performance. Using a variant of one of the new test cases I've added (`t/t1003-stress.t`), it seems the job scheduling and launching throughput performance degrades linearly:

The testing configuration was with 4 brokers, each reloading a fake full cab xml file. Then, the script submit/schedule/launch 16-way `sleep 0` jobs. It took linearly longer time to complete 1000 jobs at a time. 

I will validate/verify this further. But it seems clear we will need a better perf analysis. I plan to add some instrumentation so that I can apply a critical path analysis for various configurations. This may be the same issue that Tom has been seeing - but having a breakdown through CPA should be insightful.

```
cab690{dahn}43: cat begin.1 
Mon Jan 18 05:54:55 UTC 2016
cab690{dahn}44: cat end.1
Mon Jan 18 05:56:49 UTC 2016
=> 1 min 54 seconds  (115 seconds)

cab690{dahn}45: cat begin.2
Mon Jan 18 05:56:49 UTC 2016
cab690{dahn}46: cat end.2
Mon Jan 18 06:02:00 UTC 2016
=> 5 min 11 seconds  (311 seconds)

cab690{dahn}48: cat begin.3 
Mon Jan 18 06:02:01 UTC 2016
cab690{dahn}49: cat end.3 
Mon Jan 18 06:11:22 UTC 2016
=> 9 min 21 seconds (561 seconds)


cab690{dahn}50: cat begin.4 
Mon Jan 18 06:11:23 UTC 2016
cab690{dahn}51: cat end.4 
Mon Jan 18 06:25:28 UTC 2016
=> 14 min 5 seconds (845 seconds)

```

**Comment by grondo** [comment]
I have also seen slowdown in time to launch and run jobs without any scheduling, so this may be a problem solely with the wreck prototype. I kind of assumed the slowdown was due to increased time for kvs_commit and other kvs operations with lots of directories under `lwj.`. However, I never really tried to pin it down so I could be mistaken. (but anyway, problem has been noted in flux-core without sched...)

**Comment by dongahn** [comment]
Thanks @grondo. I think a critical path analysis should show what are the performance dominant factors as we vary different things (e.g., job geometry and scales, job counts etc). I have some idea and experiences in this area and try to make some progress.

**Comment by dongahn** [comment]
This is handled with @grondo's hierarchical job data schema work.
