### ISSUE TITLE
Failed to create timer thread: operation not permitted (docker jammy)

### ISSUE THREAD

**Issue by vsoch** [flux-framework/flux-sched#1112]
Just pulled a fresh `fluxrm/flux-sched:jammy` for some late night nonsense, here is the layer metadata:

```console
2af53f625c48: Pull complete 
Digest: sha256:256105d1ec6ddb199d0da8edf434aaa109340b77c546ef67bc350b1c598c26d4
Status: Downloaded newer image for fluxrm/flux-sched:jammy
```
The error when I shell in:
```bash
$ docker run -it fluxrm/flux-sched:jammy 
munged: Error: Failed to create timer thread: Operation not permitted
flux-broker: load_module connector-local: error starting connector-local module: Operation not permitted
```
That doesn't let me even enter the container, giving it bash does work:

```bash
$ docker run -it fluxrm/flux-sched:jammy bash
munged: Error: Failed to create timer thread: Operation not permitted
 fluxuser@c64faec21a55:~$ flux resource list
```
But no go on starting an instance (and note I tried `flux resource list` before this anticipating the entrypoint would:
```bash
 fluxuser@c64faec21a55:~$ flux start --test-size=4
flux-start: flux_exec: Operation not permitted
```
I also tried as root to test to see if it was a permission (owner) error, but got the same result. So possibly a chmod (executable) error? My previous focal pulled on this machine works OK:

```bash
$ docker run -it fluxrm/flux-sched:focal
ƒ(s=1,d=0) fluxuser@4468a7d9f7a6:~$ 
```
Although I haven't pulled a recent build (can tomorrow if you like)! I thought it might be my older machine, but it's strange the previous one works. I can use focal for the time being, but wanted to bring this to your attention in case it makes sense. Thanks!

**Comment by grondo** [comment]
FWIW, I can't reproduce this:
```
 grondo@asp:~$ docker run -ti fluxrm/flux-sched:jammy flux resource list
flux-resource: ERROR: Unable to connect to Flux: broker socket /run/flux/local was not found
 grondo@asp:~$ docker run -ti fluxrm/flux-sched:jammy
ƒ(s=1,d=0) fluxuser@0235b9093f37:~$ flux resource list
     STATE NNODES   NCORES    NGPUS NODELIST
      free      1        4        0 0235b9093f37
 allocated      0        0        0 
      down      0        0        0 
```

In your case, it appears processes are not able to create new pthreads with an `EPERM` error. The [pthread_create(3)](https://man7.org/linux/man-pages/man3/pthread_create.3.html) manual indicates that this `errno` means:

> EPERM  No permission to set the scheduling policy and parameters specified in attr.

maybe your instance of docker has some kind of limits set which the processes within the container cannot escape? I know the broker calls `pthread_create()` without any `attr` set, so your docker is somehow limiting the creation of pthreads with the default attributes? I don't know how this could happen.

**Comment by grondo** [comment]
Ah, could it be https://github.com/moby/moby/issues/42680?

**Comment by vsoch** [comment]
Yeah it could be an old version of docker - let me test on a newer machine.

**Comment by vsoch** [comment]
No issue with newer docker (on fedora!) arg, sorry for the noise (I'll update docker on my dinner computer tonight)! This issue (if found via search) might still be helpful for others. For context, here is a working docker version:

````
docker version
Client: Docker Engine - Community
 Version:           23.0.1
 API version:       1.42
 Go version:        go1.19.5
 Git commit:        a5ee5b1
 Built:             Thu Feb  9 19:49:42 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.1
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.5
  Git commit:       bc3805a
  Built:            Thu Feb  9 19:46:53 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.19
  GitCommit:        1e1ea6e986c6c86565bc33d52e34b81b3e2bc71f
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
````
(going to grab and add the broken one to this thread in a second)...

**Comment by vsoch** [comment]
Yep that fixed it. TLDR: update your docker! Thanks @grondo, closing.
