### ISSUE TITLE
C/C++ for a "MatchSatisfy" or "Satisfies" function

### ISSUE THREAD

**Issue by vsoch** [flux-framework/flux-sched#1118]
From my notes:

> We don't have support for that in the C/C++ API - need Go binding for MatchSatisfy Satisfies.

Basically, we want a function (akin to match) that is just for Satisfies. This might be related to #1115 if the intention here was not to add another argument there, but to create a separate function (and not have to deal with changing the defaults / backwards compatibility stuff). After we have this in C/C++ I should be good to write the Go binding for it.

@zekemorton @milroy hopefully this issue is the easiest one! Thanks for the meeting today, it's fun to learn more / talk about flux-sched.

**Comment by trws** [comment]
What's missing here? I would have expected match_allocate with a "satisfies" match type would do it.

**Comment by vsoch** [comment]
This was written before we had that I think - December 2023, and added February this year! 

https://github.com/flux-framework/flux-sched/commit/19270a36ea4fd73dc1bca480cc27d9ac41799c01

Good to close (and really happy to ahve this) - nice work @zekemorton !
