### ISSUE TITLE
install and package `flux ion-resource`

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-sched#1122]
While debugging and working around #1121 on a production cluster, the `flux ion-resource find` and `set-status` commands were very useful, but this command is not installed with Fluxion, so it had to be used from a build directory.

We should consider installing and packaging this command so it is available for easy future use.

**Comment by grondo** [comment]
tagging @trws, who mentioned he could take a look at this one.

**Comment by trws** [comment]
Ok, so I had forgotten this was classified as a *test script* at the moment.  I don't have an issue with installing it, but wonder a bit if we want to pull the whole thing into a "stable" state, or make it visible to users since it's a pretty owner/admin specific command.  @grondo what's your opinion on handling unstable/experimental interfaces in cases like this?

**Comment by grondo** [comment]
Good question. I believe all the RPCs used by `flux ion-resource` are instance owner only, so this could be consider an admin/plumbing command. It was really just a matter of some subcommands being useful for debugging, like `find` and `set-status`... For an admin/debug tool like that I think we'd consider it "plumbing" and thus be less strict on the interfaces. Probably @garlick and @jameshcorbett should weigh in.

**Comment by jameshcorbett** [comment]
If it isn't visible to users I think it should be OK. I don't know that I ever did anything to ensure the set-status RPC is instance-owner only though...

**Comment by grondo** [comment]
to open an RPC to any user you have to opt-in by setting `FLUX_ROLE_USER` in the flags member here:

https://github.com/flux-framework/flux-sched/blob/fe872c8dc056934e4073b5fb2932335bb69ca73a/resource/modules/resource_match.cpp#L294-L295

Since the flags are set to `0` for all these callbacks they default to instance-owner-only.

**Comment by garlick** [comment]
I'm for including at least for early days of fluxion as we work through some of these problems.  It was quite useful yesterday, with @jameshcorbett's fortuitous additions!

**Comment by trws** [comment]
Works for me.  It does make me wonder if we should consider having an "admin" or "--experimental" or other opt-in thing people have to trip to expose things like this, but I'll work something up to move this to cmd and install it shortly.
