### ISSUE TITLE
vpath functionality under automake

### ISSUE THREAD

**Issue by lipari** [flux-framework/flux-sched#114]
In autoconfiscating flux-sched, I rely on automake and libtool.  The Makefiles that these two tools create do not elicit the vpath functionality that is present in the old, hand-written Makefiles.

For example, these are present in the flux-sched/Makefile.inc:

vpath %.c $(FLUX_SRCDIR)/src/bindings/lua
vpath %.c $(FLUX_SRCDIR)/src/common/liblsd
vpath %.c $(FLUX_SRCDIR)/src/common/libutil

And when make goes to find the .c source to make xzmalloc.o for example, it searches the vpath directories above until if finds xzmalloc.c.

I have not found how this mechanism can work with automake/libtool.  There *is* vpath support, but it is for building in a separate directory outside of the source directory.

I did not find a way to construct the Makefile.am files that would activate the vpath directory search that the old Makefiles do.  I created a workaround that suffices, but it is admittedly a bit of a kludge.  I'm all for replacing it if anyone knows the proper way to write a Makefile.am file that would do the vpath search.

**Comment by garlick** [comment]
I don't know of a way to do that from automake, but is it a good idea?  It seems better to be explicit about where sources are coming from especially when they are coming from outside the project, which is not an ordinary situation.

Maybe configure should do an AS_VAR_SET on some variable like `fluxcoresrcdir`, and then Makefile.am's should list the sources e.g
```
noinst_LTLIBRARIES = libforeign.la
libforeign_la_SOURCES = \
    $(fluxcoresrcdir)/src/common/libutil/xzmalloc.c \
    $(fluxcoresrcdir)/src/common/libutil/whatever.c \
    ...
```

Although as of right now the flux-core packages do not export any sources.

**Comment by grondo** [comment]
I was going to say flux-core RHEL6 /opt based RPM places sources under `PREFIX/build`, however I just noticed there is an error in the current spec file which caused only libtap sources to be copied there. (That will be fixed though)

**Comment by lipari** [comment]
Thank you, @garlick.  I'll go with your approach.
