### ISSUE TITLE
Question about binding include (header) files

### ISSUE THREAD

**Issue by vsoch** [flux-framework/flux-sched#1142]
This is probably a set of dumb questions, but:

1. Should we have the resource api header files installed in the install location include?
2. Should our [base container images](https://hub.docker.com/r/fluxrm/flux-sched/tags) have `WITH_GO=yes` to turn on the builds?

```
$ ls /usr/include/flux
_binding  core  core.h  hostlist.h  idset.h  jobtap.h  optparse.h  pmi.h  pmi2.h  schedutil  schedutil.h  security  shell.h  taskmap.h
```
Note that `_binding` isn't for generic bindings, but the cleaned Python headers.
The missing reapi headers are included in Go:

```
/*
#include "reapi_cli.h"
*/
```
Since we are going to be wanting to test the different container bases (latest releases) of flux-sched in the Go bindings repository, I'm thinking that (for the time being) `WITH_GO` should be turned on, and primarily to generate the `libreapi_cli.so` in `/usr/lib/flux` and then the header files somewhere in `/usr/include/flux`. The reason is because (theoretically) those c/c++ bindings are not explicitly for Go, but for general use from some binding library, and (I think) should be available in our set of base containers. Theoretically, someone should be able to take the same include/so files and generate bindings for `<insert other language>` and only needing to rebuild flux-sched if they don't want to use a build provided in a release container. Otherwise, for development and testing, we still need to clone and build the entirety of flux-sched.

What I'll do for now is, for each base container, essentially do the clone and build again. to generate these files. But let's discuss if this approach makes sense once the Go bindings are removed. And sorry probably should have asked this for the PR just merged, but just thought about it now. 

Update: this is currently tangled with building the test for go (requiring go) so let's table it until we can remove that logic from the repository here. I'll just build them again in the meantime.

**Comment by vsoch** [comment]
We can have discussion here https://github.com/flux-framework/fluxion-go/discussions/3

**Comment by trws** [comment]
@vsoch is this still relevant or can we close?

**Comment by vsoch** [comment]
We can close, we definitely figured this out. Thanks for checking on it!
