### ISSUE TITLE
alloc requests are leaked for canceled jobs with queue-policy = "easy"

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-sched#1208]
Problem: flux hangs at shutdown on el cap as noted in:
- flux-framework/flux-core#5964
- flux-framework/flux-core#5990

It appears that fluxion (when configured with queue_policy=easy)  is not responding when unfulfilled alloc requests are canceled. This demonstrates in a standalone instance:

```
$ cat fluxion.toml
[sched-fluxion-qmanager]
queue-policy = "easy"
$ flux start -s2 -o,--conf=fluxion.toml
$ flux resource drain 0
$ flux submit -N2 hostname
ƒ2VGsWxto
$ flux cancel $(flux job last)
May 20 09:48:27.112761 sched-fluxion-qmanager.err[0]: jobmanager_cancel_cb: remove job (3284324581376): No such file or directory
$ flux jobs
       JOBID USER     NAME       ST NTASKS NNODES     TIME INFO
$ flux queue status -v
Job submission is enabled
Scheduling is started
0 alloc requests queued
1 alloc requests pending to scheduler
0 running jobs
$ exit
<hang>
```

**Comment by garlick** [comment]
@trws or @milroy - this seems to be a new problem on el cap with the recently installed release.

**Comment by trws** [comment]
I think I see why this is, testing a fix.

**Comment by trws** [comment]
Actually, I don't repro the `flux jobs` output being empty.  The rest I get exactly the same, pretty sure it's because there's an issue with the blocked job handling, but when I try it the job is listed.

**Comment by garlick** [comment]
> Actually, I don't repro the flux jobs output being empty.

`flux jobs` is "open loop" so that part would be racy if you do it in a script

 In a sharness script we'd normally do something like `flux job wait-event ID clean` instead.
