### ISSUE TITLE
does resource.acquire marking a node UP trigger a scheduling loop?

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-sched#1214]
Problem: I was checking to make sure that `resource.acquire` marking a node DOWN did not trigger a scheduling loop, and I can't seem to find how marking a node UP triggers one, given that `resource.acquire` is handled by the resource module and there doesn't seem to be a way for resource to signal qmanager to run the loop.  It must - somehow.  Can someone point out the mechanism?

**Comment by trws** [comment]
This is long ago now, but I did figure this out as part of the qmanager rework.  It's not the easiest to trace, but much like resource holds a streaming RPC open with core to get resource updates, qmanager holds one open for updates from resource.  On a `resource.acquire` being received in resource, it responds to qmanager and triggers update_on_resource_response: https://github.com/flux-framework/flux-sched/blob/master/qmanager/modules/qmanager.cpp#L211-L233

That calls both `set_schedulability` and `reconsider_blocked_jobs` on all queues currently regardless of whether things are being set up or down.  It's really annoying that we can't subset based on resources that _matter_ but that's what happens right now.

**Comment by trws** [comment]
Let me know if there's more you need here @garlick, closing for now.
