### ISSUE TITLE
symbol leakage in sched libraries and modules

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-sched#122]
`libflux-rdl.so` and `libflux-sim.so`, both installed libraries, don't have a symbol map or other mechanism in place to limit symbol exposure, so they are leaking internal stuff like xzmalloc, err_exit, etc..

Same for the sched plugins: `backfillplugin1.so` and `schedplugin1.so`.

`libflux-resrc.so` looks OK.

The comms modules: `schedsrv.so`, `sim_execsrv.so`, `submitsrv.so`,  `sim_sched_fcfs.so` `sim_sched_fcfs_aware.so`, and `sim_sched_easy.so` all export only `mod_main()` so they are correct.

**Comment by lipari** [comment]
Close via #127
