### ISSUE TITLE
enhance travis testing

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-sched#123]
As mentioned in #121, flux-sched could add
* coveralls support
* travis distcheck
* travis install sanity check

Not sure how convenient it is to do this, but would it make sense to have the "main" travis builds be against a tagged flux-core, and a one-off builder be against flux-core master?  That way it will be easy to distinguish problems with a PR under test from breakage due to flux-core changes on master?

**Comment by grondo** [comment]
That would be interesting and probably fairly doable with travis build matrix

**Comment by grondo** [comment]
I'll try to take a poke at this when I attempt to add coverage and install check support.

**Comment by garlick** [comment]
> That way it will be easy to distinguish problems with a PR under test from breakage due to flux-core changes on master?

A downside is that it might be hard to make all the builders pass simultaneously.  Hmm.

**Comment by grondo** [comment]
Are you thinking that because of intermittent test failures or the challenge of getting one version of flux-sched to build against both flux-core-x.y.z and flux-core master?

**Comment by garlick** [comment]
The latter, but maybe it will force us to be nice.

**Comment by lipari** [comment]
@garlick, feel free to close this if you think the original need has been addressed by the following commits:
* 3f574e0b12e0ef5481836eec8c3d1f46ff7f4ca7
* bff1b7671d22fe94459f1e80ff21649355d337d5
* 3d6ec88dbe4424167f380f3a95b80249b7d78f82

**Comment by garlick** [comment]
Yeah I think we can do that.
