### ISSUE TITLE
default empty "properties" for fluxion FluxionResourceGraphV1 should be map or null

### ISSUE THREAD

**Issue by vsoch** [flux-framework/flux-sched#1230]
If we start with an R-lite resource specification:

```python
{'version': 1,
 'execution': {'R_lite': [{'rank': '0-3', 'children': {'core': '0-9'}}],
  'starttime': 0.0,
  'expiration': 0.0,
  'nodelist': ['flux-sample-[0-3]']}}
```

And then use the fluxion Python bindings here to generate a graph from it (very cool by the way):

```python
from fluxion.resourcegraph.V1 import FluxionResourceGraphV1

graph = FluxionResourceGraphV1(rv1)

# Dump of json graph format for fluxion
jgf = graph.to_JSON()
```

I can use the fluxion service to initialize the fluxion graph. That looks like this:

```python
# Init the fluxion graph - it only sees one of the entire cluster
cli = FluxionClient(host=self.fluxion_host)
response = cli.init(json.dumps(jgf))
```

Under the hood, that is doing this as seen [here](https://github.com/converged-computing/fluxion/blob/529ef2254bd991989a208abc4402ebccafb6881f/python/v1/fluxion/client.py#L34-L50) and then [this in Go](https://github.com/converged-computing/fluxion/blob/529ef2254bd991989a208abc4402ebccafb6881f/pkg/fluxion/fluxion.go#L19-L53). That's all working OK (don't worry I'm not asking for debugging of a third party tool) but when I give the default output of `graph.to_JSON()` above, I get an error on the server:

```console
 This is the fluxion graph server
[GRPCServer] gRPC Listening on [::]:4242
[Fluxion] Created flux memory graph
reapi_cli_initialize: Runtime error: resource_query_t: ERROR: fill_fetcher: key (properties) must be an object or null for 0.ERROR: error generating resources
```

And indeed, if I look at the graph, the properties is an empty list.
```python
{'id': '44',
 'metadata': {'type': 'core',
  'basename': 'core',
  'name': 'core9',
  'id': 9,
  'uniq_id': 44,
  'rank': 3,
  'exclusive': True,
  'unit': '',
  'size': 1,
  'properties': [],
  'paths': {'containment': '/cluster0/flux-sample-3/core9'}}}
```
That's the tail end of the graph, but they all have that. If I follow the error and replace properties with a map (I could also have tried None, but I didn't do that):

```python
# Fluxion spits out an error that properties must be an object or null
for node in jgf['graph']['nodes']:
    if "properties" in node['metadata'] and not node['metadata']['properties']:
        node['metadata']['properties'] = {}
```

Then tada, works!

```python
response = cli.init(json.dumps(jgf))
if response.status == fluxion_pb2.InitResponse.ResultType.INIT_SUCCESS:
    print("✅️ Init of Fluxion resource graph success!")
else:
    sys.exit(f"Issue with init, return code {response.status}")
```
```console
✅️ Init of Fluxion resource graph success!
```
So I think the default for properties as a list is probably just wrong. I think it's probably just this line here: https://github.com/flux-framework/flux-sched/blob/e5f6754a9f40f0ab98d788b579c373aa246e28b3/src/python/fluxion/resourcegraph/V1.py#L215

I can put in a PR to fix this if that's it - it will be the tiniest PR _ever_ but still satisfying to fix it! But I'm not sure that's the cause - it looks like that "props" is not passed forward. I'm going to look again...

**Comment by jameshcorbett** [comment]
PR #1149 introduced the check you're running into. I think it's not the `props` (in the line you mentioned) that's giving you trouble because as you noted `props` is first turned into a dictionary before it's passed forward.

**Comment by vsoch** [comment]
Ahh I just saw this! https://github.com/flux-framework/flux-sched/commit/8c13ac670063d6d20d3d838acecf6006e35df3ff I think my version is old.

**Comment by vsoch** [comment]
yep this definitely looks to be the old version:

![image](https://github.com/flux-framework/flux-sched/assets/814322/d7d9a3f0-6cbe-476e-962e-d410b6c193bc)

 I'll do a quick fix for now and plan to update these views. Thanks @jameshcorbett !
