### ISSUE TITLE
sched use of hwloc data requires synchronization

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-sched#124]
If the sched module is loaded too early, hwloc data won't be there yet e.g.
```
$ flux start -o,--module=sched
[1456339141.938712] sched.err[0]: can't get hwloc data in kvs (resource.hwloc.xml.0)
```

There needs to be some synchronization here, but I'm not sure what's appropriate.  Is it possible to use the `resource-hwloc.topo` query for aggregated xml?  That rpc at least will return EAGAIN so you can use a backoff-retry to obtain the data.

Also (minor) I think there's a memory leak in `build_hwloc_rs2rank()`:  `kvs_get_string()` allocates a new `rs_buf` each iteration of the for loop, but only the last copy is freed before the function returns

**Comment by dongahn** [comment]
In my sched sharness tests, I used

```
flux hwloc reload ${shrd_1N4B} &&
flux module load sched sched-once=true &&
```
back to back. The assumption was they would be synchronized as far as `reload` succeeds and `reload` would succeed as far as `resource-hwloc` had been loaded. 

It sounds like we need to build in such a sync directly into schedsrv module to use the real hwloc data. As a short-term, using some wrapper command like `topo` may work with retry. But I'm not sure if we want to query each and all of the brokers through rpc to get the `ready` status. 

Can there be a more formal mechanism for a distributed service to tell the rest of the system it is ready? This could be done as easily as a key in KVS per distributed service. Perhaps, this can be scalably implemented using `kvs_fence` ?

**Comment by dongahn** [comment]
I feel I'm missing something. 

Looking at (resource.c#474)[https://github.com/flux-framework/flux-core/blob/master/src/modules/resource-hwloc/resource.c#L474], HW info is loaded up at load time? 

What is the semantics of `flux start -o,--module=sched`? Does it load all of the default modules first than sched? If that's the case, this issue might be something else. 

If it instead loads sched in an arbitrary order, either a synchronization is needed or we may need a way to specify module dependencies?

**Comment by dongahn** [comment]
Or may be it is guaranteed that sched is loaded after all the default modules at the single broker level. But its load order doesn't guarantee synchronization (or order) against resource-hwloc module loaded into other brokers...

**Comment by dongahn** [comment]
It seems having a way to express a module's dependency to another "distributed service" as a whole can ease sync issues like this. (Essentially going back to the first thought above). I'm not suggesting we should do this short term at all, though.

**Comment by grondo** [comment]
resource-hwloc module *starts* to load hwloc data when it is loaded, it can take awhile before the module has *completed* loading the xml and other data into the kvs, esp if there is a lot else going on in the session during this time. So resource-hwloc module is loaded, but the service might not be ready to use by the time sched is loaded.

**Comment by dongahn** [comment]
@grondo: Thank you. I see. How do we guarantee a sync between other dependent modules, say kvs module and wreck? Is there something that we can model our sync after?

**Comment by garlick** [comment]
@dongahn's code in the scheduler iterates through each rank, reading `resource.hwloc.xml.$rank` from the KVS.  The problem is it doesn't know whether all the resource-hwloc ranks have completed writing to the KVS.  The code bails out if a `kvs_get()` fails.

So actually in this case the KVS can already be used for synchronization.  Just replace `kvs_get()` with `kvs_watch_once()` with initial value of NULL, and you should be able to step through the data, blocking (without busy-waiting or backoff-retry) when you find a particular value missing.  Let me propose a PR that does this so I can be sure that works.

I don't mean to sidestep the issue of distributed module startup sync.  Maybe what's needed there is that idea of "groups", where each rank of a module joins a group after it completes initialization, and a user of the service can optionally check the group membership or block on it.  In this case we need to know that all ranks have joined.  In other cases maybe we only need a quorum or a particular rank to have joined.  I think something like a fence here would be brittle as we have to be able to handle single ranks loading and unloading, and (later) session grow/shrink.  Something like a group membership that can be monitored with a callback seems useful for those cases.

**Comment by dongahn** [comment]
> So actually in this case the KVS can already be used for synchronization. Just replace kvs_get() with kvs_watch_once() with initial value of NULL, and you should be able to step through the data, blocking (without busy-waiting or backoff-retry) when you find a particular value missing. Let me propose a PR that does this so I can be sure that works.

Ah, good idea. This should be an easiest way to get that sync in place (via blocking KVS like you said).

> Maybe what's needed there is that idea of "groups", where each rank of a module joins a group after it completes initialization, and a user of the service can optionally check the group membership or block on it.

I don't know how to do this. But if we can add some generalized and scalable "group" concept into flux, I suspect it can have lots of utility beyond startup sync... (not short term, of course). This may include multi-rpc without having to be a wrapper on top of rpc. With a group concept, each module rank wouldn't have to commit a key in response to each rpc, but all ranks in the group can use an optimized collective. 

BTW, we learned that low-overhead grouping isn't easy to implement. E.g., in MRNet, creating a distinct communicator has high enough overhead, we couldn't use it for frequent operations... 

(I know this is far easier said than done :-)
