### ISSUE TITLE
fluxion specific `libintern.so` should have package-specific prefix and version suffix

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-sched#1308]
Fluxion currently installs the string interner library as `/usr/lib64/libintern.so`. This has a larger than zero probability of conflicting with some other package, so as suggested by @jameshcorbett it should probably get a `fluxion` somewhere in there like `libfluxion-intern.so`.

Also, the library is for internal use only, and appears to be Fluxion version specific. To avoid conflicting with itself and to prevent/discourage linking directly to the library outside of Fluxion, a version should be added, like `libfluxion-intern.so.0.39.0`. 

This will prevent failure to reload fluxion modules after a package update because the broker still has the previous, incompatible libintern.so loaded.

Or, `libintern.so` could just be linked into the Fluxion modules and not installed at all (the simpler approach)

**Comment by trws** [comment]
I'm going to try and address this today.  The simplest approach, if I can make it happen reasonably and it tests out, will be to link libintern.a into `sched-fluxion-resource.so` and have qmanager use the symbols from there.  If for some reason I can't, then I'll put something up with changes made to the library naming on install.
