### ISSUE TITLE
flux-cpuset.so not installed correctly

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-sched#131]
I noticed that the Lua `cpuset.so` module was renamed to `flux-cpuset.so` (I'm assuming to differentiate it from any installed `cpuset` module), but it is still installed into `$(luaexecdir)/flux` so it will fail to load with : `require ("flux-cpuset")`.

Instead we should either install the `flux-cpuset.so` module directly to `$(luaexecdir)` or alternately follow what we did in flux-core and install `cpuset.so` to `$(luaexecdir)/flux`, and load the module as `flux.cpuset`. To do this a link from `RDL/flux/cpuset.so->../cpuset.so` would be needed to be made at build time in flux-sched project.

I'm going to work on the latter solution, unless I hear that others would rather keep the `flux-cpuset.so` name in the defualt LUA_CPATH.

**Comment by lipari** [comment]
@grondo, your plan is fine with me.
