### ISSUE TITLE
eliminate shortjson.h dependency from installed headers

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-sched#143]
currently resrc.h includes `src/common/libutil/shortjson.h`, and resrc.h, resrc_reqst.h, resrc_tree.h, and simulator.h use the `JSON` typedef from shortjson.h

These headers won't be usable outside the flux-sched source tree in their current state.

They also depend on czmq and json-c, so it might be better to just not install them until they can be reworked.

**Comment by lipari** [comment]
Close via #148
