### ISSUE TITLE
support dynamic sched plugin loading

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-sched#144]
Just wanted to float this idea -

If sched implements the `lsmod` request handler as discussed in RFC 5, `flux module list sched` can be used to list its loaded plugins.

Similarly, if `rmmod` and `insmod` handlers are implemented, `flux module remove sched.fcfs` and `flux module load sched.backfill` (say) could work.   Of course then sched has to handle "plugin not loaded" sensibly  (like pausing/restarting scheduling without losing the queue).

I'm not sure how sched guys fell about this or how much work would be involved, but it would be kind of neat to be able to swap out the scheduling algorithm on the fly.  I'd be happy to supply a PR to implement the stubbed out handlers if this is of interest.

**Comment by lipari** [comment]
Sure.  That sounds like a nice enhancement.  I'll take you up on your offer to implement the stubbed out handlers.
Will we be able to preserve the automatic default loading behavior?  Right now, you get the sched_fcfs by default if you don't specify a plugin.

**Comment by garlick** [comment]
OK, I'll get that started.  I'll just stub the handlers and you can decide what to do with the requests and the default behavior.  My suggestion would be to not wire a default into sched, but instead have a default dynamically loaded in the sched rc1 script.  (Seems like it would be as easy to support "no plugin at initialization" as "no plugin after rmmod")

**Comment by lipari** [comment]
>  My suggestion would be to not wire a default into sched, but instead have a default dynamically loaded in the sched rc1 script.

Sounds good.

**Comment by garlick** [comment]
Looks like this is complete?  Closing.
