### ISSUE TITLE
Sporadic t1001-rs2rank-basic.t failure

### ISSUE THREAD

**Issue by lipari** [flux-framework/flux-sched#149]
Still seeing an occasional failure of t1001-rs2rank-basic.t when run by travis.  Refer to [Issue 134](https://github.com/flux-framework/flux-sched/issues/134) for problems that were diagnosed and fixed.  There appears to be a third source of the intermittent failures.  It looks like this:
```
ok 1 - rs2rank: multiple ranks manage a node in a shared fashion
ok 2 - rs2rank: each manages an exclusive set of cores of a node
ok 3 - rs2rank: each manages a node exclusively
[1459804015.117512] sched.err[0]: RDL(/home/travis/build/flux-framework/flux-sched/flux-sched-2399251/t/data/hwloc-data/004N/exclusive/cab.hwloc1.lua) inconsistent w/ hwloc!
ok 4 - rs2rank: works with a matched RDL
[1459804016.807590] sched.err[0]: RDL(/home/travis/build/flux-framework/flux-sched/flux-sched-2399251/t/data/hwloc-data/004N/exclusive/cab.hwloc2.lua) inconsistent w/ hwloc!
ok 5 - rs2rank: works with an inconsistent RDL (fewer cores)
[1459804018.833648] sched.err[0]: RDL(/home/travis/build/flux-framework/flux-sched/flux-sched-2399251/t/data/hwloc-data/004N/exclusive/cab.hwloc3.lua) inconsistent w/ hwloc!
ok 6 - rs2rank: works with an inconsistent RDL (fewer nodes)
# passed all 6 test(s)
1..6
flux-start: 1 (pid 39332) Killed
FAIL: t1001-rs2rank-basic.t
```

**Comment by grondo** [comment]
Can you paste the test log and broker log from this test?
The test is actually passing but it appears the broker is killed instead of exiting cleanly. I'm not sure why that is happening. Unless `flux-start` itself will sometimes `kill -9` the brokers, this could be an OOM kill(?)

**Comment by lipari** [comment]
I have not seen this happen on my local system - only in a travis build and test.  Here's the latest one:  https://travis-ci.org/flux-framework/flux-sched/jobs/120731239

**Comment by grondo** [comment]
Arrgh. The broker log and test output file are empty or missing.

**Comment by lipari** [comment]
I haven't seen this problem in months and the code has changed quite a bit.  I'm closing.  If the problem reappears, it should probably get a fresh issue.
