### ISSUE TITLE
Change verbose level to INFO when RDL spec != hwloc

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-sched#153]
Currently, when the hwloc resource info does not match with the specified RDL file, `sched` reports 

```
[1461268835.654123] sched.err[0]: RDL(/nfs/tmp2/dahn/FLUX-20160421/flux-sched/conf/hype.lua) inconsistent w/ hwloc!
```

But this is not a fatal failure because `sched` will tolerate it and rebuild the `resrc` tree based on the hwloc resource info instead. I think @tpatki was once confused about this before. And looking at this after a while doesn't seem right to me either. 

What do folks think changing the verbose level for this condition to INFO?

**Comment by lipari** [comment]
INFO sounds good to me.  I would amend the message to state that (in addition to the RDL file not matching hwloc), that the resources discovered by hwloc would be used.

**Comment by lipari** [comment]
In thinking about this more, is this message even needed.  If the tests will never run on hype, why bother trying to read a hype.lua file?

**Comment by dongahn** [comment]
I think the message is needed since the message can potentially help debug. But in terms of test cases, you have a good point. Perhaps, what we should do is not to pass an RDL file (e.g., hype.lua) to `sched` load line for all but a few tests that deliberately test if `sched` can tolerate RDL file != hwloc info?

**Comment by grondo** [comment]
There should be at least one test that loads an example RDL file if we continue to support that. I think the `hype.lua` file was just an example meant to sanity check readers.

**Comment by dongahn** [comment]
@grondo: good point. Yes, we do have some test coverage for these cases. So we can safely remove the RDL file from other subtests...

```
ok 4 - rs2rank: works with a matched RDL
[1461271183.176294] sched.err[0]: RDL(/nfs/tmp2/dahn/FLUX-20160421/flux-sched/t/data/hwloc-data/004N/exclusive/cab.hwloc2.lua) inconsistent w/ hwloc!
ok 5 - rs2rank: works with an inconsistent RDL (fewer cores)
[1461271184.204055] sched.err[0]: RDL(/nfs/tmp2/dahn/FLUX-20160421/flux-sched/t/data/hwloc-data/004N/exclusive/cab.hwloc3.lua) inconsistent w/ hwloc!
ok 6 - rs2rank: works with an inconsistent RDL (fewer nodes)

PASS: t1001-rs2rank-basic.t
```

**Comment by dongahn** [comment]
PR #157 ready for review.
