### ISSUE TITLE
make distclean issue?

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-sched#158]
So that I don't forget. After I did make distclean, git status says I still have some Makefile.in left...

```
#	rdl/Makefile.in
#	rdl/flux/
#	rdl/test/Makefile.in
#	resrc/Makefile.in
#	resrc/test/Makefile.in
#	sched/Makefile.in
#	simulator/Makefile.in
#	src/Makefile.in
#	src/common/Makefile.in
#	src/common/liblsd/Makefile.in
#	src/common/libtap/Makefile.in
#	src/common/libutil/Makefile.in
#	t/Makefile.in
```

**Comment by garlick** [comment]
From [Automake manual](http://www.gnu.org/savannah-checkouts/gnu/automake/manual/html_node/Clean.html#Clean):
> If configure built it, then distclean should delete it.

So I think that's normal.

**Comment by dongahn** [comment]
Thank you for the reference. I had this question because the purpose of distclean is to return the state to the pristine source which is needed for rpm. 

Are you guys distribute Makefile.in for the core release? (I can check this myself but I will have to be on road now...)

**Comment by grondo** [comment]
Yes, you have to distribute Makefile.in files with a release, or `./configure` won't work. If you want to clean Makefile.in and other products of autotools, then use `make maintainer-clean`

**Comment by dongahn** [comment]
got it.
