### ISSUE TITLE
Providing a runtime option to select conservative/hybrid backfill algorithms?

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-sched#159]
This is just an idea. 

As I was trying to package things up, I thought it might be useful to make not only EASY backfill, but also conservative backfill algorithms as a **runtime** option. This way, users can try most popular online scheduling algorithms: FCFS, EAST/Hybrid/Conservative backfill. 

I have to believe all of the algorithms is already in the code, but it is currently statically determined [here]( https://github.com/flux-framework/flux-sched/blob/master/sched/sched_backfill.c#L44). 

How about we devise some ways to pass "backfill_depth=K" where K can vary from 1 to unlimited. If it is set to 1, sched will do EAST backfill. If it is set to unlimited, the algorithm becomes conservative backfill. If K is set to be some number, it becomes hybrid. 

I was thinking to pass that as a new option to sched load. But then, if there is a way to pass a option to sched.backfill load, this would even be better.

Thoughts?

**Comment by SteVwonder** [comment]
I like this idea.  It would avoid creating a different plugin for every minor variation of a particular scheduler.

To make this work, do we want to store the options as local to the plugin (some local struct), or store them in the sched and pass them into the plugin functions with every call?  It seems to me that allowing the options to be parsed and stored in the plugin is more flexible and cleaner.  I am just not sure the best way to go about implementing that.

Since the plugin is loaded directly by the sched module (and not via a flux load call), I don't see how it would be possible to directly pass arguments to the plugin.  The only thing that I can think of is to add a "setup_plugin" function to each plugin that takes in the the argv of the sched module (and is called after the plugin is loaded).  This would allow the plugin to make a pass over the arguments passed to sched for arguments relevant to it (the plugin).  The problem with this is namespace collisions.

**Comment by garlick** [comment]
see `plugin.c::insmod_cb()` - the sched modules can be loaded by `flux module load` and arguments are available in that function to do with what you like.

**Comment by dongahn** [comment]
@SteVwonder, @garlick: I agree that passing this at `flux module load` time is a way to go. FYI -- With latest runlevel support, a scheduling plugin can be selected by setting that as a load time option to an environment variable: `FLUX_SCHED_OPTIONS` before `flux start`

@SteVwonder: if you can quickly implement this, this can be used as part of Phase III testing of our [CTS-1 test plan](https://github.com/flux-framework/distribution/issues/14). I know this can also help you w/ your summer dynamic-scheduling investigation. Thanks.

**Comment by dongahn** [comment]
@SteVwonder: BTW, do you have an idea as to how we can test correctness of various scheduling algorithms for CTS-1 testing? Perhaps we can bring in some well-known workloads w/ known schedules?

**Comment by dongahn** [comment]
Great! Thank you so much for being proactive on this Steven!

**Comment by SteVwonder** [comment]
@garlick, it looks like `plugin.c::insmod_cb()` is never actually run (or at least I am unable to print from the function and gdb never breaks on it when I set a breakpoint).

What is supposed to send the `sched.insmod` request which triffers that cb? The broker? Sched?

**Comment by grondo** [comment]
@SteVwonder, @garlick may be out for the afternoon.

I think flux-sched should be using standard module interface from libflux `module.h`. If so, then a call to `flux module load sched.*` should invoke this callback. That command would be issued by instance owner on command line, or perhaps from the flux-sched `rc1` script?

Sorry I'm not much more help.

**Comment by garlick** [comment]
Right - you might also need to add an option to sched to pass a group of
options to the plugin it loads by default.

**Comment by SteVwonder** [comment]
The "sched.insmod" callback is being registered by `plugin.c::sched_plugin_loader_create` which is called by `sched.c::mod_main`.  As far as I can tell, this means that the cb is not registered until after sched has been loaded (thus I would suppose that the registration is happening after the request has occurred).

I have an rc1.d script that successfully loads the sched and starts the simulator.  Despite this, I don't see any of the log messages that I added to `plugin.c::insmod_cb`, and I cannot get gdb to break on `plugin.c::insmod_cb`.

[Coveralls](https://coveralls.io/builds/6598753/source?filename=sched%2Fplugin.c) has this cb listed as executing.  So I'm obviously missing something, but I'm not sure what.  Sorry I can't even figure out what question to ask, but a bump in the right direction would be awesome.  In the mean time, I will explore how the testsuite loads the sched module to see if there is a difference between how I load it and how the testsuite loads it.

**Comment by grondo** [comment]
The `t/t1004-module-load.t` sharness test exercises schedule component
module loading, so that is probably where that callback is being executed
during tests... I am not sure how sched loads it's initial plugin though

**Comment by grondo** [comment]
Quick peek at scheduler module shows that, by default, sched will load a
default or user supplied plugin on startup, thus bypassing the `plugin_cb`
message handler. A user supplied plugin can be passed with the `plugin=`
argument to the sched module.

Hope this helps!!

**Comment by SteVwonder** [comment]
Thanks @grondo.  You are right.  It looks as though the default or user supplied plugin doesn't trigger that insmod_cb, but if you unload then load a new sched plugin, the insmod_cb is trigger.

@garlick's previous comment about arguments to the default plugin is making more sense now.

I think I have grokked it and can get it working from here.  Thanks guys!

**Comment by garlick** [comment]
Sorry for my brevity - I was in the doctor's office waiting room on my phone.

Looks like maybe `sched_plugin_load()` needs to accept arguments.   When it's called from sched.c, those arguments would come from sched's command line arguments (maybe allow a `--plugin-args=arg,arg,...` on sched's command line?).

When it's called from insmod_cb, they are already decoded there for you from the insmod json, which came from `flux module load` command line.

if it were me I would probably add argz, argz_len members to `struct sched_plugin` for the plugin methods to access internally.
