### ISSUE TITLE
Need manpages similar to flux core

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-sched#160]
For upcoming sched releases, it seems sched can benefit from having man pages that are consistent with flux core's.
- Sched has some utility commands flux-waitjob flux-jstat (although the latter is in core) which we have been using testing. But formating the existing docs into adoc should be useful for early users
- There are some sched module load options which seem also good to document for the users. But I couldn't find a doc in core that we can model after....
- Finally I think it will also be good if we can clean up the sched emulator and documents it in a consistent style as flux core. This can further facilitate scheduler usage and research.

**Comment by grondo** [comment]
Man pages for modules to document their function and options is a good idea. A section 7 man page (like `flux-broker-attributes(7)` might work for these pages, but like you say it would be great to have a convention for naming the pages. Perhaps `flux-module-sched(7)`?

Also, if you want any installed commands to appear in `flux help` output, sched can generate a `sched.json` help file (see `etc/flux/help.d/core.json` and `etc/gen-cmdhelp.pl` for automation in flux-core). However, I'm not sure that there is currently a way for `flux help` to search multiple directories for json files, oops!  I'll try to open an issue on this in core.

**Comment by dongahn** [comment]
flux-module-ached(7) should work for me. @lipari? 

Thank you for the flux help tip!

**Comment by lipari** [comment]
`flux-module-sched(7)` works for me as well.
Also, the new issue @grondo opened is [Issue 655](https://github.com/flux-framework/flux-core/issues/655)

**Comment by dongahn** [comment]
We will not pursue manage but as part of #772 we will autogenerate both high and low level documentation leveraging in-line documentations.
