### ISSUE TITLE
time to tag flux-sched?

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-sched#178]
We're in the process of updating flux-core to 0.4.1 on TOSS3.   The first problem Trent ran into when checking the release was that the new flux-core deprecated libflux-mrpc.so but flux-sched-0.1.0-3  still required it.  I went ahead and kicked off a flux-sched rebuild (bumping the "release" number from 3 to 4).

This failed on the next problem (see [buildlog](http://tossbuild.llnl.gov/kojifiles/work/tasks/8130/18130/build.log))
```
make[2]: Entering directory `/builddir/build/BUILD/flux-sched-0.1.0/sched'
  CC       sched_la-sched.lo
  CC       sched_la-rs2rank.lo
  CC       sched_la-rsreader.lo
  CC       sched_la-plugin.lo
  CC       sched_fcfs_la-sched_fcfs.lo
  CC       sched_backfill_la-sched_backfill.lo
  CC       flux_waitjob-flux-waitjob.o
flux-waitjob.c: In function 'main':
flux-waitjob.c:260:5: error: implicit declaration of function 'flux_log_set_facility' [-Werror=implicit-function-declaration]
     flux_log_set_facility (h, "waitjob");
     ^
cc1: all warnings being treated as errors
make[2]: *** [flux_waitjob-flux-waitjob.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory `/builddir/build/BUILD/flux-sched-0.1.0/sched'
make[1]: Leaving directory `/builddir/build/BUILD/flux-sched-0.1.0'
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

Looks like this was already fixed but of course it's not in the 0.1.0 tag that we're building above.

Time for a new sched release?

**Comment by grondo** [comment]
If so, should we also convert `NEWS` to `NEWS.md` and adopt the travis based release upload on tag? I'd be happy to implement that for `flux-sched`

**Comment by dongahn** [comment]
Thanks @garlick: yeah, seems like it. I will spend most of my time today to make the first cut for CTS scale testing and I have a couple of high priority items next week. It may take me some time to get this. Also, it would be good to follow the automatic release pattern @grondo's working on to further automate sched releases. If @lipari or other members want to get to this in the meantime, feel free.

**Comment by grondo** [comment]
I can push through a release of `flux-sched` if there are no objections. I'll attempt to get Travis auto-release working first.

**Comment by dongahn** [comment]
@grondo: go for me and thank you very much!

**Comment by garlick** [comment]
FYI I did just build and check sched master against an installed flux-core-0.4.1.

**Comment by lipari** [comment]
@grondo, I appreciate the offer to work on a flux-sched release.  I'm not at work today, and only checking in when time permits.

**Comment by dongahn** [comment]
@lipari: thank you for checking in on your off day and sorry, I didn't know this was your off friday.

**Comment by grondo** [comment]
Ok, flux-sched [v0.2.0](https://github.com/flux-framework/flux-sched/releases/tag/v0.2.0) published!
