### ISSUE TITLE
Change error logging in resrc

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-sched#181]
As @lipari, @dongahn, and I discussed a few weeks ago, the resrc error logging could be changed to avoid the use of printf.   Instead of printf, the resrc could provide a pointer to an error string that the user of resrc could then log as they wish (e.g. through flux_log).

The existing setup is hard to use when the flux broker has been set to redirect flux_log's to a file and then the resrc prints to stdout/stderr.  With these two streams of logs in two different files, it can be hard to manually interleave them (since the resrc prints are missing timestamps).

**Comment by lipari** [comment]
Agreed.  The resrc_generate_hwloc_resources() provides a model for any work that is done to address this issue.

**Comment by dongahn** [comment]
AFAIK, this has been addressed sometime back.
