### ISSUE TITLE
zmq.h not found when installed in non-standard location

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-sched#187]
I have flux-core compiled and installed on a Ubuntu system in a non-standard location (i.e., `/opt/zeromq-4.1.4`).  `/opt/zeromq-4.1.4/lib/pkgconfig` was added to `PKG_CONFIG_PATH`, so that `pkg-config` correctly finds the package and generates the correct cflags and libs.  flux-sched's configure picks all of this up correctly, but I still get a compilation error in `common/libutil`:

```
# sherbein at sealand in ~/Repositories/flux-framework/flux-sched on git:dynam_sched ✖︎ [10:32:09]
→ make
make  all-recursive
make[1]: Entering directory '/data/hd1/Repositories/flux-framework/flux-sched'
Making all in src
make[2]: Entering directory '/data/hd1/Repositories/flux-framework/flux-sched/src'
Making all in common
make[3]: Entering directory '/data/hd1/Repositories/flux-framework/flux-sched/src/common'
Making all in libtap
make[4]: Entering directory '/data/hd1/Repositories/flux-framework/flux-sched/src/common/libtap'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/data/hd1/Repositories/flux-framework/flux-sched/src/common/libtap'
Making all in liblsd
make[4]: Entering directory '/data/hd1/Repositories/flux-framework/flux-sched/src/common/liblsd'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/data/hd1/Repositories/flux-framework/flux-sched/src/common/liblsd'
Making all in libutil
make[4]: Entering directory '/data/hd1/Repositories/flux-framework/flux-sched/src/common/libutil'
  CC       log.lo
log.c:39:17: fatal error: zmq.h: No such file or directory
compilation terminated.
Makefile:427: recipe for target 'log.lo' failed
make[4]: *** [log.lo] Error 1
make[4]: Leaving directory '/data/hd1/Repositories/flux-framework/flux-sched/src/common/libutil'
Makefile:395: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory '/data/hd1/Repositories/flux-framework/flux-sched/src/common'
Makefile:395: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/data/hd1/Repositories/flux-framework/flux-sched/src'
Makefile:462: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/data/hd1/Repositories/flux-framework/flux-sched'
Makefile:394: recipe for target 'all' failed
make: *** [all] Error 2
```

I was able to solve the problem by adding `$(CZMQ_CFLAGS)` to the `AM_CFLAGS` variable in `src/common/libutil/Makefile.am`.  Being unfamiliar with autotools, I am unsure if this is the correct solution.  If it is, I can submit a PR.

**Comment by lipari** [comment]
My first thought was to replace the one, call to zmq_strerror() in log.c with strerror() and remove the #include <zmq.h> from log.c.  However, the flux-core's Makefile.am in its util directory does include the $(ZMQ_CFLAGS).  So, I would say the more conservative approach would be to add $(ZMQ_CFLAGS) to the AM_CFLAGS definition in src/common/libutil/Makefile.am and see it that works.

**Comment by garlick** [comment]
> My first thought was to replace the one, call to zmq_strerror() in log.c with strerror() and remove the #include <zmq.h> from log.c.

You might want that to properly decode errnos from zeromq functions...

> So, I would say the more conservative approach would be to add $(ZMQ_CFLAGS) to the AM_CFLAGS definition in src/common/libutil/Makefile.am and see if that works.

Yeah, or AM_CPPFLAGS like in flux-core

If that doesn't work, @SteVwonder - it might be helpful to run `make V=1` and capture the error above with expanded CC lines.

**Comment by SteVwonder** [comment]
Ok, makes sense.  Some questions on the specifics:

- Why `AM_CPPFLAGS` over `AM_CFLAGS`?  I noticed this used in other Makefile.am files as well; it seems a little odd to me since we don't have any C++ code in the codebase.  I assume there is some other semantics besides C/C++.
- Is `$(CZMQ_CFLAGS)` alright to use?  `$(ZMQ_CFLAGS)` doesn't get defined in flux-sched, and the czmq flags include a pointer to the zmq headers.

**Comment by garlick** [comment]
CPP = C preprocessor in this case.  The [Program Variables](https://www.gnu.org/software/automake/manual/html_node/Program-Variables.html) section of the automake manual explains the difference bewteen those two variables.

Yes, CZMQ_CFLAGS looks like the right choice here.
