### ISSUE TITLE
Make sched's resource code multi-threaded

### ISSUE THREAD

**Issue by lipari** [flux-framework/flux-sched#194]
Based on a suggestion in [PR 189](https://github.com/flux-framework/flux-sched/pull/189#issuecomment-247657282), revisit flux-sched's resrc code to see whether it can support multi-threaded applications.

**Comment by dongahn** [comment]
Do we need to make resrc multi-threaded, though? When resrc is used by sched, there will be no two threads accessing this library at the same time?

**Comment by grondo** [comment]
Are you positive? sched is loaded as thread (module) in the broker. Will there never be any other module loaded by a broker that uses resrc library at the same time as sched? Perhaps you could argue this if resrc was itself a broker module providing a messaging interface to users like sched, but then it wouldn't need to be packaged as a reusable library?

In my other comment I didn't mean to require that resrc support multithreaded, but was more pointing out why the `library_init(void)` `library_fini(void)` style interface has fallen out of favor ...

**Comment by dongahn** [comment]
@grondo: I meant, as of now of course. If this is repackaged and used by multiple modules, this needs to be thread-safe.

**Comment by dongahn** [comment]
@SteVwonder also argued for making resrc as a service before he returned back and it sounded that it has lots of merits. @SteVwonder can chime in. 

If we take that route, we need to be very careful w/ interface design. I think it needs to stay pretty coarse grained. We probably don't want frequent operations needed by the schedulers suffer a RPC overhead (last thing you want to do is to go back and force between resrc module and sched module to perform a match function for individual resrc object). We probably want to be able to push the matcher code into resrc and get back w/ qualified resrcs... somehow...

**Comment by SteVwonder** [comment]
My argument for resrc as a service was to allow dynamic scheduling to be a modular service.  Currently, dynamic scheduling is just a subroutine of the scheduler that runs when the scheduler has been idle for several heartbeats.  This makes the scheduler code larger, more complex, and harder to maintain.  If dynamic scheduling was a separate module, users could load and unload it at will.  It would also remove the dynamic scheduling from the critical path, allowing it to run more frequently without disturbing the main scheduler.

I like @dongahn's idea of pushing the matching functionality into a separate module.  This would work perfectly for dynamic scheduling.  As for the main scheduler, I think we should wait and see how well the new job spec (and associated matcher) works for our use-cases.

Other scattered thoughts on the topic:
- The resrc module would need a priority queue to prevent modules like dynamic scheduling from starving out the main scheduler's requests.
- Can @trws's job spec matcher eventually be morphed into a module along with the resrc?
- Each module that uses the resrc module could have its own "cache" that is an eventually-consistent view of the system state.  If users so desired, they could run a cheaper, local check on their view of the system state before sending an RPC to the resrc module.

**Comment by dongahn** [comment]
For now, I am closing this. I believe we have been able to make progress for most of the suggestions here that was in a idea phase. Good to see @SteVwonder's comment:

> I like @dongahn's idea of pushing the matching functionality into a separate module. This would work perfectly for dynamic scheduling. As for the main scheduler, I think we should wait and see how well the new job spec (and associated matcher) works for our use-cases.
