### ISSUE TITLE
Scheduler Correctness: Reservations

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-sched#197]
I believe I have found a correctness issue with the current scheduler (specifically in `sched.c`), that occurs when non-homogenous job requests are issued.

If the call to `find_resources` fails (nfound == 0), then nothing else is called and the scheduler moves onto the next job.  In order for hybrid and conservative backfill to work, the scheduler should call `reserve_resources` so that a reservation is still made for the job even though there aren't any free resources for the job to execute on currently (it might be able to run very soon).

Since the reservation is not made, a job later on in the queue can be allocated a run (since it uses less memory or IO bandwidth, for example) without any consideration to if it affects the start time of the previous job.

This case should be considered in our correctness study (#168).

**Comment by dongahn** [comment]
@SteVwonder: thanks Stephen. Yes, it does sound like a bug. Do you already have a patch to throw in as a PR?

**Comment by SteVwonder** [comment]
@dongahn: yes.  I can push now.

**Comment by SteVwonder** [comment]
@lipari and I spoke over the phone.  @lipari said that `find_resources` should search into the future to find possible resources that the job can run on.  So it should only return 0 for resource requests that are permanently unsatisfiable.  Thus, if I truly am running into a bug, it is probably in `find_resources` of the backfill sched plugin not in `sched.c`.

I am running tests on turnaround time prediction today, but once those are complete, I will investigate further with this and confirm that it actually occurs with the `sched.backfill` plugin with all satisfiable requests.

**Comment by SteVwonder** [comment]
After a lengthy discussion with @tpatki, @nikhiljain, and @sampollard, it seems that this only matters if flow resources or heterogeneous nodes are involved.  If every node is exactly the same, then the current code is correct and slightly faster (since it doesn't make certain reservations).  

Another case where this might be an issue is if we are relying on the reservations to provide the users with an estimate of when the job will run. With the existing code, some jobs might not have a reservation made for them (ruining our ability to provide a turnaround time or start time prediction).

**Comment by tpatki** [comment]
Just to follow up, we believe this only matters for conservative backfilling. 
Easy backfilling will still be correct, as far as we understand.

**Comment by lipari** [comment]
Regarding start time estimates to users... As tempting as it may seem to provide start time estimates for _all_ pending jobs, all estimates become less and less reliable the further into the future they are made.  At some point, it becomes better not to provide an estimate than give report an projected start time that is bound to change in the intervening hours.  The (configurable) threshold of stopping estimate calculations has traditionally been set to 24 hours into the future.

**Comment by dongahn** [comment]
> it seems that this only matters if flow resources or heterogeneous nodes are involved. If every node is exactly the same, then the current code is correct and slightly faster (since it doesn't make certain reservations).

@SteVwonder: I would like to understand the correctness problem with heterogenous nodes. As I learned from JOWOG, traditional schedulers have issues in dealing with heterogenous machines like Trinity and understanding this problem seems pretty relevant.

**Comment by sampollard** [comment]
Here is an example Nikhil and @SteVwonder and @tpatki came up with yesterday. This is an example of a 5 node cluster with 4 "large" nodes and 1 "small" node, where a job can request small or large nodes and a small node request can be fulfilled by a large node but not the opposite.
[scheduling_example.pdf](https://github.com/flux-framework/flux-sched/files/1194475/scheduling_example.pdf)

**Comment by dongahn** [comment]
@sampollard: thanks. Questions. Job 1 should have 1 time unit, not 2? Why job 4 is reserved to 3 nodes when it requested 2 nodes in the first figure?

**Comment by sampollard** [comment]
@dongahn Those are mistakes. Sorry for the confusion and thank you for pointing them out. Here is the correct figure.
[scheduling_example.pdf](https://github.com/flux-framework/flux-sched/files/1194639/scheduling_example.pdf)

**Comment by dongahn** [comment]
The first case seems like a bug to me - since we don't have hetergeneous test cases... Going forward, It will be extremely useful to intriduce test cases like this. 

My proposal is to build such correctness tests as unit tests to the upcoming resource query utility using the actual jobspec @morrone has been pushing forward. Thank yiu Sam.

**Comment by dongahn** [comment]
A bunch of tests have been added using resource-query.
