### ISSUE TITLE
Go through flux-sched code and check the return value of all kvs calls for error

### ISSUE THREAD

**Issue by lipari** [flux-framework/flux-sched#202]
This came from a comment to [PR 201](https://github.com/flux-framework/flux-sched/pull/201)

**Comment by dongahn** [comment]
Is this still an issue?

**Comment by lipari** [comment]
It's really @garlick's call based on the recommendation of [this request](https://github.com/flux-framework/flux-sched/pull/201#issuecomment-251265305).  Practically speaking flux-sched should match flux-core in how consistently kvs return values are checked for error.

**Comment by garlick** [comment]
I think we're good.
