### ISSUE TITLE
flux-sched build broke

### ISSUE THREAD

**Issue by lipari** [flux-framework/flux-sched#209]
Not sure what changed in flux-core yet, but the build which followed the [latest sched merge](https://github.com/flux-framework/flux-sched/commit/665c88030cf59ca02972665f1385cbc3e429a4be) failed:
https://travis-ci.org/flux-framework/flux-sched/builds/166892546
configure: error: flux-core package not installed

**Comment by grondo** [comment]
Looks like Jansson wasn't found during flux-core build, I can't remember but was it added to flux-core .travis.yml as an apt package?

**Comment by lipari** [comment]
This?  https://github.com/flux-framework/flux-core/commit/990c5fd7c965bf0e14bcdd53c327d88900d907ed

**Comment by garlick** [comment]
Exactly.  Sorry about that!  I'll do a PR tomorrow AM if you don't beat me to it.
