### ISSUE TITLE
travis-ci: t0001-basic.t fails

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-sched#211]
The travis-ci builds from pr #209 were not working just before the pr was merged.  [This gcc build](https://travis-ci.org/flux-framework/flux-sched/jobs/167119632) is an example.

The first test that fails is this one:
```
2016-10-12T17:28:17.164396Z sched.err[0]: kvs_get resource.hwloc.xml.0: Protocol error
2016-10-12T17:28:17.164620Z sched.err[0]: failed to load resrc using hwloc
2016-10-12T17:28:17.164711Z sched.err[0]: failed to load resources
2016-10-12T17:28:17.164804Z sched.crit[0]: fatal error: Protocol error
not ok 1 - sched: module load works
#	
#		flux module load sched
#	
ok 2 - sched: module remove works
2016-10-12T17:28:17.196121Z sched.err[0]: kvs_get resource.hwloc.xml.0: Protocol error
2016-10-12T17:28:17.196288Z sched.err[0]: failed to load resrc using hwloc
2016-10-12T17:28:17.196373Z sched.err[0]: failed to load resources
2016-10-12T17:28:17.196455Z sched.crit[0]: fatal error: Protocol error
not ok 3 - sched: flux-module load works after a successful unload
#	
#		flux module load sched &&
#		flux module remove sched
#	
rdl_load: foo: No such file or directory
2016-10-12T17:28:17.215201Z sched.err[0]: failed to load resrc
2016-10-12T17:28:17.215322Z sched.err[0]: failed to load resources
2016-10-12T17:28:17.215429Z sched.crit[0]: fatal error: No such file or directory
ok 4 - sched: module load should fail
2016-10-12T17:28:17.230754Z sched.err[0]: kvs_get resource.hwloc.xml.0: Protocol error
2016-10-12T17:28:17.230922Z sched.err[0]: failed to load resrc using hwloc
2016-10-12T17:28:17.231007Z sched.err[0]: failed to load resources
2016-10-12T17:28:17.231089Z sched.crit[0]: fatal error: Protocol error
not ok 5 - sched: module load works after a load failure
#	
#		flux module load sched
#	
ok 6 - sched: module list works
ok 7 - get_instance_size works
# failed 3 among 7 test(s)
1..7
2016-10-12T17:28:17.276716Z broker.err[0]: Run level 2 Exited with non-zero status (rc=1) 0.1s
flux-start: 0 (pid 40522) exited with rc=1
FAIL: t0001-basic.t
```

**Comment by grondo** [comment]
I can reproduce this on hype, trying to figure out what's going on now. From an instance I can certainly run `flux kvs get resource.hwloc.xml.0`. Is there a really easy way to snoop the messages between the sched module and kvs during this test?

**Comment by garlick** [comment]
Not as easy as it should be,but you can either set `FLUX_HANDLE_TRACE=1` in the environment and try to find the trace you want in all the output, or modify the broker like this:
```diff
diff --git a/src/broker/module.c b/src/broker/module.c
index 7bb4c5f..8f3bf0c 100644
--- a/src/broker/module.c
+++ b/src/broker/module.c
@@ -133,7 +133,10 @@ static void *module_thread (void *arg)
 
     /* Connect to broker socket, enable logging, register built-in services
      */
-    if (!(p->h = flux_open (uri, 0)))
+    int flags = 0;
+    if (!strcmp (p->name, "sched"))
+        flags |= FLUX_O_TRACE;
+    if (!(p->h = flux_open (uri, flags)))
         log_err_exit ("flux_open %s", uri);
     if (flux_opt_set (p->h, FLUX_OPT_ZEROMQ_CONTEXT,
                       p->zctx, sizeof (p->zctx)) < 0)
```

**Comment by garlick** [comment]
Or maybe better, in the sched module, enclose the thing you want to trace with
```C
flux_flags_set (h, FLUX_O_TRACE);
flux_flags_unset (h, FLUX_O_TRACE);
```

**Comment by grondo** [comment]
ok, thanks! Once thing I did notice is I don't think the error is not actually from `kvs_get`, it seems to be coming from `kvs_watch_once`. Not that it gets me too much closer...

**Comment by lipari** [comment]
@grondo, I've already got a fix in progress.  Don't waste your time debugging the sched side.

**Comment by garlick** [comment]
I've been operating under the assumption that I must have broken something.  What are you thinking is wrong @lipari?

**Comment by lipari** [comment]
Sorry, I glanced too quickly at this thread.  I was thinking it related to sched [PR 210](https://github.com/flux-framework/flux-sched/pull/210).

**Comment by garlick** [comment]
It is, but the segfault in the resrc code seems to be only a part of it, and I was assuming might even be fallout from this other problem.

**Comment by lipari** [comment]
Well then, I'll share the fix that eliminated the core dump:
```
diff --git a/resrc/resrc.c b/resrc/resrc.c
index 6c32ee4..57bf1ec 100644
--- a/resrc/resrc.c
+++ b/resrc/resrc.c
@@ -691,29 +691,31 @@ resrc_t *resrc_new_from_json (json_object *o, resrc_t *parent, bool physical)
 
         jpropso = Jobj_get (o, "properties");
         if (jpropso) {
-            json_object *jpropo;        /* json property object */
+            const char *val;
             char *property;
 
             json_object_object_foreachC (jpropso, iter) {
-                jpropo = Jget (iter.val);
-                property = xstrdup (json_object_get_string (jpropo));
-                zhash_insert (resrc->properties, iter.key, property);
-                zhash_freefn (resrc->properties, iter.key, free);
-                Jput (jpropo);
+                val = json_object_get_string (iter.val);
+                if (val) {
+                    property = xstrdup (val);
+                    zhash_insert (resrc->properties, iter.key, property);
+                    zhash_freefn (resrc->properties, iter.key, free);
+                }
             }
         }
```

**Comment by lipari** [comment]
Also FWIW, all for the resrc code including test/tresrc.c does not use anything from flux-core.  Only the sched code messages with JSC and wreck.

**Comment by grondo** [comment]
kvs_watch_once() protocol is fine, the `EPROTO` is returned from this code block in `get_string_blocking()` in sched.c:

```C
    if (kvs_watch_once (h, key, &json_str) < 0) {
        saved_errno = errno;
        goto error;
    }
    if (!json_str || !(o = json_tokener_parse (json_str))
                  || json_object_get_type (o) != json_type_string) {
        saved_errno = EPROTO;
        goto error;
    }
```

Some printf debugging shows that (I think) `json_tokener_parse()` is failing here.. which is strange because the result of `kvs_watch_once` is directly generated by `Jtostr()` !?

**Comment by garlick** [comment]
@grondo just showed me that libjansson was at first being linked in with the sched.so but after removing the .la files from side-installed flux-core, it no longer was.  However, problem didn't go away.  In other words same result as in travis.

Looking at dlopen flags, I wonder if we should be using RTLD_DEEPBIND when dlopening comms modules like sched?

> Place the lookup scope of the  symbols  in  this  shared  object
              ahead  of  the  global  scope.  This means that a self-contained
              object will use its own symbols in preference to global  symbols
              with  the  same name contained in objects that have already been
              loaded.

i.e. sched calls json_tokener_parse which internally calls one of the  symbols that overlaps jansson, jansson is loaded in the global symbol table of the broker, result = sadness.  I will try to test this theory.

**Comment by garlick** [comment]
That seems to gotten me past the initial failure, only to fail on the `t0002-waitjob.t` test.  Running `flux waitjob` manually hits:
```
waitjob: error while loading shared libraries: libflux-jsc.so.0: cannot open shared object file: No such file or directory
```

I can't remember how that's supposed to work in travis; however, setting `LD_LIBRARY_PATH=$HOME/lib` fixes it.

Seems like this is heading in the right direction?  I'll put together a quick PR for both flux-core and flux-sched to add the RTLD_DEEPBIND flag to the dlopen calls.

**Comment by grondo** [comment]
> I can't remember how that's supposed to work in travis; however, setting LD_LIBRARY_PATH=$HOME/lib fixes it.

Hm, how are the other libflux* libraries being found, but not libflux-jsc?

**Comment by garlick** [comment]
I couldn't see how that normally works (will look some more later)

I didn't find anything different about libflux-jsc.so.0 compared to the other flux-core libraries.  It may just be the first library that got loaded, and that test may be the first time an executable provided by flux-sched (as opposed to flux-core that manages to statically link to its own libraries) is run.

**Comment by lipari** [comment]
I'm thinking the name collision with libjansson is responsible for the sudden failures in test/tresrc.c  I'm seeing a consistent failure of Jfromstr() which is defines in shortjson.h as json_tokener_parse().  A valid JSON string returns a NULL json_object *

**Comment by grondo** [comment]
I did notice in flux-core commands are built with `-Wl,-rpath /path/to/install/lib` whereas flux-sched doesn't append this arg when building `flux-waitjob`. Not exactly sure where the rpath is coming from in flux-core yet.

**Comment by grondo** [comment]
> I did notice in flux-core commands are built with -Wl,-rpath /path/to/install/lib

Ah, that is possibly because they link with libtool using the in-tree .la files, whereas removal of `.la` files in install target causes flux-sched libtool to link "normally"

Here's a build of `flux-waitjob` before removal of `*.la` files in the install prefix (`/tmp/inst`)

```
libtool: link: gcc -std=gnu99 -Wall -Werror -Wno-error=deprecated-declarations -g -O2 -o flux-waitjob flux_waitjob-flux-waitjob.o  -L/home/ubuntu/local/lib /home/ubuntu/local/lib/libjson-c.so -L/tmp/inst/lib /tmp/inst/lib/libflux-jsc.so /tmp/inst/lib/libflux-live.so /tmp/inst/lib/libflux-kvs.so /tmp/inst/lib/libflux-barrier.so /tmp/inst/lib/libflux-core.so /tmp/inst/lib/libflux-optparse.so ../src/common/libutil/.libs/libutil.a -lm -lxml2 /home/ubuntu/local/lib/libczmq.so /home/ubuntu/local/lib/libzmq.so -luuid /home/ubuntu/local/lib/libhwloc.so -ldl -Wl,-rpath -Wl,/home/ubuntu/local/lib -Wl,-rpath -Wl,/tmp/inst/lib -Wl,-rpath -Wl,/home/ubuntu/local/lib -Wl,-rpath -Wl,/tmp/inst/lib

$ ldd flux-waitjob | grep libflux
        libflux-jsc.so.0 => /tmp/inst/lib/libflux-jsc.so.0 (0x00007f24306c5000)
        libflux-core.so.0 => /tmp/inst/lib/libflux-core.so.0 (0x00007f243046e000)
        libflux-kvs.so.0 => /tmp/inst/lib/libflux-kvs.so.0 (0x00007f242fbfd000)
```

And the same thing after removal of .la files
```
libtool: link: gcc -std=gnu99 -Wall -Werror -Wno-error=deprecated-declarations -g -O2 -o flux-waitjob flux_waitjob-flux-waitjob.o  -L/home/ubuntu/local/lib /home/ubuntu/local/lib/libjson-c.so -L/tmp/inst/lib -lflux-jsc -lflux-live -lflux-kvs -lflux-barrier -lflux-core -lflux-optparse ../src/common/libutil/.libs/libutil.a -lm -lxml2 /home/ubuntu/local/lib/libczmq.so /home/ubuntu/local/lib/libzmq.so -luuid /home/ubuntu/local/lib/libhwloc.so -ldl -Wl,-rpath -Wl,/home/ubuntu/local/lib -Wl,-rpath -Wl,/home/ubuntu/local/lib
$ ldd flux-waitjob | grep libflux
        libflux-jsc.so.0 => not found
        libflux-core.so.0 => not found
```
