### ISSUE TITLE
tag flux-sched v0.3.0

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-sched#221]
[v0.5.0](https://github.com/flux-framework/flux-core/releases/tag/v0.5.0) of flux-core was just tagged and we'll need a version of flux-sched that works with it, if nothing else to build RPMs for TOSS systems.

If there is any more work needed before a v0.3.0 release, we can make a milestone and pin issues.

Otherwise, perhaps I'll take a stab at the `NEWS.md` file, maybe starting with [@garlick's script](https://github.com/flux-framework/flux-core/blob/master/src/test/relnotes.sh), and post a pre-tag PR?

**Comment by lipari** [comment]
@grondo, there is nothing I have waiting in the wings that should be included.  @dongahn and @SteVwonder can chime in, but I believe flux-sched is at a good state for release.  I would appreciate you working on generating the NEWS.md file.

**Comment by grondo** [comment]
@lipari, seems like the main enhancement since 0.2.0 is your PR entitled "Graph work"

Can you give a bullet summary for the NEWS file on that? I'll paste it in. I don't think the straight list of PRs merged is warranted for flux-sched like we did in flux-core, I'll just summarize.

**Comment by lipari** [comment]
Sure.  Extended the resource model to support resource membership in multiple hierarchies beyond the existing physical hierarchy.  Also added the flow graph to model flow.  These two enhancements opened the way to support the scheduling of power and bandwidth.  The existing mechanisms for finding and selecting available resources was extended to consider and allocate power and bandwidth.
Yet to do:  Modify flux-submit to support power and bandwidth requirements and migrate to the new system for representing a canonical job request.
