### ISSUE TITLE
problems with backfill scheduling

### ISSUE THREAD

**Issue by lipari** [flux-framework/flux-sched#224]
In an email to me from Yiannis, I received the following reports of bugs:
* jobs submitted via flux-submit that do not specify a --walltime option receive a 0 wallclock request
* Jobs submitted via flux-submit that specify a non-zero --walltime option are never scheduled
* Requesting the sched options specified in the NEWS.md file don't work:
```
[root@c0 flux-sched]# flux module load sched.backfill reserve-depth=-1
flux-module: sched.insmod[0]: Function not implemented
[root@c0 flux-sched]# flux module load sched plugin=sched.backfill 
reserve-depth=1
2016-11-02T13:48:33.571114Z sched.err[0]: can't process module args
2016-11-02T13:48:33.571141Z sched.crit[0]: fatal error: Invalid argument
flux-module: cmb.insmod[0]: Invalid argument
```

**Comment by lipari** [comment]
I already have a fix on my branch for the first item.  And I have started diagnosing the cause of the second.

**Comment by lipari** [comment]
Just pushed a branch that addresses the above 3 bugs.  In addition, I found what looked to be behavioral problems with the backfill plugin's reserve-depth parameter.  Specifically I made it work like so:
      <0  = Conservative Backfill
            Make a reservation for every job in the queue up to queue_depth
       0  = All backfilling (no reservations)
            Make no reservations.  Run whatever jobs can be backfilled
       1  = EASY Backfill
            Make a reservation for the top priority job, but then run
            whatever jobs can be backfilled on non-reserved resources
       >1 = Hybrid Backfill
            Conservative Backfill with a reserve_depth that is less than
            the queue_depth.

**Comment by dongahn** [comment]
I think this is done with @lipari's latest fixes.
