### ISSUE TITLE
Add a mechanism to assign a priority value to pending jobs

### ISSUE THREAD

**Issue by lipari** [flux-framework/flux-sched#228]
The idea is to decouple job scheduling from job prioritization.  This would allow the two activities to proceeded in parallel and potentially on different resources.  The goal is a solution that maximizes performance and flexibility, while minimizing bottlenecks and race conditions.

Reference the discussion which grew out of [PR 226](https://github.com/flux-framework/flux-sched/pull/226).  The desired behavior is to sort pending jobs by size.

**Comment by lipari** [comment]
> I was just asking where the job management services and in particular queuing services should belong to if that's not the scheduler service itself. Maybe the scheduler service can be grown into basic job queue services and have other services built around them...

The approach I'm proposing is to have flux-submit insert the job request into the KVS - like it does now.  One of the keys of each job will be a priority value, with a default of one less than the previously submitted job.

The job prioritization service, if it exists and is loaded, will visit each job in the KVS and potentially update each job's priority value based on the rules it enforces.  The at the top of its scheduling loop, the sched module would grab the top n jobs in priority off the queue and attempt to schedule them.

**Comment by morrone** [comment]
I am going close this ticket and start a new one that cover the current job priority plugin plans.
