### ISSUE TITLE
Bug suspected: "simsrv" -> "sim_exec"  in sim_execsrv.c ?

### ISSUE THREAD

**Issue by augu5te** [flux-framework/flux-sched#229]
I suspect a bug in following https://github.com/flux-framework/flux-sched/blob/master/simulator/sim_execsrv.c#L89
This line should not be flux_aux_set(h, "sim_exec", ctx, freectx) ?

**Comment by SteVwonder** [comment]
@augu5te: yes, good catch. That is absolutely a bug.  Would you like to submit a PR or should I?
