### ISSUE TITLE
test scripts should unload test modules

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-sched#239]
Ideally, test scripts should have a `flux module remove` for every `flux module load`, since after  flux-framework/flux-core#1005, leftover modules will be unloaded without the reactor running, under a timeout, which may not be appropriate for all modules. 

Sched has some imbalances in its test scripts:
```
$ cd t
$ grep 'module load' *.t|wc  -l
54
$ grep 'module remove' *.t|wc  -l
32
```

**Comment by grondo** [comment]
Though ideal, I'm not sure every `flux module load` will have a corresponding `flux module remove` in real world scenarios, so should tests *require* it? If the balance is required, we should perhaps enhance the module loading such that module removal is automatic during shutdown, to avoid accidental errors when initial programs exit before a user has a chance to call `flux module remove` for modules they loaded?

**Comment by garlick** [comment]
Well, it's not really required, but the "automatic unload" path has the restrictions listed above and so is prone to getting stuck and triggering an exit (0) without going through the stack of destructors.  For testing, the implication of exiting through that timeout is that the module unload path might not get test coverage.  Also if we're testing under valgrind, we'll have a lot of expected leaks creating noise in the output.

Once we've tackled the remaining problems with shutdown (flux-framework/flux-core#1006 and flux-framework/flux-core#1007) I think we could look at ways to automate module removal that takes into count inter-rank dependencies and inter-service dependencies, but for now I think the best hygiene practice is to balance loads and removes.

**Comment by grondo** [comment]
Good point, I hadn't thought of decreased test coverage. I was mainly thinking about leaving the exit timeout path untested, which will be a common case if anyone uses `flux module load` interactively (Thus we miss bugs like the one caught recently for unclean shutdown path)

For the test scripts, would it be useful to make use of the sharness `cleanup()` function to push `flux module remove` onto the test script cleanup stack. Or we could wrap `flux module load` in a helper function that does this automatically. A similar function could be used for per-test `flux module load` that called `test_cleanup()` instead.

**Comment by dongahn** [comment]
I think this can be done easily. There is an "implicit" load in our run script but our tests don't use it much.

**Comment by dongahn** [comment]
Not sure if this is still an issue.

**Comment by dongahn** [comment]
I checked all the test cases for qmanager and resource for module load/remove counts and they match. Closing.
