### ISSUE TITLE
Tag flux-sched v0.4.0

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-sched#241]
We're preparing an 0.7.0 tag for flux-core. We'll need a new flux-sched release to go along with this version.

**Comment by grondo** [comment]
Ok, I missed tagging flux-sched v0.4.0 with the v0.7.0 version of flux-core, but we're preparing v0.8.0 of flux-core now, and we'll need a version of flux-sched to go with it.

Ok to tag v0.4.0 of flux-sched after the flux-core release is done?

Here's what I have for changes since v0.3.0:


flux-sched version 0.4.0 - 2016-08-24
-------------------------------------

#### Fixes
 * Fix allocation of cores unevenly across nodes (#226)
 * Fixes and updates to track latest libflux-core API changes
   (#255, #253, #246, #238, #234)
 * simulator: fix and re-enable sim integration tests (#250)
 * Fix autoreconf when using side-installed autotools (#243)
 * flux-waitjob: fixes to avoid flux-core issue #1027 (#244)
 * Other fixes (#227, #231)

#### New features
 * simulator: add ISO time parsing to job traces (#260)
 * resrc: add resource API context support (#236)

#### Cleanup
 * simulator: refactor, cleanup, and ensure proper initialization.
   (#240, #250)

**Comment by dongahn** [comment]
Yes. And from my perspectuve, the readme LGTM except for 2016 vs 2017. Thank you @ grondo!

**Comment by grondo** [comment]
> the readme LGTM except for 2016 vs 2017.

Thanks for catching that

**Comment by grondo** [comment]
Ok, v0.4.0 released and RPMs are building locally for TOSS3 now.
