### ISSUE TITLE
Enable Travis-CI Nightly Build

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-sched#248]
As @grondo (and others) mentioned in today's group meeting, we should enable nightly builds of flux-sched so that we are notified when changes to flux-core break flux-sched (e.g. to avoid the problems in https://github.com/flux-framework/flux-sched/pull/246).

See also:
- https://docs.travis-ci.com/user/cron-jobs/
- https://github.com/flux-framework/flux-core/issues/1093

I don't think I have the correct permissions to change this setting.  @dongahn, @lipari, or @grondo?

**Comment by grondo** [comment]
Thanks @SteVwonder. I added a daily build to Travis-CI cron for flux-sched/master here:

 https://travis-ci.org/flux-framework/flux-sched/settings

I'll also try to see why you didn't have the right permissions.

**Comment by SteVwonder** [comment]
Do we know where the results of cron jobs end up?  It looks like the build is broken (as pointed out in #251), but I wasn't notified via email or github (was anyone else?).  Based on some googling, it looks like we have to manually specify email addresses for notification in the .travis.yml file:
- https://rnelson0.com/2016/12/15/scheduling-regular-travis-ci-builds-with-cron-jobs/
- https://docs.travis-ci.com/user/notifications#Configuring-email-notifications

**Comment by lipari** [comment]
I've been receiving them.  It showed the build was broken.  I assume you had all been seeing them too.

**Comment by SteVwonder** [comment]
Ah. I see.  Well at least someone is getting them.  Maybe because you were the last one to commit to the repo (when you merged the latest PR).  Is anyone else receiving notifications, @grondo or @dongahn?  I'm fine not getting notified as long as someone else is.

**Comment by dongahn** [comment]
@SteVwonder: FWIW, I didn't a notification either.

**Comment by garlick** [comment]
I haven't been results either.  Maybe [this](https://docs.travis-ci.com/user/status-images/) would be useful here?

**Comment by SteVwonder** [comment]
The cron job documentation says: (https://docs.travis-ci.com/user/cron-jobs/)

> Cron job builds use the same notification settings as normal push builds, and you can skip them in the same way

The build notification documentation says: (https://docs.travis-ci.com/user/notifications#How-is-the-build-email-receiver-determined%3F)

> By default, a build email is sent to the committer and the author, but only if they have access to the repository the commit was pushed to. The email address is then determined based on the email address in the commit, but only if it matches one of the email addresses in our database. We synchronize all your email addresses from GitHub, solely for the purpose of build notifications.
> 
> The default can be overridden in the .travis.yml as shown above. If there’s a setting specified, Travis CI only sends an emails to the addresses specified there, rather than to the committer and author.

Travis CI's main flux-sched page (https://travis-ci.org/flux-framework/flux-sched) lists me as the most recent author and committer, but I don't see any emails from Github or Travis about a broken build. Maybe I don't have my Travis-ci notifications configured correctly ¯\\_(ツ)_/¯ I will look into that further.

Either way, it would be nice if all maintainers of flux-sched got an email when the cron job detects a broken build.  We could do that by listing out all of our emails in the travis.yml file, but then non-maintainers would not get emails when they submit PRs to flux-sched.

**Comment by SteVwonder** [comment]
It seems that the email notifications from Travis are still going into a digital blackhole (since the build is currently broken but presumably no one received a notification that it is).  @trws suggested we configure travis to send flux-sched build notifications to a flux-dev mailing list.  Thoughts?

**Comment by lipari** [comment]
ok by me.

**Comment by dongahn** [comment]
Is this still an issue?

**Comment by SteVwonder** [comment]
Yes, I believe it still is.  Do we have a flux-dev mailing list that we can direct Travis emails to?  I don't think flux-discuss is the correct place for these emails.

**Comment by dongahn** [comment]
We no longer use Travis.
