### ISSUE TITLE
Add support necessary to time-based scheduling schemes

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-sched#25]
We discussed this at today's flux meeting (5/11/2015). Soon flux-sched will need support so that time-based scheduling algorithms/policies including EASY and conservative backfills can easily be implemented as a scheduler plugin. We discussed at least two possibilities: 1) we do this by building time-range querys as part of RDL abstraction and/or 2) by supporting data structures (e.g., gap_list) that can keep track of RDL states over time (e.g., gaps_list). Either has pro and cons. Ideally, either can be built on top of the same underlying mechanisms. Regardless, this support must resource-effiecient and performant with respect to very high numbers of resources and jobs.

**Comment by trws** [comment]
It seems there's no good way to reference a milestone across repositories, so this is referenced in a tracking ticket for S2 from the flux core repository.  See the link above this comment.

**Comment by dongahn** [comment]
Got it. Thanks!

**Comment by lipari** [comment]
Further discussion has moved to [Issue 62](https://github.com/flux-framework/flux-sched/issues/62)
