### ISSUE TITLE
Track Latest Change to flux-core

### ISSUE THREAD

**Issue by lipari** [flux-framework/flux-sched#251]
Unless there is a compatibility option I'm unaware of, the merging of flux-core's [PR 1095](https://github.com/flux-framework/flux-core/pull/1095) appears to have broken the flux-sched build.

make[2]: Entering directory `/g/g0/lipari/flux-sched/simulator'
In file included from simulator.c:35:0:
/g/g0/lipari/local/include/flux/core.h:33:22: fatal error: core/kvs.h: No such file or directory
 #include "core/kvs.h"

**Comment by garlick** [comment]
Ah, sorry about that.  I think I got kvs.h installed into the wrong directory.  Will add a fix to flux-framework/flux-core#1066.

**Comment by lipari** [comment]
Thanks, @garlick!  That will fix the build when it is merged.
