### ISSUE TITLE
Installing simulator modules on `make install` of flux-sched

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-sched#258]
Any opposition to installing the simulator modules (i.e. submit, simexec, sim) in `$INSTALL_DIR/lib/flux/modules/sim`?  This would make the usage of the simulator possible from both source versions of flux but also in-tree version.  Currently the only way to run the simulator is in-tree.

**Comment by lipari** [comment]
no objection

**Comment by grondo** [comment]
closed by #440
