### ISSUE TITLE
sim: change to a more sane format for the job traces

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-sched#259]
Currently the input format is based off of SLURM's job output format. The fields parsed and required can be significantly pared down.  For example, "user", "account", "start", and "end" columns are not used at all in the simulation, but are still parsed (and I believe required) by the submit module.

**Comment by tpatki** [comment]
I'm wondering if it will actually be more useful to support the existing slurm format (select sacct fields), so people can use existing traces (from LLNL as well as elsewhere)? Thoughts?

**Comment by sampollard** [comment]
I agree with @tpatki, I think it would be great to have a minimum set of fields (i.e. a subset of the `sacct -e` command), and even an accompanying sample command. For example,

```
sacct -X -P -S $START_DATE -E $END_DATE --allusers --format=jobid,jobname,partition,alloccpus,elapsed,state,exitcode,start,end
```
where it is assumed that if you have extra it would simply ignore them (perhaps log that they are being ignored).

Also, the `-P` flag makes the csv delimited with a `|`.
