### ISSUE TITLE
Placement of hierarchical scheduling modules

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-sched#263]
@dongahn and I discussed uploading the hierarchical scheduling modules that I developed for my research.  We couldn't settle on the proper place for them.  Should we make a place for them in flux-sched?  Or should we create a separate repository in flux-framework and upload them there?

My preference would be to keep them separate from flux-sched, since they are far from production-ready.  Although they might be compatible with newer versions of flux-core/sched, I have only tested them with an older version from last year. They also do not have any CI tests.

@dongahn made a good point that creating a separate repository adds more friction for users that want to try out the hierarchical scheduling.

Any thoughts from others?

**Comment by lipari** [comment]
My preference would be to keep them separate for now.  flux-sched is already pretty complicated and it's about to become even more so with the incorporation of @dongahn's planner work.  We can revisit how best to incorporate hierarchical scheduling once the dust settles.

**Comment by dongahn** [comment]
I agree with @lipari. There will be a big churn in the next few months, and we want to manage our complexity as much as possible.

**Comment by SteVwonder** [comment]
Sounds good.  Any preference on where the separate repo should be? Should we push them to a repo within flux-framework or somewhere else (LLNL bitbucket, or personal GitHub)?

**Comment by dongahn** [comment]
My preference is to have it under our flux organization to make it easy to merge it into sched later down the road.

**Comment by SteVwonder** [comment]
@dongahn, I'm unable to create a separate repo under the flux-framework org for the hierarchical modules.  I believe this is because I am only a "member" and not an "owner" of the org. Since you are an "owner", I believe you can create a repo. Could you create one for me and give me write permissions to it?

**Comment by dongahn** [comment]
@SteVwonder: Sure. What should be the name of this repo?

**Comment by SteVwonder** [comment]
No real preference.  What do you think of `flux-framework/flux-hierarchy`?

**Comment by dongahn** [comment]
@SteVwonder: ok, I've created the repo. The instructions from GitHub:

```
echo "# flux-hierarchy" >> README.md
git init
git add README.md
git commit -m "first commit"
git remote add origin git@github.com:flux-framework/flux-hierarchy.git
git push -u origin master
```

or 
```
git remote add origin git@github.com:flux-framework/flux-hierarchy.git
git push -u origin master
```

**Comment by SteVwonder** [comment]
Thanks! Before making the initial commit, I have two copyright questions.

One, should I place the LLNL copyright header at the top of each source file?

Two, which LICENSE should I use?  It looks like `flux-core` and `flux-sched` are GPLv2 and @trws went for GPLv3 with `capacitor`.

**Comment by dongahn** [comment]
I think this should be covered under the same code R&R under which flux is released. I vaguely remember that was initially GPLv2. There could have been more updates since. @garlick or @grondo?

**Comment by trws** [comment]
If it’s to be linked into user code, I think we’re now LGPL2, 
otherwise GPL2.  At least that was my understanding?

**Comment by dongahn** [comment]
@SteVwonder: now that I think about this, LGPL2 would make more sense with this layer. It will be pretty close to the user codes, workflow managers etc. So even if you don't any libraries that the app links to at the moment, LGPL can help facilitate broader adoption in the future.
