### ISSUE TITLE
Survey needed for existing scheduler resiliency models

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-sched#264]
We talked a bit about this at today's meeting. This issue is created first to list the resiliency models (taxonomy) of the existing schedulers, which then should inform us in determining the best model for sched, subject to the underlying mechanisms being evolved.

**Comment by dongahn** [comment]
flux-core's resiliency mechanisms that can be used here will be discussed in flux-core[#1187](https://github.com/flux-framework/flux-core/issues/1187) and flux-core[#1186](https://github.com/flux-framework/flux-core/issues/1186). We should factor these mechanisms into our discussions on the level(s) of scheduler resiliency we want to provide.

**Comment by dongahn** [comment]
BTW, today we talked briefly about multi-level resilience and how a service itself such as scheduler service(s) can recover from a fault. If we have good ideas, we can use this ticket. 

I have been vaguely thinking, at least the resource matching service can periodically dump the entire resource graph data store into a plain text (maybe in the **R** format) as a checkpoint and read it back in on certain classes of faults to recover the state. If there is existing research in this area, I would like to read upon some papers.

**Comment by lipari** [comment]
There are a number of categories of data the scheduler needs periodically, atomically, and persistently stored to allow it to survive a crash.  These include pending and running jobs, the resources it is scheduling, any reservations (yet to be implemented in Flux), and used resources quantities that will influence scheduling decisions, like fair-share.

**Comment by dongahn** [comment]
Thanks. 
>  pending and running jobs

Maybe, this can be restored from the KVS job schema so that we can piggyback our future KVS resilience work.

> the resources it is scheduling

Since we will not dump the entire resource graph store into KVS, it seems having some well-known recoverable points and periodically dump the resource store into a file system may make sense here.

> any reservations 

This is different than reservation operations for backfilling, I assume... What information do we need to be able to restore a reservation? 

> used resources quantities 

Yeah.. I wonder if the accumulated resource usage should also go to KVS job schema so that we can also piggyback our future KVS resilience work...

**Comment by lipari** [comment]
>>  any reservations
> This is different than reservation operations for backfilling, I assume... What information do we need to be able to restore a reservation?

Indeed.  "Reservation" is an overloaded term.  For the resiliency discussion, it refers to an immutable virtual job the scheduler has created in the future.  When the reservation's start time is reached, the job runs on the reserved resources and allows only those users specified in the reservation to run.  This is the way we implement dedication application times (DATs) as well as planned system down time.

>>  used resources quantities
> Yeah.. I wonder if the accumulated resource usage should also go to KVS job schema so that we can also piggyback our future KVS resilience work...

Our provenance plans call for jobs to be reaped and ultimately saved in some way (probably a database of some sort).  This would allow a user to query the database and retrieve records of past jobs.

The fair-share priority component depends on a very specific aggregate of combined usage divided into user/account bins.  And this is subject to half-life decay.  These bins are apart from the job records and would need to persist across crashes.

**Comment by lipari** [comment]
> What information do we need to be able to restore a reservation?


The fields of a reservation include:  name, start time, end time, reserved resource quantities (usually node count)  OR a list of specific resources (usually hostnames), users, user groups, or charge accounts allowed access to the reservation, and then flags that define the reservation's application.

**Comment by dongahn** [comment]
> The fair-share priority component depends on a very specific aggregate of combined usage divided into user/account bins. And this is subject to half-life decay. These bins are apart from the job records and would need to persist across crashes.

Ah. Another reason I should review your fair share interface interim work. Let's discuss this some more as part of that review -- e.g., call out specific fields that need to persist betwee crashes. Thanks.

**Comment by dongahn** [comment]
This was useful. Thanks @lipari!
