### ISSUE TITLE
User-data scratch space in the jobspec implementation

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-sched#266]
Hi @morrone: 

You and I talked about where in your jobspec implementation I can put the request aggregate information or find an alternative.

Just to remind you, say I have this jobspec, `cluster[1]->rack[2]->node[2]->socket[2]->core[8]` I want to put aggregate information on a subtree like: `cluster[1](core:64)->rack[2](core32)->node[2](core:16)->socket[2](core:8)->core[8]` Then, such subtree aggregate info will be used to prune the search as part of the preorder walk. What will be aggregated should be programmable by the scheduler itself, of course.

It turns out `map<string, int64_t>` for each resource vertex will just do fine for my purpose. Now, I would like to reach a design decision with you so that I can firm up my implementation.

I have three options and depending on what you prefer, I can go with any of these.

1. Introduce `void *usr_data` in `class Resource`
This will be most generic and thus definitely support my need. The downside is type safety and memory management. 

2. Introduce `map<string, int64_t> usr_data` in `class Resource`
This will definitely support my need and will also be type safe. In addition, you can do your memory management within the destructor of jobspec. But this will not be as generic as 1) and a bit memory inefficient.  

3. Not adding usr_data at all
 If you don't see other use cases for such user data scratch space, NOOP also works for me. I can create my own data structure to keep track of aggregates. This is less than ideal for me, but okay to work with.

Can we quickly reach an agreement between these options or an alternative? Once I will finish an end-to-end demonstration of  my`resource-query`, I will start doing lots of code cleanup/refactoring and having decisions like this will help me avoid redo the work later.

**Comment by morrone** [comment]
Of course 3 doesn't require me to do anything at all, so of course I am fine with that one.  :)  But I think 3 is not an option you really want to endorse.

The other option I suggested was:

4. Convert the classes to templates of classes, allowing the user to specify the user_data data type.

Two possibilities I see for templating without having actually played with them yet:

1. Both Jobspec and Resource are templates.  The type passed to Jobspec is passed by it to Resource, which uses it as the type for its templatized user_data field.

2.  Only Jobspec is a template, and the type of Resource becomes the type option.  Users can then subclass Resource to extend it as they see fit.  (At least I think that is possible...I'm still new to C++).

**Comment by dongahn** [comment]
Sure. The template option should work for me as well.  My template argument will simply `std::map<std::string, int64_t>` 

I was a bit hesitant to suggest a template option (although we discussed it) because you may have to put most of your logic directly into the header file; and I wasn't sure if you want to take that route when your implementation is in .cpp. BTW, does jobspec ever need to be used by C code? 

I understand 4.1 but I'm not sure if I fully understand 4.2. But at the first glance, extending Resource seems a bit overkill. I'm open to the idea, though.

**Comment by morrone** [comment]
> I was a bit hesitant to suggest a template option (although we discussed it) because you may have to put most of your logic directly into the header file; and I wasn't sure if you want to take that route when your implementation is in .cpp

Ohhhh, right.  Option 4 still intrigues me, but maybe that is overkill.

Well, I look at like this:  this "user_data" addition is already an extension to Resource and when you get right down to it, it is a bit of a layering violation to do that.  The jobspec library layer makes no use of that information.  It is all data that belongs to another layer.  So I guess option 3 really still is the one I like best.

But in the interest of compromise, I think maybe option 2 is the option that I dislike the least. :)  Shall I go with that?

> BTW, does jobspec ever need to be used by C code?

That is hard to say at this point.  There isn't anything in the library that can be used from C yet.  My hope is that nothing will need a pure C interface to access the details of the classes.  Hopefully, there will only be higher level functionality that needs to be exported as C symbols (e.g. check_that_this_file_parses_cleanly()).

For code that needs to do more detailed work with the jobspec, I think it is reasonable to write those immediate functions in C++.  The rest of the program can still be written in C, for C-language die hards.  There is a minor learning curve to figure out the linking between the two, but I think I understand enough about that to help others with it in the future.

**Comment by dongahn** [comment]
> Well, I look at like this: this "user_data" addition is already an extension to Resource and when you get right down to it, it is a bit of a layering violation to do that. The jobspec library layer makes no use of that information. It is all data that belongs to another layer. So I guess option 3 really still is the one I like best.

Yeah, that's along the line I was thinking behind #3 (principle). But in practice adding one field can save whole bunch of othe code and performance. So maybe we can consider this item as a co-design. So...

> But in the interest of compromise, I think maybe option 2 is the option that I dislike the least. :) Shall I go with that?

I like that spirit :-). Yes, let's go for it!

**Comment by morrone** [comment]
OK, user_data is added to Resource in my branch https://github.com/morrone/flux-core/tree/job-ingest.

**Comment by dongahn** [comment]
LGTM. Thanks!

Just curious, I see you use unordered_map as opposed to the plain map, which in this case makes perfect sense as the speed would be the optimization point. But I saw a posting saying map still has memory overhead advantages compared to unordered, when you need to optimize for memory. Did you happen to look at how much memory overhead differences unordered vs. ordered map makes?
