### ISSUE TITLE
Test for libuuid

### ISSUE THREAD

**Issue by morrone** [flux-framework/flux-sched#273]
Flux sched should have an autoconf test for libuuid.

**Comment by dongahn** [comment]
@morrone: just to clarify, we have this line in configure.ac:

> AC_CHECK_LIB([uuid], [uuid_clear])

Are you asking we need other tests?

**Comment by morrone** [comment]
The build failed to work when libuuid was missing.  So if there is already a test, either it needs to be a hard requirement, or something needs to be compiled conditionally when that library is unavailable.

**Comment by SteVwonder** [comment]
Bumping this issue, just ran into it on a fresh Ubuntu 18.04 install.
libuuid should also be listed in the README.
