### ISSUE TITLE
build: find out lua paths for flux-core at configure time

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-sched#279]
In pr #278, @grondo ran down a problem that was causing the sched `trdl` test to fail:

> The rdl/test/trdl test is failing because it can't find the flux.hostlist module in LUA_CPATH as exported by the Makefile. (This is the problem I reproduced on my desktop anyway)
>
> The problem seems to be that, up until now, compiled Lua modules have been found under $prefix/lib64/lua/5.1/. However, when I now install flux-core on my desktop they go under $prefix/lib/lua/5.1/. I'm not sure when/how that changed, but a temporary fix would be to look in both paths during make check.

I incorporated his temporary fix in pr #278 to get travis to pass, but for a long-term fix he suggested

> A better long term fix is for flux-sched to pick up the actual Lua paths from flux-core at configure time.

**Comment by grondo** [comment]
Is the flux-core "luaexecdir" something that can go into the pkg-config file?

Also, somewhat related, we should probably update flux-sched ax_lua.m4 to match that used in flux-core.
