### ISSUE TITLE
Flux future reservation design

### ISSUE THREAD

**Issue by morrone** [flux-framework/flux-sched#284]
We need to plan how we are going to handle future reservations in flux.

Presumably, before the requested resources are allocated, the reservation request is mostly tracked by flux-sched, more-or-less like it would track any pending job in its pool of job requests except that it will block out a fixed period of time in the future for when the resources will be granted rather than the start time changing as the job's priority changes.

Once the reservation is granted though, how will jobs be run under the newly allocated resources?

(We must keep in mind that the reservation may need to be usable to multiple users, or a group, or some other combination of entities.)

When we begin an allocation, who/what gets charged for the reserved resources?  Depending on how we implement the reservation mechanism, the resource may be idle at times.  But one might decide that all of the resources should be charged to some account, since the resources _are_ logically assigned to the reservation and unusable to other people on the system.

So perhaps reservations have an assigned account to charge.  But then how to we handle who can run under the reservation?  Do eligible users need to be members of that account?  If they are not, does the reservation's account still accumulate usage, or does the user+account of the job accumulate that set of usage instead?

Our decisions here will influence the design of resource usage tracking (issue #285) and by extension the design of the job priority plugin (#282).

**Comment by dongahn** [comment]
Maybe a reservation can specify a user or a set of users as well as an account that will be charged if the reserved allocation is idle. If a single user, the default account to charge for idling time maybe that user...

BTW, I am not yet fully clear how we implement an advanced revervation system in flux though.

**Comment by SteVwonder** [comment]
> When we begin an allocation, who/what gets charged for the reserved resources?

>  But then how to we handle who can run under the reservation?

By `reserved resources` do you mean the resources in the current allocation (i.e., the resources actively being used by a job)?  Or do you mean the future resources that had been reserved (i.e., charging users for the time that certain resources spent reserved for them)?

With `reservation` I think of a set of resources that have been set a side for a job at some point in the future (to guarantee that starvation doesn't occur).  Once that future time arrives, the `reservation` is converted into an `allocation`, in which the job actually executes.  So at least in my mental model, no jobs ever execute in a `reservation` and jobs are only charged for their `allocations`.  I think it would be helpful to me if you expounded on what you mean by `reservation`.

Tying back into the discussion in #282, I am not necessarily convinced that we need to charge accounts for `reservations` in order to reach our S4 goal.  AFAIK, SLURM only charges accounts for `allocations` and not for `reservations`.

**Comment by morrone** [comment]
> With reservation I think of a set of resources that have been set a side for a job at some point in the future (to guarantee that starvation doesn't occur). Once that future time arrives, the reservation is converted into an allocation, in which the job actually executes.

I'm talking about a different kind of reservation.  A good example is what we call a "Dedicated Application Time (DAT)" around here.  Some person, or group of people, reserve a set of resources at a particular time in the future.  For example, Group B needs 2000 nodes to themselves for 24 hours starting at 8am on Thursday.  There is not necessarily a single job that Group B wants to run.  There may be many jobs to run, and there may be a degree of manual tweeking of the runs, so there can also be idle times during the DAT.    Nevertheless, Group B's account should probably be charged the entire time.

It is a common use case that is not terribly well supported in slurm.

If we want to call this an "allocation", that is fine with me.  But now we need to figure out how to run jobs in the allocation.

I am not advocating that this needs to be implemented for S4.  I am just requesting that we makes some decisions about the the broad strokes of the _design_ soon, because it will influence the way that we implement the things at are part of S4.

**Comment by dongahn** [comment]
I think this is generally called "advanced reservation."

**Comment by SteVwonder** [comment]
@morrone: thanks.  That makes a lot of sense to me.  I am in agreement with your idea that all of the resources should be charged to some account regardless if they are idle or not.

Do we know how LC handles DATs under SLURM currently?  I am only aware of a few pieces to the puzzle.  I know they usually create a job in the queue that is set to start when the DAT is scheduled.  That way users that don't want their job preempted for the DAT can set their jobs to run after the "DAT job".  I am totally ignorant of what happens once the DAT is supposed to start.  Do LC staff manually set the DAT nodes to drain and then kill all the jobs running on those nodes?  How do users submit jobs to those DAT nodes? Maybe the nodes are moved to a special queue that only the DAT users have permissions to submit to.

In the long term, it would be cool to spin up a nested Flux instance within the DAT resources.  The permissions in that instance could be configured to accept connections/jobs from every user in the group that has requested the DAT.  Once we have support for dynamically sized resource allocations, we could even spin up a 1 node Flux instance before the DAT is started, to allow the users time to submit all their jobs.  Then once the DAT's `advanced reservation` becomes an `allocation`, we could  expand the 1 node Flux instance's resource set to include the DAT's resources.

**Comment by morrone** [comment]
I talked to a couple of people, and I think I have a clearer view of how we do this with slurm.

We use slurm reservations (https://slurm.schedmd.com/reservations.html) for our DATs.

It usually works like this: About an hour before the DAT time, the reservation is created.  Because this is so close in time before the reservation's start time, many of nodes in the DAT will still have jobs running on them when the reservation starts.  Slurm will not kill those jobs.  The operators then go in and kill off all of the running jobs that are still employing the reservation's resources.

Users can submit jobs to a "reservation" much like they would to a "partition".  So the one hour early creation of the reservation gives our users a little time to get things queued up before the start time.  Slurm would allow the reservation to be created much earlier (days, weeks, etc.), but in practice we avoid that because the resources that are going to be used in the reservation would likely go idle for hours before the reservation's start time.  We like to keep our usage numbers as high as possible.  And very often our user's jobs checkpoint frequently, so it is reasonable to allow a 12 hour job to be killed after 10 hours.  The user gets work done, and the usage numbers stay high.

Slurm "reservations" seem to be a lot like "partitions" with added time constraints.  Plus a number of other small differences. :)

This might be a place where having a minimum run time expressed in the job request would allow flux to run better than slurm.  Then a job that wants 12 hours, but has a minimum of 1, could have started when there are only 9 hours until a reservation's start time.  It would also then allow flux to terminate the jobs when the reservation begins rather than making the operators kill them.  

Another small local usage detail is that we often add additional nodes to the reservation in case of hardware failures during the reservation.

**Comment by dongahn** [comment]
Thank you for the findings @morrone. Did you happen to talk to them about the accounting details Slurm uses as well? Like what account(s) are used when the nodes are idle?

**Comment by dongahn** [comment]
Advanced reservation (AR) can be easily implemented by "allocating" a job into the future. With the capability within our fluxion resource, this can be easily extended. We will plan this work when it is needed as part of our future rollout.
