### ISSUE TITLE
Tracking Resource Usage

### ISSUE THREAD

**Issue by morrone** [flux-framework/flux-sched#285]
Flux needs to implement a system that tracks and adjusts usage of resources over time.

In slurm, (ignoring "TRES" for a moment, becuase I haven't investigated that yet), usage boils down to a single floating point value per account, and per user per account.  The latter is "per user per account" rather than just "per user", because a user may be a member of multiple accounts and each user/account combination is treated as a separate entity for usage and job prioritization purposes.

One of our first decisions will need to be where this information is tracked.  Will it be in flux-core?  flux-sched?

One of the main consumers of usage information will be the prioritization plugin (issue #282), which resides in flux-sched.  Also, flux-sched may perhaps be in the best position to decide when usage accumulates.  flux-core might only know about actual running jobs.  Depending upon the way we implement reservations (issue #284) flux-core may or may not know about an ongoing reservation; it may only see running "jobs".

The usage tracking system also need to implement an optional usage decay system, in which usage values diminish over time (for instance, exponential decay in slurm).

Finally, usage values need to be persistent in some way.  Potentially, this information could be reconstructed from historical job usage (although extra handling for reservations might be required depending upon implementation).  We don't necessarily need to go back in time to the beginning of known jobs when decay is used.  Instead we could read back in time to some multiple of the decay half-life.  For instance, usage decays to under 1% of its original value after seven multiple of the half-life.  For a half life of two weeks, that would mean reading 14 weeks of job data to reconstruct a reasonable approximation of the usage data.

Alternatively, the usage data could be stored regularly in some persistent store (KVS?).  Perhaps some combination of the two approaches could be employed: regularly, but not excessively frequently, write the usage values to persistent data, and then reconstruct missing information from recent job usage records.  This of course assumes that job start/end records are reliably written to persistent storage.

**Comment by dongahn** [comment]
This reminds me of a discussion we had wild back about dumping the snapshot of information to some storage. [rfc Issue #116](https://github.com/flux-framework/rfc/issues/116).

**Comment by dongahn** [comment]
Tagging @admgc.

**Comment by dongahn** [comment]
@cmoussa1 owns this and having discussions with the stakeholders with flux-accounting as well as usage DB within flux-core.
