### ISSUE TITLE
Design of "partition" equivalent

### ISSUE THREAD

**Issue by morrone** [flux-framework/flux-sched#286]
We need to evaluate the use cases of "partitions" in slurm and design solutions for those use cases in flux.

In slurm, partitions are sometimes referred to as "queues".  However, strictly speaking they really are not separate queues.  slurm partitions are sets of resource.  A job that is assigned a partition is constrained to only be allocated resources that are within the partition's resource set.

Slurm partitions also have an added wrinkle that they may introduce, or adjust, the rules that effect their jobs.  Also, a user may have different rules that apply to them individually from the "associations" table.  A user may individually have different rules for every single partition that exists, independent of the default partition rules.

The resource sets in partitions are _not_ exclusive.  A resource may appear in many partitions.  It is mainly for this reason that partitions are not truly independent queues, but rather resource constraints applied to a job.  All of the jobs from differing partitions still need to be queued, prioritized, and scheduled as a group.  It is only in the special case of non-overlapping partitions that partitions begin to approximate true separate queues.

One of the common use cases for partitions is to have a set of nodes that are dedicated to smaller, shorter-lived, interactive jobs, and a second partitions for longer running batch jobs.  The former partition is frequently used for interactive development and debugging ("debug" partition), and the latter for real batch computation ("batch" partition).

One thing to notice is that the _real_ use case is normally to reserve some _number_ of resources for interactive debugging, not really to reserve _specific_ resources.

How we go about solving the underlying use cases for slurm partition will likely have implications for the design of the job priority plugin (issue #282) and its interfaces with the rest of the scheduler.

**Comment by garlick** [comment]
Thanks for the excellent problem description!

The debug/batch partitioning is one use case.     As you indicate, I think it's just about reducing the wait time for small jobs with short run time requirements.  Could we have policy knobs for "interactive responsiveness" that prevents jobs with greater than a certain run time requirement from monopolizing more than some fraction of the system?  (Maybe during certain hours?)

Another use case we discussed is for data intensive computing one, where (overlapping) partitions are used to identify sets of specific nodes.  As I understand it, each partition has access to some data set on local storage that persists across jobs.  This seems like slurm is not providing a way to model the storage (or the data set) as a resource, or giving the user a proper way of asking for it, and so partitions are pressed into service. 

Possibly I am over simplifying...

**Comment by dongahn** [comment]
> Another use case we discussed is for data intensive computing one, where (overlapping) partitions are used to identify sets of specific nodes. As I understand it, each partition has access to some data set on local storage that persists across jobs. This seems like slurm is not providing a way to model the storage (or the data set) as a resource, or giving the user a proper way of asking for it, and so partitions are pressed into service.

Interesting. Is this used in catalyst?

**Comment by garlick** [comment]
Right.  I'll check in with Trent this week and try to get more detail on this.

**Comment by garlick** [comment]
> Another use case we discussed is for data intensive computing, where (overlapping) partitions are used to identify sets of specific nodes. As I understand it, each partition has access to some data set on local storage that persists across jobs.

I did check in with Trent and got basically the same explanation as above.  Users need a way to specify that they want to run only on the nodes that they previously left data on.

One other use case Trent mentioned for partitions is that some clusters have a "pall" that is the union of "pdebug" and "pbatch", used mainly for sys admins or other special cases to run on the whole system.  He mentioned that pdebug and pall usually bypass "banks and all that" (meaning the fair share calculations?)

**Comment by morrone** [comment]
From recent a recent meeting, it sounds like we would like to try to develop a design that does not use partitions like slurm.  One idea is to allow a "class" to be applied to a job request.  A class could have an aggregate resource limit across running jobs.  For instance, it might have a limit of 20 nodes for a debug class.  But _any_ of the nodes on the cluster could be used to provide the 20 nodes, so the class is less impacted by down nodes than a partition that contains a fixed set of nodes.

Probably the biggest challenge that we will need to address in this approach will be how to address cluster usage reporting requirements.  Currently reporting is generally done on the "pbatch" partition on LLNL slurm clusters.

**Comment by dongahn** [comment]
As you and I chatted, one proposal would be:
amounts of resources (e.g., compute node hours) used by batch class jobs / amount of resources configured to be used by batch class jobs.

This can exceed 1, but I think this is a good thing?

**Comment by SteVwonder** [comment]
@morrone, are we proposing only a upper limit on the number of nodes for a given class. For example, on a 100 node cluster, we could configure up to 100 nodes for batch and up to 20 nodes for debug.  In that case, I think that what @dongahn is suggesting makes sense (i.e. resources actually used by batch class jobs / resources configured as the upper limit for batch class jobs), but we will probably want to report the true cluster utilization in that case (batch usage + debug usage / 100 nodes).

**Comment by dongahn** [comment]
@SteVwonder: speaking w/ @morrone, my understanding is reporting batch usage is just a requirement imposed upon us. BTW, just to be clear, using your example, 100 nodes for batch for Flux (now that we won't have true partitions) are not static. At one time, we may run batch class jobs on node0-node99; at another time, we may run batch class jobs on node20 - node199.

**Comment by SteVwonder** [comment]
@dongahn reading back over your earlier message:

> This can exceed 1, but I think this is a good thing?

I think I'm misunderstanding something.  How can the value exceed 1?   If we are enforcing an upper limit on each class, then the real utilization should always be less than the configured limit, but I think you are thinking of a different scenario that I haven't considered.  Could you give an example where it would be greater than 1?

**Comment by dongahn** [comment]
Yes. To simplify the argument, let's say, there is no debug class jobs to run while there is a bunch of standby batch class jobs that can run. In this case, the entire 120 nodes can be utilized by batch class jobs? So I was thinking 120/100 is the batch utilization for certain duration? For something like this, we can cap at 1 for reporting purpose though.

Make sense?

**Comment by SteVwonder** [comment]
Yes, that clarifies things.  Thanks!

**Comment by morrone** [comment]
> Yes. To simplify the argument, let's say, there is no debug class jobs to run while there is a bunch of standby batch class jobs that can run. In this case, the entire 120 nodes can be utilized by batch class jobs? So I was thinking 120/100 is the batch utilization for certain duration? For something like this, we can cap at 1 for reporting purpose though.

Why would we make "standby" class jobs part of "batch" class if we don't want "standby" to have the same restrictions as the "batch" class?  That is a puzzling approach to me.  It is not terribly clear to me what the rule system would look like to make that scenario happen...would the job have two classes, "batch" and "standby", and somehow we would specify that the limits of "standby" preempt the limits in "batch"?

> amounts of resources (e.g., compute node hours) used by batch class jobs / amount of resources configured to be used by batch class jobs.

When you say "configured to be used", I assume that you mean the resource upper limits?  That does not necessarily meet our needs.  For instance, a reservation for a DAT might not use class "pbatch" because it needs to use the _entire_ cluster.  Now during that DAT, class "pbatch" jobs accumulate no usage, and our reported "cluster usage" based on pbatch is now artificially lower than it should be.

The more that I think about it, it is not at all clear to me that there is an easy way to satisfy the reporting requirement with the less restrictive class model.  Unless we can convince the powers that be to accept a different style of cluster usage reporting.  The latter may be the technically easier approach, but it will be politically quite a bit more difficult.

**Comment by SteVwonder** [comment]
> One idea is to allow a "class" to be applied to a job request. A class could have an aggregate resource limit across running jobs.

Just dropping a note that this was discussed during one of our afternoon coffee meeting.  There are still details to work out, but this approach seems to resonate with everyone.

>  Unless we can convince the powers that be to accept a different style of cluster usage reporting.

As Chris pointed out, we should probably talk to someone that works on utilization reporting (Greg Tomaschke?) before proceeding with this.

Two design points that we should consider are the ability for a scheduler to declare/broadcast which classes it supports and letting simple schedulers ignore the class entirely.

**Comment by dongahn** [comment]
Tagging @admgc.

**Comment by dongahn** [comment]
We settled on multi-queues.
