### ISSUE TITLE
Design of "QoS" equivalent

### ISSUE THREAD

**Issue by morrone** [flux-framework/flux-sched#287]
Slurm has something it calls "QoS".  Essentially, a QoS is a label (action?) that is applied to a job which then results in some set of changes to the processing of the job.  The QoS can change a job's priority, as well as various rules such as whether it can preempt other jobs, or changing (adding, removing, or changing) various limits.  Some common QoS in use at LLNL are (from https://hpc.llnl.gov/banks-jobs/running-jobs/slurm-user-manual)

* normal (nominal priority and standard job size and wall clock time limits)
* expedite (higher job priority and an exemption from job size and wall clock time limits)
* exempt (normal job priority and an exemption from job size and wall clock time limits)
* standby (below normal job priority and an exemption from job size and wall clock time limits)

Some of these QoS levels may require special privileges apply to a job.  Slurm "associations" may grant different QoS access to users by cluster, by partition, and by account.  The columns in an "association" are (at least as reported by the sacctmgr command):

* Cluster
* Account
* User  Partition
* Share
* GrpJobs
* GrpTRES
* GrpSubmit
* GrpWall
* GrpTRESMins
* MaxJobs
* MaxTRES
* MaxTRESPerNode
* MaxSubmit
* MaxWall
* MaxTRESMins
* QOS
* Def QOS
* GrpTRESRunMin

Some common settings at LLNL for the "QOS" field are, "normal,standby", "exempt,normal,standby", and "exempt,expedite,normal,standby".

"associations" and "QOS" tie together a lot of different concepts.  Figuring out how we will address similar use cases in flux will help in many aspects of the scheduler design.  For instance, if our solution allows adjusting priorities, that will have an impact on the design and implementation of the priority plugin (issue #282).

See also https://slurm.schedmd.com/qos.html.

**Comment by dongahn** [comment]
OK, as we discussed today, here is a reference for multilevel queuing in the operating system space: https://en.wikipedia.org/wiki/Multilevel_queue. At first glance, this seems pretty straightforward to applying to flux scheduling. Just grouping classifications are different.

**Comment by dongahn** [comment]
Tagging @admgc from ORNL as he has expressed interest in contributing to Flux on the related areas.

**Comment by dongahn** [comment]
This is not handled through flux-accounting.
