### ISSUE TITLE
Refactor flux_lwj_t code

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-sched#293]
As suggested in https://github.com/flux-framework/flux-sched/pull/291#issuecomment-375002548, job representation needs to be refactored to reduce code complexity -- promoting it to a first level class and changing the name to be flux_job_t as we abandoned the concept of lightweight job long time ago.

**Comment by grondo** [comment]
Can this one be closed by #440?

**Comment by dongahn** [comment]
Yes.
