### ISSUE TITLE
build: configure fails to find boost libraries on Raspbian GNU/Linux 8 (jessie)

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-sched#302]
When building on this system, configure fails with
```
checking for boostlib >= 1.53.0 (105300)... yes
checking whether the Boost::System library is available... yes
configure: error: Could not find a version of the library!
```
even though the boost libraries are installed.  A workaround is to configure with
```
configure --with-boost-libdir=/usr/lib/arm-linux-gnueabihf
```

It would appear that `ax_boost_base.m4` is setting `BOOST_LDFLAGS=-L/usr/lib`, but the boost libraries (and libraries in general on this system) are in the gnueabihf directory noted above.

**Comment by dongahn** [comment]
Oh well...  PI is an animal (?) of itself!

**Comment by garlick** [comment]
True (!) though it seems these macros include hardwired hacks for older architectures, but don't have one for arm, so we may run into it on other multi-arch arm systems.  Low priority.

**Comment by dongahn** [comment]
Agreed. Love those little pi's.  Having all sorts of fun to control church instruments :-).

**Comment by grondo** [comment]
I hit this same/similar issue on ppc64le builder inside of the koji buildfarm.

Let me first just say that the error from `AX_BOOST_SYSTEM` is ridiculously unhelpful.

In order to build flux-sched on this platform I had to add

```
%configure --with-boost-libdir=%{_libdir}
```

Thanks @garlick for the hint.

Further information:

configure output:
```
checking for FLUX_CORE... yes
checking for flux... flux
checking for boostlib >= 1.53.0 (105300)... yes
checking whether the Boost::System library is available... yes
BUILDSTDERR: configure: error: Could not find a version of the library!
```

config.log:
```
configure:18885: checking for flux
configure:18901: found /usr/bin/flux
configure:18912: result: flux
configure:19066: checking for boostlib >= 1.53.0 (105300)
configure:19098: g++ -std=c++11 -c -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mcpu=power8 -mtune=power8  -I/usr/include conftest.cpp >&5
configure:19098: $? = 0
configure:19100: result: yes
configure:19292: checking whether the Boost::System library is available
configure:19317: g++ -std=c++11 -c   -I/usr/include conftest.cpp >&5
configure:19317: $? = 0
configure:19332: result: yes
configure:19491: error: Could not find a version of the library!
```

**Comment by tpatki** [comment]
I might be interested in working on this.

**Comment by tpatki** [comment]
Is there a node/system on which I can reproduce this?

**Comment by dongahn** [comment]
Not sure if we have one among LC systems...

**Comment by SteVwonder** [comment]
What about Ulna?  It is at least ARM.

**Comment by dongahn** [comment]
It might be a porting effort of its own...  Ah. Now that I think about this I had to specify `--with-boost-libdir=` in Sierra. Maybe Sierra is the machine to test this.

**Comment by dongahn** [comment]
@garlick: 

> It would appear that ax_boost_base.m4 is setting BOOST_LDFLAGS=-L/usr/lib, but the boost libraries (and libraries in general on this system) are in the gnueabihf directory noted above.

I see the same issue on `powerpc64le` platforms (rzansel, sierra, and lassen). It looks to me like the root cause is that `ax_boost_base.m4` has just not been ported to powerpc64 little endian, and the following patch seems to solve the issue. 

```diff
diff --git a/m4/ax_boost_base.m4 b/m4/ax_boost_base.m4
index 2bce519..6fe83bb 100644
--- a/m4/ax_boost_base.m4
+++ b/m4/ax_boost_base.m4
@@ -113,7 +113,7 @@ AC_DEFUN([_AX_BOOST_BASE_RUNDETECT],[
     dnl are found, e.g. when only header-only libraries are installed!
     AS_CASE([${host_cpu}],
       [x86_64],[libsubdirs="lib64 libx32 lib lib64"],
-      [ppc64|s390x|sparc64|aarch64|ppc64le],[libsubdirs="lib64 lib lib64"],
+      [ppc64|s390x|sparc64|aarch64|ppc64le|powerpc64le],[libsubdirs="lib64 lib lib64"],
       [libsubdirs="lib"]
     )
```

So, I can also add `lib/arm-linux-gnueabihf` for the platform type of your ARM jessie. Do you happen to know what ${host_cpu} looks like on your system? Is that just `aarch64`?
