### ISSUE TITLE
docs: documentation for resource states and transitions

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-sched#307]
Originally mentioned in #305

**Comment by garlick** [comment]
There was an attempt to come up with a list of states for the new system in [RFC 16](https://github.com/flux-framework/rfc/blob/master/spec_16.adoc)

I wonder if it would make sense to just create a new short RFC for job states, how to change them, how to sync on them, and then RFC 16 (and other RFCs) can reference?

**Comment by dongahn** [comment]
Thanks @SteVwonder and @garlick. Yes, a new job state and valid transition RFC makes sense to me. In addition, we need to create a scheduler RFC and should cross refence  this new RFC there as well. As to the scheduler RFC, I believe the right time is when I make a bit more progress with @tpatki on the new data model.

**Comment by dongahn** [comment]
Great info @grondo! For future shrinkable/fault torelent worrkload, it seems we want to make this extendible so that we can support partial migration and partial kill as well...

**Comment by dongahn** [comment]
This has been done.
