### ISSUE TITLE
sched fails to load hwloc data from KVS on sierra

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-sched#308]
(Originally opened as flux-framework/flux-core#1361 but solution turned out to be on the sched side)

On sierra system:

```
2018-03-15T20:43:44.086519Z sched.err[0]: can't load hwloc data: resrc_generate_hwloc_resources: Failed to create resrc from hwloc depth 1: Success
2018-03-15T20:43:44.086548Z sched.err[0]: failed to load resrc using hwloc
2018-03-15T20:43:44.086566Z sched.err[0]: failed to load resources
```

@trws followed up wtih
> I found it, and fixed it, the reader is hard-coded to the resources it will take, and sierra has a new one. WIll upload patch when time.

Then
> It's right [here](https://github.com/flux-framework/flux-sched/pull/296/files#diff-7cc8c5f0cadb0013dfa0589d1e78c50bR801) over in sched.  The "group" type was unhandled.  If possible it would be really good to switch this over to something more generic like what resource.c uses, but this gets it done for sierra.

**Comment by garlick** [comment]
@dongahn says
> It seems this should go into resrc. As part of this, it will be good to take a representative hwloc xml file from sierra and add to our tests. I will see of I can do a quick PR before moving to another project.

**Comment by dongahn** [comment]
@trws:
I gathered hwloc xml files from some sierra compute nodes to use them for testing. For example

```
sierra4371{dahn}23: hwloc-info
depth 0:	1 Machine (type #1)
 depth 1:	1 Group0 (type #7)
  depth 2:	6 NUMANode (type #2)
   depth 3:	2 Package (type #3)
    depth 4:	16 L3Cache (type #4)
     depth 5:	16 L2Cache (type #4)
      depth 6:	32 L1dCache (type #4)
       depth 7:	32 L1iCache (type #4)
        depth 8:	32 Core (type #5)
         depth 9:	128 PU (type #6)
Special depth -3:	24 Bridge (type #9)
Special depth -4:	17 PCI Device (type #10)
Special depth -5:	26 OS Device (type #11)
```

Somehow it shows 32 cores instead of 44 cores. Maybe I'm misinterpreting this... I used `lstopo 0.xml` to generate the xml version of this. Did I do something wrong?

**Comment by trws** [comment]
You ran it on a launch or login node.  Those have 32 cores, it’s the 
compute nodes that have 44.

**Comment by dongahn** [comment]
Thanks. It turns out the 32 core hwloc xml files also have the group type so they are good for testing purposes. 

https://github.com/flux-framework/flux-sched/pull/310 addressed this issue.
