### ISSUE TITLE
high rate job submission stalls sched message queue

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-sched#309]
(originally opened as flux-framework/flux-core#1376)

@trws reported:
> Submitting jobs fast enough, or enough of them over time, stalls sched out completely. I've seen this happen with <5000 jobs when submitted at a very high rate, and around 35000 jobs at a slightly slower rate.

He later added:
> If you want to get it consistently, use `seq 1 50000 | xargs -n 1 -P 15
flux submit -n 1 sleep 0`.  It may take up to 15 minutes to stall out,
but that will do it.

**Comment by dongahn** [comment]
@garlick and I had a good discussion this morning. To summarize the action items that came out from that discussion. Two parts:

- JSC optimization: @garlick will revisit JSC optimization work which includes converting synchronous RPCs to asynchronous ones
- sched optimization:
    - @dongahn will identify synchronous RPCs within flux-sched
    - will restructure the code to use asynchronous. But won't worry about being able to overlapping     handlers in this round -- simultaneous activation of handlers may cause subtle correctness issues and this isn't the main bottleneck for this use case anyway. 
    - Still, while doing 2, will identify those handlers that can be overlapped so that later we can further optimize this by overlapping computation/communication

**Comment by garlick** [comment]
On the overlapping handlers, just to be sure we're on the same page - when you change multiple synchronous RPCs into an asynchronous, you can retain the order of operations you had before by chaining continuations (callback registers another callback, etc..).  But once you register a continuation and return control to the reactor, other messages (and their continuations) can start to be interleaved with the in-progress ones.  I'm not sure if that is a concern in sched.  If it is then probably some internal queues will be needed.

**Comment by dongahn** [comment]
Also, we agreed that we will leave emulator conversion to next time.

**Comment by grondo** [comment]
closed by #440
