### ISSUE TITLE
[enhancement] resrc query request handler is needed

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-sched#315]

**Comment by SteVwonder** [comment]
Is the general idea to build the foundation for the [S3 Resource Status Tool](https://github.com/flux-framework/planning/blob/master/requirements/s3/03-Resource-Services.md)?  Or were you thinking of different functions for this query mechanism?

**Comment by dongahn** [comment]
FYI -- we discussed this https://github.com/flux-framework/flux-core/pull/1418#issuecomment-379898281 and decided to implement this in a future PR. This issue is so that we don't miss it.

**Comment by dongahn** [comment]
Reading the S3 resource status tool once again, I am not sure if this was meanted to be provided by distributed services or the scheduler. 

Certainly, the scheduler needs to provide an RPC to present the state of a resource or a set of resources. But I can see why the distributed services be more scalabke with TBON merging. @grondo or @garlick, what did you have in mind for this?

In any case, implementing this within the current framework should be the goal of this ticket.

Still, how a resource status interface (presumably provided by monitoring service) is implemented in a way to provide the liveliness of resources to the scheduler is TBD. And the protocol in which the scheduler will pass info on the drained info to the corresponding brokers is also TBD.

**Comment by dongahn** [comment]
I came across @grondo this morning and discussed this a bit. The conclusion was:

We will ultimately want a distributed service responsible for querying and controlling resource status. So, for now, let's call it a Resource Status and Control API (RSC API).

Then, the scheduler will ultimately be a user of RSC API (e.g., getting notified of nodes going up and down and being excluded/included) and update its resource state accordingly.

Also, currently node exclusion and inclusion are implemented within the scheduler, but this can create a state inconsistency problem. E.g., if the scheduler does not have a way to communicate a node exclusion to the corresponding broker or this service (which shouldn't be necessary), RSC API will present the state information inconsistent with the scheduler's state. 

@grondo and I agree that we should ultimately move the node exclusion logic from the scheduler to RSC API and be its user. 

Finally, short term, we can add a resource query request handler within the scheduler to provide a stopgap solution while gaining more hands-on. 

For this, we have to decide what are the proper granularities of the query information. For sure, we want to be able to
1. Provide the state information about a single node
2. Provide aggregate information about all of the resources, similar to SLURM's sinfo

But what is other granularities in between, which will be useful? Mocking up the end results of various granularities of this will help implement it.

We will also need a user-facing interface. For rapid prototyping, @grondo and I believe that a path to least resistance would be to augment `flux wreck`: `flux wreck resource-info` or similar.

**Comment by SteVwonder** [comment]
Do you expect the RSC API will also provide information about whether nodes are idle or allocated?  Or is this purely an "up/down" & "excluded/included" query mechanism?

I'm envisioning writing a flux equivalent of `sinfo`.  Under the proposed changes, I envision it querying the RSC API for which nodes are up/down and simultaneously querying the scheduler for which nodes are idle/allocated. Does that sound right?

**Comment by dongahn** [comment]
@tpatki: instead, this might be of your interest since the design pattern will be similar to your other PR. This is something that's readily useful for the current Sierra MLSI push as well.

**Comment by tpatki** [comment]
@dongahn, @SteVwonder: 
As a first cut on this, what type of information (up/down/drained, total/available) and which resources (nodes, cores, gpus?) do we want to support?

**Comment by dongahn** [comment]
@tpatki: I think reporting the full information on nodes and all of their sub-tree resources would be a good start.

As a start, it would be good to allow for two modes: individual node (by taking a hostname from the user) and all of the nodes (if no hostname is provided)?

Extra credit would be to take a jobid and then report the same thing for all of the nodes allocated to the jobid.

**Comment by garlick** [comment]
One thought on this:  there is currently a "nodeset" (a set of ranks e.g. [0-127]) that is built during bootstrap, before rc1 gets executed, and afterwards it is always "full". 

For S3 the core TBON/boostrap code will need to support:
* launching rc2 (initial program) before set is completely full
* running rc1 for new ranks as they join
* a way to administratively add/remove nodes
* a way to automatically remove nodes when they become unresponsive

It seems like the resource status service is a higher level service that will need to be notified when broker ranks join/leave.  It will need to know what resources are associated with a given rank and adjust their status accordingly.

The exec system will also need to be a consumer of this information so it can take appropriate action for jobs running on broker ranks that leave.

It seems like for a first cut we can generate an event whenever the nodeset changes.

We might also want to consider whether resource status information belongs in the KVS under `resource` such that it can be watched.

I'm not sure exactly what you had in mind here for the short term, but just wanted to be sure these other S3 needs were part of the discussion.

**Comment by dongahn** [comment]
> I'm not sure exactly what you had in mind here for the short term, but just wanted to be sure these other S3 needs were part of the discussion.

@tpatki: as we are closing the door for the next release, I think it may make sense to start this work for the long term. 

> It seems like for a first cut we can generate an event whenever the nodeset changes.

@garlick: This seems like a reasonable approach to take. Maybe we can have an agreement on what event will look like and make progress independently for a while? 

> We might also want to consider whether resource status information belongs in the KVS under resource such that it can be watched.

@garlick: who should be the provider for the resource status data in KVS?

> I'm a bit confused about how this will be implemented more generally when we have a resource service though. I see two components here: (1) Monitoring infrastructure that informs the resource service and eventually the scheduler of nodes that went up/down, where the customer for the information is the scheduler module, and 

@tpatki: I think @garlick is proposing an event that gets generated when the nodeset changes. That would be (1). See my comment above.

> (2) Where the customer is the user who queries the system about information about their job or a certain node/resource, and the scheduler has up-to-date information.

I think there are two different types of resource status info. A) simple node status type of info. I guess this can be satisfied by the resource status information in the KVS @garlick is talking about. B) detailed schedule information. I think it makes sense to add a query handler in our new resource matching service?

> When I think of a multi-user system scheduler though, I feel that this current design (scheduler responding to queries) may have some scalability bottlenecks if many users query the scheduler about their jobs or node/resource information. 

True and I have no clear answer yet. Let me give some thoughts on this.

**Comment by tpatki** [comment]
> I think there are two different types of resource status info. A) simple node status type of info. I guess this can be satisfied by the resource status information in the KVS @garlick is talking about. B) detailed schedule information. I think it makes sense to add a query handler in our new resource matching service?

For (A), this won't be showing information about the entire resource tree, correct? I'm assuming that nodeset is just the ranks/nodes. Not sure how this connects with other node-level resources eg GPUs, burst buffers or power/network, which will be available in sched/resource. I'm guessing you mean to capture the latter in (B).

@SteVwonder and I discussed this a bit. If we understand correctly, there'll be an RSC API that sits in core, a resource matching service that sits in flux-sched, and the actual scheduler. Depending on what information we need, we'll have to query different components (e. node up/down goes to RSC API, node allocation info/tree goes to resource service, and job/queue info goes to sched). Is our general understanding of this space correct?

**Comment by grondo** [comment]
>   Depending on what information we need, we'll have to query different components (e. node up/down goes to RSC API, node allocation info/tree goes to resource service, and job/queue info goes to sched). Is our general understanding of this space correct?

I would think all resource queries would go to the resource service. Since nodes are resources, the resource matching service should have up-to-date information about what resources are up/down/drained/allocated/idle/etc. In most cases, users will be interested in what resources are available for scheduling, how much of the system is free etc. So an `sinfo` like tool could be built just from querying the resource service.

Of course, it would be nice if the utility was the same no matter what scheduler you were using, so we should consider if there is a way to build a "RSC" service in core such that it was extensible to allow schedulers and resource matching service to update resources with allocated/idle status, and then we could query the core resource service instead (maybe there is a way to grow resource-hwloc into this thing)

> and job/queue info goes to sched

I think job queries are slated to go to the job manager service in core. We will need some co-design here, but the idea would be to have schedulers send updates for jobs directly to the job manager, which could then be used to build a query interface (e.g. scheduler could add a job priority which would allow a queue listing to be implemented). This offloads job and queue queries from the scheduler to the in-core job manager.

We even proposed the idea of having a lightweight db running hung off rank 0 to store information about all jobs and which could be used to create advanced queries (like sqlog for instance)

Perhaps something similar could be discussed for resource information (just an idea)

**Comment by tpatki** [comment]
>  So an `sinfo` like tool could be built just from querying the resource service.
> Of course, it would be nice if the utility was the same no matter what scheduler you were using, so we should consider if there is a way to build a "RSC" service in core 

@grondo: I thought @garlick was proposing the latter approach (RSC in core) because that's more general, at least with the nodes/nodeset design. More details about resources on each node (eg capturing heterogeneous components such as gpus/burst buffers or power etc) would need interaction with the matching service in sched, I think. Is there a preferred design/implementation you have in mind?

> I think job queries are slated to go to the job manager service in core.
Can you elaborate a bit more on the job manager service you have in mind for core?  I was envisioning the equivalent of `squeue` here, I believe that info sits in sched currently and will have to be communicated to core like you suggested. Is there a vision for what this communication would look like: eg what interfaces, granularity (how often) etc. 

A database/snapshot hanging off rank 0 is a good idea, but I'm not sure how that'd scale, and if the query engine would need to be its own service.

More generally, in terms of design, do we want users pinging core or sched for queries related to resource/queue info?

**Comment by grondo** [comment]
>@grondo: I thought @garlick was proposing the latter approach (RSC in core) because that's more general, at least with the nodes/nodeset design. More details about resources on each node (eg capturing heterogeneous components such as gpus/burst buffers or power etc) would need interaction with the matching service in sched, I think. Is there a preferred design/implementation you have in mind?

I don't have a good implementation in mind. I was (ineptly) trying to make a point that whatever scheme we develop, it should be extensible to be used with other schedulers, so the framework for basic resource and queue query should be in core. (I realize that isn't too helpful at this point!)

> Can you elaborate a bit more on the job manager service you have in mind for core? I was envisioning the equivalent of squeue here, I believe that info sits in sched currently and will have to be communicated to core like you suggested. Is there a vision for what this communication would look like: eg what interfaces, granularity (how often) etc.

We will have to revisit this soon (after Aug 17 unfortunately). I lost my context on it when we were pushing out 0.10. @garlick had developed a prototype for the job manager and the idea was for the list of active jobs to be kept within that service. The scheduler would be notified of new jobs via a job.fetch service or similar, which would block (asynchronously) when there are no new jobs. Schedulers and other Flux components can update various job states via a job update service. The job manager may or may not stream updates for jobs to a job database as described above. (That's the general gist anyway)

> A database/snapshot hanging off rank 0 is a good idea, but I'm not sure how that'd scale, and if the query engine would need to be its own service.

I think the idea would be to wrap the common operations into a frontend service which would allow the backend db to be swapped out. Very small, short-lived jobs could use sqlite or something, and larger long-running instances (e.g. a cluster instance) could be implemented on top of something with known scalability like mongodb. Advanced queries could then target the mongodb directly and avoid targeting Flux directly (e.g. accounting reports, sqlog like functionality, etc.)

> More generally, in terms of design, do we want users pinging core or sched for queries related to resource/queue info?

Long-term, I would argue for core, but this is just my own opinion. I think some design needs to be done here. In the short term (e.g. S3 milestone). It may be easier to develop flux-sched specific interfaces that implement the required queries, then wrap them in the UI we want to present for the long-term. (If that makes sense)

I hope I'm not being unhelpful here...

**Comment by tpatki** [comment]
This is very helpful @grondo, I was trying to understand this space better, let us revisit in mid August again.

**Comment by dongahn** [comment]
Pilot2 workflow team said today that this feature will be very useful for their next round of calculation.

**Comment by tpatki** [comment]
I can look at this again and see if we can help them out. From what I gathered, they wanted general resource information (eg one that will list all nodes as allocated/available/drained). So equivalent of `sinfo` (next step would be `squeue`, but they have `flux wreck ls` for now).  They may want similar information for GPUs/BB's. 
Looking at the previous discussion though, I don't know which approach to take to resolve this.

**Comment by dongahn** [comment]
@tpatki: this will be a stop gap solution. So I would talk to @Ingolfsson and @FrankD412 and provide a minimum viable solution on top of the old infrastructure. The feedback we get from this should be useful for doing this on the new infrastructure.

**Comment by dongahn** [comment]
@tpatki and I decided to pursue this under the old resrc-based sched since this is a soon to be throw-away code.
