### ISSUE TITLE
Need more useful error messages when schedule_job fails

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-sched#347]
@koning hit this when he used `job.submit` rpc with slightly incorrect keys. The `schedule_job ()` was getting a NULL resrc_reqst object and so it returned, but it didn't print out any error message about this failure.

**Comment by grondo** [comment]
We could improve the `job.create` RPC in flux-core as well. I had thought we'd at least added some validation when the job module was rewritten, but reviewing the code that is not the case.
A simple improvement might be to make the basic members of the request structure required, with an indicator (like 0 or -1) meaning unset. Then callers would get a protocol error if any of `nnodes` `ncores` `ntasks` or `ngpus` is not included in the request.

In the replacement we have a well defined jobspec so this is only a short-term problem.
