### ISSUE TITLE
Scheduler needs to populate GPU resources from hwloc

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-sched#352]
With @trws's help, I built hwloc with CUDA enabled. Now the scheduler needs to be updated to use the GPU information exported by hwloc in its resource model.

**Comment by dongahn** [comment]
Adding `hwloc_topology_set_flags(topology, HWLOC_TOPOLOGY_FLAG_IO_DEVICES)` between `  hwloc_topology_init ()` and `hwloc_topology_load ()` will make the I/O hierarchy visible.

But it turned out the array style iteration that `resrc` relies on ([here](https://github.com/flux-framework/flux-sched/blob/master/resrc/resrc.c#L1058)) isn't traversing the I/O hierarchy straightforwardly. 

I will look into this more closely. But if someone else knows how to traverse down to the I/O hierarchy with the array style, please let me know.

If worse comes to the worst, I may have to make changes to use recursive traversing instead, which apparently allows for walking the I/O hierarchy.

**Comment by dongahn** [comment]
Using a simple test code that uses an array style traversal for Sierra:
```c
  hwloc_topology_init (&topology);
  hwloc_topology_set_xml (topology, "./topo.xml");
  hwloc_topology_ignore_type (topology, HWLOC_OBJ_CACHE);
  hwloc_topology_ignore_type (topology, HWLOC_OBJ_GROUP);
  hwloc_topology_set_flags(topology, HWLOC_TOPOLOGY_FLAG_IO_DEVICES);
  hwloc_topology_load (topology);

  hwloc_obj_t obj;
  topodepth = hwloc_topology_get_depth (topology);
  for (depth = 0; depth < topodepth; depth++) {
    level_size = hwloc_get_nbobjs_by_depth (topology, depth);
    for (size = 0; size < level_size; size++) {
       obj = hwloc_get_obj_by_depth (topology, depth, size);
       hwloc_obj_snprintf (verbose, 1024, topology, obj, NULL, 0);
       for (int i=0; i < depth; ++i)
           printf (" ");
       printf ("obj: %s\n", verbose);
    }
  }
```

```
butte5{dahn}67: hwloc_test | grep -i coproc
butte5{dahn}68:
```

Using a simple test code that uses a recursive traversal for Sierra:
```c
static void print_children(hwloc_topology_t topology, hwloc_obj_t obj, int depth)
{
  char string[128];
  unsigned i;
  hwloc_obj_snprintf(string, sizeof(string), topology, obj, "#", 0);
  printf("%*s%s\n", 2*depth, "", string);
  for (i = 0; i < obj->arity; i++) {
    print_children(topology, obj->children[i], depth + 1);
  }
}

int main(int argc, char *argv[])
<CUT> 
  print_children(topology, hwloc_get_root_obj(topology), 0);
```

```
butte5{dahn}74: hwloc_test | grep -i coproc
        CoProc
        CoProc
        CoProc
        CoProc
```

**Comment by dongahn** [comment]
If I use the recursive traversal, I suspect that this will change the order of `resrc` object creation. This may then lead to some test failures as well. More changes than what I hope to introduce for this item. Oh well.

**Comment by trws** [comment]
There is also one other option in case it's more palatable.  I can't remember if it's a pcidev or an osdev, but coprocs are one of the two, so you can use the io object specific functions to iterate over just those.  See the API [here](https://www.open-mpi.org/projects/hwloc/doc/v1.11.10/a00143.php).  It would be an extra loop, but it's probably the smallest possible change in that it will touch less code and also less devices.

**Comment by dongahn** [comment]
Thanks @trws. At the first glance, my worry is I might not be able to hang the gpus to the closer socket that way... 

I am testing recursive walks at the moment. If that has too many side effects like testing failures, I will look at your suggestions more carefully.

**Comment by dongahn** [comment]
Jus FYI -- Odd. I've put some hwloc filtering options to the scheduler so that it doesn't have to walk certain OS hierarchies. But I've found 

`hwloc_topology_ignore_type (topo, HWLOC_OBJ_OSDEV_NETWORK)`

somehow causes [a later call to `hwloc_get_nbobjs_by_type (t, HWLOC_OBJ_SOCKET)`](https://github.com/flux-framework/flux-sched/blob/master/sched/rs2rank.c#L306)  to fail. (Return 0 for the number of sockets)!

I will work around this by not ignoring this type but I thought I should pass this along.

**Comment by trws** [comment]
That’s a fair point.  If the recursive walk works, that would be my preferred method as well FWIW.  If you do need to do it with the extra loop, I would recommend walking up through the parents of each CoProc to find the nearest socket above them.  It’s a bit more code but it would certainly work.


On Jun 29, 2018, at 7:08 PM, Dong H. Ahn <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks @trws<https://github.com/trws>. At the first glance, my worry is I might not be able to hang the gpus to the closer socket that way...

I am testing recursive walks at the moment. If that has too many side effects like testing failures, I will look at your suggestions more carefully.

**Comment by trws** [comment]
That’s sufficiently odd, and disturbing, that we might want to report that upstream as a bug if it repros in the current stable, which I assume is what you built anyway.

On Jul 2, 2018, at 10:13 AM, Dong H. Ahn <notifications@github.com<mailto:notifications@github.com>> wrote:


Jus FYI -- Odd. I've put some hwloc filtering options to the scheduler so that it doesn't have to walk certain OS hierarchies. But I've found

hwloc_topology_ignore_type (topo, HWLOC_OBJ_OSDEV_NETWORK)

somehow causes a later call to hwloc_get_nbobjs_by_type (t, HWLOC_OBJ_SOCKET)<https://github.com/flux-framework/flux-sched/blob/master/sched/rs2rank.c#L306> to fail. (Return 0 for the number of sockets)!

I will work around this by not ignoring this type but I thought I should pass this along.

**Comment by SteVwonder** [comment]
I don't have access to a GPU machine right now (request in progress), so I couldn't try this out myself.  But maybe the function `hwloc_get_non_io_ancestor_obj` does the necessary upwalk from a GPU to the closest socket?  The function description sounds promising: 
```
Get the first non-I/O ancestor object.

Given the I/O object ioobj, find the smallest non-I/O ancestor object. This regular object may then be used for binding because its locality is the same as ioobj.
```

**Comment by dongahn** [comment]
```diff
diff --git a/resrc/resrc.c b/resrc/resrc.c
index f43ede7..2b8da9b 100644
--- a/resrc/resrc.c
+++ b/resrc/resrc.c
@@ -928,12 +935,19 @@ static resrc_t *resrc_new_from_hwloc_obj (resrc_api_ctx_t *ctx, hwloc_obj_t obj,
         type = xstrdup ("cache");
         name = xasprintf ("L3cache%"PRId64"", obj->attr->cache.depth, id);
         size = obj->attr->cache.size / 1024;
+#endif
     } else if (!hwloc_compare_types (obj->type, HWLOC_OBJ_CORE)) {
         type = xstrdup ("core");
         name = xasprintf ("%s%"PRId64"", type, id);
     } else if (!hwloc_compare_types (obj->type, HWLOC_OBJ_PU)) {
         type = xstrdup ("pu");
         name = xasprintf ("%s%"PRId64"", type, id);
+    } else if (!hwloc_compare_types (obj->type, HWLOC_OBJ_OS_DEVICE)
+               && obj->attr
+               && obj->attr->osdev.type == HWLOC_OBJ_OSDEV_COPROC) {
+        type = xstrdup ("gpu");
+        name = xasprintf ("%s%"PRId64"", type, id);
+        printf ("#### GPU detected!\n");
     } else {
         /* that's all we're supporting for now... */
         goto ret;
```

I can now pick up NVIDIA GPUs this way (after replacing array style walks to recursive walks of course).

One issue is, though, the scheduler uses `obj->logical_index` to add the ID suffix to the resource. But hwloc treats a GPU device as just one of `HWLOC_OBJ_OS_DEVICE` objects, it doesn't give the scheduler nice GPU IDs like 0 through 3.  On the first socket, it gives 11 and 14 instead.

```
sched.info[0]: resrc type: gpu, path: /cluster/sierra4367/numanode0/gpu11, basename: gpu, name: gpu11, ...
sched.info[0]: resrc type: gpu, path: /cluster/sierra4367/numanode0/gpu14, basename: gpu, name: gpu14, ...
```

I looked at other attributes of the CoProc type, they don't appear to have an fine grained logical index to use either.

Two choices:

Though it may not be robust, I can parse the suffix ID (xx) of `cudaxx` which is the name of the `coproc` device. Or try to find a way to generate 0-based consecutive IDs at the scheduler code level.

**Comment by dongahn** [comment]
Seems hwloc guys also uses the name parsing in their [example code](https://github.com/open-mpi/hwloc/blob/a658125f91a9314f4ba74dd7b8af7b003a3088b4/doc/examples/gpu.c#L45)... Until they add more fine-grain index support, I will go with it.

**Comment by dongahn** [comment]
> Just FYI -- Odd. I've put some hwloc filtering options to the scheduler so that it doesn't have to walk certain OS hierarchies.

Well, now I understand hwloc interface better. From `hwloc.h`:

`int hwloc_topology_ignore_type(hwloc_topology_t topology, hwloc_obj_type_t type)`

So with this interface, filtering only works on `hwloc_obj_type_t` enumerator. I was trying to filter out based on `osdev` or `pcidev` types! The reason `socket` was filtered was probably the particular `osdev` enum field has the same value as `hwloc_obj_type_t` enum field for `socket`.

Sorry for the noise.

**Comment by dongahn** [comment]
PR https://github.com/flux-framework/flux-sched/pull/354 addresses this.
