### ISSUE TITLE
queue_depth correctness

### ISSUE THREAD

**Issue by tpatki** [flux-framework/flux-sched#363]
- Setting`queue_depth` to a negative value should result in an error
- Check that `pq_state` is updated correctly (when adding a new job to the queue)
- Ensure that `schedule_jobs` is called only when `pq_state` is true. 

Discussed in #337 and [flux-core/pull/1579](https://github.com/flux-framework/flux-core/pull/1579)

**Comment by grondo** [comment]
Can this be closed since #440 was merged?

**Comment by dongahn** [comment]
Yes, this should be closed.
