### ISSUE TITLE
sierra: one flux instance per socket

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-sched#367]
I tried one of the things we talked about today: running 2 flux instances per node (1 per socket)  It seems to work well for the LBANN use-case: 1 task per GPU, 2 tasks per socket (for locality).  The only oddity is that the number of nodes in `resrc` is artificially doubled, which I think is a known unintended side-effect.

```
$ bsub -Is -G guests -nnodes 1 `which zsh`
$ PMI_LIBRARY=/usr/global/tools/pmi4pmix/blueos_3_ppc64le_ib/lib/libpmi.so jsrun -a 1 -c 22 -g 2 -n 2 --bind=rs flux start flux wreckrun -N2 -n2 -c22 -g 2 ./get_taskset.sh
sierra1549: pid 110874's current affinity list: 0-87
sierra1549: pid 110875's current affinity list: 88-175
```

I can run the test again once https://github.com/flux-framework/flux-core/issues/1562 and https://github.com/flux-framework/flux-core/issues/1591 hit master.  Just wanted to bookmark the progress thus far.

**Comment by dongahn** [comment]
Probably `--bind=rs` doesn't do binding correctly... 

Wouldn't it be more fruitful just to add `-o cpu-affinity=per-task`?

**Comment by dongahn** [comment]
While 2 instances per node may work for other cases, it won't work for MLSI. They will want to launch 1 celery broker per physical node.

**Comment by SteVwonder** [comment]
> Probably --bind=rs doesn't do binding correctly...

The bindings look correct to me....What is incorrect about the bindings?

> Wouldn't it be more fruitful just to add -o cpu-affinity=per-task?

Once we get the logical vs os core IDs straightened out, @grondo said he can add a twin to the `gpubind` plugin that he made in https://github.com/flux-framework/flux-core/issues/1562.  I'm looking into the ID issue now.

**Comment by grondo** [comment]
@dongahn, yes we just discussed this. As long as we use a heuristic where cpu binding and GPU binding for tasks results in the tasks being bound to the cores local to the GPU, then this should be doable. I think the broker per socket was just a suggestion to ensure tasks could *only* use "local" GPUs...

**Comment by SteVwonder** [comment]
@dongahn:
```
→ cat get_taskset.sh 
#!/bin/bash

echo "$(hostname): $(taskset -cp $$)"
```
So whatever taskset returns, which should be logical cores rather than physical cores.

**Comment by SteVwonder** [comment]
Also as part of testing this workaround and testing @grondo's gpubind, I realized that `nvidia-smi` does not respect `CUDA_VISIBLE_DEVICES`.  So the workaround that I found is to compile one of the NVIDIA samples `deviceQueryDrv` and run that.

So the nail in the coffin of this workaround is that the GPU binding doesn't work as intended:
```
→ PMI_LIBRARY=/usr/global/tools/pmi4pmix/blueos_3_ppc64le_ib/lib/libpmi.so jsrun -a 1 -c 22 -g 2 -n 2 --bind=rs flux start flux wreckrun -N2 -n2 -c22 -g 2 -l ./deviceQueryDrv | sort
0: 
0: 
0: 
0: CUDA Device Query (Driver API) statically linked version 
0: Detected 2 CUDA Capable device(s)
0: Device 0: "Tesla V100-SXM2-16GB"
0: Device 1: "Tesla V100-SXM2-16GB"
0:   Device PCI Domain ID / Bus ID / location ID:   4 / 4 / 0
0:   Device PCI Domain ID / Bus ID / location ID:   4 / 5 / 0
0: ./deviceQueryDrv Starting...
0: Result = PASS
1: 
1: 
1: 
1: CUDA Device Query (Driver API) statically linked version 
1: Detected 2 CUDA Capable device(s)
1: Device 0: "Tesla V100-SXM2-16GB"
1: Device 1: "Tesla V100-SXM2-16GB"
1:   Device PCI Domain ID / Bus ID / location ID:   4 / 4 / 0
1:   Device PCI Domain ID / Bus ID / location ID:   4 / 5 / 0
1: ./deviceQueryDrv Starting...
1: Result = PASS
```

Ok. Enough with this and onto the logical vs os IDs.  (Closing)

**Comment by dongahn** [comment]
Great. Thanks!
