### ISSUE TITLE
Check if there is a race condition in GPU scheduling test

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-sched#374]
From https://github.com/flux-framework/flux-sched/pull/372#issuecomment-410261786. Travis randomly fails with:

```
not ok 8 - rs2rank: can schedule GPUs using hwloc
```

There may be a race condition in the test.

@SteVwonder only commented:

> Following up on the hwloc error from before, it seems that the hwloc documentation blames the OS/hardware for returning erroneous results: https://www.open-mpi.org/projects/hwloc/doc/v1.11.2/a00030.php#faq_os_error

> So maybe we can just blame that one on Travis?

**Comment by grondo** [comment]
closed by #440
