### ISSUE TITLE
resource: rs2rank replacement (ranked vs rankless R)

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-sched#375]
Summary of the discussion that @dongahn and I had about how to handle mapping resources to rank with the new resource matching service.

It appears that there exists two main scenarios that we must handle:

1. There is at most one rank per node in a Flux instance.  So when a particular node is included in an `R` or `R_lite`, that node's hostname uniquely identifies which rank is responsible for launching the associated task.
2. Each node has multiple ranks on it (i.e., the node is oversubscribed). In this scenario, the number of resources present in the hwloc xml is an integer multiple equal to the number of ranks on each node (i.e., the over-subscription factor).  Specifically, if CPU affinity is not used, the number of nodes and cores present in the hwloc xml will both be multiplied by the over-subscription factor.  If CPU affinity is used, and each rank is bound to its own unique set of CPUs, only the number of nodes will be multiplied by the over-subscription factor.  This causes problems for the execution service since there are multiple "copies" of each node/hostname in the resource model and a 1:1 mapping between node hostname and Flux rank no longer exists.

In the former case (1), the resource matching service can remain agnostic to the mapping of ranks to nodes and can emit a "rankless R" or "rankless R_lite".  Despite the emitted `R` being rankless, the execution service should be able to unambiguously determine which tasks run on which ranks based on the node hostnames in the emitted `R`.

In the latter case (2), the resource matching service must emit rank information in `R`/`R_lite` to eliminate the ambiguity of which rank should execute the job/task.  

The exact format for how rank information will be added to the emitted `R` is yet to be determined.

**Comment by dongahn** [comment]
Per PR #355, at least`rank` info is now encoded in hwloc reader mode for resource matching service module.

**Comment by dongahn** [comment]
For nested scheduling using JGF, this will be needed and we don't have this schedule in our plan yet.

**Comment by dongahn** [comment]
Remapping needed for https://github.com/flux-framework/flux-sched/issues/375#issuecomment-538215376 will be addressed as part of RV2.
