### ISSUE TITLE
implicit declaration of function 'flux_msg_get_string'

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-sched#381]
This is probably something wrong that I am doing. But somewhat I start to see the following compilation error on quartz. Anyone hit this before? 

```
make[2]: Entering directory `/nfs/tmp2/dahn/workspace/FluxRMS/flux-sched/build-toss_3_x86_64_ib/simulator'
  CC       libflux_sim_la-simulator.lo
  CCLD     libflux-sim.la
  CC       simsrv_la-simsrv.lo
../../simulator/simsrv.c: In function 'join_cb':
../../simulator/simsrv.c:223:5: error: implicit declaration of function 'flux_msg_get_string' [-Werror=implicit-function-declaration]
     if (flux_msg_get_string (msg, &json_str) < 0 || json_str == NULL
     ^
```

**Comment by grondo** [comment]
Check the version of flux-core you are compiling against. I think `flux_msg_get_string()` recently replaced `flux_msg_get_json()` (i.e. you need at least flux-core v0.10.0 I think)

**Comment by dongahn** [comment]
@grondo: thanks! Indeed, it was linking this against a system installed flux.
