### ISSUE TITLE
Need FY-end performance analysis + tuning for resource

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-sched#390]
This is to finalize my ECP milestone work. 

1. Find the right Linux performance and memory tools to analyze `resource-query` and `resource` module.

2. Gather performance profiles with 4 configurations
      - Tiny machine configuration with 10K `match allocate_orelse_reserve` jobs
      - Medium machine configuration with 10K `match allocate_orelse_reserve` jobs
      - Large machine configuration with 10K `match allocate_orelse_reserve` jobs
      - Largest machine configuration with 10K `match allocate_orelse_reserve` jobs

3. Tuning exploration
     - Explore ways to fully integrate planner-based schemes into both `resource-query` and `resource` 
      - Document ways to reduce the memory footprint and edge traversal performance

**Comment by dongahn** [comment]
This was an initial performance profiling on Mac OS/X, showing that one of the hot spot is edge traversal. 
<img width="1361" alt="28486440-ac973152-6e36-11e7-8453-6938eac10ee3" src="https://user-images.githubusercontent.com/862123/45789153-14049a00-bc33-11e8-9d6b-c24c59400639.png">

**Comment by dongahn** [comment]
Doing such an analysis on Linux with `perf`. I find the output isn't all that intuitive so far. 

I used perf-record as:
$perf record --call-graph dwarf -e cpu-clock resource-query -G tiny.graphml < input
 
I used perf-report as:
perf report --stdio -g graph

![screen shot 2018-09-19 at 4 46 49 pm](https://user-images.githubusercontent.com/862123/45789181-30a0d200-bc33-11e8-85f0-a7765d78d2ce.png)

**Comment by dongahn** [comment]
I gathered some feedback from RedHat and used https://github.com/jrfonseca/gprof2dot.

This tool doesn't seem very helpful. 

![screen shot 2018-09-19 at 4 56 33 pm](https://user-images.githubusercontent.com/862123/45789216-59c16280-bc33-11e8-9e1a-0df4cf97d518.png)

**Comment by dongahn** [comment]
Some other work that falls into this category:

PR https://github.com/flux-framework/flux-sched/pull/349 - This is both correctness and performance, though.

**Comment by SteVwonder** [comment]
If you are still looking for profiling applications, maybe try Callgrind + Kcachegrind.  I've had success profiling flux-sched with them in the past.  That was pure C code though.  Although I haven't tried with C++, there are some blog posts that make me believe it is doable and useful: https://baptiste-wicht.com/posts/2011/09/profile-c-application-with-callgrind-kcachegrind.html

**Comment by dongahn** [comment]
> If you are still looking for profiling applications

I am. Big time. OK. I will take a look at this. When you used this on flux-sched, what was the application slowdown looked like?

**Comment by SteVwonder** [comment]
> When you used this on flux-sched, what was the application slowdown looked like?

That is a great question.  It was long enough ago that I don't remember.  Since callgrind is built on valgrind, I imagine it is a pretty heavyweight/high overhead profiler.

**Comment by dongahn** [comment]
http://www.brendangregg.com/FlameGraphs/cpuflamegraphs.html seems more scalable and I think I will go with this tool combined with `perf report` for now. Still with the long C++ symbols, I have to render an gigantic frame image, but this is much more legible than the other tools. 


![my2](https://user-images.githubusercontent.com/862123/46107918-8de7d680-c191-11e8-9e82-ec2b18d71b8a.png)

**Comment by dongahn** [comment]
Uggg. It looks like call stack merging isn't done correctly by this tool.

Flux::resource_model::dfu_traverser_t::schedule shows up at least twice through different call paths, which I believe is happening because stack traces are not being correct done. 

One without the `main->__libc_start_main->_start prefix`, one with the `main->__libc_start_main->_start `prefix...

Not sure if it will be worthy manually parsing through these kinds of errors in the tool...
![screen shot 2018-09-26 at 4 08 54 pm](https://user-images.githubusercontent.com/862123/46114372-2d639400-c1a7-11e8-8b77-6fc73db8ccf0.png)

![screen shot 2018-09-26 at 4 09 22 pm](https://user-images.githubusercontent.com/862123/46114376-348aa200-c1a7-11e8-819f-69f1154a84af.png)

**Comment by zvonkok** [comment]
@dongahn Have you tried this one [ https://github.com/KDAB/hotspot]( https://github.com/KDAB/hotspot)?
The time line allows filtering the results by time, process or thread. The data views will update accordingly.

![timeline-filter-thread](https://user-images.githubusercontent.com/3725238/46124479-bf5db200-c224-11e8-9fe0-ad21581e9f40.png)

![timeline-flamegraph](https://user-images.githubusercontent.com/3725238/46124482-c2f13900-c224-11e8-8a48-2f28dd27d9c3.png)

**Comment by dongahn** [comment]
@zvonkok: This will be awesome if I can try it. But its dependency appeared to me pretty complex so I didn't dare to make a side installation on our large system...

**Comment by dongahn** [comment]
Though not perfect, I got some performance profile using the Flame Graph for **resource-query initialization** -- constructing a largish cluster configuration.

Because of what appears to be incorrect strace backtrace, `Flux::resource_model::dfu_traverser_t::initialize ()` appears multiple times, but this amounts to **29.78%** of the runtime. On the other hand, **62.48%** of the runtime went into `Flux::resource_model::resource_generator_t::read_graphml ()`.  Both of these high-level operations account for over 92% of the runtime for this phase.

Zooming in on `read_graphml ()` first:

<img width="1307" alt="screen shot 2018-09-26 at 10 14 21 pm" src="https://user-images.githubusercontent.com/862123/46125012-01aed100-c1dc-11e8-8829-676a8bfddb8a.png">


Through its call path, it looks like `dfs_emitter_t::emit_vertex` takes the most time, which adds resource vertices into the graph store.

One good optimization target is the `initialize ()` function within `planner_new ()`. Somewhat surprisingly, [`zhash_new ()`]( https://github.com/flux-framework/flux-sched/blob/master/resource/planner/planner.c#L599) consumes the most of the time, which is somewhat unfortunate because its implementation is outside of my control. I wonder if `zhashx_new ()` is a bit more performant. Also my guess is `std::map` will be actually faster, but this part of the code is C...

Perhaps more importantly, the most timing consuming part is the `resize ()` method of the `std::vector` which is being used as the container to store resource vertices. **33.47%**! I suspect we may end up paying extra initialization overheads as the vector grows with `resize ()` for larger cluster configurations. There got to be a smarter way to set the initial vector size to minimize such a penalty. 

On the other hands, the most expensive operation of `Flux::resource_model::dfu_traverser_t::initialize ()` is, as expected the full graph traversal, in particular, [`out_edges ()` ](https://github.com/flux-framework/flux-sched/blob/c27dc1474467cf05646912fa175d1da22fa0ee15/resource/traversers/dfu_impl.cpp#L309). I will have to think about this some more because I don't fully understand why returning out-edge iterator pairs take the big time like this...

<img width="324" alt="screen shot 2018-09-26 at 10 56 31 pm" src="https://user-images.githubusercontent.com/862123/46125802-9b2bb200-c1df-11e8-8655-7ba966a89d75.png">

Next is to analyze the match performance.

**Comment by dongahn** [comment]
@zvonkok: AppImage is awesome! This made the hotspot tool work out box on one of our clusters and I could construct a similar flame graph and interactively traverse caller-callee chains through a window.

A question, though. As with the Flame Graph issue above, some functions I want to analyze show up multiple times through different stack traces. For example, `initialize ()` showed up with a path `resource-query -> initialize ()` **and** `_start->__libc_start_main->main->...::initialize()` See below.

Would this be due to a failure in stack tracing during `perf record` phase or something else?

Maybe there is better way to do the recording which will prevent me from getting such presentations. As mentioned above, I'm using

```
$perf record --call-graph dwarf -e cpu-clock resource-query <CUT>
```

![screen shot 2018-09-27 at 9 56 33 am](https://user-images.githubusercontent.com/862123/46162033-00ad8c00-c23c-11e8-8ddf-21a1747315b4.png)



![screen shot 2018-09-27 at 9 45 25 am](https://user-images.githubusercontent.com/862123/46161641-ede68780-c23a-11e8-9b9d-754d63761189.png)

**Comment by dongahn** [comment]
As expected, match performance is completely dominated by graph traversal:

![screen shot 2018-09-27 at 3 40 00 pm](https://user-images.githubusercontent.com/862123/46178540-2eaac480-c26c-11e8-9f93-9ae58bf844c8.png)

So, the hottest spot seems to be [here](https://github.com/flux-framework/flux-sched/blob/master/resource/traversers/dfu_impl.cpp#L326)


![screen shot 2018-09-27 at 3 38 38 pm](https://user-images.githubusercontent.com/862123/46178557-3b2f1d00-c26c-11e8-8bf8-a6d39c8b8f5e.png)

**Comment by dongahn** [comment]
Some of the optimization ideas so far:

#### Initialization Performance
- Use `vector::reserve ()` to reserve an increasingly larger allocation (`N`) for larger machine configurations so that `vector` doesn't grow with `resize ()`, paying a high initialization cost with excessive resource vertex copying. The trick is how to determine the proper allocation size `N`. In addition, I have to see if boost graph library will let me access the internal vertex vector *safely* (since the type is determined by the template argument) to reserve larger dynamic memory.

- Find a more lightweight hash implementation instead of `zhash_new ()` in the hot spot. `zhash` seems to allocate a relative large memory chunk. 

- Or invoke `zhash_new ()` as part of a lazy initialization. This way, we don't at least have to pay the cost of this function redundantly due to `vector::resize ()`

- Devise a cheaper method for `out_edges`


#### Matching Performance
Definitely the optimization should be centered on search "pruning" as well as making out-edge traversing faster. 

- I already have the scheduler-driven aggregate update scheme factored into the design for pruning by subtree aggregate. This will significantly help once the machine gets into a loaded state. But I believe we need be much more aggressive for lightly loaded state and for reservation operations for back filling. 

- Devise a cheaper method for `out_edges` (This isn't shown up in the performance profile, but if the total graph has multiple subsystems and the scheduler doesn't use some of them, this BGL-provided `out_edges` can be even more expensive with more out edges that we don't have to traverse. Need to see if we can use an associative map in providing `out_edges` equivalent.

- Need a good heuristic to stop the search. Depending on the match selection objective, we don't have to traverse the entire graph to find the best match. Maybe "stop" search mechanism can be exposed to the match policy plugin. And/or introduce a `stop-on-finding-N-matches` as resource load parameter.

**Comment by SteVwonder** [comment]
> Maybe "stop" search mechanism can be exposed to the match policy plugin.

That is a great idea.  Maybe one stopping mechanism could be a score threshold.  Once a resource set with a high enough score is found, the search ends.

**Comment by dongahn** [comment]
> Use vector::reserve () to reserve an increasingly larger allocation (N) for larger machine configurations so that vector doesn't grow with resize (), paying a high initialization cost with excessive resource vertex copying. The trick is how to determine the proper allocation size N. In addition, I have to see if boost graph library will let me access the internal vertex vector safely (since the type is determined by the template argument) to reserve larger dynamic memory.

Thinking about this some more, maybe simpler solution to change the container type for vertex to be a list.

 In theory this should be as easy as changing the template instantiation for `resource_grapth_t` type so I can do some quick experiment. 

This will increase the memory overhead slightly. But the main memory use is due to the size of the element itself (e.g., `resource_pool_t`) instead of what the container does. So this should be fine there I think. 

My main concern is the impact to the match transversal. Will see the impact.

**Comment by dongahn** [comment]
> Thinking about this some more, maybe simpler solution to change the container type for vertex to be a list.

Changing VertexList type to `std::list` wasn't fruitful because there seem to be other places in the code that requires `RandomAccessContainer`.

It also appears BGL completely hides the container object for VertexList and EdgeList into its implementation detail, calling`std::vector::reserve` on that container object *safely* is impractical.

**Comment by dongahn** [comment]
> Find a more lightweight hash implementation instead of `zhash_new ()` in the hot spot. zhash seems to allocate a relative large memory chunk.

Ok. This one worked.  Simply changing `zhash_new ()` to `zhashx_new ()` with other minor changes reduces the overhead of `planner_new ()` to 2.88% from 9.1% of the initialization phase. 

Lesson: Avoid `zhash_new ()` on a performance critical code!

The overhead due to `vector::resize` went down to 27% from 34% accordingly.

Still, I have to think if I can somehow tell the `vector` to make an appropriately large allocation, the entire 27% will be gone. Just haven't found the way to call `reserve ()` on it with respect to BGL...

**Comment by SteVwonder** [comment]
> It also appears BGL completely hides the container object for VertexList and EdgeList into its implementation detail, callingstd::vector::reserve on that container object safely is impractical.

Not sure how helpful this is, but in the BGL quick tour they have an example of creating a graph that is pre-allocated for a certain number of vertices: https://www.boost.org/doc/libs/1_68_0/libs/graph/doc/quick_tour.html (the section titled "Constructing a Graph").  I presume that when you construct the graph in this way, it calls `reserve` on the underlying vector.  I assume that MutableGraphs supports both creation with a pre-allocated number of vertices and then post-creation addition of more vertices.

As for the edge list, the quick tour also mentions something about an "edge iterator constructor" being more efficient than repeated calls to `add_edge`.

If you so desired, it seems that you could also provide your own custom data structures for the vertex and edge lists: https://www.boost.org/doc/libs/1_68_0/libs/graph/doc/using_adjacency_list.html#sec:custom-storage

**Comment by dongahn** [comment]
>  I presume that when you construct the graph in this way, it calls reserve on the underlying vector. I assume that MutableGraphs supports both creation with a pre-allocated number of vertices and then post-creation addition of more vertices.

Good thought. But not sure if `reserve` will be called. BGL supports arbitrary container types as far as they model the requisite and `std::vector` is one of them. So it is unclear if the BGL proper will use the vector specific`reserve` call.

There are other graph types which require the user to manage the vertex list etc. With those types, since we will have full access to the vector in this case, this is definitely possible. Just that, the changes would be too pervasive.

**Comment by dongahn** [comment]
OK. Boot Graph Library code is pretty complex to read through, but what I ended up finding is there **IS** a way to effect `reserve`. Similarly, I've also found: https://lists.boost.org/boost-users/2008/11/42425.php

```diff
--- a/resource/utilities/resource-query.cpp
+++ b/resource/utilities/resource-query.cpp
@@ -475,13 +475,14 @@ int main (int argc, char *argv[])

     // Generate a resource graph data store
     resource_generator_t rgen;
+   ctx->db.resource_graph.m_vertices.reserve (1000000);
     if ( (rc = rgen.read_graphml (ctx->params.grug, ctx->db)) != 0) {
         cerr << "ERROR: " << rgen.err_message () << endl;
         cerr << "ERROR: error in generating resources" << endl;
         return EXIT_FAILURE;
     }
```

As expected, this give an additional ~20% improvement.  

W/  the above`zhash_new()` enhancement, populating ~200K vertices (as well as the number of edges being some fraction of it), takes 7.33 seconds.

Combining that w/ the`reserve` enhancement,  it takes 5.92 seconds.

Given that this code wasn't even compiled with optimization flag, my guess is the loading phase of the resource matching service should just be doing fine for a foreseeable future.

Although this way of accessing the vertex list member is not so safe -- in fact, `m_vertices` is in the `detail` namespace! -- the improvement is such that I will want to introduce this as an option.  Then, when BGL introduces `reserve` support into its public interface (as suggested in the posting), we can latch onto that.

**Comment by dongahn** [comment]
> Given that this code wasn't even compiled with optimization flag, my guess is the loading phase of the resource matching service should just be doing fine for a foreseeable future.

Finally, with -O2 GCC compiler optimization, this goes further down to 2.25 secs! I am now okay for this phase.
