### ISSUE TITLE
libjobspec: temporarily copy from flux-core

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-sched#393]
As described in flux-framework/flux-core#1714, libjobspec will be rewritten in C.  Meanwhile the C++ interface is being used by sched.  To simplify the transition, it was suggested that libjobspec could be copied into sched.  Then when a new libjobspec from flux-core is available that can provide the interfaces needed by sched, the copy can be dropped and the interfaces changed in one go.

**Comment by dongahn** [comment]
Copying should be fine. This will allow us to keep running resource query tests and etc.

Will I be able to construct a jobspec object from the J passed from the core though using this though?

**Comment by garlick** [comment]
Yes, that should work.  It will be JSON but YAML parser should be able to parse same jobspec in either JSON or YAML form.  We won't make the change in flux-core until we've validated that all this works as expected though.
