### ISSUE TITLE
`-L/usr/lib64` polluting libtool line

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-sched#404]
After poking around with @grondo, it looks like `-L/usr/lib64` is coming from `$(BOOST_LDFLAGS)` which is added to `AM_LDFLAGS`, which appears early on in the link line.  This causes the wrong (i.e., system) `czmq` to be picked up. Not sure what the right move is here.  Maybe we can tweak the BOOST m4 to not add `-L/usr/lib64`?

Other relevant info: I'm using gcc8.2 and a flux-core that is built using spack and then loaded via lmod (with all of its dependencies).  I forgot to manually load boost via lmod, so configure picked up the system one.

FWIW, the full link lines:
```
/bin/sh ../../libtool  --tag=CXX   --mode=link /usr/workspace/wsb/herbein1/packages/toss3/toss3/spack/opt/spack/linux-rhel7-x86_64/gcc-4.9.3/gcc-8.2.0-2hwyxzty6l3z4sljoaxasish3fnehqh4/bin/g++ -Wall -Werror -Werror=missing-field-initialize
rs -Wno-error=deprecated-declarations -Wno-unused-local-typedefs -Wno-deprecated-declarations -Wno-unused-variable -Wno-error  -g -O2 -L/usr/lib64  -o grug2dot grug2dot-grug2dot.o ../libresource.la -lboost_system -lboost_filesystem -lboos
t_graph -lboost_regex-mt
libtool: link: /usr/workspace/wsb/herbein1/packages/toss3/toss3/spack/opt/spack/linux-rhel7-x86_64/gcc-4.9.3/gcc-8.2.0-2hwyxzty6l3z4sljoaxasish3fnehqh4/bin/g++ -Wall -Werror -Werror=missing-field-initializers -Wno-error=deprecated-declara
tions -Wno-unused-local-typedefs -Wno-deprecated-declarations -Wno-unused-variable -Wno-error -g -O2 -o grug2dot grug2dot-grug2dot.o  -L/usr/lib64 ../.libs/libresource.a /usr/workspace/wsb/herbein1/packages/toss3/toss3/spack/opt/spack/linux-rhel7-x86_64/gcc-8.2.0/czmq-4.1.1-gxlyc2fmjwnmbledkjmppjuymzcyagla/lib/libczmq.so -L/usr/workspace/wsb/herbein1/packages/toss3/toss3/spack/opt/spack/linux-rhel7-x86_64/gcc-8.2.0/zeromq-4.2.5-ttsphgxpdhlje6ry4skwt6fafxwd7imm/lib -L/usr/
workspace/wsb/herbein1/packages/toss3/toss3/spack/opt/spack/linux-rhel7-x86_64/gcc-8.2.0/libsodium-1.0.15-oe5ns7kmitv3ziqhnjzovbbxaw76kgkd/lib -L/usr/workspace/wsb/herbein1/packages/toss3/toss3/spack/opt/spack/linux-rhel7-x86_64/gcc-8.2.0
/libuuid-1.0.3-cdb6wj66i6h22copq3buy6p5f2j64oxd/lib /usr/workspace/wsb/herbein1/packages/toss3/toss3/spack/opt/spack/linux-rhel7-x86_64/gcc-8.2.0/libuuid-1.0.3-cdb6wj66i6h22copq3buy6p5f2j64oxd/lib/libuuid.so /usr/workspace/wsb/herbein1/pa
ckages/toss3/toss3/spack/opt/spack/linux-rhel7-x86_64/gcc-8.2.0/zeromq-4.2.5-ttsphgxpdhlje6ry4skwt6fafxwd7imm/lib/libzmq.so /usr/workspace/wsb/herbein1/packages/toss3/toss3/spack/opt/spack/linux-rhel7-x86_64/gcc-8.2.0/libsodium-1.0.15-oe5ns7kmitv3ziqhnjzovbbxaw76kgkd/lib/libsodium.so -lrt -lpthread -ldl -lyaml-cpp -lhwloc -lflux-core /usr/workspace/wsb/herbein1/packages/toss3/toss3/spack/opt/spack/linux-rhel7-x86_64/gcc-4.9.3/gcc-8.2.0-2hwyxzty6l3z4sljoaxasish3fnehqh4/lib
/../lib64/libstdc++.so -lm -lboost_system -lboost_filesystem -lboost_graph -lboost_regex-mt -pthread -Wl,-rpath -Wl,/usr/workspace/wsb/herbein1/packages/toss3/toss3/spack/opt/spack/linux-rhel7-x86_64/gcc-8.2.0/czmq-4.1.1-gxlyc2fmjwnmbledk
jmppjuymzcyagla/lib -Wl,-rpath -Wl,/usr/workspace/wsb/herbein1/packages/toss3/toss3/spack/opt/spack/linux-rhel7-x86_64/gcc-8.2.0/libuuid-1.0.3-cdb6wj66i6h22copq3buy6p5f2j64oxd/lib -Wl,-rpath -Wl,/usr/workspace/wsb/herbein1/packages/toss3/
toss3/spack/opt/spack/linux-rhel7-x86_64/gcc-8.2.0/zeromq-4.2.5-ttsphgxpdhlje6ry4skwt6fafxwd7imm/lib -Wl,-rpath -Wl,/usr/workspace/wsb/herbein1/packages/toss3/toss3/spack/opt/spack/linux-rhel7-x86_64/gcc-8.2.0/libsodium-1.0.15-oe5ns7kmitv
3ziqhnjzovbbxaw76kgkd/lib -Wl,-rpath -Wl,/usr/workspace/wsb/herbein1/packages/toss3/toss3/spack/opt/spack/linux-rhel7-x86_64/gcc-4.9.3/gcc-8.2.0-2hwyxzty6l3z4sljoaxasish3fnehqh4/lib/../lib64 -Wl,-rpath -Wl,/usr/workspace/wsb/herbein1/packages/toss3/toss3/spack/opt/spack/linux-rhel7-x86_64/gcc-8.2.0/czmq-4.1.1-gxlyc2fmjwnmbledkjmppjuymzcyagla/lib -Wl,-rpath -Wl,/usr/workspace/wsb/herbein1/packages/toss3/toss3/spack/opt/spack/linux-rhel7-x86_64/gcc-8.2.0/libuuid-1.0.3-cdb6w
j66i6h22copq3buy6p5f2j64oxd/lib -Wl,-rpath -Wl,/usr/workspace/wsb/herbein1/packages/toss3/toss3/spack/opt/spack/linux-rhel7-x86_64/gcc-8.2.0/zeromq-4.2.5-ttsphgxpdhlje6ry4skwt6fafxwd7imm/lib -Wl,-rpath -Wl,/usr/workspace/wsb/herbein1/pack
ages/toss3/toss3/spack/opt/spack/linux-rhel7-x86_64/gcc-8.2.0/libsodium-1.0.15-oe5ns7kmitv3ziqhnjzovbbxaw76kgkd/lib -Wl,-rpath -Wl,/usr/workspace/wsb/herbein1/packages/toss3/toss3/spack/opt/spack/linux-rhel7-x86_64/gcc-4.9.3/gcc-8.2.0-2hw
yxzty6l3z4sljoaxasish3fnehqh4/lib/../lib64
/usr/bin/ld: warning: libczmq.so.3, needed by /usr/lib64/libflux-core.so, may conflict with libczmq.so.4
```

**Comment by grondo** [comment]
Reading the autotools [Program and Library Variables](https://www.gnu.org/software/automake/manual/html_node/Program-and-Library-Variables.html#Program-and-Library-Variables) section of the manual. It seems like `LDFLAGS` is the wrong variable in which to put `-L` for libboost.

Can we try moving this to the `*_LIBADD` (for libraries) or `*_LDADD` (for executables) and see if automake/libtool's handling of the flags is more appropriate? (AFAICS, `LDFLAGS` is supposed to just be for linker *flags*, and that might be why the `-L/usr/lib64` gets promoted ahead of other flags when doing the link.

It is also interesting that boost even adds `-L/usr/lib64` to BOOST_LDFLAGS, but that is perhaps a separate question.

**Comment by dongahn** [comment]
Last time when I looked at it, `BOOST_LDFLAGS` is decided through

https://github.com/flux-framework/flux-sched/pull/394/commits/85da2f8553ed7ba3c3eacf6ea361bf3a50f8240a and [here](https://github.com/dongahn/flux-sched/blob/85da2f8553ed7ba3c3eacf6ea361bf3a50f8240a/m4/ax_boost_base.m4#L157)

So this would be the directory where the dependent boost libraries should be picked up.

**Comment by dongahn** [comment]
> Can we try moving this to the *_LIBADD (for libraries) or *_LDADD (for executables) and see if automake/libtool's handling of the flags is more appropriate?

This sounds pretty promising. Sorry for misusing `AM_LDFLAGS`.

**Comment by dongahn** [comment]
@SteVwonder: will you be able to try this out on your branch? I don't have a failure case so I won't be able to tell if @grondo's suggestion fixes this or not.

**Comment by SteVwonder** [comment]
Thanks @grondo for researching this.  I think we are getting closer. I switched BOOST_LDFLAGS from AM_LDFLAGS to resource_query_LDADD, and it did move the `-L/usr/lib64` later in the link line, but there are still some problems.

1) I'm still getting the error about czmq version mismatches from `/usr/lib64/libflux-core.so`.  I believe the problem here is that there is a `-lflux-core` flag but no `-L/path/to/flux-core` flag within the libresource.la.  I am attempting to add that now (but I think there will be some problems there, we shall see soon).
2) There are still libraries whose `-L` comes after boost's `-L`.  In particular, `JANSSON_LIBS` comes after `BOOST_LDFLAGS` in `resource_query_LDADD`, so I imagine the linker is picking up the system-installed jansson (if there is one).   I'm not sure how to solve that general.  We could probably fix this particular scenario by rearranging it such that boost is absolutely last on the link line, but what happens when jansson or yaml-cpp "pollutes" the link line with `-L/usr/lib64`?

New full link line:
```
libtool: link: /usr/workspace/wsb/herbein1/packages/toss3/toss3/spack/opt/spack/linux-rhel7-x86_64/gcc-4.9.3/gcc-8.2.0-2hwyxzty6l3z4sljoaxasish3fnehqh4/bin/g++ -Wall -Werror -Werror=missing-field-initializers -Wno-error=deprecated-declarations -Wno-unused-local-typedefs -Wno-deprec
ated-declarations -Wno-unused-variable -Wno-error -g -O2 -o resource-query resource_query-resource-query.o resource_query-command.o  ../.libs/libresource.a /usr/workspace/wsb/herbein1/packages/toss3/toss3/spack/opt/spack/linux-rhel7-x86_64/gcc-8.2.0/czmq-4.1.1-gxlyc2fmjwnmbledkjmpp
juymzcyagla/lib/libczmq.so -L/usr/workspace/wsb/herbein1/packages/toss3/toss3/spack/opt/spack/linux-rhel7-x86_64/gcc-8.2.0/zeromq-4.2.5-ttsphgxpdhlje6ry4skwt6fafxwd7imm/lib -L/usr/workspace/wsb/herbein1/packages/toss3/toss3/spack/opt/spack/linux-rhel7-x86_64/gcc-8.2.0/libsodium-1.0
.15-oe5ns7kmitv3ziqhnjzovbbxaw76kgkd/lib -L/usr/workspace/wsb/herbein1/packages/toss3/toss3/spack/opt/spack/linux-rhel7-x86_64/gcc-8.2.0/libuuid-1.0.3-cdb6wj66i6h22copq3buy6p5f2j64oxd/lib /usr/workspace/wsb/herbein1/packages/toss3/toss3/spack/opt/spack/linux-rhel7-x86_64/gcc-8.2.0/
libuuid-1.0.3-cdb6wj66i6h22copq3buy6p5f2j64oxd/lib/libuuid.so /usr/workspace/wsb/herbein1/packages/toss3/toss3/spack/opt/spack/linux-rhel7-x86_64/gcc-8.2.0/zeromq-4.2.5-ttsphgxpdhlje6ry4skwt6fafxwd7imm/lib/libzmq.so /usr/workspace/wsb/herbein1/packages/toss3/toss3/spack/opt/spack/l
inux-rhel7-x86_64/gcc-8.2.0/libsodium-1.0.15-oe5ns7kmitv3ziqhnjzovbbxaw76kgkd/lib/libsodium.so -lrt -lpthread -ldl -lyaml-cpp -lhwloc -lflux-core /usr/workspace/wsb/herbein1/packages/toss3/toss3/spack/opt/spack/linux-rhel7-x86_64/gcc-4.9.3/gcc-8.2.0-2hwyxzty6l3z4sljoaxasish3fnehqh4
/lib/../lib64/libstdc++.so -lm -lreadline -L/usr/lib64 -lboost_system -lboost_filesystem -lboost_graph -lboost_regex-mt -L/usr/workspace/wsb/herbein1/packages/toss3/toss3/spack/opt/spack/linux-rhel7-x86_64/gcc-8.2.0/jansson-2.9-pc3rsd6lh5bj4sartxdggdbtsbcf55zm/lib -ljansson -pthrea
d -Wl,-rpath -Wl,/usr/workspace/wsb/herbein1/packages/toss3/toss3/spack/opt/spack/linux-rhel7-x86_64/gcc-8.2.0/czmq-4.1.1-gxlyc2fmjwnmbledkjmppjuymzcyagla/lib -Wl,-rpath -Wl,/usr/workspace/wsb/herbein1/packages/toss3/toss3/spack/opt/spack/linux-rhel7-x86_64/gcc-8.2.0/libuuid-1.0.3-
cdb6wj66i6h22copq3buy6p5f2j64oxd/lib -Wl,-rpath -Wl,/usr/workspace/wsb/herbein1/packages/toss3/toss3/spack/opt/spack/linux-rhel7-x86_64/gcc-8.2.0/zeromq-4.2.5-ttsphgxpdhlje6ry4skwt6fafxwd7imm/lib -Wl,-rpath -Wl,/usr/workspace/wsb/herbein1/packages/toss3/toss3/spack/opt/spack/linux-
rhel7-x86_64/gcc-8.2.0/libsodium-1.0.15-oe5ns7kmitv3ziqhnjzovbbxaw76kgkd/lib -Wl,-rpath -Wl,/usr/workspace/wsb/herbein1/packages/toss3/toss3/spack/opt/spack/linux-rhel7-x86_64/gcc-4.9.3/gcc-8.2.0-2hwyxzty6l3z4sljoaxasish3fnehqh4/lib/../lib64 -Wl,-rpath -Wl,/usr/workspace/wsb/herbei
n1/packages/toss3/toss3/spack/opt/spack/linux-rhel7-x86_64/gcc-8.2.0/czmq-4.1.1-gxlyc2fmjwnmbledkjmppjuymzcyagla/lib -Wl,-rpath -Wl,/usr/workspace/wsb/herbein1/packages/toss3/toss3/spack/opt/spack/linux-rhel7-x86_64/gcc-8.2.0/libuuid-1.0.3-cdb6wj66i6h22copq3buy6p5f2j64oxd/lib -Wl,-
rpath -Wl,/usr/workspace/wsb/herbein1/packages/toss3/toss3/spack/opt/spack/linux-rhel7-x86_64/gcc-8.2.0/zeromq-4.2.5-ttsphgxpdhlje6ry4skwt6fafxwd7imm/lib -Wl,-rpath -Wl,/usr/workspace/wsb/herbein1/packages/toss3/toss3/spack/opt/spack/linux-rhel7-x86_64/gcc-8.2.0/libsodium-1.0.15-oe
5ns7kmitv3ziqhnjzovbbxaw76kgkd/lib -Wl,-rpath -Wl,/usr/workspace/wsb/herbein1/packages/toss3/toss3/spack/opt/spack/linux-rhel7-x86_64/gcc-4.9.3/gcc-8.2.0-2hwyxzty6l3z4sljoaxasish3fnehqh4/lib/../lib64                                                                                  
/usr/bin/ld: warning: libczmq.so.3, needed by /usr/lib64/libflux-core.so, may conflict with libczmq.so.4
```

**Comment by dongahn** [comment]
> I'm still getting the error about czmq version mismatches from /usr/lib64/libflux-core.so. I believe the problem here is that there is a -lflux-core flag but no -L/path/to/flux-core flag within the libresource.la. I am attempting to add that now (but I think there will be some problems there, we shall see soon).

I thought this should be taken care by `$PKG_CONFIG_PATH` ...?

**Comment by dongahn** [comment]
> libresource.la

This library is the new resource infrastructure which should have no dependency to flux core libraries. Its sub-component, `planner` depends on czmq though.

**Comment by grondo** [comment]
Well, this whole scenario seems like there is no possible good solution for the linker.

Any one of the `*_LDFLAGS` from dependencies could add a `-L/usr/lib64`, and since `-L` paths are searched in the order they appear on the cmdline (and not the more reasonable last-first order), this means any later library could be found in /usr/lib64 instead of whatever side-install path you wanted.

This isn't an issue unless your side install version of the library is a newer version, which actually seems like the most likely case (except, Spack).

So no matter what you do, you are stuck with a potential future problem. I think we just have to hope not too many people run in this mode where all the dependencies except one or two come from some personal, side-install version.

**Comment by dongahn** [comment]
>  This isn't an issue unless your side install version of the library is a newer version, which actually seems like the most likely case (except, Spack).

For Spack, our flux recipe can list all of the dependencies so that they are explicitly pulled in. This way, there will no dependencies to the system-locations like `/usr/lib64`.

I understand this would be a problem if flux is manually built and some of the dependencies are satisfied by Speck-Installed packages.

**Comment by grondo** [comment]
> For Spack, our flux recipe can list all of the dependencies so that they are explicitly pulled in. This way, there will no dependencies to the system-locations like /usr/lib64.

Yeah, that is good advice for Spack overall: "all in or not at all" :smirk:

**Comment by grondo** [comment]
>  Won't this also be a problem if even just one library comes from a side-install (especially if the system-installed version is incompatible with Flux's requirements)? 

Yeah, It seems like it *could* be a problem, but I don't think there is a way the flux build system can work around these potential problems. This is just what you get when you have lots of side installed software. Long term, Flux is system software so hopefully not every single user has to build up their own personal version of Flux, and therefore I don't see this as a *crititcal* issue to fix.

> I wonder if libtool does some intelligent stripping of flags when they are in *_LIBS as opposed to *_LDFLAGS.

Event if you stripped `-L/usr/lib64` from flags, you haven't completely solved the problem. One of your side-install paths could have multiple dependencies in it, one of which is not the one you want (which is in a different side-install path). I just don't see a good foolproof solution to this problem.

**Comment by SteVwonder** [comment]
Ok. It looks like the main action item from this issue is moving `BOOST_LDFLAGS` into `*_LDADD`, which I plan to do in #385.  Once that happens, I think we should close this issue, and re-open it if we discover anything new that could help with this side-install issue.
