### ISSUE TITLE
Enabling fast high throughput mode within LLNL UQP with flux

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-sched#408]
This is to discuss potential issues and lessons learned from adapting flux scheduling into LLNL UQP to solve their high throughput needs. 

David Domyancic and I will team up at the next COMP hackathan to create a prototype.

Problem: UQP users typically have a canonical batch script on which they want to utilize UQP high throughput mode where it creates a largish batch allocation and run many many instances of the same batch script into that allocation. UQP uses `srun`'s offset technique to do ad hoc scheduling on this batch allocation. However, this doesn't work well when the users have `srun` invocations in their scripts, which is typical.

 Nesting sruns is not well supported. Generally speaking, nesting system launchers are bad idea beyond slurm (Sierra jsrun has the same issue, for example) and we want to use flux scheduling to solve the issue. 

Proposal: Replace this user level scheduling with a single flux instance. Use JSC to keep track to job status changes similar to https://github.com/flux-framework/flux-workflow-examples/tree/master/example7. One problem is whether we can just use flux submit (or submit rpc) per each job script or whether we need a full sub instance. It depends on what the script requires. If it only requires a CWD change and some unique environment variable, we should be able to do this with flux submit; otherwise a flux instance per job. The latter has some implication to our JSC usage pattern.

**Comment by dongahn** [comment]
The last issue David reported was a coredump from one of the flux instance.

A question. Do we need to specify some extra`-o` options with `flux wreckrun` to launch a MPI job on TOSS3 systems at all?

**Comment by grondo** [comment]
> A question. Do we need to specify some extra-o options with flux wreckrun to launch a MPI job on TOSS3 systems at all?

We should not, especially if the MPI supports PMI.

At the moment, only the spectrum MPI wreck "plugin" makes use of `-o mpi=personality` option to `wreckrun/submit`.

**Comment by dongahn** [comment]
UQP's refactored lightweight ensemble manager called Themis is now using Flux tree and other interface. It essentially unified its scheduler with Flux. This is no longer a problem.
