### ISSUE TITLE
resource: introduce class hierarchy for resource generator

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-sched#411]
As suggested by @dongahn in #385:
>  Wondering if this is a good time to introduce a class hierarchy for the generator class.
> - Base generator class defines the interfaces
> - Make GRUG-based class as a derived class of that
> - Make Hwloc-based class also as a derived class of that

> This way, when we add more reader types, it becomes easier to plug into our system ?

**Comment by dongahn** [comment]
This is being looked at in support of JGF reader work and elastic job scheduling work that me, @milroy and @SteVwonder are working on.

**Comment by dongahn** [comment]
This has been done in PR #521.

**Comment by dongahn** [comment]
I believe the resource reader class hierarchy is our response to this.
