### ISSUE TITLE
resource-match: reduce kvs watches and synchronous operations

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-sched#412]
When bootstrapping, the resource matching service performs a synchronous `kvs_watch_once` on multiple keys in the KVS (one for each rank in the instance) to extract the hwloc xml information.

One potential solution is https://github.com/flux-framework/flux-core/issues/1826.

Another solution could be to watch the `resource.hwloc.loaded` kvs diretory and process the new hwloc xml in the watch callback as it is loaded by each rank.

**Comment by dongahn** [comment]
W/ PR #694, this should no longer be a problem. Though we will still use kvs_watch_once "just in case", the sync is being done through `flux-resource.acquire` interface.
