### ISSUE TITLE
hwloc parsing: add tests for opencl coprocessors

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-sched#413]
We currently have code that supports opencl devices, but no tests for that code.  We should grab the hwloc output from a machine with AMD (or maybe even Xeon Phi) coprocessors and add that to the test suite.

**Comment by dongahn** [comment]
Thanks! yes this topic came out today and this will be very important!

**Comment by dongahn** [comment]
A question is, though how we can get AMD GPU machine access so that we can collect some hwloc data.

**Comment by dongahn** [comment]
This was done as part of #464.
