### ISSUE TITLE
sched: create simple priority plugin for testing

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-sched#415]
#282 tracks the development of a fair-share plugin.  I figured we could tackle even lower hanging fruit in this issue by just developing a simple priority plugin that gets loaded and run during the CI tests. Currently we have nothing that tests the ability to load and run a priority plugin (as noted in #414).

**Comment by dongahn** [comment]
Make sense. And/or develop some unit tests for fair-share plugin code...

**Comment by dongahn** [comment]
Priority plug-in is actively addressed in flux-accounting. The core's plugin API has been co-designed and the plugin in flux-accounting is being developed in tandem.
