### ISSUE TITLE
[schedsrv] convert to argc, argv style argument parsing

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-sched#43]
In PR flux-framework/flux-core#289 the module main function prototype changed to pass arguments in argc, argv format rather than a zhash_t. This was to eliminate another CZMQ exposure in the public API, and also to conform with RFC 5.

In my haste to get this fixed throughout the code base I avoided doing the right thing in flux-sched/sched/schedsrv.c, and just converted the args to a hash and let the existing code run. Probably this should be cleaned up as a low priority.

This code is also duplicated in the simulator modules.

**Comment by lipari** [comment]
This issue was addressed with the merge of https://github.com/flux-framework/flux-sched/pull/45
