### ISSUE TITLE
Pilot2 workflow need to design the best hierarchical scheduling scheme.

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-sched#431]
Placeholder to capture the results of our discussion next week with the Pilot2 team.

**Comment by FrankD412** [comment]
@dongahn @ingolfsson @SteVwonder -- Feel free to correct if I'm mistaken.

We met today and discussed a potential scheme for allowing for an allocation to be hierarchically constructed of multiple batch allocations. The initial concept is that the first flux instance can register other allocations that spin up brokers as children and then inherit job tracking and status information from them. To the high level user, calls to flux would remain the same with the underlying flux-sched framework being aware of the hierarchy and scheduling in a balanced fashion to its registered children brokers.

If I recall correctly, the above option is a more lightweight path forward to the another route which would be to assimilate new resources into the top level flux instance, but some hesitation was expressed on turnaround time for the feature compared to the more ad-hoc approach described above.

**Comment by dongahn** [comment]
@FrankD412: Yes, this is correct. Thank you for adding this info. Since our `flux-hierarchy` repo will be the module that is likely to address your needs. I will remove this ticket from `flux-sched` and open a new ticket under that repo.

**Comment by dongahn** [comment]
@SteVwonder: Oh cool! yes I see that in the same location. Thanks.
