### ISSUE TITLE
Support for minimal jobspec

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-sched#438]
As discussed in https://github.com/flux-framework/rfc/issues/149, the minimal jobspec only has nodes, slots, and cores, while the HWLOC and resource matching service have caches, PUs, sockets, and other resource types in the containment hierarchy.

In the short-term, we either need to filter the "non-minimal" resources out of the hwloc/resource module, or we need to insert the "non-minimal" resources into the jobspec that the scheduler/resource module sees.

In the long-term, it would be great if the scheduler could handle "sparse" jobspecs (i.e., jobspecs where an arbitrary subset of the resources in the containment hierarchy are specified).

**Comment by dongahn** [comment]
> In the short-term, we either need to filter the "non-minimal" resources out of the hwloc/resource module, or we need to insert the "non-minimal" resources into the jobspec that the scheduler/resource module sees.

If this can be filtered at the hwloc-resource module, that will be my preference. 

> In the long-term, it would be great if the scheduler could handle "sparse" jobspecs (i.e., jobspecs where an arbitrary subset of the resources in the containment hierarchy are specified).

From the `resrc` experience, the implementation dealing with "sparse" jobspec has proven to be pretty fragile. The prefix can be omitted pretty reliably, but anything missing from the intermediate vertices are fragile.

**Comment by SteVwonder** [comment]
> From the `resrc` experience, the implementation dealing with "sparse" jobspec has proven to be pretty fragile.

I am not recalling the fragility of the sparse-ness. Are there any issues/PRs on GitHub related to that?  A quick search for `sparse` didn't turn any `resrc`-related stuff up.

For the long-term, I think not supporting sparse-ness will make jobspec portability across systems hard.  For example, if one system includes the processors' caches in the resource hierarchy so that users/Flux can optimize binding/placement but another system doesn't include the caches for simplicity/scheduler performance, then a single jobspec will not work for both systems.

**Comment by dongahn** [comment]
I think we had a bunch of issues when sched was pounded first by pilot2 work. I had to work several times to get something going but even then it was very difficult to reason about the correctness. If a brave soul wants to solve this in a general way, I am all for it. But I am just sharing my own experience.

**Comment by dongahn** [comment]
@SteVwonder: is this addressed with PR #467?

**Comment by SteVwonder** [comment]
That is a good question. One thing we will need to confirm is that the current resource matching service can handle the latest proposal, which includes GPUs (assuming only nodes, cores, and gpus are in the whitelist).

Link to the latest proposal: https://github.com/flux-framework/rfc/issues/149#issuecomment-503778131

**Comment by dongahn** [comment]
I believe PR #454 addresses this. If not, please reopen.
