### ISSUE TITLE
Compilation fail on MAC OS/X with docker

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-sched#441]
resource_match.cpp: In function 'json_t* get_string_blocking(flux_t*, const char*)':
resource_match.cpp:259:53: error: cannot convert 'const char*' to 'char**' for argument '3' to 'int flux_kvs_watch_once(flux_t*, const char*, char**)'
     if (flux_kvs_watch_once (h, NULL, key, &json_str) < 0) {
                                                     ^
Makefile:564: recipe for target 'resource_la-resource_match.lo' failed

**Comment by dongahn** [comment]
Was there a recent change to `flux_kvs_watch_once`?

**Comment by grondo** [comment]
Looks like you might not have an up to date `fluxrm/flux-core` docker image?

**Comment by dongahn** [comment]
Running `./src/test/docker/docker-run-checks.sh --no-home -j 2 --` in the latest `flux-sched` isn't enough?

**Comment by dongahn** [comment]
Maybe I need to run this for the latest flux-core as well...

**Comment by grondo** [comment]
I *think* that making sure you run `docker pull fluxrm/flux-core:latest` and maybe `docker pull fluxrm/flux-core:centos7`  should work. I'm not sure it tries to pull from docker hub by default if you've already got a local tag...

**Comment by grondo** [comment]
(I'll check on the script later, maybe we can make that automatic..)

**Comment by dongahn** [comment]
> I'm not sure it tries to pull from docker hub by default if you've already got a local tag...

This makes sense since I have a local copy. I will try your suggestion.

**Comment by dongahn** [comment]
`docker pull fluxrm/flux-core:latest` and `docker pull fluxrm/flux-core:bionic` did the trick. Thanks @grondo.
