### ISSUE TITLE
uuid_generate adds a huge startup overhead

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-sched#451]
I tried to add uuid support into `resource` and found that this blows up the graph populating time by multiple factors. 

I don't remember why we decide to use an uuid for each resource. Does anyone remember? 

If there isn't a good reason for this, can we just use a "unique" integer id into each resource? Our graph implementaiton is such as way that `vtx_t` and `edg_t` resolve to integers and uniquely identify each vertex and edge. Can we use this instead of the heavyweight uuid?

**Comment by grondo** [comment]
> If there isn't a good reason for this, can we just use a "unique" integer id into each resource? Our graph implementaiton is such as way that vtx_t and edg_t resolve to integers and uniquely identify each vertex and edge. Can we use this instead of the heavyweight uuid?

Yes, that seems fine to me.

The UUID per resource was just a way to resolve the same resource between any instance running within a datacenter (or I suppose any instance anywhere). This allows resolving an error, data, resource tags, etc from any child instance to the parent easily.

However, a uuid per resource seems like a concept that doesn't really have a good (or possible?) implementation, and besides, we don't really have a use case yet for matching resources across instances (and I bet there is a better way for parent<->child instances anyway)

**Comment by grondo** [comment]
> Our graph implementaiton is such as way that vtx_t and edg_t resolve to integers and uniquely identify each vertex and edge. Can we use this instead of the heavyweight uuid?

Just curious, will the implementation keep the same vtx_t id in all Rs generated from the parent instance R?

**Comment by dongahn** [comment]
> Just curious, will the implementation keep the same vtx_t id in all Rs generated from the parent instance R?

Yes, that is my current plan. 

The top-level instance that will use a grug-based  or hwloc-based generator, which will use the vtx_t id. Then, the nested instances will use an R reader such as RV1 reader which will keep this same unique id instead of regenerating a new one.
