### ISSUE TITLE
./configure with no prefix try to install under /usr/local/lib

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-sched#452]
I am using docker on my Mac osx. 

I checkout a flux-shed branch and then did:

`src/test/docker/docker-run-checks.sh --no-home -I --`

And once I have the interactive shell within docker, I did `./configure` (with no option like `--prefix`), `make` and `make install`. To my surprise, I get

```
make[3]: Nothing to be done for 'install-exec-am'.
 /bin/mkdir -p '/usr/local/lib/flux/modules'
/bin/mkdir: cannot create directory '/usr/local/lib/flux': Permission denied
```

I don't fully understand why this tries to install this under `/usr/local/lib/` when it should `/usr/lib` where our flux core docker images are installed.

Any idea?

**Comment by grondo** [comment]
The default for all autoconf `configure` scripts is `--prefix=/usr/local`. You have to provide `--prefix=/usr` if you want to install to `/usr`.

**Comment by dongahn** [comment]
Ah. I didn't know. Thanks. Does this work for `/etc/flux` as well where flux-core's rc scripts seem to be installed?

```
ahn1@c7ec51045e3e:/usr/src/t$ ll /etc/flux/
total 24
drwxr-xr-x 4 root root 4096 Mar 14 01:45 ./
drwxr-xr-x 1 root root 4096 Mar 21 22:16 ../
drwxr-xr-x 2 root root 4096 Mar 14 01:45 conf.d/
-rwxr-xr-x 1 root root  710 Mar 14 01:45 rc1*
drwxr-xr-x 2 root root 4096 Mar 14 01:45 rc1.d/
-rwxr-xr-x 1 root root  869 Mar 14 01:45 rc3*
```

**Comment by grondo** [comment]
> Does this work for /etc/flux as well where flux-core's rc scripts seem to be installed?

I think you also have to provide `--sysconfdir=/etc` or else the sysconfdir files will be installed to `$prefix/etc`.

So to install to `/usr` correctly with `make install` run `./configure --prefix=/usr --sysconfdir=/etc`

**Comment by dongahn** [comment]
Works!
