### ISSUE TITLE
update flux-sched to new flux_respond() and flux_respond_error() prototypes

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-sched#456]
In flux-framework/flux-core#2120 the function signatures for `flux_respond()` and `flux_respond_error()` changed, so we need to update flux-sched services that uses these functions (travis currently failing).

Sorry! I should have noticed that before merging.

**Comment by garlick** [comment]
Uh oh, I thought sched was currently inoperable with flux-core master.

**Comment by grondo** [comment]
No we marched flux-sched forward along with flux-core. 

This one's pretty straightforward. I can push a branch or let me know if you want to take it.

**Comment by garlick** [comment]
I'm offline for a while so go ahead if you have time.  So how are sched's
tests working?  Did we interface it with the job manager?

**Comment by grondo** [comment]
See #440. We removed everything that used old interfaces from flux-core.
We still need to tie the new resource service-based scheduler into the scheduler service exported by the job manager. Right now flux-sched can't run jobs with flux-core master, but it has the resource matching service and related tools with their unit tests.
