### ISSUE TITLE
Scheduling property/policy configuration

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-sched#458]
One use case described in #447. 

Needing to specify resource exclusivity is captured in https://github.com/flux-framework/rfc/issues/101#issuecomment-329020512

**Comment by dongahn** [comment]
We discussed this at our meeting yesterday. 

This needs to be co designed with flux-core's configuration design. Ideally core would allow an external scheduler like ours to add config files in the same format (tomal) to customize the schedule's behavior.

**Comment by dongahn** [comment]
Now we have completed the current phase, we should add a bit more detailed plan to co-design this. @garlick took on an action item to start this planning.

**Comment by dongahn** [comment]
@garlick: somehow I can't find the example you suggested, which shows how TOML configuration should be used. Could you put a link here? Sorry.

**Comment by garlick** [comment]
This is the interface:
https://github.com/flux-framework/flux-core/blob/master/src/common/libflux/conf.h

An example:
https://github.com/flux-framework/flux-core/blob/3af5a6b813f9df2f5e1a8853f4b7a311b7a9f05e/src/broker/boot_config.c#L170

I have to run to an appointment right now, and the above may not be quite enough to make sense.  More explanation to come.

**Comment by garlick** [comment]
Here are a few notes on the config stuff.  It is pretty bare bones and you will likely find it lacking.  As I recall lots of ideas were tossed around prior to this and none really stuck, or were considered a good idea to implement at that time, so this was the minimum design needed to get the broker bootstrap config going.  The sched use case may help us see what work needs to be done to improve the situation.

If you want to add a `qmanager.toml` config file for that module, you would first prepare to install config files to the default flux location.  Add to configure.ac:
```
AS_VAR_SET(fluxcfdir, $sysconfdir/flux/conf.d)
AC_SUBST(fluxcfdir)
```
Then in a Makefile.am you can do e.g.
```
dist_fluxcf_DATA = \
        qmanager.toml
```

Where `qmanager.toml` looks something like:
```toml
[qmanager]
foo = 42
```
See https://github.com/toml-lang/toml for the TOML language reference.

We convert TOML to JSON internally (wrapped in a `flux_conf_t`), combining all the toml fragments into one object and give you an "unpack" style function to access it, e.g. the above could unpacked from the aggregate config object like the JSON object `{"qmanager":{"foo":42}}`.

The config is not cached instance or broker-wide.  It is cached in the `flux_t` handle so the scope is  same as the handle, e.g. your module.  The first call to to `flux_conf_get()` catches general TOML parse errors.  Any error here should be logged and cause your `mod_main()` to exit.  On success, subsequent calls to `flux_conf_get()` always succeed as they just return the cached object.

You can then call `flux_conf_unpack()` to access specific data in the config object with the usual unpack semantics, although note that more detailed error info may be available via the `error` struct than we typically have for other unpack style API calls.

Hope that helps a little.

Some more examples can be found in:
https://github.com/flux-framework/flux-core/blob/master/src/common/libflux/test/conf.c

A bit more info in the PR (with ref to issues):
https://github.com/flux-framework/flux-core/pull/2501

**Comment by dongahn** [comment]
This is extremely helpful. Thanks @garlick!

**Comment by dongahn** [comment]
@garlick: This looks pretty promising. This will allow me to implement the following order of configuration precedence. (a lower numbered config source takes precedence over a higher numbered source).

1. module load-time parameters (which can be specified either manually for reload or through RC environment variables for the initial load)
2. configuration file load-time parameters
3. compilation time parameters (via header files)

We talked about providing config parameters through home directory (e.g., `~/.flux`) etc, but I don't think we will need it for the current use case. 

A question: how did you test this scheme though? I want to be able to test if this precedence order is correctly enforced and wether the whole scheme still works when there is no configuration file etc.

**Comment by garlick** [comment]
> A question: how did you test this scheme though? I want to be able to test if this precedence order is correctly enforced and wether the whole scheme still works when there is no configuration file 

Test of boot configuration:
https://github.com/flux-framework/flux-core/blob/master/t/t0013-config-file.t

input files for above test:
https://github.com/flux-framework/flux-core/tree/master/t/conf.d

unit tests
https://github.com/flux-framework/flux-core/blob/master/src/common/libflux/test/conf.c

Note that there is a default "in tree" path for config files pointing to `etc/conf.d` in flux-core, and a configured install path, e.g. `${prefix}/etc/flux/conf.d`.  In the scheduler:
* install any config file fragments to the configured install path (see autoconf hunk above).  The files must end in `.toml` and should have the same name as the stanza they provide.  E.g. `qmanager.toml` with a `[qmanager]` stanza
* for testing, use the FLUX_CONF_DIR environment variable to point flux to a test's config directory.  At present nothing in flux _requires_ a config file, so this won't break other parts of the system.

**Comment by dongahn** [comment]
@garlick:

> The first call to to flux_conf_get() catches general TOML parse errors. Any error here should be logged and cause your mod_main() to exit.

Should not having a toml file (e.g., `qmanager.toml`) in the conf directory also be a fatal error which leads your module to exit, though? It seems there could be some single-user flux use cases where users just remove (rename) the configuration file and go with other ways to pass configurations.

Do you currently require the existence of the conf file in other modules?

**Comment by dongahn** [comment]
Just posted a WIP PR (#599) in case folks want to give early feedback.

FYI I plan to post two PRs: one will be for qmanager (#599) and the other will be for resource (to be done later.)

**Comment by dongahn** [comment]
File an issue with the semantics of FLUX_CONF_DIR: https://github.com/flux-framework/flux-core/issues/2759

Instead of using flux module load at runtime for testing, it seems I will have to use flux start for each test.

**Comment by dongahn** [comment]
This has been done for `qmanager`. For fluxion-resource, we need to see the evolution of RV2 a bit before adding conf support to fluxion-resource prematurely.
