### ISSUE TITLE
hwloc isn't configured for AMD GPUs on crayz

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-sched#462]
As part of future Corona support, we still need to test our current AMD GPU scheduling support as I wrote the code without proper testing (I had no machine access back then).

 I had a chance to look at one of the crayz compute nodes today in an attempt to get an hwloc XML file that includes GPU info. But It seems hwloc isn't configured for proper AMD GPU support. The only GPU device info contained within the XML file:

```xml
        <object type="Bridge" os_index="0" bridge_type="0-1" depth="0" bridge_pci="0000:[00-04]">
          <object type="Bridge" os_index="18" bridge_type="1-1" depth="1" bridge_pci="0000:[01-02]" pci_busid="0000:00:01.2" pci_type="0604 [1022:1453] [1022:1453] 00" pci_link_speed="0.000000">
            <object type="Bridge" os_index="4096" bridge_type="1-1" depth="2" bridge_pci="0000:[02-02]" pci_busid="0000:01:00.0" pci_type="0604 [1a03:1150] [1a03:1150] 04" pci_link_speed="0.000000">
              <object type="PCIDev" os_index="8192" pci_busid="0000:02:00.0" pci_type="0300 [1a03:2000] [1a03:2000] 41" pci_link_speed="0.000000">
                <object type="OSDev" name="card0" osdev_type="1"/>
                <object type="OSDev" name="controlD64" osdev_type="1"/>
              </object>
            </object>
          </object>
        </object>
```

With this, I suspect hwloc won't detect this as the `HWLOC_OBJ_OSDEV_COPROC` type as coded [here](https://github.com/flux-framework/flux-sched/blob/master/resource/generators/gen.cpp#L566). My suspicion is, hwloc would work better if it is configured with `--enable-opencl`. So I downloaded hwloc-1.11.12 and typed in the following, but `configure` encountered an issue:

```
$ ./configure --enable-opencl

<CUT>
checking for final PCIACCESS support... yes
checking CL/cl_ext.h usability... no
checking CL/cl_ext.h presence... no
checking for CL/cl_ext.h... no
configure: WARNING: Specified --enable-opencl switch, but could not
configure: WARNING: find appropriate support
configure: error: Cannot continue
```

I can keep looking, but if someone else like @trws already looked at this before, I could use some help?

**Comment by trws** [comment]
The config I used for chimera was this:

`./configure --enable-libnuma --enable-cuda --enable-opencl CPPFLAGS=-I/opt/rocm/opencl/include -I/usr/local/cuda-10.1/include  LDFLAGS=-L/opt/rocm/opencl/lib/x86_64/ -L/usr/local/cuda-10.1/lib64`

The xml for chimera is attached as well.

[chimera.txt](https://github.com/flux-framework/flux-sched/files/3143764/chimera.txt)

It shows a coproc for each of the NVIDIA gpu and the AMD one.

**Comment by dongahn** [comment]
Great! I will give it a try. 

chimera as in the configurable system that ANL runs or something else?

**Comment by trws** [comment]
It's the mixed-gpu test box I had built to do some of the packaging tests for toss on my desk.  If you want I can probably make you an account on it.

**Comment by dongahn** [comment]
Ah... Now I remember. And the ANL testbed system is actually called Chameleon: https://www.anl.gov/mcs/article/chameleon-cloud-computing-testbed-renewed-for-second-phase

**Comment by dongahn** [comment]
FYI -- crayz doesn't have `/usr/local/cuda-10.1/include` nor `/usr/local/cuda-10.1/lib64` (this is probably one of the reasons you are looking at this), so I configured:

```
 $ ./configure --prefix=/g/g0/dahn/workspace/ROCM/inst --enable-libnuma --enable-opencl CPPFLAGS=-I/opt/rocm/opencl/include LDFLAGS=-L/opt/rocm/opencl/lib/x86_64

<CUT>

-----------------------------------------------------------------------------
Hwloc optional build support status (more details can be found above):

Probe / display I/O devices: PCI(pciaccess+linux) OpenCL GL
Graphical output (Cairo):    yes
XML input / output:          full
libnuma memory support:      yes
Plugin support:              no
-----------------------------------------------------------------------------
```

Seemed configure went ok. But the resulting xml still doesn't contain coproc type...


[crazy5.txt](https://github.com/flux-framework/flux-sched/files/3143821/crazy5.txt)

**Comment by trws** [comment]
That should only happen if the opencl stuff isn't installed correctly, or just isn't installed at all.  Does /opt/rocm/opencl/bin/**/clinfo list the GPU?

**Comment by dongahn** [comment]
crayz5{dahn}183: /opt/rocm/opencl/bin/x86_64/clinfo
ERROR: clGetPlatformIDs(-1001)

**Comment by trws** [comment]
Yup, that's what it is.  The opencl support just isn't there for some reason.

**Comment by dongahn** [comment]
Ok. Thanks. You saved me ton of time that I could have wasted, chasing this down! 

I will talk to Trent about it. When I get my access to Corona, maybe things set up a bit more properly.

**Comment by trws** [comment]
Good idea.  It may be an arm support issue for all I know, maybe they just don't have OpenCL driver support over there right now.

**Comment by dongahn** [comment]
Hmmm... arm support? At least `/proc/cpuinfo` on crayz5 node says CPUs are AMD EPYC... Should I try some other nodes?

```
rocessor	: 47
vendor_id	: AuthenticAMD
cpu family	: 23
model		: 1
model name	: AMD EPYC 7451 24-Core Processor
stepping	: 2
microcode	: 0x8001227
cpu MHz		: 2300.000
cache size	: 512 KB
physical id	: 0
siblings	: 48
core id		: 30
cpu cores	: 24
apicid		: 61
initial apicid	: 61
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc art rep_good nopl nonstop_tsc extd_apicid amd_dcm aperfmperf eagerfpu pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_l2 cpb hw_pstate sme retpoline_amd ssbd ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif overflow_recov succor smca
bogomips	: 4590.68
TLB size	: 2560 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 43 bits physical, 48 bits virtual
power management: ts ttp tm hwpstate cpb eff_freq_ro [13] [14]
```

**Comment by trws** [comment]
Ugh, I was thinking of ulna instead of CrayZ.  There's no technical reason it shouldn't be working there that I know of, would have to be software or permission issues.

**Comment by dongahn** [comment]
Ok. An email sent to Trent, we'll see if crazy is viable for this testing. Thank you so much Tom!

**Comment by dongahn** [comment]
I was able to get an hwloc xml from corona! In case others stumble across this, here is what I did.

```sh
corona82{dahn}24: salloc -p pgpu -N 1 #So that you can get a node from the GPU enabled partition"
corona11{dahn}21: module load rocm
corona11{dahn}22: /opt/rocm/opencl/bin/x86_64/clinfo
<CUT>
  Extensions:					 cl_khr_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_fp16 cl_khr_gl_sharing cl_amd_device_attribute_query cl_amd_media_ops cl_amd_media_ops2 cl_khr_subgroups cl_khr_depth_images cl_amd_copy_buffer_p2p cl_amd_assembly_program
$
$
$ ./configure --prefix=/g/g0/dahn/workspace/ROCM/inst --enable-libnuma --enable-opencl CPPFLAGS=-I/opt/rocm/opencl/include LDFLAGS=-L/opt/rocm/opencl/lib/x86_64
$ make
$ make install
$ ../inst/bin/lstopo corona11.xml
```
The generated XML file: [corona12.txt](https://github.com/flux-framework/flux-sched/files/3150097/corona12.txt). The relevant section is the following:

```xml
        <object type="Bridge" os_index="1" bridge_type="0-1" depth="0" bridge_pci="0000:[10-15]">
          <object type="Bridge" os_index="65553" name="Advanced Micro Devices, Inc. [AMD] Family 17h (Models 00h-0fh) PCIe GPP Bridge" bridge_type="1-1" depth="1" bridge_pci="0000:[11-13]" pci_busid="0000:10:01.1" pci_type="0604 [1022:1453] [0000:0000] 00" pci_link_speed="0.000000">
            <info name="PCIVendor" value="Advanced Micro Devices, Inc. [AMD]"/>
            <info name="PCIDevice" value="Family 17h (Models 00h-0fh) PCIe GPP Bridge"/>
            <object type="Bridge" os_index="69632" name="Advanced Micro Devices, Inc. [AMD]" bridge_type="1-1" depth="2" bridge_pci="0000:[12-13]" pci_busid="0000:11:00.0" pci_type="0604 [1022:1470] [0000:0000] 01" pci_link_speed="0.000000">
              <info name="PCIVendor" value="Advanced Micro Devices, Inc. [AMD]"/>
              <object type="Bridge" os_index="73728" name="Advanced Micro Devices, Inc. [AMD]" bridge_type="1-1" depth="3" bridge_pci="0000:[13-13]" pci_busid="0000:12:00.0" pci_type="0604 [1022:1471] [0000:0000] 00" pci_link_speed="0.000000">
                <info name="PCIVendor" value="Advanced Micro Devices, Inc. [AMD]"/>
                <object type="PCIDev" os_index="77824" name="Advanced Micro Devices, Inc. [AMD/ATI] Vega 10 [Radeon Instinct MI25]" pci_busid="0000:13:00.0" pci_type="0300 [1002:6860] [1002:0c35] 01" pci_link_speed="15.753846">
                  <info name="PCIVendor" value="Advanced Micro Devices, Inc. [AMD/ATI]"/>
                  <info name="PCIDevice" value="Vega 10 [Radeon Instinct MI25]"/>
                  <object type="OSDev" name="card1" osdev_type="1"/>
                  <object type="OSDev" name="renderD128" osdev_type="1"/>
                  <object type="OSDev" name="controlD65" osdev_type="1"/>
                  <object type="OSDev" name="opencl0d0" osdev_type="5">
                    <info name="CoProcType" value="OpenCL"/>
                    <info name="Backend" value="OpenCL"/>
                    <info name="OpenCLDeviceType" value="GPU"/>
                    <info name="GPUVendor" value="Advanced Micro Devices, Inc."/>
                    <info name="GPUModel" value="Vega 10 [Radeon Instinct MI25]"/>
                    <info name="OpenCLPlatformIndex" value="0"/>
                    <info name="OpenCLPlatformName" value="AMD Accelerated Parallel Processing"/>
                    <info name="OpenCLPlatformDeviceIndex" value="0"/>
                    <info name="OpenCLComputeUnits" value="64"/>
                    <info name="OpenCLGlobalMemorySize" value="16760832"/>
                  </object>
                </object>
              </object>
            </object>
          </object>
```

**Comment by dongahn** [comment]
Finally, crayz worked fine with 

`module load rocm`

**Comment by dongahn** [comment]
But still hwloc is misconfigured (configured with `--enable-opencl`). @trws: do you want me to take this to Trent and Jim Silva or do you have other plans out of your chimera effort?

**Comment by trws** [comment]
Don’t worry about it for now.  It’s not that hwloc is misconfigured, but rather that the rocm and cuda deps don’t exist when it’s built, working with Trent on it already so hopefully we can resolve it sometime soon.

On May 6, 2019, at 4:10 PM, Dong H. Ahn <notifications@github.com<mailto:notifications@github.com>> wrote:


But still hwloc is misconfigured (configured with --enable-opencl). @trws<https://github.com/trws>: do you want me to take this to Trent and Jim Silva or do you have other plans out of your chimera effort?

**Comment by dongahn** [comment]
@trws: would you like me to add `chimera.xml` into our testing rig as well? My guess is that our graph-based scheduler should be able to handle such a multi-GPU type system easily. How this system should be handled by the execution system is a different story though.

**Comment by trws** [comment]
May as well, it’s not likely anyone is going to build a cluster out of nodes like that, but we might end up with multiple coprocs of some type at some point, not to mention nodes with each in the same system.  Will have to do some disambiguation for exec, and maybe sched too, possibly by programming model? Something to think about.

On May 6, 2019, at 4:23 PM, Dong H. Ahn <notifications@github.com<mailto:notifications@github.com>> wrote:


@trws<https://github.com/trws>: would you like me to add chimera.xml into our testing rig as well? My guess is that our graph-based scheduler should be able to handle such a multi-GPU type system easily. How this system should be handled by the execution system is a different story though.
