### ISSUE TITLE
Is hwloc's naming convention for AMD GPUs stable?

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-sched#463]
It turned out the current AMD GPU support *almost* worked :-). 

As you can see from [here](https://github.com/flux-framework/flux-sched/blob/master/resource/generators/gen.cpp#L574), the code takes the suffix string that comes after `opencl` as the id of the discovered GPU (following the NVIDIA naming conversion).

But it appears that the names on CORONA is actually: `opencl0d1`, `opencl0d2`, `opencl0d3`, and `opencl0d4`. They contain the extra "0d"

I can always go like:

```diff
             else if (strncmp(obj->name, "opencl", 6) == 0)
-                id = atoi (obj->name + 6);
+                id = atoi (obj->name + 8);
```
Or do a string matching with "opencl0d". In fact, when I did this, things seem to work fine:

[out.pdf](https://github.com/flux-framework/flux-sched/files/3150793/out.pdf)

But this naming convention is reverse engineered at best and I'm unsure if this is future proof. Anyone knows about this? Otherwise, I will contact hwloc guys. 

BTW, this convention also means that for chimera, both NVIDIA GPU and AMD GPU each will become `gpu0` as in 
[chimera.pdf](https://github.com/flux-framework/flux-sched/files/3150813/chimera.pdf)

 I think this is okay as ether can have the same resource type and id but their property will be different. One would be "NVIDIA" and the other would be "AMD" or similar.

**Comment by dongahn** [comment]
It appears hwloc examples essentially use the same trick to fetch the device id as in:

https://github.com/open-mpi/hwloc/blob/ba157bab62d3ffd0b53565f18d3260b7468e5a6e/doc/examples/gpu.c#L71

So this seems okay.

**Comment by dongahn** [comment]
So, from this [code/comment](https://github.com/open-mpi/hwloc/blob/ba157bab62d3ffd0b53565f18d3260b7468e5a6e/include/hwloc/opencl.h#L159), the naming convension for OpenCL devices in hwloc is: "opencl" followed by a platform id followed by a device id. Then, the letter `d` delimits platform id and device id. I believe I have enough to do a PR based on this.

**Comment by dongahn** [comment]
PR #464 has this support.

**Comment by trws** [comment]
I'm thinking we might want to do some re-naming, or having an alias perhaps? As you say, either would show up as "GPU" 0, which means we probably want to have them logically numbered by coproc rather than device ID, then have something like cuda0 and opencl0d0 ourselves, hopefully the latter eventually becoming rocm0 rather than opencl really.  I'm not sure what the best way to deal with that is though.

**Comment by dongahn** [comment]
>  hopefully the latter eventually becoming rocm0 rather than opencl really
I think we should file an issue to hwloc to solve this at the hwloc level.

**Comment by trws** [comment]
Agreed, that’s not something we’ll do.  But having a way to ask flux for a coda-capable GPU or an OpenCL capable GPU seems like something we want to allow if possible, since “GPU” in many (but not quite all) cases is insufficiently specific to run a given code.

On May 7, 2019, at 11:35 AM, Dong H. Ahn <notifications@github.com<mailto:notifications@github.com>> wrote:


hopefully the latter eventually becoming rocm0 rather than opencl really
I think we should file an issue to hwloc to solve this at the hwloc level.

**Comment by dongahn** [comment]
> But having a way to ask flux for a coda-capable GPU or an OpenCL capable GPU seems like something we want to allow if possible, since “GPU” in many (but not quite all) cases is insufficiently specific to run a given code.

Absolutely. My initial thought was to support such constraints through properties. A jobspec can specify GPU as a resource type, and if it needs that to be of a specific type or having specific capabilities, it can contain this as a property (or properties) of the GPU.

BTW, do we have a way to specify a property in the current jobspec? 

We can also consider adding a new resource type for each different GPU. There is not a fundamental problem with that approach if that turns out to be better for our users. But it seems going with an evolutionary approach is easier for now? 

> As you say, either would show up as "GPU" 0, which means we probably want to have them logically numbered by coproc rather than device ID, then have something like cuda0 and opencl0d0 ourselves

FWIW, I actually don't currently keep the name `cuda0` and `opencl0d0`. I only took the suffix integer to get the device number. My proposal would be to keep it this way, and when this meets with the new execution system we can adjust this for whatever makes best sense for both scheduler and execution system. My suspicion is we will need to do some amount of adjustment and tuning anyway?

**Comment by trws** [comment]
On May 7, 2019, at 11:43 AM, Dong H. Ahn <notifications@github.com<mailto:notifications@github.com>> wrote:

FWIW, I actually don't currently keep the name cuda0 and opencl0d0. I only took the suffix integer to get the device number. My proposal would be to keep it this way, and when this meets with the new execution system we can adjust this for whatever makes best sense for both scheduler and execution system. My suspicion is we will need to do some amount of adjustment and tuning anyway?

Probably so, but part of my point was that having both come out as GPU 0 is probably worse than having them come out as GPU 0 and 1, or coprocessor 0 and 1 or something of the like.

**Comment by dongahn** [comment]
> Probably so, but part of my point was that having both come out as GPU 0 is probably worse than having them come out as GPU 0 and 1, or coprocessor 0 and 1 or something of the like.

Point taken. I will open an issue so that we can in the future add support for better numbering scheme for multi-device nodes. No matter what we do there, this has to make sense for both the scheduler and execution system. Thank you for the valuable feedback @trws!

**Comment by dongahn** [comment]
BTW one question I had:
If a job wants both types of GPUs on Chimera, what device numbering should be used with respect to each corresponding VISIBLE_DEVICES environment variables?

**Comment by trws** [comment]
They each take their own native numbering, the docs on the cuda version are actually somewhat interesting: https://docs.nvidia.com/cuda/cuda-c-programming-guide/#env-vars

It can take GPU IDs, UUID strings, or other identifiers (we should use the UUIDs if at all possible).  You can also set how it orders devices, the default for which is apparently a simple heuristic for “fastest first” which seems moderately insane.

Apparently hip will read from CUDA_VISIBLE_DEVICES or HIP_VISIBLE_DEVICES but only supports indexes… yay… https://github.com/ROCm-Developer-Tools/HIP/blob/29b3b46b425a039b9a4de6ff81a12605b8f7f648/src/hip_hcc.cpp#L1138

So… yeah, that’s going to be frustrating.

On May 7, 2019, at 12:18 PM, Dong H. Ahn <notifications@github.com<mailto:notifications@github.com>> wrote:


BTW one question I had:
If a job wants both types of GPUs on Chimera, what device numbering should be used with respect to each corresponding VISIBLE_DEVICES environment variables?

**Comment by dongahn** [comment]
> Apparently hip will read from CUDA_VISIBLE_DEVICES or HIP_VISIBLE_DEVICES but only supports indexes… yay… https://github.com/ROCm-Developer-Tools/HIP/blob/29b3b46b425a039b9a4de6ff81a12605b8f7f648/src/hip_hcc.cpp#L1138 So… yeah, that’s going to be frustrating.

Ugg.
