### ISSUE TITLE
Mechanism to add property to resource

### ISSUE THREAD

**Issue by tpatki** [flux-framework/flux-sched#469]
As per discussion with @dongahn.

One thing that we need before we can productize the research code version of the variation-aware scheduler is a mechanism to specify a property for some resources. For example, we may want to specify a node performance class (say "class-1" for best preforming nodes, "class-2" for less efficient nodes, so on) , or a memory-efficiency choices ("big" or "small"), etc. Note that such information cannot be obtained from `hwloc`. 

The current version of the variation-aware scheduler accomplished this by adding a "-f <node-distribution-filename>" option to `resource-query` and setting a[ node_dist variable](https://github.com/tpatki/resource-query/blob/power_var_cab/node_dist.hpp), adding a [`perf_class` member to the `resource_pool`](https://github.com/tpatki/resource-query/blob/power_var_cab/resource_data.hpp#L322), and then setting the correct class in [`resource_gen`](https://github.com/tpatki/resource-query/blob/power_var_cab/resource_gen.cpp#L226). It uses this `perf_class` for matching with the score later in `dfu_match_power.hpp`. 

The current version doesn't use the [node property map ](https://github.com/tpatki/resource-query/blob/power_var_cab/resource_data.hpp#L315). As per @dongahn's suggestion, we should add a `flux resource add-properties <resrc:value=x>` command to allow for populating such information (eg performance class) to the property map. Instead of a single CSV file as input (as with the `-f` option above), we would now have to call for each node the `flux resource add-property <>` command to input such data, and we can also add a `flux resource add-bulk-propery <>` at some point. 

This ticket is to seek ideas on how we should go about doing this, and what is the best path forward with it.

**Comment by dongahn** [comment]
Thanks @tpatki. 

> `flux resource add-properties <resrc:value=x>`

The trick is how to specify `resrc` to uniquely identify the resource vertex in our graph data store. There are obvious cases like hostnames (for the case where we run one broker per node) but this isn't always the case. 

One idea would be:
`flux resource add-properties <uniq_id:key=value>` as each resource vertex now has that field that uniquely identify the resource. It used to be `uuid` but we ditched that because of huge initialization overheads. https://github.com/flux-framework/flux-sched/issues/451. But then we don't have `flux resource query` so getting the `uniq_id` might be difficult...

Another idea would be to disambiguate with hierarchical resource specification:
`flux resource add-properties <cluster.atlas77:key=value_x>`
`flux resource add-properties <cluster.atlas77.socket0:key=value_y>`

**Comment by grondo** [comment]
> Another idea would be to disambiguate with hierarchical resource specification:

This is what we had proposed from the early days, and is much better from a UX perspective, IMO.

We may want to think about using something other than `.` as resource separator (e.g. '/' was used in RDL) since `.` could be part of a future resource name.

A more familiar interface might be
```
flux resource set-property [resource] PROPERTY[=VALUE]
```
e.g. 

```
flux resource set-property fluke/fluke1/socket0/core0 class-1   #defaults to true
```
or
```
flux resource set-property fluke/fluke1/socket0/core0 class=1
```

**Comment by tpatki** [comment]
@dongahn: Can we also think of use-cases where we need this, aside from specifying a node performance class that is derived from benchmarked tests? For big/small mem, will `hwloc` be able to populate this? I'm asking to ensure our solution is general enough...

**Comment by tpatki** [comment]
@dongahn: Another dumb question. Currently, the node properties are defined as a string map, which we cannot use with the scoring API which would compare against numeric values. Do you have a good solution on where to dump the `perf_class` value for each node so we can use it in a comparative form?

**Comment by dongahn** [comment]
> We may want to think about using something other than . as resource separator (e.g. '/' was used in RDL) since . could be part of a future resource name.

Yeah `/` would be better. In fact, I think `resource` index each resource vertex with its hierarchical path (per each subsystem -- as the path will be different depending on what system you are talking about). When this is passed to `resource`, I can find that resource w/ `O(1)` using this index.

**Comment by dongahn** [comment]
One issue I see with the hierarchical specification is when we run multiple brokers on a node -- even hierarchical spec will not uniquely identify a resource. We need to add "signature" support within `resource` for multi-broker case. This can be done easily but I thought I should mention this.

**Comment by dongahn** [comment]
> flux resource set-property [resource] PROPERTY[=VALUE]

Love it!

**Comment by dongahn** [comment]
> @dongahn: Can we also think of use-cases where we need this, aside from specifying a node performance class that is derived from benchmarked tests? For big/small mem, will hwloc be able to populate this? I'm asking to ensure our solution is general enough...

There will be lots of use cases. Any special feature that we want to annotate a resource with (beyond the base schema specified in [RFC 4](https://github.com/flux-framework/rfc/blob/master/spec_4.adoc#resource-pool-data-model) can use this interface.

**Comment by dongahn** [comment]
> Another (potentially dumb) question. Currently, the node properties are defined as a string map, which we cannot use with the scoring API which would compare against numeric values. Do you have a good solution on where to dump the perf_class value for each node so we can use it in a comparative form?

Can we store the performance class in a string and then later somehow cast it to a numeric? 

Or now that I think about this, in your match policy pluggin, you will essentially write your own "comparator" function so it doesn't matter what type you store this property info with?

**Comment by tpatki** [comment]
> Can we store the performance class in a string and then later somehow cast it to a numeric?
> 
> Or now that I think about this, in your match policy pluggin, you will essentially write your own "comparator" function so it doesn't matter what type you store this property info with?

Yes, that's do-able, wanted to know if there was a better thought out there.

**Comment by tpatki** [comment]
> > flux resource set-property [resource] PROPERTY[=VALUE]
> 
> Love it!

Yes, this looks good. What would be a good starting point to start adding this, and what format should we consider, I'm a bit unclear about your and @grondo's  hierarchical resource comment (as in node-->socket-->core).

**Comment by dongahn** [comment]
> Yes, this looks good. What would be a good starting point to start adding this, and what format should we consider,

I would first see if you can add this into `resource-query` cli for debugging and testing.I would add the suggseted subcommand (`set-property`) into resource-query (like [here](https://github.com/flux-framework/flux-sched/blob/master/resource/utilities/command.hpp#L80) and work out the biz logic into the cli first. This will allow you to do:

```console
resource-query> set-property fluke/fluke1 class=1
```
And this should come in handy for testing etc. Once that's demonstrated, I would add this subcommand to [this](https://github.com/flux-framework/flux-sched/blob/master/t/scripts/flux-resource) so that you can also interface with `resource-match` module via

```console
flux resource set-property [resource] PROPERTY[=VALUE]
```

You will also need to replicate the cli biz logic into the `resource-match` module in the form of a callback, similar to [here](https://github.com/flux-framework/flux-sched/blob/master/resource/modules/resource_match.cpp#L613)

**Comment by dongahn** [comment]
> I'm a bit unclear about your and @grondo's hierarchical resource comment (as in node-->socket-->core).

Here would be an example @tpatki. Say, you want to set a property for fluke1 node's socket 0. You can't specify `set-property socket0 class=1` because there are just too many socket0s. So the idea would be to fully qualify this resource to disambiguate like `set-property fluke/fluke1/socket0 class=1`. This still doesn't solve when we have multiple brokers per node, but this is a good starting point. We will ultimately add signature support so that multi-broker cases can also be supported.

**Comment by tpatki** [comment]
@dongahn: thanks! Both those pointers are helpful, I'll start on putting this together.

**Comment by tpatki** [comment]
@dongahn @grondo 

Sorry about the delay on this, I migrated my initial work on this from the[ old standalone resource-query fork](https://npm.pkg.github.com/tpatki/resource-query) I had to flux-sched (and had to set it up in docker + eclipse to be able to build entirely), and have had to look through some differences between the two versions that I hadn't thought of earlier which are making this a little complicated that I initially thought. Or maybe I'm missing something really simple.

I have two questions here: 

1) In my previous version, I was setting  `property=value` part in the `emit_vertex` in `gen.cpp`, where it got added to the graph based on the resource type. This worked well because we had the `property=value` information stored before hand -- it was provided through a `node_dist.csv` file that was provided as input to `resource-query`, and I could create a [separate unordered map](https://github.com/tpatki/resource-query/blob/power_var_cab/node_dist.hpp) that kept track of the property and the value (in my case, the performance class of a node and its ID were a part of this input file). This map would be populated in `resource-query.cpp:main()` before the resource graph was populated, allowing us to [lookup the property in `emit_vertex`](https://github.com/tpatki/resource-query/blob/power_var_cab/resource_gen.cpp#L230) and set the class of the node there. In the new version, this will occur before the `init_resource_graph`. 

Assuming a workflow where `set-property` is always called before `match_orelse_allocate`, in our current version, we'll have to maintain a structure somewhere that tracks the `set-property` inputs so they can be queried when get to the point of `emit_vertex`. This was the initial workflow I was thinking of -- but without knowing how many properties will be set at runtime and for how many resources, I'm wondering how this information should be stored, and I'm also wondering if it should be stored at all and if there's a way to add in one property at a time in a location other than `emit_vertex` *after* the graph has been populated? How do I update the vertex after the graph has been populated?


2) What would be the best way to to parse something such as `fluke/fluke1/node0` and match the ID of the input resource (node0). The input will have to follow the GRUG structure and nomenclature, and we'll need a check somewhere to ensure that `set-property` input is sane and throw an error if it doesn't match the GRUG. We'll also need a way to check that the property has been added for all resource IDs. That is, if we have 100 nodes, we need to identify if we got (at least) 100 performance classes, and if not, fail with an error.  What's the best way of doing this?

I think both (1) and (2) are coming down to assuming a workflow of when the `set-property` command can be called, and what order do we assume as the first cut.

**Comment by dongahn** [comment]
>  I'm wondering how this information should be stored, and I'm also wondering if it should be stored at all and if there's a way to add in one property at a time in a location other than emit_vertex after the graph has been populated?

I would insert this into the `properties` field of each corresponding resource vertex. 

- Specified in [RFC4](https://github.com/flux-framework/rfc/blob/master/spec_4.adoc)
- Implemented as `std::map`<std::string, std::string>` in the current [resource pool vertex schema]( https://github.com/flux-framework/flux-sched/blob/master/resource/schema/resource_data.hpp#L52).

Its value template type might need some adjustment but we can discuss. 

> if there's a way to add in one property at a time in a location other than emit_vertex after the graph has been populated? How do I update the vertex after the graph has been populated?

There would be a few ways. A less efficient way would be to traverse the entire graph just to find a matching vertex, which you probably want to avoid. 

A much more efficient way would be to take advantage of index tables.  When we build up the graph, the vertices are indexed in [three different ways](https://github.com/flux-framework/flux-sched/blob/master/resource/schema/resource_graph.hpp#L115): by type, by name, and by path. So in theory you should be able to locate your vertex or vertices using these lookup tables. BTW, this has never been used so if those tables don't work well, don't hesitate let me know. 


> What would be the best way to to parse something such as fluke/fluke1/node0 and match the ID of the input resource (node0). The input will have to follow the GRUG structure and nomenclature, and we'll need a check somewhere to ensure that set-property input is sane and throw an error if it doesn't match the GRUG. 

Again try to utilize the lookup tables. These should be very efficient. Since we have the index-by-path table, your path might just work out of box if you are lucky. And yeah, we need robust error checking and we can't get away with it. 


> We'll also need a way to check that the property has been added for all resource IDs. 

If `insert` succeeded for each resource, this means your property has been successfully added? 

> That is, if we have 100 nodes, we need to identify if we got (at least) 100 performance classes, and if not, fail with an error. What's the best way of doing this?

I guess I don't understand the question.

**Comment by tpatki** [comment]
Yes, I was looking at the properties map in `resource_pool_t`, sorry didn't clarify that sooner (string, string is fine as a first cut). 

> There would be a few ways. A less efficient way would be to traverse the entire graph just to find a matching vertex, which you probably want to avoid.
> 
> A much more efficient way would be to take advantage of index tables. When we build up the graph, the vertices are indexed in three different ways: by type, by name, and by path. So in theory you should be able to locate your vertex or vertices using these lookup tables. BTW, this has never been used so if those tables don't work well, don't hesitate let me know.

Thanks, this is helpful. Let me look into this, I was stuck at the traversal part earlier and wasn't sure if we are adding the property after the graph is populated or before, and if doing it one way is better than the other. 

I was looking at the index tables you suggested, but I am unclear how the `uniq_id` can be matched there. As in, how do we guarantee that a property of node0 got added to node0? The path-based search may work, I hadn't thought of that. Thanks for that insight, let me try that out.

---


> We'll need a check somewhere to ensure that set-property input is sane and throw an error if it doesn't match the GRUG.
> And yeah, we need robust error checking and we can't get away with it.

I suppose the question is how do we even know if the input is sane considering I can add any property I like? As in, the only thing we can check for is that if we have N nodes, we have one property (eg. it's perf class) per node (see the segment below, this elaborates my previous question), but we can't check if the value is sane. The following error is hard to detect, because we don't know the data type of the value and we assume everything is a string (which is needed for a generic interface). 

```
flux resource set-property tiny-cluster/rack0/node0 class=1     /*correct*
flux resource set-property tiny-cluster/rack0/node1 class=2    /*correct*
flux resource set-property tiny-cluster/rack0/node1 class=1    /*correct*
...
flux resource set-property tiny-cluster/rack0/node69 class=3hgd    /*incorrect*/
```

--- 

> If insert succeeded for each resource, this means your property has been successfully added?

So, the way I expect this to work is if we have a GRUG with 100 nodes, the external test script or user script will have to add a 100 properties, individually, as follows: 

```
flux resource set-property tiny-cluster/rack0/node0 class=1
flux resource set-property tiny-cluster/rack0/node1 class=2
flux resource set-property tiny-cluster/rack0/node1 class=1
...
flux resource set-property tiny-cluster/rack0/node99 class=3
```

Now, unless 100 such `set-property` statements are provided by the user, we will not be able to match as we will have an incomplete graph where some vertices have properties and others don't. Imagine the scenario where the user only enters 10 commands for `set-property`, and we have a 100 nodes. Or if they make a typographical mistake and specify `tiny-cluster/rack0/core75` as opposed to `tiny-cluster/rack0/node75` -- there needs to be a mechanism to detect that -- that'll add a core property and not a node property, and will lead to inconsistency. Our matcher will fail (eg, the scoring mechanism will seg fault if one of the nodes doesn't have the "class" property). We will need to somehow set defaults, but because these are runtime parameters we wouldn't even know what the name of the property is and what the defaults should be. 

We also will need to think of a bulk add, similar to #487.

**Comment by dongahn** [comment]
> I suppose the question is how do we even know if the input is sane considering I can add any property I like? As in, the only thing we can check for is that if we have N nodes, we have one property (eg. it's perf class) per node (see the segment below, this elaborates my previous question), but we can't check if the value is sane. The following error is hard to detect, because we don't know the data type of the value and we assume everything is a string (which is needed for a generic interface).


 I don't think you can validate the type at the property set time unless you define a rigorous schema for each and every property which is infeasible. Inwould suggest you detect this at runtime when  your match policy callback makes use of it.

**Comment by dongahn** [comment]
> Now, unless 100 such set-property statements are provided by the user, we will not be able to match as we will have an incomplete graph where some vertices have properties and others don't. Imagine the scenario where the user only enters 10 commands for set-property, and we have a 100 nodes. Or if they make a typographical mistake and specify tiny-cluster/rack0/core75 as opposed to tiny-cluster/rack0/node75 -- there needs to be a mechanism to detect that -- that'll add a core property and not a node property, and will lead to inconsistency. Our matcher will fail (eg, the scoring mechanism will seg fault if one of the nodes doesn't have the "class" property). We will need to somehow set defaults, but because these are runtime parameters we wouldn't even know what the name of the property is and what the defaults should be.

Yes we need to detect this at runtime and handle gracefully. Having a default behavior will go a long way toward improving robustness of your match policy callback. If the key doesn't exist, the callback can assume that a visiting vertex belong to a default performance class. It would be good if we add such default in a sched config later down the road.

**Comment by tpatki** [comment]
Yes, sounds good. By the way, I'm also adding a simple `get-property fluke/fluke1/node0` for testing purposes, we can expand it later and it can be a useful interface to test/update for users as well (eg, if they want to update the class of a node, they can test it before updating by doing a get).

**Comment by dongahn** [comment]
Sounds good.  My suggestion is to post a WIP PR as early as practical so that you can get early feedback on your direction. Thanks.
