### ISSUE TITLE
Add state reconstruction support to resource module

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-sched#470]
This will be one of the work items for the next year. Looking at the scheduler interface, it feels like we can get some good mileage by using a scheduler state reconstruction scheme instead of the traditional checkpoint/restart-based resiliency.

At initialization, the resource match service can walk through each and every currently allocated (or reserved) job and then fetch `R` associated with each job. Then, this service can simply update the resource graph data store using this information. 

We don't currently have ways to update the resource data store in this way. I have to believe it is quite doable. We will need some initial feasibility study though. One thing that isn't immediately clear to me is how easy or difficult we can reconstruct some of the metadata like pruning filter states etc in addition to the resource vertex allocation data. 

The traditional technique would be the checkpoint and restart thereby the scheduler periodically dumps the resource data store state somewhere and restarts when we need it. But given that much of the job state is already kep at the job-manager and kvs, it seems the traditional approach would be an overkill in terms of performance. And perhaps more importantly, this can lead to state inconsistency between the scheduler state and job-manager and kvs state. Of course, with this, we will loose the reservation (for backfilling) information that was made at the last scheduler loop as we won't store this into the kvs job schema. But I have to believe this can be accurate recomputed as far as we can accurately reconstruct the currently allocated jobs state.

BTW, this assumes that job-manager and kvs will be resilient. But this is something we must solve in this timeframe anyway.

**Comment by dongahn** [comment]
This also tells me that `R` here must be *full*. Without `JFG` section (IOW, only with `R_lite`), we won't be able to reconstruct the state. Finally, it feels like we really want to put some thoughts for https://github.com/flux-framework/flux-sched/issues/444 so that we can use this JGF reader work not only for nested scheduling support but also this kind of reconstruction-based resiliency scheme.

**Comment by dongahn** [comment]
@garlick or @grondo: It appears that the hello callback invoked by job-manager is currently only being passed an `R` string per each allocated job. Was there any reason that their jobids are not passed as well? The reason I'm asking is that all of the fail-over cases for the scheduler components (`qmanager` and `resource`) would need the jobid per each existing allocated job to be efficient with their state reconstruction schemes.

**Comment by garlick** [comment]
Part of the design for minimizing complexity in the scheduler was to make it a "resource allocator" that is not job aware.  I think we could attach the jobid trivially, if it's needed.

Note: eventually we will return R fragments, not the original full R, when parts of the job terminate before others.   For now it's the full allocated R.

**Comment by dongahn** [comment]
> Part of the design for minimizing complexity in the scheduler was to make it a "resource allocator" that is not job aware. I think we could attach the jobid trivially, if it's needed.

Good to hear the jobid can be attached easily.

Hmmm. Maybe too late in the afternoon, but I don't see how this would minimize complexity for real-world schedulers. An alternative would be for the scheduler maintain its own resource allocation ID space and have a map between flux_jobid_t and the resource allocation id. And/or hashing the R and use that as an identifier. Either case seems only increase overheads with no immediate benefit for the current use case.

> Note: eventually we will return R fragments, not the original full R, when parts of the job terminate before others. For now it's the full allocated R.

Ah, good to know. Still having a jobid as a key to quickly find the resource set seems useful. 

More will be known once we start to do more hands-on for the new proposed scheme. Thanks.

**Comment by garlick** [comment]
> I don't see how this would minimize complexity for real-world schedulers.

Yeah, I was just referencing the concept of scheduler as "resource allocation service" that motivated the alloc/free interface.  Minimizing the surface area of that interface was a goal.  However, that just got us to a first cut, and expanding it to include things that we find useful as we start actually using it is completely appropriate IMHO.

**Comment by grondo** [comment]
> Good to hear the jobid can be attached easily.

IIRC, an array of jobids is actually sent along with the scheduler `hello` request, and it is libschedutil which is abstracting the jobids away and fetching R instead. It would perhaps be a single line change to adapt the interface's `hello_f` callback to add the jobid, if you wanted to do that for now in `flux-sched`. (see `src/common/libschedutil/hello.c:schedutil_hello_job()`)

**Comment by garlick** [comment]
Oh duh, I didn't look at the code when I was commenting.  That is indeed an easy one then.

**Comment by dongahn** [comment]
> IIRC, an array of jobids is actually sent along with the scheduler hello request, and it is libschedutil which is abstracting the jobids away and fetching R instead. It would perhaps be a single line change to adapt the interface's hello_f callback to add the jobid, if you wanted to do that for now in flux-sched. (see src/common/libschedutil/hello.c:schedutil_hello_job())

Great. I was going to look into this soon. So this really is helpful!

**Comment by dongahn** [comment]
```diff
diff --git a/src/common/libschedutil/hello.c b/src/common/libschedutil/hello.c
index 5d38f9b..18ca497 100644
--- a/src/common/libschedutil/hello.c
+++ b/src/common/libschedutil/hello.c
@@ -31,7 +31,7 @@ static int schedutil_hello_job (flux_t *h, flux_jobid_t id,
         return -1;
     if (flux_kvs_lookup_get (f, &s) < 0)
         goto error;
-    if (cb (h, s, arg) < 0)
+    if (cb (h, id, s, arg) < 0)
         goto error;
     flux_future_destroy (f);
     return 0;
diff --git a/src/common/libschedutil/hello.h b/src/common/libschedutil/hello.h
index bfea14b..552efe3 100644
--- a/src/common/libschedutil/hello.h
+++ b/src/common/libschedutil/hello.h
@@ -18,7 +18,7 @@
  * Failure of the callback aborts iteration and causes schedutil_hello()
  * to return -1 with errno passed through.
  */
-typedef int (hello_f)(flux_t *h, const char *R, void *arg);
+typedef int (hello_f)(flux_t *h, flux_jobid_t id, const char *R, void *arg);

 /* Send hello announcement to job-manager.
  * The job-manager responds with a list of jobs that have resources assigned.
```

I guess easy enough. As part of recovering the running queue, I also need to recover the running job's `priority`, `userid` and `t_submit` for completeness. I presume this cab be easily retrieved from the KVS job schema now that I have the jobid?

**Comment by dongahn** [comment]
Also I can look it up myself. But in case someone knows this off the top of your head. 

Is the pending `alloc` requests be replayed when `qmanager` gets loaded again? Or do they somehow come to hello_cb. My guess would be the former...

**Comment by garlick** [comment]
Jobs are resubmitted by the job manager.  The intent was to make it so the
queue wouldn't need to be reconstructed by sched...

**Comment by dongahn** [comment]
Excellent exactly as I expected!

Dong
________________________________

**Comment by dongahn** [comment]
>  As part of recovering the running queue, I also need to recover the running job's priority, userid and t_submit for completeness. I presume this cab be easily retrieved from the KVS job schema now that I have the jobid?

It appears I can get this from the eventlog. But if this info is already being maintained by the 'jobmanager', it seems reasonable to pass them as well into the hello callback to help reconstruct the queue: this was included in the initial alloc request so it seems to make sense to include it again in the hello message to be consistent and less surprising. 

Thoughts?

**Comment by garlick** [comment]
Doable, but I have to ask - can't you simply forget about jobs once they
have allocated resources?   The job manager actively tracks running jobs...

**Comment by dongahn** [comment]
That is really a good question @garlick!

This has some good benefits for this particular two-component scheduler architecture.

Having the running queue within qmanager allows qmanager itself to be able to check the validity of a free request without having to resort to the resource matching service, and perhaps more importantly this then allows qmanager to isolate all of the interaction with the maching service in a single method that all of different queue policy class (fcfs, easy, hybrid and conservative) so far: run_sched_loop.


Dong
________________________________

**Comment by dongahn** [comment]
Gave some more thoughts. I thought about this in terms of three basic failure cases. I believe the recovery protocol should be pretty straightfoward if we can assume `job-manager` be resilient. 

#### A. `qmanager` alone fails:
1. Upon restart, `qmanager` issues an "erase" RPC for the `resource` match service, which makes the state of `resource` pristine: a new RPC will be needed within `resource`
2. Then, within each hello callback invocation, `qmanager` reconstructs both its running job queue and also call an `reconstruct` RPC to  `resource`: a RPC will be needed with `resource`

#### B. `resource` alone fails:
In this case, we will not going to get assistance from `job-manager` directly, I can think of two different approaches.
1. Upon restart,  `resource` kills and restarts `qmanager` along with it such that the recovery sequence A can be repeated.
2. Or build a logic directly into `qmanager` which enables the newly restarted `resource` to reconstruct its service: a new procedure will be needed within `qmanager`

It feels like B.2 is a bit better though with a bit more effort. Less overhead. Less prone to various potential synchronization errors

#### C. both fail
In this case, we want to start `resource` first and then go back to A protocol. 


#### Other cases
There will be cases where `qmanager` and `resource` fail in a staggered way and/or a failure occurs during recovery, on which above basic recovery may not work. We can deem these as a panic mode. So we begin our recovery from a well known state (C recovery above) with a known number of trials.

**Comment by garlick** [comment]
Don't forget about administrative (on purpose) unloading and reloading of scheduler module(s) on a live system to fix a bug, change a static parameter, or even change the scheduling algorithm.  It's not failure per se but it's a more controlled "soft restart" situation that requires state recovery and may be easier to reason about up front than other random failures.

**Comment by dongahn** [comment]
> Don't forget about administrative (on purpose) unloading and reloading of scheduler module(s) on a live system to fix a bug, change a static parameter, or even change the scheduling algorithm. It's not failure per se but it's a more controlled "soft restart" situation that requires state recovery and may be easier to reason about up front than other random failures.

Yes, that's exactly the initial test case / use case I'm using! Thank you for pointing this out.

**Comment by dongahn** [comment]
We discussed at our coffee hour. We will focus on the use case where users manually reload the scheduler modules. We will assume that the users will reload `resource` before `qmanager`:

```console
% flux module load resource ...
% flux module load qmanager ...
```

Because `flux module load` will return after the loading module starts its reactor, `qmanager` will be able to use the newly loaded `resource` service reliably to reconstruct the resource state within the hello callback.

We will not try to pair the scheduler modules in a way that these reloads can be done in one command. We don't have a lot of primitives that we can use to pair them effectively yet.

Also I will make the scheduler resiliency optional. It requires each job's RV1 has the `jgf` key, which can have a significant performance implication.Then, during our optimization phase, we will look at how to condense the `jgf` portion of RV1 to the extent that this can be on by default.

**Comment by dongahn** [comment]
I did some scoping:

-	`resource-query`: add `update` operation as in `resource-query> update <jobid> <starttime> <endtime> <jgf_filename>` for testing & debugging;
-	resource match module: add `update_request_cb`;
-	`flux-resource`: add `flux resource update <jobid> <starttime> <endtime> <jgf_filename>` for testing & debugging;
-	add `update()` method into the `resource_reader_jgf` class: make sure we make this operation transactional;
    i. read JGF node one by one, find a matching resource graph vertex using `by_path` metadata, and find potential errors as much as possible. This will result in a temporary map whose key is graph's vtx_t and the value is fetched JGF data; 
    ii. If no error found, we update the resource graph by iterating through this vector in one swoop; otherwise abandon this temporary map.
-  add `update()` method into `resource_graph_db_t` class as a thin wrapper around the reader's `update()` method;
-	`qmanager`: integrate this into `qmanager`'s `jobmanager_hello_cb` callback for state reconstruction. In this case, JGF will be fetched from `R` being passed through `schedutil`. If no `scheduling` key is found from `R` (since this is optional), report "unsupported"

**Comment by dongahn** [comment]
To better map this feature into our stated plan, I am splitting this up into two.

1. Will use this issue to track "integrate state reconstruction into resource match service.
2. Will create a new ticket to track "add update method into the JGF reader"

**Comment by dongahn** [comment]
> add update() method into the resource_reader_jgf class: make sure we make this operation transactional;

I realized this doesn't have to be transactional. The only use case for `update` (at least initially) will be to reconstruct the allocation state from `R`s fetched from `job-manager` during module load time. As far as `update` fails with a descriptive `errno` and error message, this should be okay: The intermediate state left behind by a update error will just lead to module load failure.
