### ISSUE TITLE
Need a high-level, simple resource interface within resource (module)

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-sched#471]
Two use cases:

- As I'm looking at the queue manager layer (a new service that will interact with job manager), I found a need to call either `match.allocate` rpc (to build a service module) or match_allocate function call (to build a testing utility). 

- This will help @cmisale interface our resource infrastructure with Kubernetes and Go.

**Comment by cmisale** [comment]
I saw that you restructured the code quite recently. The code I used as reference for the Go wrapper is older than those changes. 
I see it is basically the same, the newer version has the code just restructured in functions.
I can confirm that such high-level interface will help also in my case.

Talking specifically about my instance, I made that kind of restructuring by myself time ago, to allow a rpc kind of service.
In my code, I have a `ResQWrapper` class where I have the initialization logic (i.e., create the context, set the match subsystem and policy, grug file..) as well as the match method, which prepares the command using method's argument, and then call `cmd_match(ctx, tokens)` function in `command.hpp` file.
I will be available to help and/or provide feedback.

**Comment by dongahn** [comment]
Thanks @cmisale. 

> I see it is basically the same, the newer version has the code just restructured in functions.

Sorry about this. But this project is under active development and this kind of implementation and internal API refactoring is unavoidable. 

One benefit fo introducing a high level interface is to make it stable so that users like you (and me) don't have to change our code much.

**Comment by dongahn** [comment]
@grondo: A question. It would be best for me to minimize `resource`'s flux-core dependency (other than the module itself). One thing that I noticed is that the new execution system introduces a new jobid type `flux_jobid_t`. How does this type work if being casted to `int64_t`? As you can guess, I am wondering if I can still use a non-flux-specific`int64_t` type as the internal jobid type within `resource` and somehow convert`flux_jobid_t` into it.  

If this is not feasible, I will think about other ways.

**Comment by grondo** [comment]
>  I noticed is that the new execution system introduces a new jobid type flux_jobid_t. How does this type work if being casted to int64_t?

`flux_jobid_t` is just:
```C
typedef uint64_t flux_jobid_t;
```

int64_t should work I guess if the code doesn't assume values > 0 and is just using the jobid as a unique identifier. However, it might be better to switch to `uint64_t`.

**Comment by dongahn** [comment]
@grondo: Ok this should be good then. If you going to change the type for `flux_jobid_t` with a user defined type later down the road, I need to know about it. I used `int64_t` because that made the code look a bit easy to handle error cases (returning -1) and the signed portion should still be good enough to hold massive large number of jobs. For conversion, I will do some sanity check to make sure `flux_jobid_t` won't be larger than the max integer `int64_t` can represent.

**Comment by grondo** [comment]
> and the signed portion should still be good enough to hold massive large number of jobs

Keep in mind that `flux_jobid_t` is representing a flux unique identifier ([FLUID](https://github.com/flux-framework/rfc/blob/master/spec_19.adoc)), not a monotonically increasing integer.

Doing the sanity check is wise, though we could also probably calculate how long an instance would be running before a FLUID overflowed `int64_t` max positive int given the definition.

**Comment by dongahn** [comment]
> Keep in mind that flux_jobid_t is representing a flux unique identifier (FLUID), not a monotonically increasing integer.

Yes. I believe this should be okay though I will surely check. 

> Doing the sanity check is wise, though we could also probably calculate how long an instance would be running before a FLUID overflowed int64_t max positive int given the definition.

Yup. This was my rational. I think it was multiple decades even if you increment it at every cycle.

**Comment by dongahn** [comment]
Decomposing the issue into two. This issue ticket is for
- Defining the high level API and
- Providing an API set that implements this high level API against the resource-match modules

A new ticket for
- Providing an API set that implements the same high level API for CLI use

**Comment by dongahn** [comment]
PR #481 resolved this.
