### ISSUE TITLE
The absence of duration in flux-jobspec produced JSONs crashes libjobspec

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-sched#477]
Not sure if this is a flux-core issue or flux-sched issue so I'm starting this at the core first.

```console
ahn1@8a06403418e4:/usr/src/scratch$ flux jobspec srun -n1 hostname | jq > test.json
```

```json
{
  "tasks": [
    {
      "slot": "task",
      "count": {
        "per_slot": 1
      },
      "command": [
        "hostname"
      ],
      "attributes": {}
    }
  ],
  "attributes": {
    "system": {}
  },
  "version": 1,
  "resources": [
    {
      "count": 1,
      "with": [
        {
          "count": 1,
          "type": "core"
        }
      ],
      "type": "slot",
      "label": "task"
    }
  ]
}
```

```console
ahn1@8a06403418e4:/usr/src/scratch$ ../resource/utilities/resource-query -G ../t/data/resource/grugs/tiny.graphml
INFO: Loading a matcher: CA
resource-query>
resource-query> match allocate ./test.json
Segmentation fault
```

I will try to diagnose the issue. But I think we would need testing coverage for this.

**Comment by SteVwonder** [comment]
> OK. Turns out this is not a huge issue. Looks to me: it is just that libjobspec (or resource) requires the duration field. W/o this, the utility led to SIGSEGV.

Nice catch!

> Ultimately, flux-sched will need a config file that allows resource to fill default values into the jobspec fields that are not specified. I will move this ticket to flux-sched.

I wonder if the scheduler is the right place for this or not.  By the time that the scheduler sees the jobspec, it has already been signed by the user and cannot be modified.  Long term, I wonder if this is something that should be handled by front-end tools like `flux-jobspec` and `flux-submit`.  One benefit of the latter being that the ultimate duration used for the job will be documented in the jobspec stored in the KVS.

> I will try to diagnose the issue. But I think we would need testing coverage for this.

Agreed.  The strawman jobspec v1 in https://github.com/flux-framework/rfc/issues/149 requires that the `duration` key exists.  So at least for the period of time that we only support jobspec V1, the `flux-jobspec` command should be modified to always include the `duration` key and the job validator json-schema needs to be updated to require `duration` for the jobspec to pass validation.

**Comment by dongahn** [comment]
> I wonder if the scheduler is the right place for this or not. By the time that the scheduler sees the jobspec, it has already been signed by the user and cannot be modified. Long term, I wonder if this is something that should be handled by front-end tools like flux-jobspec and flux-submit. One benefit of the latter being that the ultimate duration used for the job will be documented in the jobspec stored in the KVS.

 I think the bottom line is we need a config mechanism that a site or user can use to specify the scheduler's default behavior.  I am unsure if attributes where the `duration` field belong there or not. I would like a general strategy of

- making the emitted jobspec as full as possible
- making the scheduler configuration file to fill the rest of the information to disambiguate the scheduler's default behavior. (e.g., [Resource exclusivity policy is another](https://github.com/flux-framework/rfc/issues/101#issuecomment-329020512) )

**Comment by dongahn** [comment]
PR #481 resolved this.
