### ISSUE TITLE
libjobspec: Add full duration support that complies with the RFC23 format

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-sched#484]
https://github.com/flux-framework/rfc/blob/master/spec_23.adoc

**Comment by garlick** [comment]
If I'm not mistaken, jobspec `attributes.system.duration` is specified as a floating point seconds, not FSD.  FSD was intended to normalize user specification of durations.  (apologies if I'm not understanding the goal of this issue).

**Comment by dongahn** [comment]
> If I'm not mistaken, jobspec attributes.system.duration is specified as a floating point seconds, not FSD. FSD was intended to normalize user specification of durations. (apologies if I'm not understanding the goal of this issue).

Ah. I think you are, right. :-) Then, I already have it. One less task to do.
