### ISSUE TITLE
Branch/Tag creation request

### ISSUE THREAD

**Issue by cmisale** [flux-framework/flux-sched#497]
Hello,
would it be possible to tag or create a branch with the current version of the code?
I would like to hard-code a version in my Dockerfile for kube-flux project, so that if I do a clean build I can avoid getting possible errors.

Thanks

**Comment by dongahn** [comment]
We don't create branch in the main repo so it will have to be a tag. How soon do you need this tag? I was thinking to tag a next release when we will complete our 7/31 milestones. Do you think you can wait for this? Or do you need it more or less now?

**Comment by cmisale** [comment]
Yes!
End of the month is perfect. So I'll lock with that tag.
Thanks a lot!

------------
Claudia Misale, PhD
Research Staff Member
Cognitive and Cloud Solutions
Data Centric Systems
IBM T. J. Watson Research Center

E-mail: c.misale@ibm.com
Phone: +1 (914) 945-1693
