### ISSUE TITLE
Default hwloc-whitelist for our next near-term target?

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-sched#498]
I think this is a good time to add `hwloc-whitelist=` into `resource`'s `rc1` script so that our graph scheduler can build and operate on a significantly trimmed  graph for scheduling (thus fast). I have two options and I am hoping to get feedback as to the best default given our next production target.

#### 2. flux module load -r 0 resource hwloc-whitelist=node,core,gpu

The advantage of option 1 is that it will provide a better topology for scheduling as it includes socket. But the downside is, your node will be represented as `node[1]->socket[2]->core[8]` and so if your jobspec is

```json
  "resources": [
    {
      "count": 1,
      "with": [
        {
          "count": 16,
          "type": "core"
        }
      ],
      "type": "slot",
      "label": "task"
    }
  ]
```

The scheduler will deem this to be unsatisfiable. From the graph matching point of view, this jobspec will be interpreted as prefix-omitted *"->core[16]"* and clearly there is no match. 

By contract, option 2 will represent each node as `node[1]->core[16]` and this job spec will match just fine (at the expense of lesser topological info). 

My current thinking is to go with option 2 as the default hwloc-whitelist unless there are other compelling reasons not to do that. 

Are we even going to support `socket` in our near-term target? 

Thoughts?

**Comment by SteVwonder** [comment]
> My current thinking is to go with option 2 as the default hwloc-whitelist unless there are other compelling reasons not to do that.

> Are we even going to support socket in our near-term target?

I agree with your plan.  At the top-level, we will be doing node-exclusive allocations anyway, so I don't think that specifying sockets at the top-level scheduler helps a ton (maybe it helps when the user has multiple tasks in a single jobspec, but v1 doesn't support that either).  So for now, I think we allocate gpus/cores/nodes and then let the advanced users that care about sockets take advantage of mpibind or something similar.

For user-level schedulers, which will be doing core-level scheduling, the socket information may be more important.  I think we wait until Flux is deployed on LC systems and someone has that particular use-case, and then we develop a solution in coordination with them (or if we have extra time at the end of the year, we do it then).

**Comment by dongahn** [comment]
Thanks @SteVwonder!

> At the top-level, we will be doing node-exclusive allocations anyway

Our new scheduler is capable of doing node-exclusive and -nonexclusive at the same time.

At the top level, if we want to configure the system to always enforce node-exclude, we will need to configure this into our future sched configuration file. I think all this requires will be to say `node: exclusive`.


> For user-level schedulers, which will be doing core-level scheduling, the socket information may be more important. I think we wait until Flux is deployed on LC systems and someone has that particular use-case, and then we develop a solution in coordination with them (or if we have extra time at the end of the year, we do it then).
If the nesting scheduler instance builds a graph out of hwloc directly (not out of RV1), they can have their nested scheduler as fine grained as they want. So we will need RV1 bypass option (which IS the current behavior because we don’t have RV1 reader support for fuller nesting scheduling support).

What we won’t have is jobspecs that support this fully at the flux-core level. But my guess is, this shouldn’t prevent users from making use of this capability -- users themselves can carefully create their own jobspecs to take advantage of more fine grained scheduling at a nested instance level.

**Comment by dongahn** [comment]
This also raises an issue. When we have our scheduler configuration file support, we need our scheme support hierarchical scheduling. Schedulers at different levels will require different configurations and we need to make sure our configuration schemes support this well.

**Comment by grondo** [comment]
>  agree with your plan. At the top-level, we will be doing node-exclusive allocations anyway, so I don't think that specifying sockets at the top-level scheduler helps a ton (maybe it helps when the user has multiple tasks in a single jobspec, but v1 doesn't support that either). So for now, I think we allocate gpus/cores/nodes and then let the advanced users that care about sockets take advantage of mpibind or something similar.

We do have some machines in LC that use Slurm's consumable resources plugin to do core-level scheduling. I think we'll at least want a solution for those machines that is aware enough of sockets to avoid placing 2 cores on different sockets, or least give that allocation a very low score.

> So for now, I think we allocate gpus/cores/nodes and then let the advanced users that care about sockets take advantage of mpibind or something similar.


I'm not sure that could work. Even if user had an option with Flux not to constrain a job to the cores the scheduler actually allocated, mpibind for a single job doesn't have any concept of other jobs currently running on the system so how can it make a good decision about where to bind without possibly overlapping resources with these other jobs?

Ideally a scheduler which has a holistic view of the system would be making these decisions about what resources to give each job, and then mpibind and similar plugins take care of distributing resources *within* that job..

**Comment by dongahn** [comment]
> We do have some machines in LC that use Slurm's consumable resources plugin to do core-level scheduling. I think we'll at least want a solution for those machines that is aware enough of sockets to avoid placing 2 cores on different sockets, or least give that allocation a very low score.

Our scheduler has the capability. But jobspec V1 needs to be upgraded to cover this.

> Ideally a scheduler which has a holistic view of the system would be making these decisions about what resources to give each job, and then mpibind and similar plugins take care of distributing resources within that job..

I agree.

**Comment by dongahn** [comment]
PR #504 solves this issue.
