### ISSUE TITLE
ResourceQuery returned value

### ISSUE THREAD

**Issue by cmisale** [flux-framework/flux-sched#510]
I would need to get back an ID of a node from the ResourceQuery tool for Kube-Flux plugin.
When I generate the GRUG file in my application, I create a generic node this way:

```
func (grug Grug) MakeNode(name string) (node *graphml.Node, err error) {
    attributes := make(map[string]interface{})
    attributes["type"] = "node"
    attributes["basename"] = name
    grug.nodes["node"], err = grug.graph.AddNode(attributes, "node")
    return grug.nodes["node"], err
}
```

The name I'm passing there is the IP of a node, but it can be anything that can identify a particular node. 
As you can guess, the IP is actually one that is replicated 29 times because the cluster has 29 nodes, and a number is appended at the end by the runtime.
For instance, having 172.17.1.13 as generic ID, I have an allocation like this:

```
[RQ] Got request to -allocate- on pod spec -/data/flux/yamlexample.yaml-.
      ---------------core158[1:x]
      ---------------memory0[1938030592:x]
      ------------socket0[1:s]
      ---------172.17.1.1213[1:s]
      ------rack0[1:s]
      ---Kubernetes-cluster0[1:s]

```
where the ID is modified, in this case with a 13 added at the end.
I understand that this is made by design, since we specify the specs for one node and this gets replicated as many times as the number of nodes in the system, but in this way I can't have an ID back and the current result is not something I can use.
It would be great to be able to specify an IP, but I imagine that to do that with the current implementation, I should create 29 nodes with multiplier 1.
This solution would actually be ok because this way I can specify the amount of resources available on each and every node at the moment of the creation of the GRUG file, but still I would have some number appended to the ID. I could solve it with a map or something, of course, but it would add extra cycles.

Is there a way to address this aspect that you would recommend? Or there exists an attribute for the GRUG specification that addresses exactly this aspect?

Just to add a bit more context: for now I would use the bind function that kubernetes uses, and it requires an IP of a node. For a finer binding, we will need to implement something more, but I still didn't investigate that aspect.

Another little issue is that the match function is printing out the allocation result and I have a success/error return value back. This is minor problem now, I think I can modify the code myself to have something else back from the match function.

**Comment by dongahn** [comment]
@cmisale: I believe this can be achieved using the set/get property support @tpatki added: https://github.com/flux-framework/flux-sched/pull/490. I will try to test this in my flight to Nashville and leave more details when I arrive there.

**Comment by dongahn** [comment]
@cmisale: Here is an example.

```console
ahn1@6a22300901a8:/usr/src/resource/utilities$ ./resource-query -G ../../t/data/resource/grugs/tiny.graphml -F pretty_simple
INFO: Loading a matcher: CA
resource-query> help set-property
INFO: set-property (p) -- Add a property to a resource: resource-query> set-property resource PROPERTY=VALUE
resource-query> help get-property
INFO: get-property (g) -- Get all properties of a resource: resource-query> get-property resource
resource-query> set-property /tiny0/rack0/node0 IP=172.17.1.12
resource-query> set-property /tiny0/rack0/node1 IP=172.17.1.13
resource-query> get-property /tiny0/rack0/node0
IP=172.17.1.12
resource-query> get-property /tiny0/rack0/node1
IP=172.17.1.13
```

However, if you match,
```console
resource-query> match allocate ../../t/data/resource/jobspecs/basics/test001.yaml
      ---tiny0[1:shared]
      ------rack0[1:shared]
      ---------node1[1:shared]
      ------------socket1[1:exclusive]
      ---------------core35[1:exclusive]
INFO: =============================
INFO: JOBID=1
INFO: RESOURCES=ALLOCATED
INFO: SCHEDULED AT=Now
INFO: =============================
```

Notice that the property will not be emitted. So you will need to use a more sophisticated emit like our JSON Graph Format emitter.

```console
./resource-query -G ../../t/data/resource/grugs/tiny.graphml -F jgf
INFO: Loading a matcher: CA
resource-query>
resource-query> set-property /tiny0/rack0/node0 IP=172.17.1.12
resource-query> set-property /tiny0/rack0/node1 IP=172.17.1.13
resource-query>
resource-query>
resource-query> match allocate ../../t/data/resource/jobspecs/basics/test001.yaml
{"graph":{"nodes":[{"id":"79","metadata":{"type":"core","basename":"core","name":"core35","id":35,"uniq_id":79,"rank":-1,"exclusive":true,"unit":"","size":1}},{"id":"7","metadata":{"type":"socket","basename":"socket","name":"socket1","id":1,"uniq_id":7,"rank":-1,"exclusive":true,"unit":"","size":1}},{"id":"3","metadata":{"type":"node","basename":"node","name":"node1","id":1,"uniq_id":3,"rank":-1,"exclusive":false,"unit":"","size":1, "properties":{"IP":"172.17.1.13"}}},{"id":"1","metadata":{"type":"rack","basename":"rack","name":"rack0","id":0,"uniq_id":1,"rank":-1,"exclusive":false,"unit":"","size":1}},{"id":"0","metadata":{"type":"cluster","basename":"tiny","name":"tiny0","id":0,"uniq_id":0,"rank":-1,"exclusive":false,"unit":"","size":1}}],"edges":[ {"source":"7","target":"79","metadata":{"name":":containment.contains"}},{"source":"3","target":"7","metadata":{"name":":containment.contains"}},{"source":"1","target":"3","metadata":{"name":":containment.contains"}},{"source":"0","target":"1","metadata":{"name":":containment.contains"}}]}}
INFO: =============================
INFO: JOBID=1
INFO: RESOURCES=ALLOCATED
INFO: SCHEDULED AT=Now
INFO: =============================
```

If the emitted resource set is pretty printed by jq, you will see IP is a part of the properties list of the allocated nodes. 

```json
ahn1@6a22300901a8:/usr/src/resource/utilities$ cat jgf.json | jq
{
  "graph": {
    "nodes": [
      {
        "id": "79",
        "metadata": {
          "type": "core",
          "basename": "core",
          "name": "core35",
          "id": 35,
          "uniq_id": 79,
          "rank": -1,
          "exclusive": true,
          "unit": "",
          "size": 1
        }
      },
      {
        "id": "7",
        "metadata": {
          "type": "socket",
          "basename": "socket",
          "name": "socket1",
          "id": 1,
          "uniq_id": 7,
          "rank": -1,
          "exclusive": true,
          "unit": "",
          "size": 1
        }
      },
      {
        "id": "3",
        "metadata": {
          "type": "node",
          "basename": "node",
          "name": "node1",
          "id": 1,
          "uniq_id": 3,
          "rank": -1,
          "exclusive": false,
          "unit": "",
          "size": 1,
          "properties": {
            "IP": "172.17.1.13"
          }
        }
      },
      {
        "id": "1",
        "metadata": {
          "type": "rack",
          "basename": "rack",
          "name": "rack0",
          "id": 0,
          "uniq_id": 1,
          "rank": -1,
          "exclusive": false,
          "unit": "",
          "size": 1
        }
      },
      {
        "id": "0",
        "metadata": {
          "type": "cluster",
          "basename": "tiny",
          "name": "tiny0",
          "id": 0,
          "uniq_id": 0,
          "rank": -1,
          "exclusive": false,
          "unit": "",
          "size": 1
        }
      }
    ],
    "edges": [
      {
        "source": "7",
        "target": "79",
        "metadata": {
          "name": ":containment.contains"
        }
      },
      {
        "source": "3",
        "target": "7",
        "metadata": {
          "name": ":containment.contains"
        }
      },
      {
        "source": "1",
        "target": "3",
        "metadata": {
          "name": ":containment.contains"
        }
      },
      {
        "source": "0",
        "target": "1",
        "metadata": {
          "name": ":containment.contains"
        }
      }
    ]
  }
}
```

BTW, I don't yet have JGF reader so I can't repopulate the graph data store for recursive scheduling. I have a time frame as to when this will be implemented but I don't have access to my plan spreadsheet on my plane. 

In any case, maybe dealing with JGF-based resource set would be easier to handle to transform into K2s' representation as it is structured than the simple text based emitter that you have been using? (-F simple or -F pretty_simple).

**Comment by dongahn** [comment]
Ah... this is a part of our data model (loosely defined in our RFC4.).


Some of them are assigned by our infrastructure during the initialization. But the infrastructure assume some of them are assigned to good values. 

For now, id should be the numeric value such that base name + id should form the symbolic name for the resource. myhost0, myhost10, and socket0, core1 would be examples. They don't have to be unique (e.g. socket0) but for flux used it to emit `R_lite` portion of core, gpu and optionally nodename.

`uniq_id` should be an actual unique id assigned to each vertex. It used to be uuid but we found that added too much overheads. I would assign unique integer id. You will also need this in creating edges portion of JGF. 

`exclusive`: If the resource is exclusive allocated, it should be true. If shares, it should be false. Higher level resources such as cluster and rack would typixally be false and node local resources would be true.

`unit` should be a string indicating the granualiry of the resource pool. If a schedulable memory resource pool vertex is 32GB, the count field can be 32 and the unit GB. (I currently don't use this field in my infrastructure but we will need this soon.)

**Comment by dongahn** [comment]
Leave the rank as -1. This is flux-core specific and you don't use the core part for this part of the project.

**Comment by dongahn** [comment]
You can see how JGF is emitted by specifying `--match-format=[jgf|pretty jgf]` and do matching. There also is a jsonschema validator we use for testing, which is a vanilla validator from JGF.

**Comment by dongahn** [comment]
http://jsongraphformat.info/

https://github.com/flux-framework/flux-sched/blob/master/t/scripts/flux-jsonschemalint

https://github.com/flux-framework/flux-sched/blob/master/t/schemas/json-graph-schema.json

**Comment by dongahn** [comment]
OK. Per our discussion at today's concall, @cmisale will add support for her k2s to be able to emit a resource set in JGF for `resource-query`,  and I will work on the JGF reader to read from it to populate the resource graph data store per Flux's roadmap, starting from the next week. 

As part of this, I will see if I can easily y add "drain" or "exclude" command to exclude a resource from being scheduled, which I will ultimately need anyway. 

"Growing" part of the elasticity will be looked into by Dan Milroy as part of his research.

**Comment by dongahn** [comment]
FYI -- once PR #521 gets in, you can use the JGF reader @cmisale.
