### ISSUE TITLE
flux-tree

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-sched#512]
To explore the performance and scalability of our graph-based scheduler, I needed a front-end command called `flux-tree` which allows for an ease instantiation of a Flux scheduler hierarchy with three distinct controls: match policy, queuing policy and hierarchal policies (i.e., the shape of the hierarchy). 

`flux-tree` automatically starts a tree of flux instances as specified in the hierarchal policy (e.g., `--topology=4x4x4`) and also sets the specified match and queuing policies for `resource` and `qmanager` modules per each level in this hierarchy. 

To avoid a file system bottleneck, each nested Flux instance will write the performance data into the guest namespace of the parent such as way that these data will be recursively merged up the tree and the overall performance data is tabulated and printed by the root instance. 

This issue is created so that I will create a PR for this command with test cases.

**Comment by SteVwonder** [comment]
FWIW: In addition to propagating performance data up the tree, it might be useful to also propagate stderr and merged exit-codes of jobs. Something that I found useful in my studies/experiments was the saving of stderr from children.  In particular, I found that most of my problems happened at the leaves (where the jobs were actually running), but my terminal was only showing output from the top instance.

**Comment by dongahn** [comment]
Good suggestion!

**Comment by dongahn** [comment]
Related discussions: #566

**Comment by dongahn** [comment]
> FWIW: In addition to propagating performance data up the tree, it might be useful to also propagate stderr and merged exit-codes of jobs. Something that I found useful in my studies/experiments was the saving of stderr from children. In particular, I found that most of my problems happened at the leaves (where the jobs were actually running), but my terminal was only showing output from the top instance.

Since we do `eval ${jobscript}`, we can collect `$?` for each those eval and push that to the parent's KVS guest namespace in the same way we roll up the performance data.
