### ISSUE TITLE
Variation-aware scheduling

### ISSUE THREAD

**Issue by tpatki** [flux-framework/flux-sched#514]
First cut of the production version will focus on a small graph with a representative job queue with 15-20 jobs. It will leverage the recently developed `set-property` interface in `resource-query` for initial testing. 

Node-level scheduling will be assumed, and we will use ~3 performance classes for distributing nodes by their performance efficiency. We will also assume that users specify the execution time of their job based on the worst-case scenario (i.e., slowest node) and as a result we will not modify a job's runtime. In this version, we will place application ranks on similar-performing nodes and compare against the lowest-first or highest-first default policies. This will minimize rank-to-rank variation within the application.

One question is about potentially missing property values due to user entry error. Prior to scoring and matching, we will have to add a method to check that the associated property (in our case performance class) is available for each node and is in the expected range (the latter is harder to determine).  Not sure if we should do this for a first cut (comments, @dongahn)?

**Comment by dongahn** [comment]
Thanks Tapasya:

> Node-level scheduling will be assumed

The graph-based scheduler doesn't make a distinct between node exclusive vs. non-node executive scheduling. It just schedule based on the resource specification in a jobspec. Does this break your assumption?

>  Prior to scoring and matching, we will have to add a method to check that the associated property (in our case performance class) is available for each node and is in the expected range (the latter is harder to determine).

I think it would be a reasonable assumption to treat those unannotated vertex as the lowest performing resource?

**Comment by tpatki** [comment]
> Node-level scheduling will be assumed.
    The graph-based scheduler doesn't make a distinct between node exclusive vs. non-node executive scheduling. It just schedule based on the resource specification in a jobspec. Does this break your assumption?

I believe this will apply to testing, and the code will be general enough to handle any sort of variation. It is the input properties we provide externally that'll make a difference.
The properties (eg node perf_class) is important for physical mapping--  the real-world data we collect (be it based on manufacturing variation or for aging) will either be node-level or socket-level. For power, this assumption is important as we're looking at underlying power domains (i.e. individual subparts of chips where power caps can be placed). Assuming node-level granularity for the testing part because that's the data we have. 

> I think it would be a reasonable assumption to treat those unannotated vertex as the lowest performing resource?

In general, we cannot make any assumptions about the "range" of the data. That will be for the user to specify/interpret. As in, how would we assign the "worst performing value"? A user could provide say `set-property perf_class=253`, `set-property perf_class=5` and `set-property perf_class=1` as inputs. For missing perf_class value for a node, do we assign 253 or 1? We have no idea which is the worst performing class. 

As a first cut we will assume only numeric values for performance class and assume that lowest number is best class (ie, say `perf_class 1` is best, for example) or something similar to allow for scoring. Even then, we don't know the range that the user specified for the property, as in, 
(1) we'll have to look at all nodes for whom a perf_class property is available, pick the highest number in the range, eg 253 in our example, and,
(2) then in a second pass set the property of all the nodes that have missing perf_class to that number.

Similarly, note that user inputs are not limited to numbers. We could have someone specify `set-property perf_class=best`, `set-property perf_class=worst`, `set-property perf_class=medium` as input. Currently, we don't have a scoring mechanism to support this or to translate best, worst and medium into numeric enum assignments.

**Comment by dongahn** [comment]
> I believe this will apply to testing

Good to know. 

> Similarly, note that user inputs are not limited to numbers. We could have someone specify set-property perf_class=best, set-property perf_class=worst, set-property perf_class=medium as input. Currently, we don't have a scoring mechanism to support this or to translate best, worst and medium into numeric enum assignments.

Hmmm... I think we should assume that the variation aware match policy callback understands all the values set in the `perf_class` property fields. If the value is out of range (too high, too low, or string when an integer value is expected) from what the callback expects, the callback should handle them gracefully. 

If we assume this, we can perhaps handle any unannotated vertex or out-of-range vertex as a lowest performing resource?

**Comment by tpatki** [comment]
@dongahn: 
Looking at [resource_match.cpp](https://github.com/flux-framework/flux-sched/blob/master/resource/modules/resource_match.cpp#L182), no code changes are necessary as the `dfu_match_policy_factory` should instantiate the correct matcher. So, I need to mostly add test cases (see eg below) to ensure that the var_aware scheduling is working correctly. Just checking as I wanted to confirm and ensure that I didn't miss anything. 

`flux module load resource grug-conf=${grug} subsystems=containment policy=var_aware`
`flux resource set-property /path/to/nodeID perf_class=val`
`flux resource match allocate <jobspec> ...`

**Comment by dongahn** [comment]
Yes that is correct. I introduced the factory class so that policy developers like you can easily plug theirs in. Don't forget to add a name for your policy to enum etc though. Maybe `variation` as opposed to `var_aware`? We named locality aware locality similarly...

**Comment by tpatki** [comment]
@dongahn: yes, I already updated the enum/string matching, etc (see the PR), I will change the name and add more tests and update the PR sometime today.

**Comment by tpatki** [comment]
@dongahn:
I found a bug while tracing through `resource_match.cpp`. It seems like no matter which policy you select through `flux module load resource grug-conf=${grug} subsystems=containment policy=variation`, only the `high` policy gets implemented. 

This is because the ordering seems incorrect in [`init_module`](https://github.com/flux-framework/flux-sched/blob/master/resource/modules/resource_match.cpp#L268). The function `process_args ()`, which updates the `args.match_policy` to the one specified from command line input, is called after `getctx`. The matcher is [created in `getctx` based on the default value of `args.match_policy`](https://github.com/flux-framework/flux-sched/blob/master/resource/modules/resource_match.cpp#L190), which is `high`, and is never updated after that to the one specified by the user. 

I will attach a reproducer test case for this shortly with the `low` or `locality` policy here. 

Let me know if I missed something...

**Comment by dongahn** [comment]
Ah. Good finding. I don't think I will need a reproducer. This is a straight-out bug. This was probably introduced while refactoring the initialization. I think this can be fixed by delaying the match policy initialization in the same way the graph objects are initialized. 

https://github.com/flux-framework/flux-sched/blob/master/resource/modules/resource_match.cpp#L478

https://github.com/flux-framework/flux-sched/blob/master/resource/modules/resource_match.cpp#L190

I can fix this unless you can beat me to it.

**Comment by tpatki** [comment]
Thanks for the prompt reply after hours, @dongahn! Appreciate it :) 

I was on my last set of tests with `flux resource` (`resource-query` is done) when I found this, so yes, I can include the fix to this in my PR, which I should be able to submit in 1-2h.

Just to confirm, setting `ctx->matcher = NULL` in `getctx` [here](https://github.com/flux-framework/flux-sched/blob/master/resource/modules/resource_match.cpp#L190), and then setting it correctly in `init_resource_graph` [here](https://github.com/flux-framework/flux-sched/blob/master/resource/modules/resource_match.cpp#L478), should fix the issue, right?

**Comment by dongahn** [comment]
Yes, I believe so. Thank you @tpatki. Someone other than me extending code for this infrastructure is extremely useful to discover bugs like this!

**Comment by tpatki** [comment]
Of course, @dongahn!

**Comment by tpatki** [comment]
Just FYI, @dongahn, the variation-aware scheduling PR is ready for your review, and I addressed this bug in it as well.

**Comment by dongahn** [comment]
PR #517 has been merged.
