### ISSUE TITLE
resource: fast graph indexing in gen.cpp needs additional testing

### ISSUE THREAD

**Issue by tpatki** [flux-framework/flux-sched#518]
@milroy and I are a bit confused with how fast indexing is taken care of in `gen.cpp`. 

Specifically, the indexers are defined as a map between a string and a vector of vertices in `resource_graph.hpp` [here](https://github.com/flux-framework/flux-sched/blob/c27dc1474467cf05646912fa175d1da22fa0ee15/resource/schema/resource_graph.hpp#L118), eg:

`std::map<std::string, std::vector <vtx_t>> by_type;`
`std::map<std::string, std::vector <vtx_t>> by_path;`

I remember stepping through `gen.cpp` using several test cases when implementing with the `by_path` option for `set-property`, and identifying that the mapping between the path and the vertex was always unique, that is, `/tiny0/rack0/node1` will identify exactly one vertex in a given subsystem. That would mean that we don't need a vector of vertices for the `by_path`, but just a single vertex in the definition above and we should update the code accordingly. 

@milroy is seeing something similar when he's using indexing `by_type`. I thought that for `by_type` and `by_name`, the mapping will not be unique, but he's getting a segfault when he tries to walk through the vector of vertices and sees exactly one vertex in the vector. 

@dongahn: Can you explain to us if there's a test case where (1) the vector of vertices is necessary,  (2) if all three index mappings (`by_path`, `by_name`, and `by_type`) are not always unique? What are we missing?

**Comment by dongahn** [comment]
Thanks @tpatki and @milroy. These indices have not been used until the recent get/set-properties so there would be rough edges. With that caveat:

> I remember stepping through gen.cpp using several test cases when implementing with the by_path option for set-property, and identifying that the mapping between the path and the vertex was always unique, that is, /tiny0/rack0/node1 will identify exactly one vertex in a given subsystem. That would mean that we don't need a vector of vertices for the by_path, but just a single vertex in the definition above and we should update the code accordingly.

Yeah, this is probably right. I cannot think of a case where you will have multiple vertices sharing the same prefix. In fact, changing the code this way would provide an extra constraint check.

 > @milroy is seeing something similar when he's using indexing by_type. I thought that for by_type and by_name, the mapping will not be unique, but he's getting a segfault when he tries to walk through the vector of vertices and sees exactly one vertex in the vector.

We should take a look at this. If I'm not mistaken, It *should* be multiple vertices when the input is right. I'm refactoring this code for JGF writer code so I can take a look and say exactly what the intent was way back when I wrote it. BTW, even if the vector size is 1, this shouldn't lead to a SEGV. 

> @dongahn: Can you explain to us if there's a test case where (1) the vector of vertices is necessary, (2) if all three index mappings (by_path, by_name, and by_type) are not always unique? What are we missing?

Like I said, this was a code that was looking for future use case and as such I don't have test codes. As they will find more use cases, we should firm up the design and harden it with more test cases. 

Again if I'm not mistaken (I will look at the code later), the general case is to have multiple vertices for all but `by_path` indices.

**Comment by tpatki** [comment]
> Again if I'm not mistaken (I will look at the code later), the general case is to have multiple vertices for all but `by_path` indices.

That was my understanding as well from what I remember from our discussions earlier. So, we should modify the `by_path` to not be a vector. I can take care of this sometime soon, there's only 2 places where `by_path` is used and it is in the `set-property` PRs that I've created.

**Comment by dongahn** [comment]
Sounds good to me. 

@tpatki: you can concentrate on the variability PR. I can take care of these issues as part of JGF reader work which will touch this code section heavily.

**Comment by tpatki** [comment]
@dongahn: sounds good, thanks!

**Comment by milroy** [comment]
> BTW, even if the vector size is 1, this shouldn't lead to a SEGV.

@dongahn that's correct.  There was a bug in my code; after fixing it there aren't SEGVs.

**Comment by dongahn** [comment]
`by_path` optimization support has been added by @milroy in PR #536
