### ISSUE TITLE
Change ggv_t to vtx_t for a few hwloc reader code sites

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-sched#519]
`ggv_t` is the data type of a vertex of a graph generation recipe graph whereas `vtx_t` is the data type of a vertex of the actual resource graph.

`vtx_`t is defined at https://github.com/flux-framework/flux-sched/blob/master/resource/schema/resource_graph.hpp#L93

`ggv_t` is defined at https://github.com/flux-framework/flux-sched/blob/781b95eccec1a7cc78f2a0e184dfb041c7deb7d5/resource/generators/spec.hpp#L75

I found a few sites where ggv_t type is used when vtx_t should have been used during a code review and fix them: e.g., https://github.com/flux-framework/flux-sched/blob/master/resource/generators/gen.cpp#L414

No actual harm done though as they both would have been typedef'ed to be `size_t` as they are the index type for std::vector: I used std::vector as the vertex container for both graphs.

**Comment by dongahn** [comment]
PR #520 fixed this.

**Comment by tpatki** [comment]
@dongahn: Looking at your PR, I'm confused about what is a legitimate use of `ggv_t`. Can you elaborate?

**Comment by dongahn** [comment]
`ggv_t` is the typedef of the graph generation graph vertex type and `vtx_t` is that for the resource graph vertex type itself. They are currently resolved to a same integer type. But they can change if the implementation of either graph type change in the future. Hope this makes sense.
