### ISSUE TITLE
Floating point exception

### ISSUE THREAD

**Issue by trws** [flux-framework/flux-sched#52]
There is now a version of capacitor with a flag to select the flux-sched backend on demand.  The first run of that with flux-sched loaded and populated with a 4-node cab RDL produced this result:

```
scogland at cab668 in ~/projects/flux/capacitor (master●)
$ ./flux-capacitor -S flux -n 4 hostname
cl command : ['hostname']
flux-broker: [1440546532.910099] job.info[0] Setting job 3 to reserved
flux-broker: [1440546532.910133] sched.debug[0] new_job_cb invoked: key(lwj.next-id), val(4)
flux-broker: [1440546532.910175] sched.debug[0] jobstate_hdlr registered
flux-broker: [1440546532.910206] sched.debug[0] attempting job 3 state change from null to null
flux-broker: [1440546532.910413] sched.err[0] job_state_cb: key(lwj.3.state), val((null))
flux-broker: [1440546532.910431] sched.debug[0] registered job lwj.3.state CB
flux-broker: [1440546532.911769] sched.debug[0] attempting job 3 state change from null to reserved
lwj.3.state
3 reached reserved
flux-broker: [1440546532.914290] sched.debug[0] attempting job 3 state change from reserved to submitted
flux-broker: [1440546532.914592] sched.debug[0] extract lwj.3.nnodes: 0
lwj.3.state
3 reached submitted
flux-start: 0 (pid 188920) Floating point exception
flux-start: 2 (pid 188922) Killed
flux-start: 3 (pid 188923) Killed
flux-start: 1 (pid 188921) Killed
```

It seems to happen consistently.  To reproduce, build and install flux-core (my cap_support branch is required for python fixes) and flux-sched in the same prefix, start flux with four ranks on one node, then load flux-sched with this RDL:

```lua
uses "Node"

Hierarchy "default" {
    Resource{ "cluster", name = "cab",
    children = { ListOf{ Node,
                  ids = "1-4",
                  args = { name = "cab", sockets = {"0-7", "8-15"} }
                 },
               }
    }
}
```

With sched loaded, run `flux capacitor -n 4 hostname`.  The submit script also seems to be having an issue in this configuration, but it's less fatal.

**Comment by dongahn** [comment]
FPE is such an odd signal for scheduler :-) I see from the output 

```
flux-broker: [1440546532.914592] sched.debug[0] extract lwj.3.nnodes: 0
```

Perhaps divide-by-zero kind is happening. Is there a way you can specify the number of nodes to `flux-capacitor` as well? Does it make a difference?

**Comment by lipari** [comment]
@trws, did you find the urwid module on cab?

**Comment by trws** [comment]
Ah, sorry about that, I thought I had removed that import.  It's for what's meant to be an optional interface module.  I'll do so shortly, though for later I think the best way to get it for now is to use `pip install --local urwid`.  

@dongahn, you can specify the number of nodes, but I didn't try that specific case.  If you want to, you can give the `-N` flag with a number, though it treats each broker rank as a "node" right now for testing purposes.

**Comment by trws** [comment]
The urwid import has been removed, apologies again for that.

**Comment by lipari** [comment]
I have been able to recreate the problem.  I'll look into it now...

**Comment by dongahn** [comment]
Thanks @lipari

**Comment by lipari** [comment]
I see the cause.  Fix forthcoming...

**Comment by trws** [comment]
That was quick, thanks Don!

**Comment by lipari** [comment]
https://github.com/flux-framework/flux-sched/pull/53 fixes this problem, but it looks like there might be more issues to address...

**Comment by trws** [comment]
Interesting. Will this mean that a job requesting 200 tasks but no nodes 
will run them all on one node? I can change the job spec to always 
specify a sane number of nodes if I need to, but then the tool will have 
to hold rather more knowledge about the instance shape than I was hoping 
to need for this version.

**Comment by lipari** [comment]
Assuming a minimum of one node is a low risk fix.  Applying deeper reasoning to decide how to accommodate a request for n tasks and no nodes is not as simple.  The job submission logic would have to not only assume one task per core, but look over all its nodes to factor in the number of cores on each node.  Then there is the question of how many threads are available on each core and whether the user would want their tasks distributed across the threads.  While this logic could be added someday, for the moment, I suggest we keep it simple.

**Comment by trws** [comment]
While I agree it's best to keep things simple, doing it that way is incompatible with the notion of specifying resources for a job in terms of tasks with associated individual resources, and also with the goal of being able to fit an N task job that takes cores on any N cores that happen to be free.  I can, and will, work around this for however long flux-sched is set up this way, but the result is that I'll be doing that logic in capacitor (as its scheduler already does) to get the behavior we need.

**Comment by lipari** [comment]
So, to be clear, you would like to only ask for tasks and have the scheduler find the necessary cores available across however many nodes to launch those tasks.  And, in the absence of any task-per-core or cores-per-task specification, you would expect one task per core.  Does that capture it?

**Comment by trws** [comment]
What I really want is to be able to provide the number of task slots and what the shape of that is.  Given these, the scheduler has the complete specification for the resources required by the job.  As it is now, I'm not explicitly asking for cores, but I can if that makes things work easier.  Maybe just put something like `task-slots = 4, task-slot-shape = core
What came to mind is that, unless I'm missing something, the scheduler only really cares about task slots and the time for the job to complete with a given amount if it handles malleability. I can specify a resource, or aggregate resource, and number of those required for each job, independently of the number of tasks.

Tasks could then be a separate specification/mapping that the shell or other remote exec system uses.  

The resulting specification to the scheduler would then be something like " task-slots = 4, task-slot-shape = `core`", would that be more reasonable?

**Comment by trws** [comment]
Actually, the number of tasks, and their mapping to slots, is orthogonal to that whole thing too come to think of it.  Does the scheduler care how many entities will actually run on the requested resources?

**Comment by lipari** [comment]
The scheduler receives a request for resources and looks to provide those resources at some time.  That request could be derived at submit time as the product of the number of tasks times a resource slot where the slot definition is specified.
That being said, the flux-sched scheduler should support a request for n cores w/o any node count specified and find idle cores across all of its resident nodes.  I will be testing that scenario.

**Comment by lipari** [comment]
@trws , can we close this issue as the reported bug has been fixed?  As to the larger issue of task support, [Issue 69](https://github.com/flux-framework/flux-sched/issues/69) will track that progress.

**Comment by trws** [comment]
Yup. Thanks for triaging this @lipari, I didn't mean to leave it open.
