### ISSUE TITLE
flux-sched rc3 script doesn't shut qmanager down cleanly

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-sched#524]
This is a minor issue with the scheme for overriding sched-simple in the `flux-sched` rc1,rc3 scripts. Actually, `rc1` seems to work fine, in that `qmanager` is cleanly loaded in place of `sched-simple`, however at shutdown the reverse is not true

```
$ exit
exit
2019-10-01T18:19:46.154151Z broker.err[0]: rc3: flux-module: cmb.rmmod[0] sched-simple: No such file or directory
flux-broker: module 'qmanager' was not cleanly shutdown
```

This seems to be reproducible, but someone let me know if it is only in my environment.

See also flux-framework/flux-core#2273.

**Comment by dongahn** [comment]
@grondo: Thank you for reporting this. I can reproduce it in my environment. I think this is a straight out bug in `configure.ac` (copy and paste error):

```diff
diff --git a/configure.ac b/configure.ac
index 77463a1..a58192c 100644
--- a/configure.ac
+++ b/configure.ac
@@ -136,7 +136,7 @@ AC_SUBST(fluxresourcerc3dir)
 AS_VAR_SET(fluxqmanagerrc1dir, $sysconfdir/flux/rc1.d)
 AC_SUBST(fluxqmanagerrc1dir)

-AS_VAR_SET(fluxresourcerc3dir, $sysconfdir/flux/rc3.d)
+AS_VAR_SET(fluxqmanagerrc3dir, $sysconfdir/flux/rc3.d)
 AC_SUBST(fluxqmanagerrc3dir)
```

Once I test this, I will do a quick PR.

**Comment by dongahn** [comment]
PR #525 has been posted.

**Comment by grondo** [comment]
Great!
