### ISSUE TITLE
Multi queue design

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-sched#529]
Creating a tracking issue to reflect what we have in our plan doc.

**Comment by SteVwonder** [comment]
# Requirements

In terms of requirements, I think Chris Morrone captured them well in #286:

> One of the common use cases for partitions is to have a set of nodes that are dedicated to smaller, shorter-lived, interactive jobs, and a second partitions for longer running batch jobs. The former partition is frequently used for interactive development and debugging ("debug" partition), and the latter for real batch computation ("batch" partition).

> One thing to notice is that the real use case is normally to reserve some number of resources for interactive debugging, not really to reserve specific resources.

To add to that, LC typically puts different policy constraints on the two queues.  For example, the `debug` queue may only allow jobs requiring fewer than `X` nodes and `Y` minutes.  The `debug` queue may also limit the number of jobs that a user can have running or queued at a time.

To continue the requirements from #286:

> In slurm, partitions are sometimes referred to as "queues". However, strictly speaking they really are not separate queues. slurm partitions are sets of resource. A job that is assigned a partition is constrained to only be allocated resources that are within the partition's resource set.

> Slurm partitions also have an added wrinkle that they may introduce, or adjust, the rules that effect their jobs. Also, a user may have different rules that apply to them individually from the "associations" table. A user may individually have different rules for every single partition that exists, independent of the default partition rules.

> The resource sets in partitions are not exclusive. A resource may appear in many partitions. It is mainly for this reason that partitions are not truly independent queues, but rather resource constraints applied to a job. All of the jobs from differing partitions still need to be queued, prioritized, and scheduled as a group. It is only in the special case of non-overlapping partitions that partitions begin to approximate true separate queues.

# Ideas

@garlick and I chatted for a bit about this during the coffee time.  We tossed around a few ideas, including:

1. users tagging jobs with "batch" or "debug" (as suggested in #286)
2. the system automatically figuring out the jobs classification based on job metadata/geometry and then tagging or bumping priority appropriately
3. using sibling instances (one batch, one debug)
4. using nested instances (debug runs inside batch)

4 appealed to the two of us the most.  The top-level system instance could be the "batch queue", which would also be the default instance for users running flux commands.  The "debug queue" would be a job within the top-level system instance. It would have it's own scheduler, ingest module, and prioritization module.  We could run whatever configuration makes sense for the "batch queue" (e.g., conservative backfilling with fair-share prioritization and very little job geometry limits at the top-level).  In the "debug queue" instance, we could specialize the instance to whatever makes sense for interactive debug jobs (e.g., load the scheduler with EASY backfilling, FIFO prioritization, and very tight job geometry limits). The job geometry limits (and many of the other "debug queue" policies) would be enforced by the ingest module, either through jsonschema or some other, new validation method.

The main hurdle to this proposed solution is making it easy for users to target the instance they want to run commands in.  We have a way to switch to an instance (`flux-proxy`), but that requires knowing the full URI of the instance. Not too user-friendly. It would be nice to use simple, easy-to-remember names like "debug" to target instances.  One idea for that is FNS (Flux Name Service): a service that would allow instances to register simple names that map to their remote URIs.   Combined with proxy, this could look like `flux proxy fns://debug flux mini run -N2 myapp`.  We could also provide syntactic sugar within the flux command to avoid the need for chaining with proxy.  For example `flux -t debug mini run -N2 myapp` (I chose `-t` arbitrarily, not an actual suggestion).

This proposed configuration (4) also becomes much more powerful once we support grow and shrink.

The downsides to 1 & 2 are that it would most likely fall upon the scheduler to enforce all the various constraints, policies, and oddities of each partition.  This will add considerably complexity to the scheduler.   In contrast, 4 leverage much of the functionality that we already have.  2 also tries to infer user intent, which is not usually wise.

The downside to 3 is that it makes communication and synchronization between the two "queues" much harder.  There is also no longer any central authority for the cluster in this configuration.

**Comment by grondo** [comment]
Could the parent "batch" instance just forward jobs with debug attributes or debug-like parameters to its child "debug" instance?

It is not just submitting jobs that is a problem/drawback for (3) and (4). Users are used to seeing their jobs in all partitions with a single queue listing command. We may want to consider a way for the default  query commands to optionally recursively list children or something.

Furthermore, by running a new instance to handle a partition, the FLUID space for jobids might overlap, and "accidently" attaching/canceling the wrong jobid might be too easy (because you forgot the `flux -t debug` before your `job cancel`.

I think these drawbacks could be overcome, however, I thought they bore bringing up.

> The downsides to 1 & 2 are that it would most likely fall upon the scheduler to enforce all the various constraints, policies, and oddities of each partition. 

My one question here is that if a scheduler can support QoS, is it that far of a jump to support simple partitions with different limits and policies? Honestly asking because I'm not sure of the answer.

Another naive question, would it be wrong to allow a single instance to have two schedulers loaded. That is perhaps a novel approach which might not be too difficult to support with our job-manager design (just allow multiple schedulers to say hello, and allow them to get first dibs on jobs with certain attributes (e.g. "interactive"))

Sorry if I've taken us OT!

**Comment by dongahn** [comment]
@SteVwonder: we already chatted a bit. But it would be good to check if there are real use cases with overlapping partition for both Slurm and LSF.

**Comment by grondo** [comment]
How bank/accounting will work in these different multi-queue scenarios is another point to consider. If a debug queue is a separate instance and thus completely independent, how does it influence the accounting and fair share calculations of its parent/system instance?

We may need a similar story for DATs anyway (maybe a DAT could be treated as a single job for accounting purposes -- not sure how that works now)

**Comment by SteVwonder** [comment]
Thanks @grondo for the feedback.

Based on our offline discussions, I think @garlick, @grondo, and I shifted onto the idea of loading multiple schedulers per instance, each in control of a non-overlapping set of resources.  Users would then manually tag their jobs, and the tag would determine which scheduler the job(s) go to. To make this possible, we will have to evolve the `job-manager`/`sched` protocol to account for "queue tags".

We suggested that the scheduler should be responsible for enforcing the various queue policies (e.g., max nodes per job, max walltime per job, max num jobs per user per queue, max num nodes per user per queue).  Most (all?) of these can be done at ingest time.  We already need to evolve the ingest module to support rejecting unsatisfiable jobs (https://github.com/flux-framework/flux-core/issues/2049).  We could leverage that same technique to reject jobs that violate queue policies/limits.

**Comment by SteVwonder** [comment]
> But it would be good to check if there are real use cases with overlapping partition for both Slurm and LSF.

Feedback from Ryan Day about LC's usage of overlapping partitions:

> We use overlapping partitions/queues on a few of our slurm clusters. On quartz and a few other systems we use overlapping queues to allow us to easily do full system DATs. Under normal usage on quartz, we have a small pdebug partition and a large pbatch partition active, but sometimes someone will want to do a hero run where they use all of the nodes. In those cases, we activate a ‘pall’ partition that has all of the nodes and give that user access to it. The other cases are more like the GPU case. On flash, there is a phmem, for some nodes with more memory than others (presumably your heterogeneous clusters solution would be able to deal with this). On catalyst, there are a number of ‘ditNN’ partitions that overlap with pbatch. I’m not actually sure what they’re for. Probably something to do with the persistent storage on catalyst that could also be captured by treating it as a heterogeneous cluster
 
> We do also use overlapping queues extensively on the LSF systems because LSF doesn’t really have anything that’s analogous to Slurm’s quality of service (qos). So, for example, if we want to give users an exemption from the normal queue limits, we give them access to an ‘exempt’ queue that has the same nodes as pbatch, but no time or maxnode limits. Slurm lets us do that with a qos that overrides the partition limits. In addition to the ‘exempt’ queue there, we have a ‘standby’ queue (standby jobs can be preempted by jobs submitted to the other queues) and an ‘expedite’ queue (jobs in expedite get a big priority boost).

**Comment by dongahn** [comment]
> Based on our offline discussions, I think @garlick, @grondo, and I shifted onto the idea of loading multiple schedulers per instance, each in control of a non-overlapping set of resources. Users would then manually tag their jobs, and the tag would determine which scheduler the job(s) go to. To make this possible, we will have to evolve the job-manager/sched protocol to account for "queue tags".

@SteVwonder: You and I discussed a bit in passing the other day.

 For `flux-sched`,  we probably should be able to tackle this at the `qmanager` level while still keeping one instance of `resource`. 

I am not fully convinced that loading two instances of `qmanager` is the way to go though. Because of how the job queue policy is abstracted in `qmanager`, one may be be able to extend `qmanager` to instantiate and multiple queues each with different queuing policies and name to do this. 

This is one of those one needs to sit down and design a little.

**Comment by dongahn** [comment]
https://github.com/flux-framework/flux-sched/blob/master/qmanager/modules/qmanager.cpp#L266

This is how a queue is instantiated with a "named" queuing policy. One could have multiple of these based on some configuration options...

**Comment by dongahn** [comment]
We also need to think about how resources are partitioned in an non-overlapping manner. 

One approach is to add some "labels" into the property (or other new) fields of resource graph vertex and use that for matching.

**Comment by dongahn** [comment]
As we discussed, I want to see if I can make progress for this. 

Maybe a quick prototyping within `flux-sched` to pin the design is the right way to go. 

This is also relevant to @cmoussa1's work: https://github.com/flux-framework/flux-accounting/issues/7#issuecomment-600893904. It seems having overlapping queues (or labels -- whatever you name it) can simplify what @cmoussa1 has to do. This may lead to minimal or no QoS support, for example.

**Comment by dongahn** [comment]
This has been done. The remaining part is to put queue labels to our graph data store, which will be address as part of RV2.
