### ISSUE TITLE
Technique to catch all uncaught C++ exceptions

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-sched#539]
Tagging @trws.

We currently catch all std exceptions at the mod_main level to prevent an uncaught C++ exception from killing the broker. @trws wants to propose a way to extend this to catch all C++ exception beyond `std::exception.`

This should make our system more robust as there could be undocumented or missed exceptions that could arise from our dependent C++ libraries such as YAML CPP.

**Comment by trws** [comment]
The two constructs I was referring to are `catch(...)` and
`std:current_exception`, the first one will match absolutely anything not
matched by another arm of a catch series, the second will get whatever the
exception is and give it to you in an `exception_ptr` so you can try and do
something with it.  We probably want something along these lines:

```c++
try {
  // stuff
} // more specific catch clauses
 catch(std::exception const &e) {
  // turn into flux error code and return as appropriate
} catch(...) {
  if (flux_some_debug_flag) {
    // rethrow or abort or something to get a debugger here
  }
  // no clue why we're dying, return generic error
}
```

One other thing to note, `mod_main` actually isn't the part I'd be worried
about, that would cause a failure right off at startup, but any of the callbacks
could throw an exception straight out into the reactor, since they get called
directly by C code.  That's part of why I mentioned making a wrapper or
something, something along these lines (kinda like the trampolines in the python
bindings).  We could extend this to carry arbitrary captured data too, but this
would probably work for the existing uses in resource_match, or at least
something like it.

```c++
using cb_type = void (*)(flux_t *h, flux_msg_handler_t *w,
                         flux_msg_t const *msg, void *arg);
struct cb_wrapper {
  std::function<void(flux_t * h, flux_msg_handler_t * w, resource_ctx_t * ctx)> cb;
  resource_ctx_t *ctx;
};
void cb_caller(flux_t *h, flux_msg_handler_t *w, flux_msg_t const *msg,
               void *arg) {
  cb_wrapper *cb = dynamic_cast <cb_wrapper *>(arg);
  try {
    cb->cb(h, w, msg, cb->ctx);
  } catch(...) {
    // stuff with flux_error
  }
}
```

**Comment by dongahn** [comment]
> One other thing to note, mod_main actually isn't the part I'd be worried
about, that would cause a failure right off at startup, but any of the callbacks
could throw an exception straight out into the reactor, since they get called
directly by C code. 

@trws: This is really a good point. So you want the same effect as having try/catch  around each of your raw callback function implementation. 

If I understand your code snippet, this should be a great idea in general for any C++ module. This has a stylistic advantage of not having to include try/catch for each callback (at the expense of a slight performance overhead -- negligible). 

So the callback functions you would directly register with Flux would be those callback wrapper functions like `cb_caller`. And you would pass the pointer of your `cb_wrapper` object into `flux_msg_handler_addvec ()` so that it will be passed down to your callback wrapper functions. 

When your module has multiple request callback functions, you will need to define more `cb` like members for `cb_wrapper` and assign each "real" callback func to each cb member. 

In this particular case, why `dynamic_cast` used here though, when you know the type is `cb_wrapper` already? Wanted to do more runtime checking just in case? 

Maybe this would allow you to do something like this at the expense of a slight performance hit. 

```
if (!cb)
    //flux_error
```

**Comment by dongahn** [comment]
Also thank you for the `catch (...)` suggestion. This should make our modules more exception safe. (for lack of a better word).

**Comment by trws** [comment]
FWIW, “exception safe” is exactly the standard term for handling exception safety, especially writing code in a way you can’t end up with partially constructed objects  :)

As to the rest, we can actually write a templates type, or function, that generates these wrappers so we only have to define it once. The snippet I included actually already does that but it needs a different instance of cb_wrapper for each callback (no new members, just instances). We could make it substantially more flexible but that’s a simple way to get it done.

The dynamic_cast is defensive as you guessed, it’s just in case the function is called wrong to give a better error. In fact it should catch the null case, but that would be reasonable add to get a more specific error. That’s one big advantage to this kind of wrapper generator approach IMO, it lets you add lots of specific handling in one place that you can benefit from in many places, like we do with the python binding generator.

I’ve never actually gone through to make c++ wrappers for some of our c stuff, but for message handler and maybe future the benefits are large enough it might be really worthwhile.

**Comment by dongahn** [comment]
> I’ve never actually gone through to make c++ wrappers for some of our c stuff, but for message handler and maybe future the benefits are large enough it might be really worthwhile.

Ol. Sounds good. Just think about this some and if you think you will tackle that in a reasonably near future I will latch on that instead of creating my own ad hocs.
