### ISSUE TITLE
Please tag the current master

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-sched#544]
@cmisale requested that we tag the current master which has her "JGF update" feature. I'm going to make it the 0.8 release. This has been overdue anyway.

**Comment by dongahn** [comment]
@grondo: it's been awhile and I forget.

```
Once the PR is merged, create and push an annotated tag with the version number
For example: git tag -a v0.11.0 -m "Tag v0.11.0" && git push origin v0.11.0
```

Are we supposed to push the tag directly to the main repo or are we supposed to add the tag into our fork and do some sort of PR to the main repo?

**Comment by grondo** [comment]
You push the tag directly

**Comment by dongahn** [comment]
OK. Done.

**Comment by dongahn** [comment]
Remaining work:

- Submit a PR to spack with the latest version
- Build new RPMs for TOSS
- Update http://flux-framework.org/news/ (This should be updated manually right?)

BTW, it appears http://flux-framework.org/docs/quickstart/ needs an update. If nothing else, this uses `wreckrun`. Maybe @cmoussa1 can work on it?

**Comment by SteVwonder** [comment]
Thanks everyone for getting this done, is this issue good to be closed now that the `0.8.0` release has been tagged?

**Comment by dongahn** [comment]
I has bee tagged but there are three remaining tasks @SteVwonder: https://github.com/flux-framework/flux-sched/issues/544#issuecomment-562605306

**Comment by grondo** [comment]
We probably do not need to create TOSS RPMs for this particular tag...

**Comment by dongahn** [comment]
Just posted https://github.com/flux-framework/flux-framework.github.io/pull/34 to update our webpage.

**Comment by dongahn** [comment]
> We probably do not need to create TOSS RPMs for this particular tag...

Taking this suggestion :-).
