### ISSUE TITLE
README out of sync?

### ISSUE THREAD

**Issue by andre-merzky** [flux-framework/flux-sched#545]
Hi, 

I want to have a closer look at Flux and try to get it running on a local box.  Installation worked smoothly when following the instructions from the README (thanks!), and starting the brokers also yield the expected processes.  But the next step, which would be loading the `flux-sched` module, seems to fail:
```
$ flux module load sched rdl-conf=$HOME/flux-sched/conf/hype.lua plugin=sched.fcfs
flux-module: sched: not found in module search path
```
I  am not familiar enough with LUA to understand what might be involved here, apologies - but I don't see a `conf/` subdir, nor a `sched.fcfs` anywhere in the tree (neither in the source tree nor in the install tree.

Do you happen to have any advise?  The above is on master as of b54ff48 (sched) and 2e299e27 (core).  Running on a Linux 
```
Linux rivendell 4.13.0-25-generic #29-Ubuntu SMP Mon Jan 8 21:14:41 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

Many thanks, Andre.

**Comment by grondo** [comment]
You are correct, the README in flux-sched is not up to date, and is referencing our old prototypes which are no longer supported. If you've already successfully installed flux-core@master and flux-sched@master, then I believe submission of jobs should "just work", though things are in rapid development, so there may be some rough edges.

There are new minimal commands for running and submitting jobs that replace the old interface documented in the README, they include

 * `flux mini submit` instead of `flux submit`
 * `flux mini run` instead of `flux wreckrun`
 * `flux job list` to list jobs

**Comment by andre-merzky** [comment]
Thanks for the quick reply, let me try that!  Do you want a PR for the README, or are things still in flux (ha!) and fixing the doc would be premature?

**Comment by grondo** [comment]
A PR would be awesome if you are already walking through the process!

If you have better things to do, we can fixup the README asap as well (and perhaps either way get a new user's feedback on it.)

**Comment by andre-merzky** [comment]
Cool.  Let me see if I get this to work, then the PR is easy :-)  Cheers!

**Comment by dongahn** [comment]
@andre-merzky: sorry about the out-of-sync readme.

@grondo: I was working on a new README as part of tagging and releasing of the current master. I will see if I can find sometime to finish this up at SC.

**Comment by andre-merzky** [comment]
I got a `hello_world` to work now. - thanks for the feedback!

@dongahn : thanks for the heads-up on the README update, but let me know if you want input.  One additional piece I found missing from the README is that I needed to install the Lua POSIX module - `flux dmesg` said as much though, so it was easy to figure out.

**Comment by dongahn** [comment]
@andre-merzky: Although @cmoussa1 is in the process of updating our workflow examples: https://github.com/flux-framework/flux-workflow-examples, these examples still might be useful for you. 

@cmoussa1: TBA for updating these examples with new interfaces?

**Comment by dongahn** [comment]
> Let me know if you want input.
Sure. When I do a PR, I will tag you so that you can provide your feedback. Having a fresh set of eyes about basic instructions should be useful.

**Comment by dongahn** [comment]
> One additional piece I found missing from the README is that I needed to install the Lua POSIX module - flux dmesg said as much though, so it was easy to figure out.

@grondo: Hmmm I thought we are completely off of Lua... No?

**Comment by cmoussa1** [comment]
@dongahn: 6 out of the 10 examples have been updated with the new interfaces. Once the Python bindings get updated (which are close to being merged) then we'll have most of them updated!

**Comment by andre-merzky** [comment]
@dongahn , @cmoussa1 : Fantastic!  I am actually looking at the Python bindings right now, and those look exactly like what I want to use.  Thus thanks for that example link, specifically `example7` which covers my use case! to the dot :-D

**Comment by dongahn** [comment]
@andre-merzky: you might also want to see https://github.com/LLNL/merlin/blob/340033fbdfefbcaacbdbf1aa3b338d251faed1fe/docs/source/index.rst, which has one model as to how another workflow manager similar to RAPID Pilot leverages Flux.

**Comment by andre-merzky** [comment]
@dongahn : Did that repo appear literally today?  Neat! :-)  Yes, this looks similar to what we try to do, so thanks for the pointer!

BTW: is this (github issues) the right way to ask for support questions (like clarification on documentation or deployment), or is there a different channel I should use?

**Comment by dongahn** [comment]
Yes, you can use the GitHub issue tracker so that when other users come across a similar issue, they can self-resolve their issue too. 

You can also send an email to flux-discuss@lists.llnl.gov  as well.
