### ISSUE TITLE
Need job type in resource_graph_metadata_t

### ISSUE THREAD

**Issue by milroy** [flux-framework/flux-sched#551]
To enable elastic job shrink and expand, `resource_graph_metadata_t` needs a data structure that permits quick lookups of job type keyed by `jobid`.  This will allow resources that are currently running a job of type "elastic" to be allocated by another job.

**Comment by dongahn** [comment]
Sounds good to me.

**Comment by dongahn** [comment]
This probably didn't work out. Please reopen if I'm mistaken.
