### ISSUE TITLE
flux ion front-end command

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-sched#556]
Per today's discussion (https://github.com/flux-framework/flux-core/issues/2608) , we will piggyback @chu11's job listing tool to present basic scheduler information such as estimated start-time and reason for pending etc. 

For other advanced resource information, for example, detail  information on a particular resource (e.g., reservation information of a particular compute node), we will develop a new scheduler frontend called `flux-ion` as we will rebrand our scheduler as `fluxion`.

One thing we have to make sure: flux-ion gracefully fails if another scheduler (e.g., `sched-simple`) is being used.

**Comment by dongahn** [comment]
Now that many of the front-end functionality is (and will be) supported via flux-core's front end. We need to identify a minimum set of fluxion-only functionality needed from this and make progress.

I think it makes sense to refactor `t/scripts/flux-ion-resource.py` for this purpose.

**Comment by SteVwonder** [comment]
In recent call, there was a question from Robin about the ability to dump the contents of the resource graph database along with the status of all the resources within it.  For resources like `node`s, `core`s, `gpu`s, there is the flux-core interface `flux resource list`, but for more "exotic" resources outside of nodes like AI accelerators, burst buffers, filesystems, licenses, etc, how do we want to support the dumping/listing/querying of those?  Should that be a flux ion feature or a flux-core feature?

**Comment by grondo** [comment]
The eventual goal would be to dump this information via Rv2, then have a set of tools that can display Rv2 in various ways. For now, though it might make sense to have a Fluxion only util, if one doesn't exist already...
