### ISSUE TITLE
Add mergify bot to flux-sched

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-sched#559]
Any opposition to adding the mergify bot to this repo?  It is the same one that is used in flux-core to help with PR merging.  Once you set the 'merge-when-passing' label on a PR, mergify automatically attempts to rebase PRs onto master (assuming the PR branch is out-of-date), and if the rebase is conflict-free and passes Travis, mergify updates the PR and merges it.

**Comment by dongahn** [comment]
This sounds good to me.
