### ISSUE TITLE
Eliminate from flux-sched products the dependency on libflux-internal

### ISSUE THREAD

**Issue by lipari** [flux-framework/flux-sched#56]
This is the beginning step toward streamlining flux-sched's build system.  This leaves a dependence on the flux-core library only.

**Comment by SteVwonder** [comment]
What is our plan for shortjson.h?
I know copying the version in flux-core into flux-sched has been discussed.
Did we ever agree on a solution?

**Comment by lipari** [comment]
https://github.com/flux-framework/flux-sched/pull/57 indeed copies shortjson.h into flux-sched/common to make things simple.  Long term, we can ferret out all the places that rely on the shortjson.h defs and replace them with the json-c equivalents, if such a cleansing is desired.

**Comment by SteVwonder** [comment]
I now see the discussions happening in #57 and flux-framework/flux-core#336

**Comment by SteVwonder** [comment]
Ok. Thanks @lipari!

**Comment by lipari** [comment]
While we discussed this a while ago, I thought I would bring it up again as a way to embed the flux-core code base into flux-sched.  This would allow us to build flux-sched using the latest commits to flux-core.  There are three similar git tools to do this:

* https://git-scm.com/book/tr/v2/Git-Tools-Submodules#_git_submodules
* https://git-scm.com/book/tr/v2/Git-Tools-Advanced-Merging#_subtree_merge
* https://github.com/git/git/blob/master/contrib/subtree/git-subtree.txt

Of these three, `git subtree` appears to be favored in various tutorials I have seen.  My understanding is that, once we have flux-core embedded in the flux-sched project, we could add Autotool components to flux-sched and it would recursively build flux-core.  I also believe this allows flux-core to remain an independent project:  flux-sched would depend on flux-core and not vice versa.

**Comment by lipari** [comment]
Copying in the contents of an email thread that discussed a different approach where flux-sched would not contain flux-core and instead pull in flux-core sources...

@garlick said:
On the build farm, the flux-core RPM would be installed into the mock root that is being used to build flux-sched's RPM.

In travis-ci, an RPM would not be used.  flux-core would be "side installed" (make install prefix=my-side-dir) and used by flux-sched the same way that flux-core uses its dependencies.  See src/test/travis-dep-builder.sh.

In both of the above cases, flux-sched would use normal mechanisms like pkg-config to locate flux-core.  It may need some help from environment variables if non-system locations are used, e.g. PKG_CONFIG_PATH, LD_LIBRARY_PATH.

@grondo referenced his work here:
https://github.com/flux-framework/distribution/issues/5#issuecomment-169416474

@lipari gave a cursory listing of the flux-core components flux-sched relies on:
rdl needs
  list in lsd
  optparse in libutil

sched needs
  xzmalloc, log, jsonutil

@garlick replied:
That's a small list that gives me hope we can solve this without major contortions.  Substantially more was pulled in when you proposed [PR #57](https://github.com/flux-framework/flux-sched/pull/57), so are you sure you've got it right above?

(@lipari:  the list was gathered quickly.  There could be sources I missed.)

optparse and list *are* indeed well designed, reusable modules that we might consider exporting from core in a libflux-util.so library or something like that.

As far as I'm concerned, xzmalloc and shortjson are throw-aways that could be duplicated in sched without issue.

Probably we should get rid of jsonutil, as it's just an earlier version of shortjson, though it currently has some unique parts that you may or may not be making use of (such as the base64 json-encoding stuff).

It seems like we should be getting rid of log and move towards a unified set of those functions provided by flux-core, using the flux_log() series of functions as a starting point.  (E.g. add stderr option and allow handle to be NULL).

**Comment by lipari** [comment]
Close via #115 and #121
