### ISSUE TITLE
problems when building against flux-core configured with Python 3.6 when /usr/bin/python != 3.6

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-sched#567]
I'm not able to build flux-sched RPMs against our new flux-core v0.14 RPMs. The flux-core RPMs are now successfully built against the system installation of Python 3.6, though obviously `/usr/bin/python` is still pointing to 2.7.

The first issue is that flux-sched `./configure` doesn't seem to obey `PYTHON_VERSION=3.6` and instead always detects the python version of `/usr/bin/python`. In the buildfarm, this means that even though the Python 3.6 `yaml` and `jsonschema` modules are pulled in as dependencies of `flux-core`, flux-sched does not detect them because it is looking for python 2.7 versions of the modules.

However, the Python dependencies in `flux-sched` are only required for `make check`, so perhaps it is ok to just install the python 2.7 versions of the modules to satisfy configure.

Even outside the buildfarm, however, I'm unable to get `flux-sched`'s `make check` to work when built against a `flux-core` installation that is configured with Python 3.6. For example, I'm getting this error from the `flux-resource` test script:

```
expecting success: 
    flux resource match allocate ${jobspec} &&
    flux resource match allocate ${jobspec} &&
    flux resource match allocate ${jobspec} &&
    flux resource match allocate ${jobspec}

Traceback (most recent call last):
  File "/g/g0/grondo/git/flux-sched.git/t/scripts/flux-resource", line 291, in <module>
    main ()
  File "/g/g0/grondo/git/flux-sched.git/t/scripts/flux-resource", line 272, in main
    args.func (args)
  File "/g/g0/grondo/git/flux-sched.git/t/scripts/flux-resource", line 74, in match_alloc_action
    r = ResourceModuleInterface ()
  File "/g/g0/grondo/git/flux-sched.git/t/scripts/flux-resource", line 27, in __init__
    self.f = flux.Flux ()
  File "/tmp/grondo/flux/lib/flux/python3.6/flux/__init__.py", line 17, in Flux
    import flux.core.handle
  File "/tmp/grondo/flux/lib/flux/python3.6/flux/core/handle.py", line 14, in <module>
    from flux.rpc import RPC
  File "/tmp/grondo/flux/lib/flux/python3.6/flux/rpc.py", line 14, in <module>
    from flux.future import Future
  File "/tmp/grondo/flux/lib/flux/python3.6/flux/future.py", line 13, in <module>
    from flux.util import check_future_error
  File "/tmp/grondo/flux/lib/flux/python3.6/flux/util.py", line 22, in <module>
    from flux.core.inner import ffi, raw
  File "/tmp/grondo/flux/lib/flux/python3.6/flux/core/inner.py", line 11, in <module>
    from _flux._core import ffi, lib
ImportError: dynamic module does not define init function (init_core)
```

I have no idea where to start looking on this one. :confused:

**Comment by grondo** [comment]
BTW, I can reproduce this on a TOSS system by configuring flux-core with python 3.6 and installing to a temporary path, e.g. 
```
PYTHON_VERSION=3.6 ./configure --prefix=/tmp/grondo/flux && make install
```
Then attempt to configure `flux-sched` against this version:
```
$ PYTHON_VERSION=3.6 PKG_CONFIG_PATH=/tmp/grondo/flux/lib/pkgconfig ./configure --prefix=/tmp/grondo/flux
```

Note that configure finds python version 2.7 not 3.6. However, flux-sched still builds, though `make check` will fail as above.

**Comment by grondo** [comment]
This sanity check seems to work fine, so ostensibly the bindings installed by flux-core are sanely working:

```console
$ /tmp/grondo/flux/bin/flux start flux python -c 'import flux; h = flux.Flux(); print (h.rpc("kvs.ping", {}).get())'
{'route': '9abba5d9-cba7-4e67-a084-650db7067e34!7fa4ee1e-c2e8-4144-b014-80881fbf29b3!0!0', 'userid': 6885, 'rolemask': 1}
```

**Comment by grondo** [comment]
Ah, but it fails with the same error as above if I run with the wrong python version
```
$ /tmp/grondo/flux/bin/flux start python -c 'from flux.core.inner import ffi, lib'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/grondo/flux/lib/flux/python3.6/flux/core/inner.py", line 11, in <module>
    from _flux._core import ffi, lib
ImportError: dynamic module does not define init function (init_core)
2020-01-14T19:05:43.041223Z broker.err[0]: Run level 2 Exited with non-zero status (rc=1) 0.0s
```

**Comment by grondo** [comment]
Ah, the problem is that `flux-resource` and `flux-jsonschema` do not have a `.py` suffix, so the `flux` command driver doesn't execute them with the flux configured python, it instead just executes them and they run with `/usr/bin/python` due to the shebang `#!/usr/bin/env python`.

I think renaming these scripts to have a `.py` suffix (and removing the shebang to avoid future confusion) will fix this particular error.

**Comment by dongahn** [comment]
@grondo: good catch! Is that the only issue we have to fix for the RPM?

**Comment by grondo** [comment]
Still looking. However, I think we can build RPMs without this fix since it is only necessary for `make check`.

**Comment by SteVwonder** [comment]
Reopening since the configure still doesn't respect the `PYTHON_VERSION` variable.

**Comment by grondo** [comment]
Oops, sorry. Shouldn't have closed this one in that testsuite commit!
