### ISSUE TITLE
Skip planner update for elastic job type

### ISSUE THREAD

**Issue by milroy** [flux-framework/flux-sched#576]
Resources allocated to elastic jobs should be considered available here: https://github.com/flux-framework/flux-sched/blob/c03c083a7b4afb34fbfe2ed76e69309ed42732c8/resource/traversers/dfu_impl.cpp#L554
which means `planner_avail_resources_during` should return a positive integer.  I think the simple solution is to add a check for vertex job type before this line: https://github.com/flux-framework/flux-sched/blob/c03c083a7b4afb34fbfe2ed76e69309ed42732c8/resource/traversers/dfu_impl_update.cpp#L141
If the job type is elastic, the `planner_add_span` block should be skipped.

This is a sub-issue of #554.

**Comment by milroy** [comment]
@dongahn could skipping over `planner_add_span` cause unexpected behavior?

**Comment by dongahn** [comment]
Seems possible. But it is difficult to say whether this will work with no side effect without seeing some sort of a prototype. 

> @dongahn could skipping over planner_add_span cause unexpected behavior?

This is like not adding a schedule to the visiting resource. So when we visit this resource to schedule it for the next job, the resource state will be the same as there is no job scheduled. 

What happens to the other states? I have no idea without actually making some changes and running things. I certainly didn't design this subsystem with this use case in mind. But at the same time, this may work (potentially with some other changes).

In general, the main question would be to understand what fields of visiting resource (as well as its ancestor vertices) still needs to be updated and what fields must not be updated to add an elastic job. We are adding a whole new 3rd class job (no job scheduled, rigid job scheduled and elastic job scheduled). So, we need to be really clear about what a resource vertex and other metadata allow us to add this new class of job. Or even possible with the current infrastructure? Because this is pretty complex, we need some design exploration here.

I would prototype what you suggested and actually see the behaviors (to start with, what happens to all the test cases we have etc. then, new test cases...) and iterate.

**Comment by milroy** [comment]
>This is like not adding a schedule to the visiting resource. So when we visit this resource to schedule it for the next job, the resource state will be the same as there is no job scheduled.

That is my intention, and I'm hoping it won't break anything else and won't make future design more difficult.

> What happens to the other states? I have no idea without actually making some changes and running things. I certainly didn't design this subsystem with this use case in mind. But at the same time, this may work (potentially with some other changes).

I wanted to get your input to make sure that this idea wouldn't create obvious issues before jumping in.

> I would prototype what you suggested and actually see the behaviors (to start with, what happens to all the test cases we have etc. then, new test cases...) and iterate.

Agreed, and will do.  Thanks for the feedback!

**Comment by dongahn** [comment]
> I wanted to get your input to make sure that this idea wouldn't create obvious issues before jumping in.

Yeah... this is complex enough I can't say definitely whether it will work or now off the bat... Need some testing.

**Comment by milroy** [comment]
> Yeah... this is complex enough I can't say definitely whether it will work or now off the bat... Need some testing.

I'll get to the testing.

Also I should mention that this issue depends on additional metadata described in issue #551.

**Comment by milroy** [comment]
After discussing more details of the implementation with @dongahn today, I tested the proposed change in `flux-sched/resource/traversers/dfu_impl_update.cpp`.  Without elastic jobs all Travis tests passed.  

If I modify `t/data/resource/jobspecs/basics/test001.yaml` by designating the job as elastic:
```attributes: 
  system:
    duration: 3600
    jobtype: "elastic"
```

five Travis tests fail.  This helped me identify another block to skip for elastic jobs: https://github.com/flux-framework/flux-sched/blob/c03c083a7b4afb34fbfe2ed76e69309ed42732c8/resource/traversers/dfu_impl_update.cpp#L368

That block needs to be skipped because if the vertex job type is elastic there won't be an associated planner entry due to `planner_add_span` being skipped at allocation.  After including a check that skips over `planner_rem_span`, only two Travis tests fail:

t3001-resource-basic.t - "Once all sockets are exclusively allocated, no jobs can match"
t3015-resource-basic-jgf.t - JGF: "Once all sockets are exclusively allocated, no jobs match"

Which is to be expected with an elastic job.  In fact I could modify this test to succeed in a similar case.

One remaining question: what happens when the duration is hit (i.e. walltime reached) for an elastic job (since it's not in planner)?

**Comment by dongahn** [comment]
> One remaining question: what happens when the duration is hit (i.e. walltime reached) for an elastic job (since it's not in planner)?

Off the top of my head, I think the flux-core will detect the wall time is hit and kill the job and send the free request to the scheduler. I don't know why this wouldn't work equally for elastic jobs.

**Comment by milroy** [comment]
@dongahn, the question you posed during our discussion this week about the usefulness of this elastic job type has me thinking we might want another elastic subcategory.  What if a job wants more resources, but needs to do work that isn't preempted?

Such a job would be similar in implementation to the concept I've been pitching, but should be entered into planner.  It also shouldn't have extremely high priority like the class (outside of planner) proposed here.  In case this job type sounds interesting, I think I should come up with better `jobtype` names than those in PR #584.

**Comment by milroy** [comment]
While preparing a PR for issue #558 I realized that assigning a score to each vertex depends on information of which job types are allocated or reserved at the time of the resource request.  Technically, skipping the planner update will still work, but it can result in suboptimal resource matching, especially if multiple policies are used together.  For example, a resource reservation request far in the future will get a lower score if an elastic job is currently running on the vertex in question.

That means the elastic job type I propose here needs its own `planner_t` and can't be skipped.

**Comment by milroy** [comment]
@dongahn: I’ve been mulling over our conversation today, and am now leaning back toward a single planner.  There is one hangup I’m having which may be a misunderstanding on my part.  When a reservation becomes an allocation in the sched loop, does that trigger another match allocate, or does the job start on the resources marked as reserved?  Presumably it’s the latter.

The reason I ask goes back to our discussion about the match stage.  To rephrase and extend my previous comment: we want to discourage rigid jobs from starting on a vertex with an allocated elastic job, so the matcher should penalize vertices with an elastic job running during `jobmeta.at` but not otherwise.  If the elastic job isn’t in a planner we can’t get this information.  We could just reduce the score of a vertex if it has an allocated elastic job regardless of the new rigid job’s `jobmeta.at`, but this could result in the suboptimal placement I mentioned.  If the sched loop triggers a “match allocate” when a reservation converts to an allocation (which probably isn’t happening), just considering allocated elastic vertices independent of jobmeta.at would work fine.

**Comment by dongahn** [comment]
> When a reservation becomes an allocation in the sched loop, does that trigger another match allocate, or does the job start on the resources marked as reserved? Presumably it’s the latter.

There will be no case where a reserved job will get started. Per each schedule loop, a pending job will either be marked as reserved or allocated. Only when it is marked allocated, it will start.

**Comment by dongahn** [comment]
> If the elastic job isn’t in a planner we can’t get this information. 

If I understand today's discussion, the elastic job should be in the planner. It is just that when you perform an "availability" check, you would take it out of the planner and perform that check. If that check says the vertex is available, the vertex becomes a selection candidate. However since it is elastic, you score this vertex low...

If performing the check once doesn't give you this info, I guess you can perform the availability query twice. First, with the elastic job in the planner. Second without that job in the planner?

**Comment by milroy** [comment]
> There will be no case where a reserved job will get started. Per each schedule loop, a pending job will either be marked as reserved or allocated. Only when it is marked allocated, it will start.

My question wasn't clear.  What I meant to ask was are the resources associated with the jobid when it's reserved guaranteed to be the same as the resources when the job is marked allocated and starts?

> If I understand today's discussion, the elastic job should be in the planner. It is just that when you perform an "availability" check, you would take it out of the planner and perform that check [...]

Yes, you're right.  I confused myself during my mulling!

**Comment by dongahn** [comment]
> What I meant to ask was are the resources associated with the jobid when it's reserved guaranteed to be the same as the resources when the job is marked allocated and starts?

No it is not guaranteed at all.

**Comment by milroy** [comment]
> No it is not guaranteed at all.

Ok, yes, it looks like the magic happens here: https://github.com/flux-framework/flux-sched/blob/17553f7b527bf24fb7bbbdb2c0350e1a746acdfc/qmanager/policies/queue_policy_fcfs_impl.hpp#L71

Since the transition between reservation and allocation involves a `match_allocate`, the suboptimal vertex selection for reserved jobs doesn't matter.  Then it's fine to just check if a vertex has an elastic job allocated and deprioritize it accordingly.

It should be fine to leave elastic jobs out of planner entirely.

**Comment by dongahn** [comment]
Yap! Awesome.

**Comment by dongahn** [comment]
@milroy: I will close those issues for now. If you want to keep any of those, feel free to reopen.
