### ISSUE TITLE
rc scripts don't have number prefix

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-sched#587]
After building and installing `flux-core` and `flux-sched`, the `etc/rc1.d` directory looks like:

```
→ ll rc1.d
total 16K
-rwxr-xr-x 1 root   root   571 Jan 30 21:33 01-enclosing-instance
-rwxr-xr-x 1 root   root   632 Feb  1 01:17 qmanager-start
-rwxr-xr-x 1 root   root   683 Feb  1 01:17 resource-start
```

I think they should be numbered to ensure an ordering, especially when user/site rc scripts start getting added into the mix.

**Comment by dongahn** [comment]
You envision we use like 02 to indicate the rc scripts came from the sched project?

**Comment by SteVwonder** [comment]
Yeah.  I think `02-resource` and `03-qmanager` would work (assuming they need to be loaded in a particular order, if not then `02` would work for both). @garlick and @grondo: any object to `flux-sched` using `02` or should we leave some space for other modules?  What's the typical best practice here?

**Comment by garlick** [comment]
That's fine for now.  We still need to figure out a better way to select which scheduler runs in a given instance (and more generally how modules are customized in an instance), but not today I think.

**Comment by dongahn** [comment]
This has been added to PR #694
