### ISSUE TITLE
planner: store jobid and jobtype in scheduled_point_t

### ISSUE THREAD

**Issue by milroy** [flux-framework/flux-sched#590]
This question and potential enhancement is related to (and may supersede) PR #584, as well as issues #576, #558, and #552.

Scheduling of adaptive and elastic jobs extends the intention of: https://github.com/flux-framework/flux-sched/blob/05243593bd908f96599700eab5000e44ac4655d0/resource/planner/planner.c#L823  Since different job types have different relative priorities, the number of available resources at each scheduled point depends on the job type being matched.  Furthermore, the score of each vertex should depend on the number of elastic, adaptive, and rigid jobs allocated or reserved at the point in time in question.

So far I've been refactoring flux-sched to accommodate a `planner_t` for each job type.  This approach has undesirable effects: the additional overhead of multiple planners, the code bloat of added logic related to checking which job types are running at various times (and their relative priorities), and the inelegance of querying the `g[v].schedule.allocations` or `g[v].schedule.reservations` to get `jobid`s.  Note that my testing indicates that the exclusive planner will also need a separate instance per job type.

Beyond that, if we allow adaptive jobs to hold reservations: https://github.com/flux-framework/flux-sched/blob/af4447ffd27400cc33a908c62201380a98075571/resource/traversers/dfu_impl_update.cpp#L122 will need to check which and how many job types are allocated/reserved during `jobmeta.at`.  Such functionality is ~~not possible~~ clumsy with the current planner design.

Should we extend planner and `scheduled_point_t` to store `jobid`s and `jobtype`s?  An inspection of `planner.c` suggests that this could be an involved undertaking.

**Comment by milroy** [comment]
@dongahn and I discussed this issue today.  We decided that modifying planner to include the specified metadata will add significant, undesirable complexity.  @dongahn suggested that I subsume this information and the logic checks for availability into `planner_multi_t`.

**Comment by dongahn** [comment]
Also probably old.
