### ISSUE TITLE
planner_t to planner_multi_t refactor

### ISSUE THREAD

**Issue by milroy** [flux-framework/flux-sched#591]
Based on feedback on issue #590, I'm refactoring flux-sched to use `planner_multi_t` instead of `planner_t`.  The purpose of this change is to enable clean handling of a planner per job type per resource vertex.  This introduces a difficulty related to an extension/abuse of `planner_multi_t`: 

```
planner_multi_t *planner_multi_new (int64_t base_time, uint64_t duration,
                                    const uint64_t *resource_totals,
                                    const char **resource_types, size_t len);
```

In particular, `resource_types` is a "string array of size `len` where each element contains the resource type corresponding to each corresponding element in the resource_totals array."  Considering `resource_types` to be job types, e.g., `{"rigid", "elastic"}` will probably work fine, but the planners will lose information about the actual resource types.

@dongahn or @SteVwonder do you recommend that I create another entry in the `planner_multi` struct for job types (and related calls), or is there a better approach?

**Comment by dongahn** [comment]
@milroy: does `planner_multi_t` need to know whether a planner at index I is rigid or elastic? Can `resource_types` still be like `{"node", "node"}` and elasticity semantics be implemented by the user of `planner_multi_t`? IOW, is there any logic you need to implement within `planner_multi_t` that depends on whether a planner in it has the resource state from the rigid jobs vs. that from the elastic jobs?

**Comment by milroy** [comment]
@dongahn: the answer to both of your questions is yes, but upon further consideration/experimentation I think the better approach is to create a new type.  While `planner_multi_t` can be extended to perform the needed functions, it carries a lot of unneeded overhead in the form of data structures and more dimensions (e.g. `request iter`, `char **resource_types`, `uint64_t *resource_totals`).

**Comment by dongahn** [comment]
This probably is old at this point. We can reopen if needed of course.
