### ISSUE TITLE
cannot load qmanager/source: not found in module search path

### ISSUE THREAD

**Issue by fmuelle4711** [flux-framework/flux-sched#592]
I built flux-sched and installed it, just as flux-core, with
export PKG_CONFIG_PATH=$HOME/local/lib/pkgconfig:$PKG_CONFIG_PATH
PYTHON_VERSION=3.6 ./configure --prefix=$HOME/local

Notice that flux-core was gcc compiled, but a mek for flux-sched (on CentOS 7.5) throws:
/usr/include/yaml-cpp/node/impl.h:158: undefined reference to `YAML::detail::node_data::empty_scalar[abi:cxx11]'

I got around this by switching to clang, just for flux-sched:
#need to build w/ clang since yaml-cpp has c11++ problems...
#https://github.com/scylladb/scylla/issues/855
export CC=/usr/bin/clang
export CXX=/usr/bin/clang++
./autogen.sh
...
make install

Now, with a fresh flux instance:
srun -w c[93-94] -X --pty --mpi=none ~/projects/flux-core/src/cmd/flux start

and the modules are there
ls /home/fmuelle/local/lib/flux/modules
aggregator.la       content-sqlite.la  job-info.la     kvs.la        qmanager.la      userdb.la
aggregator.so       content-sqlite.so  job-info.so     kvs.so        qmanager.so      userdb.so
barrier.la          cron.la            job-ingest.la   kvs-watch.la  resource.la
barrier.so          cron.so            job-ingest.so   kvs-watch.so  resource.so
connector-local.la  job-exec.la        job-manager.la  pymod.la      sched-simple.la
connector-local.so  job-exec.so        job-manager.so  pymod.so      sched-simple.so

I get:
flux module list
Module                   Size Digest  Idle  S Service
barrier               1127680 05EC221    3  S 
kvs-watch             1306600 481B278    3  S 
userdb                1124824 89376A1    3  S 
job-exec              1272992 A2DF82F    3  S 
job-manager           1339608 84CB2EB    3  S 
cron                  1211720 F8A985B    0  S 
job-info              1323128 5399319    3  S 
content-sqlite        1132424 A97FB33    3  S content-backing
connector-local       1113128 FC29BEE    0  R 
job-ingest            1216472 110855C    3  S 
kvs                   1565520 9F562B9    0  S 
sched-simple          1252144 CFC0EE8    3  S sched
aggregator            1143200 F2AF991    3  S 

module load qmanager
Lmod has detected the following error:  The following module(s) are unknown:
"qmanager"

Any ideas?

**Comment by fmuelle4711** [comment]
Never mind, my mistake, it was due to calling my flux-core build in src:
FLUX_MODULE_PATH=/home/fmuelle/projects/flux-core/src/modules

I should have done this:
srun -w c[93-94] -X --pty --mpi=none ~/local/bin/flux -v start

**Comment by dongahn** [comment]
> Notice that flux-core was gcc compiled, but a mek for flux-sched (on CentOS 7.5) throws:
/usr/include/yaml-cpp/node/impl.h:158: undefined reference to `YAML::detail::node_data::empty_scalar[abi:cxx11]'

Well mixing c++ compilers in general is a bad idea. What is the GCC version that gives you this error?

Also what is your yaml cpp RPM version?

**Comment by fmuelle4711** [comment]
yaml-cpp-devel-0.5.1-2.el7.x86_64

It's a CentOS problem, compiling yaml-cpp from sources does not fix it, I tried up/down grading, no go. But clang gets around it. Not the best of solutions but good enough for now.

**Comment by dongahn** [comment]
I think the best approach is to upgrade yaml-cpp  compiled with the GCC version you are using. It is likely your library is currently built with an older version of GCC with _GLIBCXX_USE_CXX11_ABI=0.

**Comment by dongahn** [comment]
Odd...

**Comment by fmuelle4711** [comment]
I tried, no go. See my last msg.

**Comment by fmuelle4711** [comment]
BTW, flux-core does *not* compile w/ clang, maybe also something to check out.
Due to that, I settled for a mixed compilation scenario, no problems so far.

**Comment by dongahn** [comment]
> BTW, flux-core does not compile w/ clang, maybe also something to check out.
Due to that, I settled for a mixed compilation scenario, no problems so far.

@fmuelle4711: Thank you for kicking the tires for this! We need to file this against flux-core, though. We actually have a pretty extensive compiler coverage w/ Travis matrix. So this is a bit surprising. It would be good to have the tested clang version and platform information when a new ticket against flux-core is created.

**Comment by grondo** [comment]
Hm, through various iterations of our travis config I think we're only testing against clang-6.0, and only in Ubuntu bionic. I hate to add more builders to our test matrix, but we should perhaps at least test against newer clang version.

**Comment by grondo** [comment]
See flux-framework/flux-core#2740. We aren't testing with older clang so a couple issues seem to have crept in.

**Comment by fmuelle4711** [comment]
Well, you decide, ticket filed. I'd rather see PMIX support after my install experience, but I'm sure you have a technical reason not to. (What might that be?)

Here's a clang compile warning for flux-sched you may care about:
  CXX      resource_query-resource-query.o
warning: unknown warning option '-Wno-unused-local-typedefs'
      [-Wunknown-warning-option]
resource-query.cpp:658:51: warning: comparison of unsigned expression < 0 is
      always false [-Wtautological-compare]
                if ( (ctx->params.reserve_vtx_vec < 0)
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~

From here on, I'll turn it over to Subhendu.

**Comment by dongahn** [comment]
> CXX resource_query-resource-query.o
warning: unknown warning option '-Wno-unused-local-typedefs'
[-Wunknown-warning-option]
resource-query.cpp:658:51: warning: comparison of unsigned expression < 0 is
always false [-Wtautological-compare]
if ( (ctx->params.reserve_vtx_vec < 0)

Thanks!

**Comment by dongahn** [comment]
I will close this. I will create a new ticket for 

```
Well, you decide, ticket filed. I'd rather see PMIX support after my install experience, but I'm sure you have a technical reason not to. (What might that be?)

Here's a clang compile warning for flux-sched you may care about:
CXX resource_query-resource-query.o
warning: unknown warning option '-Wno-unused-local-typedefs'
[-Wunknown-warning-option]
resource-query.cpp:658:51: warning: comparison of unsigned expression < 0 is
always false [-Wtautological-compare]
if ( (ctx->params.reserve_vtx_vec < 0)
~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~
```
