### ISSUE TITLE
`make check` fails when run after `make install`

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-sched#607]
If flux-sched is configured with the same prefix as flux-core and you attempt to run `make check` after a `make install`, `t1005-qmanager.t` will fail because the flux-sched rc.d scripts are run twice. The first time is the installed rc.d scripts being run by the installed rc script (from flux-core) and the second time is the in-tree rc.d scripts being run by the test (via FLUX_RC_EXTRA).  We need some way to disable installed flux-sched rc scripts when running certain tests.

One suggestion (which would have to be implemented in flux-core I believe), would be to add a variable like `FLUX_IGNORE_INSTALLED_SCHED_RC` that disables the installed sched rc.d scripts (but still runs the installed flux-core rc scripts) without affecting the in-tree sched rc scripts.

**Comment by grondo** [comment]
> One suggestion (which would have to be implemented in flux-core I believe), would be to add a variable like FLUX_IGNORE_INSTALLED_SCHED_RC that disables the installed sched rc.d scripts (but still runs the installed flux-core rc scripts) without affecting the in-tree sched rc scripts.

How is flux-core going to know which rc scripts belong to flux-sched?

If the flux-core `rc1` script sourced everything in `rc1.d` instead of running it, then packages could add guards to their rc scripts like

```sh
test -n "$FLUX_SCHED_HAVE_RC_QMANAGER" && return 0
FLUX_SCHED_HAVE_RC_QMANAGER=1
```

Maybe we could turn this into a convenience function exported by `rc1`.

It all kind of feels like stopgap measures though, and that there's a deeper issue here.

**Comment by dongahn** [comment]
> How is flux-core going to know which rc scripts belong to flux-sched?

I was thinking to add RC script prefix like "qmanager:resource" and flux-core can do a file name matching to ignore certain RC scripts....

> If the flux-core rc1 script sourced everything in rc1.d instead of running it, then packages could add guards to their rc scripts like

Sorry I don't follow this suggestion. What is the condition in which `FLUX_SCHED_HAVE_RC_QMANAGER` is defined?

**Comment by grondo** [comment]
It would always be defined. Equivalent to C preprocessor header guard. 

You would just have to make sure the test copy of the rc script is sourced first.

**Comment by dongahn** [comment]
> You would just have to make sure the test copy of the rc script is sourced first.

 I like the C preprocessor guard analogy. Yeah I think this is the key then.
