### ISSUE TITLE
Add a `--with-flux-core-prefix` configure option

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-sched#609]
Adding @grondo's suggestion from https://github.com/flux-framework/flux-docs/pull/23, it would nice to have a option like `--with-flux-core-prefix=PREFIX` as opposed to setting `PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig`.

**Comment by SteVwonder** [comment]
> should this be a flux-sched issue?

yeah, sorry about that. just transferred

**Comment by dongahn** [comment]
With @grondo's PR https://github.com/flux-framework/flux-sched/pull/603, do we need this though?

**Comment by grondo** [comment]
Yeah that fix was meant to supplant my earlier idea
