### ISSUE TITLE
Pass starttime estimate to "note"

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-sched#626]
@chu11 and @garlick: 

We talked about utilizing the flux-core's front end as much as possible to pass scheduler information. I want to see what it takes to pass the starttime estimate to the "note" to each `alloc` request for backfill based policies within manager. What needs to happen within flux-core to make use of (e.g., display) this information?

**Comment by garlick** [comment]
As we discussed earlier,  the response should be a JSON dict rather than a human readable message.  The job manager must be modified do something with this when it is received.  Originally the design was to attach it to the job hash entry, in memory only, and update it each time that response type is received for the job, discarding the old value.  (adding it to the persistent job event log seemed not to be useful and potentially high overhead if it could be updated many times per job)

I don't remember what we came up with for how to get the data from job manager to job-info and thus to the listing tool.  Do you remember @chu11?

**Comment by garlick** [comment]
Ah actually we opened flux-framework/flux-core#2608 after that discussion.

**Comment by dongahn** [comment]
> As we discussed earlier, the response should be a JSON dict rather than a human readable message. The job manager must be modified do something with this when it is received. Originally the design was to attach it to the job hash entry, in memory only, and update it each time that response type is received for the job, discarding the old value. (adding it to the persistent job event log seemed not to be useful and potentially high overhead if it could be updated many times per job)

Thanks. @garlick.

Since flux-core doesn't use "note" just yet, it seems I can make progress in flux-sched independently and pass a JSON object to the note instead of a plain text.  

Also too frequent of an update response will be bad as this can happen when there are lots of churns that lead to schedule loop invocations.I will see if I can add some heuristics to send a note response only when the state (starttime estimate and pending reason) change significantly.

**Comment by dongahn** [comment]
At today's meeting, we agreed that it would be good for `qmanager` to add queue and start time to "note" in JSON. This can facilitate the development of properly displaying the scheduler info within flux-core's job listing tool.

**Comment by dongahn** [comment]
Also would be good to add this soon.

**Comment by dongahn** [comment]
Preliminary support has been added to https://github.com/dongahn/flux-sched/tree/starttime-estimate

**Comment by dongahn** [comment]
```
update_annotations: job 313482280960 not found: Success
```

```console
ahn1@9322372c5ba3:/usr/src/t$ ./t1003-qmanager-policy.t
==29201== Memcheck, a memory error detector
==29201== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==29201== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==29201== Command: /usr/libexec/flux/cmd/flux-broker --setattr=rundir=/tmp/flux-29168-r3sv0a --setattr=tbon.endpoint=ipc://%B/req -Slog-filename=t1003-qmanager-policy.broker.log -Slog-forward-level=7 -Sinit.rc2_timeout=300 -g 10 sh\ ./t1003-qmanager-policy.t\
==29201==
ok 1 - qmanager: generate jobspecs of varying requirements
ok 2 - qmanager: hwloc reload works
ok 3 - qmanager: loading qmanager (queue-policy=easy)
2020-08-25T03:57:03.978102Z job-info.err[0]: update_annotations: job 134939148288 not found: Success
ok 4 - qmanager: EASY policy correctly schedules jobs
ok 5 - qmanager: loading qmanager (queue-policy=hybrid)
2020-08-25T03:57:14.570105Z job-info.err[0]: update_annotations: job 313482280960 not found: Success
2020-08-25T03:57:15.150778Z job-info.err[0]: update_annotations: job 320226721792 not found: Success
2020-08-25T03:57:16.421696Z job-info.err[0]: update_annotations: job 329571631104 not found: Success
not ok 6 - qmanager: HYBRID policy correctly schedules jobs
#
#	    jobid1=$(flux job submit C08.T3600.json) &&
#	    jobid2=$(flux job submit C10.T3600.json) && # reserved
#	    jobid3=$(flux job submit C12.T3600.json) && # reserved
#	    jobid4=$(flux job submit C14.T3600.json) && # reserved
#	    jobid5=$(flux job submit C16.T3600.json) &&
#	    jobid6=$(flux job submit C06.T7260.json) &&
#	    jobid7=$(flux job submit C04.T10800.json) && # BF A
#	    jobid8=$(flux job submit C04.T14400.json) &&
#	    jobid9=$(flux job submit C02.T14400.json) && # BF C when 8 completes
#	    jobid10=$(flux job submit C02.T18000.json) &&
#	    jobid11=$(flux job submit C02.T3600.json) && # BF B
#
#	    flux job wait-event -t 10 ${jobid1} start &&
#	    flux job wait-event -t 10 ${jobid7} start &&
#	    flux job wait-event -t 10 ${jobid11} start &&
#	    flux job cancel ${jobid7} &&
#	    flux job wait-event -t 10 ${jobid9} start &&
#	    test $(flux job list --states=active | wc -l) -eq 10 &&
#	    test $(flux job list --states=running| wc -l) -eq 3 &&
#	    flux job list --states=active | jq .id | xargs -L 1 flux job cancel &&
#	    flux job wait-event -t 10 ${jobid11} clean
```

**Comment by dongahn** [comment]
```
2020-08-25T03:57:33.589058Z sched-fluxion-resource.err[0]: match_request_cb: existent job (313482280960).: Invalid argument
2020-08-25T03:57:33.946334Z sched-fluxion-resource.err[0]: match_request_cb: existent job (320226721792).: Invalid argument
2020-08-25T03:57:34.077074Z sched-fluxion-resource.err[0]: match_request_cb: existent job (329571631104).: Invalid argument
not ok 8 - qmanager: CONSERVATIVE correctly schedules jobs
#
#	    jobid1=$(flux job submit C08.T3600.json) &&
#	    jobid2=$(flux job submit C10.T3600.json) && # reserved
#	    jobid3=$(flux job submit C12.T3600.json) && # reserved
#	    jobid4=$(flux job submit C16.T3600.json) && # reserved
#	    jobid5=$(flux job submit C14.T3600.json) && # reserved
#	    jobid6=$(flux job submit C06.T7260.json) && # reserved
#	    jobid7=$(flux job submit C04.T10800.json) && # BF A
#	    jobid8=$(flux job submit C04.T14400.json) && # reserved
#	    jobid9=$(flux job submit C02.T14400.json) && # reserved
#	    jobid10=$(flux job submit C02.T18000.json) && # reserved
#	    jobid11=$(flux job submit C02.T3600.json) && # BF B
#
#	    flux job wait-event -t 10 ${jobid1} start &&
#	    flux job wait-event -t 10 ${jobid7} start &&
#	    flux job wait-event -t 10 ${jobid11} start &&
#	    flux job cancel ${jobid7} &&
#	    flux job wait-event -t 10 ${jobid7} clean &&
#	    test $(flux job list --states=active | wc -l) -eq 10 &&
#	    test $(flux job list --states=running| wc -l) -eq 2 &&
#	    flux job list --states=active | jq .id | xargs -L 1 flux job cancel &&
#	    flux job wait-event -t 10 ${jobid11} clean
#
```

**Comment by dongahn** [comment]
PR #735 has been merged.
