### ISSUE TITLE
not ok 5 - jobs scheduled in correct order

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-sched#63]
I'm finding that `test 5 - jobs scheduled in correct order` is consistently failing for me in the following tests

**t2000-fcfs**

Expected:  `1 2 3 4 5 6 7 8 9 10 11 12`
Actual: `1 2 4 10 11 12`

**t2001-fcfs-aware**

Expected: `1 2 3 4 5 6 7 8 9 10 11 12`
Actual: `1 2 4 10 11 12`

**t2002-easy**

Expected: `1 2 3 6 7 8 9 10 11 4 5 12`
Actual: `1 2 4 5 6 7 9 11 10 8 12 3`

This occured on current master of flux-sched:  f912cb256b1efb191c0f196fdba4a4494e5760a0 and flux-framework/flux-core@ad0f54b452791231eb9952e6f74298e21cc2d796.
I also tried one PR back in flux-framework/flux-core@8d00634cbb60a3f49d58f4595860c43ac6299248 

This is on RHEL 6/TOSS 2 based desktop.

**Comment by dongahn** [comment]
@garlick: I reported this to @SteVwonder last week and he plans to address these as part of his next PR.

**Comment by SteVwonder** [comment]
If you want, we can remove those tests from the HEAD of flux-sched while we are waiting on my next PR.  I am not sure why they are failing all of a sudden given that @dongahn's changes shouldn't have affected the simulator.  Either way, I will make sure they work again in the "new and improved" scheduler framework service.

**Comment by dongahn** [comment]
@SteVwonder: I think @garlick is saying these tests are failing on a desktop, not on Travis. This aggrees with my experience: they fail on cab while passing on Travis.

**Comment by garlick** [comment]
I am fine either way - just wanted to make sure I reported the failure in case it was new.

**Comment by garlick** [comment]
This just came up in our meeting and I _thought_ the we decided that the failing tests had been fixed.  However I just pulled master and noted that the tests are still disabled from commit 22250a2ddc3b58cb3f1aa75077e4f2d56c9368b7

When I uncommented the fcfs test, it failed on my RHEL6 based desktop.

Maybe the discussion was referring to a branch that hasn't been committed yet?

**Comment by dongahn** [comment]
Ah, I misspoke then. I mistakenly thought that getting 

>
# passed all 4 test(s)

are all that we need to get the pass and didn't realized this test case was disabled that way. 

@SteVwonder: please take a look at this issue as soon as *Practical*. I know you have your IPDPS deadline coming so I trust your sense of priority. Please note that I can reproduce this on Cab as well.

**Comment by SteVwonder** [comment]
The sim tests in my [branch/fork](https://github.com/SteVwonder/flux-sched/tree/sched_sim_merge/t) are uncommented (actually running and testing output) and pass on my VM.  The problem now is that the waitjob and jsc tests fail.  If we can get those working on the recently merged sim/schedsrv, then this issue should fix itself.

**Comment by dongahn** [comment]
@SteVwonder: Ok, as I promised, I will take a look at your branch this afternoon.

**Comment by dongahn** [comment]
OK. I confirmed this branch passes on Cab as well. On to the jsc integration issues.

**Comment by dongahn** [comment]
I will use #48 for the rest of integration issues.

**Comment by dongahn** [comment]
Hi @garlick: With the latest PR merged, this problem doesn't occur in my environments (on Cab and Travis.) When you have a moment, could you do a quick check on your environment for us? If this doesn't occur there, I would say we close this issue.  Thanks in advance!

**Comment by garlick** [comment]
Sorry for the delay - just tried current master 33e82b0d935ceec0d641294bd1cd5a216f72cf25 four times, and all three "jobs scheduled in correct order"  tests seem to be passing.
