### ISSUE TITLE
python: flux-shed doesn't configure on CORAL

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-sched#636]
With TCE:
```
checking whether yaml-cpp has YAML::Node::Mark... no
checking for boostlib >= 1.53.0 (105300)... yes
checking for buggy boostlib versions (105400-105800)... no
checking whether the Boost::System library is available... yes
checking for exit in -lboost_system... yes
checking whether the Boost::Filesystem library is available... yes
checking for exit in -lboost_filesystem... yes
checking whether the Boost::Graph library is available... yes
checking for exit in -lboost_graph... yes
checking whether the Boost::Regex library is available... yes
checking for exit in -lboost_regex-mt... yes
checking for readline in -lreadline... yes
checking for python3.7... no
configure: error: Cannot find python3.7 in your system path
```

Don't know if python3.6 would satisfy the python requirement of flux-sched. @SteVwonder: are we using unique features from python3.7 within flux-sched?

**Comment by dongahn** [comment]
`module load python/3.7.2` seems to do things better. Let me reconfig and rebuild both flux-core and flux-sched with this.

**Comment by dongahn** [comment]
OK. Turns out `module load python/3.7.2` was the key.

**Comment by SteVwonder** [comment]
Hmm.  That's an interesting behavior.  The flux-sched configure is [still set to check for 2.7+](https://github.com/flux-framework/flux-sched/blob/master/configure.ac#L72).  Did you happen to configure flux-core against py3.7?  My suspicion is that flux-sched is attempting to configuring itself against the same python that core was configured against (which is probably the behavior that we want to enforce.....error message could be better though).

**Comment by dongahn** [comment]
> Did you happen to configure flux-core against py3.7?

No when I tested this, I configured flux-core against py3.6...

> My suspicion is that flux-sched is attempting to configuring itself against the same python that core was configured against (which is probably the behavior that we want to enforce.....error message could be better though).

How does flux-sched figure this out though?

**Comment by SteVwonder** [comment]
> No when I tested this, I configured flux-core against py3.6...

Do you know which py3.6 interpreter you were using?  I'd like to try and reproduce this.  In https://github.com/flux-framework/flux-core/issues/2881, it looks like the system-installed 3.6 failed for you.  Did you use a python 3.6 in your home directory?

> How does flux-sched figure this out though?

[This little bit of m4/python/flux magic](https://github.com/flux-framework/flux-sched/blob/8238aee6427e42f568026cb3ff17c27d54e5001e/config/ax_flux_core.m4#L83) (credit goes to @grondo):
```
FLUX_PYTHON_VERSION=$($FLUX python -c 'import sys; print(".".join(map(str, sys.version_info[[:2]])))')
```

So to be precise, flux-sched tries to configure itself with the same python **version** as flux-core.  It doesn't enforce the exact same interpreter path.
