### ISSUE TITLE
[discussion] multi-queue design

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-sched#637]
Maybe I can get some feedback from a coffee hour but just to kick this:

At a very high level, supporting multiple queues using the concept of "label" would require following changes.

- jobspec: add a  `partitition_label` or similar. I think 'attributes.system.partition_label` would do. Thoughts?

- run/submit (e.g., flux mini run) commands: support an command line option corresponding to this key like `-p or --partition`

- `qmanager`:  introduce new load and config options so that it can instantiate multiple queues using the qmanager policy queue classes. 

- `resource`: add this label into each and every resource vertex. As a new field in the vertex resource data or as a property. I think that part is easy. One thing that is not clear to me is how to generate this label for resource readers like `hwloc` reader.

**Comment by SteVwonder** [comment]
To summarize the things that I took away from the coffee time discussion (thanks again @dongahn for your patience in talking through your thought process with me):

> qmanager: introduce new load and config options so that it can instantiate multiple queues using the qmanager policy queue classes.

This makes sense to me.  

>

**Comment by dongahn** [comment]
> Note to myself: we cannot handle the queue limits at the qmanager level because that would preclude supporting reservations. This method allows us to still make reservations on jobs in the batch queue (and technically in the debug queue as well).

At first glance, it seems this adds too much resource and job inspection at the qmanager level, which could better be handled by other orthogonal modules and plugins. Seemed to violate separations of concerns. 

If `qmanager` has to do this, it now needs to know which user submitted the job, crack open each jobspec and inspect it throughly. It also has to check various limits not only on the requests of each jobspec level but also on the other jobs that belong to the same user or even to other users. 

Broadly speaking, it seemed this would be a logic that needs to be packed into another modules or plugins if possible...

I think doing this at the job-manager level would be ideal. But with the introduction of multi-queues, it is not clear if it can do this with requisite granularity...

We need to keep talking.

**Comment by dongahn** [comment]
> I may have missed something in the discussion, but I believe the outcome was that we would do something quick (and maybe a little dirty) on the flux-core side to get the resource labels embedded in the hwloc xml. (Link to Github issue, existing or new, required).

Put my first thought at https://github.com/flux-framework/flux-core/issues/2890

**Comment by dongahn** [comment]
> I was initially thinking there could be a attributes.system.labels array that users could append a bunch of labels to (e.g., debug, pre-emptible), but I'm starting to like your proposed approach. The separation of concerns is much better. My only suggestion would be to name it attributes.system.queue or if we want to stick with the partition name: attributes.system.partition (see next comment for my motivation why).

Yeah, I am having a similar thought. Please look at the "hierarchical" label that I mentioned at flux-framework/flux-core#2890. Whatever we do, the label specification should match between the jobspec and hwloc annotation levels..

**Comment by dongahn** [comment]
> One thought would be to just use the existing attribute functionality to achieve this. For example: flux mini run --setattr system.queue=debug hostname. If we added a flag for setting system attributes (similar to our -o flag for setting jobshell options), we could get something even shorter like flux mini run -s queue=debug hostname. (-s is just a strawman for the example).

Excellent!

> `flux mini run --setattr system.queue=debug hostname`

I actually like this because it is a general solution! If we were to go this route, we will need GOOD documentation, though.

**Comment by dongahn** [comment]
As we discussed during our coffee hour, implementing multi queue support in its entirety is pretty substantial so I will break up the tasks into a more manageable set of issues. We need:

1. Introduce multiple queue objects into `qmanager` and adjust all of its business logic for multi-queue.
2. Introduce label support into `resource` and adjust all of its matching logic to make use of it.
3. Add label support into `hwloc` within flux-core.

**Comment by dongahn** [comment]
The `qmanager` piece has been completed. The `sched-fluxion-resource` will require RV2 (that @grondo is leading) at which point I will start a new thread. Closing for now.
