### ISSUE TITLE
resource: JGF reader not adding elements to by_path map

### ISSUE THREAD

**Issue by milroy** [flux-framework/flux-sched#639]
I've come across a problem when generating a resource graph with the JGF reader.  When the JGF reader is selected as the load format in the Flux resource module or in `resource-query` the `by_path` map in the resource graph metadata is not populated.  Here's an example where I modified `resource-query` to print the size of `by_path`:

```
$ resource-query -L ~/flux-sched/t/data/resource/jgfs/tiny.json -f jgf
Number of keys in by_path map: 0
INFO: Loading a matcher: CA
resource-query> quit
$ resource-query -L ~/flux-sched/t/data/resource/grugs/tiny.graphml -f grug
Number of keys in by_path map: 100
INFO: Loading a matcher: CA
resource-query> 
```

The cause is missing logic in `resource_reader_jgf_t::add_graph_metadata`:
 https://github.com/flux-framework/flux-sched/blob/280863295b335b2a005b315b78490fe8ff540b5d/resource/readers/resource_reader_jgf.cpp#L257
The loop should insert a key-value pair unless the second `if` condition is satisfied.  After making the modification and recompiling:

```
$ resource-query -L ~/flux-sched/t/data/resource/jgfs/tiny.json -f jgf
Number of keys in by_path map: 100
INFO: Loading a matcher: CA
resource-query>
```

**Comment by milroy** [comment]
I should add that this behavior occurs with the latest flux-sched master.

**Comment by dongahn** [comment]
Great catch! The patch sounds good to me.
