### ISSUE TITLE
Add multiple queue support within qmanager

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-sched#640]
This is the first task to implement multiple queue support as discussed at https://github.com/flux-framework/flux-sched/issues/637.

1. Replace a single queue object (of `queue_policy_base_t` type) within `qmanager_ctx_t` with a `std::map` that contains a configurable number of queue objects keyed off of distinct queue names. 

2. Add ways to specify multiple queues both in configuration files and module load options while keeping the current conf/load option set backward compatible as much as possible. Each specified queue should be able to enforce a queueing policy, queuing parameters and queueing-policy parameters, independent of one another.

3. Bring in libjobspec to fetch the queue information from `system.attributes.queue` key of a jobspec and use it to identify the corresponding queue. 

4. Adjust biz logic in each and every job-manager callbacks like `jobmanager_alloc_cb`

5. Add the queue name into `R` (as part of `scheduling` key) so that it will help reconstruct multiple named queues on `qmanager` reload. 

6. Adjust the existing test cases (the backward compatibility from #2 should  make this easier) and add new cases.

Once this support is added, jobspecs with different queues will be enqueued into correspondingly named queues within `qmanager` upon submission. So these jobs will be bounded by the queuing policies etc, enforced on their belonging queues.

However, the actual resources will be selected from any resource in the `resource` module. This will be this way until the next set of tasks are implemented.

**Comment by cmoussa1** [comment]
This is just for my own curiosity and learning, but how does `qmanager` perform a check to make sure the queue requested can fulfill the resources requested by a job? Here's a hypothetical example of what I am talking about:

A job is submitted to the **debug** queue; this job is requesting 5 nodes, but the **debug** queue only supports a max of 3 nodes per job.

Does `qmanager` have its own table (where each queue's limits are defined) that it checks? Or does it do something else?

Or maybe what I am asking about is already answered in your initial comment:

> Bring in libjobspec to fetch the queue information from system.attributes.queue key of a jobspec and use it to identify the corresponding queue.

**Comment by dongahn** [comment]
@cmoussa1 and I chatted yesterday and this topic came up. I think the easiest way to put certain limits (e.g., max node count and wall time) would be through a configuration file (or module load option). We will not be able to enforce per-user limits this way, but I am not sure if that's necessary.

**Comment by cmoussa1** [comment]
To add to this, from conversations with Ryan:

> We do enforce some per-user limits that are stored in the slurmdb. The biggest ones are what slurm calls grpTRES limits, which are basically limits on the total number of resources (nodes, cpus) that a user can have across all of their running jobs.

These per-user limits, from what I can tell, are defined in an association table, so we could add this as a field in that table.

**Comment by dongahn** [comment]
> all of their running jobs.

Is that really "all of their running jobs"? Or ... running jobs per queue?

**Comment by cmoussa1** [comment]
Here is the explanation I was given. Hope this helps clarify:

> The grpTRES limit is set on a particular user/bank association, and applies across all partitions on a cluster. So, on a cluster, all of the users in banks have grpTRES=cpu=XXXX which limits the number of CPUs that their running jobs can have on the cluster, regardless of which partition those jobs are running in. We do also have a MaxTRESPU=node=8 limit (via a partition qos) on a cluster debug queue that limits the total number of nodes that any user can run on at a time. I think I forgot about that limit in my last email, but it is an example of a case where we limit the total number of resources that a user can use in a partition.

**Comment by dongahn** [comment]
> The grpTRES limit is set on a particular user/bank association, and applies across all partitions on a cluster. So, on a cluster, all of the users in banks have grpTRES=cpu=XXXX which limits the number of CPUs that their running jobs can have on the cluster, regardless of which partition those jobs are running in.

So still my biggest question is why can't this be handled by faireshare.

**Comment by dongahn** [comment]
> We do also have a MaxTRESPU=node=8 limit (via a partition qos) on a cluster debug queue that limits the total number of nodes that any user can run on at a time. I think I forgot about that limit in my last email, but it is an example of a case where we limit the total number of resources that a user can use in a partition.

As we discussed, an easy way to implement this is to add this per-queue limit into the qmanager configuration file and have a way to override this via a module load option. Or do this at the job-ingest plug-in level via a mechanism like https://github.com/flux-framework/flux-sched/issues/642#issuecomment-611783946.

**Comment by dongahn** [comment]
> Or do this at the job-ingest plug-in level via a mechanism like #642 (comment).

Actually this seems a "runtime" limit so qmanager would be the right place.

**Comment by dongahn** [comment]
FYI -- it turned out this requires some substantial change and in order to keep the complexity of a single PR sane, I need to break up this issue even to more sub issues. 
- PR to add generic C++ exception handling wrapper and apply it to qmanager. (PR #644 posted).
- PR to refactor configuration management (with multiple queue support, the option set for `qmanager` is becoming increasingly more complex and without a systematic configuration management scheme, I found the half of the `qmanager` code is doing config management! 
- Final PR that actually adds multi-queue support.

**Comment by dongahn** [comment]
This should have been fixed. @cmoussa1: if you want to capture some of the discussion w/ limits, please carve out the thread and create a new issue.
