### ISSUE TITLE
Rundir test with flux-tree is failing,

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-sched#643]
```
FAIL: t2001-tree-real.t 8 - flux-tree: works with pre-existing rundir subdirectories
FAIL: t2001-tree-real.t 9 - flux-tree: rundir is propagated to nest instances
```

**Comment by SteVwonder** [comment]
What system is this happening on?  Is it succeeding in Travis and failing on an LC system?  If it's happening in docker, what is the base image? Centos or ubuntu?

I wonder if it's a difference in shells.

**Comment by dongahn** [comment]
This seems only happening with a bit long CWD directory like `/usr/src/t/trash-directory.t2001-tree-real` where the rundir base directory is create.

 I wonder if there is a set buffer with the connector code... Kind of surprising because `/usr/src/t/trash-directory.t2001-tree-real/DIR/tree.1.pfs/0/local` seems a reasonable length.


```console
ahn1@4dff53c131c0:/usr/src/t/trash-directory.t2001-tree-real$ flux job attach 4466229116928
flux-job: task(s) exited with exit code 1
2020-04-18T22:49:09.654823Z connector-local.err[0]: DIR/tree.1.pfs/0/local: cannot set up socket listener: File name too long
2020-04-18T22:49:09.655129Z connector-local.crit[0]: fatal error: File name too long
2020-04-18T22:49:17.761608Z broker.err[0]: rc1: flux-exec: flux_open: No such file or directory
```

**Comment by dongahn** [comment]
Don't fully understand... 

From /usr/include/linux/un.h, it is true that max path for Unix domain socket is small (108 characters) compared to other path limits. But still the the path being used is 65 is smaller than the max.

```c
#ifndef _LINUX_UN_H
#define _LINUX_UN_H

#include <linux/socket.h>

#define UNIX_PATH_MAX   108

struct sockaddr_un {
        __kernel_sa_family_t sun_family; /* AF_UNIX */
        char sun_path[UNIX_PATH_MAX];   /* pathname */
};

#define SIOCUNIXFILE (SIOCPROTOPRIVATE + 0) /* open a socket file with O_PATH */

#endif /* _LINUX_UN_H */

```

**Comment by dongahn** [comment]
But the native path corresponding to the path visible to Docker is dangerously close to the limit:

```
/Users/ahn1/workspace/flux_dev_topical/flux-sched/t/trash-directory.t2001-tree-real/DIR/tree.1.pfs/0/local
```

= 106.

**Comment by dongahn** [comment]
This was it. When I rename flux_dev_topical to flux_dev2, this test case succeeds!

I don't know what to do about this since this is a system limit. Blame Linux. 

One thing, though, flux tree seems to hang under this condition, when it would be much better if  probably prints out an error message and exit. Probably have something to do with the error code checks...

Please keep this open until I have a chance to take a look at it.

**Comment by dongahn** [comment]
I don't believe this is still a problem. We can reopen if we encounter hangs.
