### ISSUE TITLE
Tests that use `jq` not protected by a guard

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-sched#653]
Like over in core, there are new tests that fail if `jq` isn't installed because they are missing a `jq` guard: https://github.com/flux-framework/flux-core/issues/2935

```
t/t4008-match-jgf.t
t/t6001-match-formats.t
```

Waiting to see if core makes `jq` a hard dependency, if so, adding a guard is unnecessary.  Otherwise, we should add guards to these two tests.

**Comment by dongahn** [comment]
Thanks. It seems the verdict is we will wait until a fix is made to flux-core and then replicate that at flux-sched.

**Comment by grondo** [comment]
Thanks for the reminder, I should pull over `TEST_CHECK_PREREQS` support from flux-core `sharness.d/flux-sharness.sh`.

**Comment by dongahn** [comment]
I believe this has been fixed.
