### ISSUE TITLE
Feature: emit scheduler resources

### ISSUE THREAD

**Issue by jameshcorbett** [flux-framework/flux-sched#659]
It would be nice if there was a utility for viewing the resources managed by a Flux instance. I was thinking primarily of nodes, cores per node, and gpus per node, but other information might be useful as well. This would be helpful for a couple of reasons:

1. Sanity checks for users. Also, I might know how many hardware threads my machine has per node, but I might not know whether my particular Flux setup takes them into account.
2.  When creating nested Flux instances based on the number of cores, you [need to know](https://github.com/flux-framework/flux-core/issues/2647) the number of cores per node.
3. It would render the ``-c`` option to ``flux tree``, and possibly ``-N`` option as well,  unnecessary.
4. For several reasons, the UQP usually doesn't submit all of its runs to Flux at once; it only submits enough to ensure that Flux stays at full capacity. However, in order to know what full capacity is, it needs to know how many resources are available to the enveloping Flux instance.

I would really like to be able to fetch this information programmatically, not just have it displayed ad hoc to the console. If it could be written somewhere as JSON, or fetched through Flux's bindings, that would be excellent.

**Comment by dongahn** [comment]
How about `flux hwloc info` though it didn't report GPUs last time when I looked at it. 

ahn1@fac505dfc7be:/usr/src$ flux hwloc info
1 Machine, 4 Cores, 4 PUs

1 node with 4 cores 4 hardware threads.

**Comment by dongahn** [comment]
Also if https://github.com/flux-framework/flux-sched/issues/583 is provided, this will make step 3 easier? Not that I can work on it, but I thought I would ask.

**Comment by jameshcorbett** [comment]
``flux hwloc info`` looks like it's almost what I want, thanks @dongahn. I would prefer if I could either get the information in the bindings, or have it emitted as JSON so it's easier to parse. It would be nice if it could display GPUs as well. But yeah, #583 would make step 3 easier---not that it was really all that difficult to begin with, just a little obnoxious.

**Comment by dongahn** [comment]
> I would prefer if I could either get the information in the bindings, or have it emitted as JSON so it's easier to parse. It would be nice if it could display GPUs as well.

@grondo and @garlick are reworking the module so this would be a good feedback for them.  

> But yeah, #583 would make step 3 easier---not that it was really all that difficult to begin with, just a little obnoxious.

Understood.

**Comment by jameshcorbett** [comment]
Oh yeah, one last use case---it could replace the ``FLUX_TREE_NNODES``, ``FLUX_TREE_NCORES_PER_NODE``, and ``FLUX_TREE_NGPUS_PER_NODE`` environment variables.

**Comment by grondo** [comment]
@jameshcorbett, support for this feature is long overdue, I apologize.

After the new `resource` module work in flux-core (flux-framework/flux-core#2918) is complete, I think we will propose a new interface and command that will support what you want. See also flux-framework/flux-core#2898.

In the end, I think coarse grained resource status (all available resources) can be obtained from the `resource` module itself. But only the scheduler will know allocated vs free resources, so in order to get this level of detail, Flux schedulers will also have to implement a standard query or status interface.

In either case, the response to these RPCs will contain JSON _R_ representation, and we should eventually offer Python interface to parse and work with these objects.

**Comment by jameshcorbett** [comment]
Thanks @grondo. I'll close this issue because it looks like it's handled elsewhere.

I should clarify, though---I don't have any real need to know the current allocated/free resource breakdown. I just want to know all available resources.

**Comment by garlick** [comment]
Excellent to have your input, as always @jameshcorbett.

**Comment by grondo** [comment]
> I should clarify, though---I don't have any real need to know the current allocated/free resource breakdown.

Great input. Perhaps the flux-core `resource` module should also provide a simple RPC that users can use to get the currently available resources. Although perhaps redundant with any scheduler RPC, it would be much lighter weight, and perhaps would be useful in developing a monitoring tool if, as in the scheduler/resource interface, it could offer multi-response updates for when resources go up/down.

**Comment by dongahn** [comment]
> Oh yeah, one last use case---it could replace the FLUX_TREE_NNODES, FLUX_TREE_NCORES_PER_NODE, and FLUX_TREE_NGPUS_PER_NODE environment variables.

I have to think these environment variables should still be useful. There would be advanced API users like you but there would be shell users who rather want to rely on module calls, JSON parsing and other APIs. 

The current problem is: flux tree doesn't automatically calculate this but rely on the user-provided input. That can be made better like Issue #583 or similar can be implemented.

**Comment by jameshcorbett** [comment]
That's true, good point. But in that case, why not have every Flux instance automatically export those variables (removing the ``TREE`` part of course)? If it did, that would cover my most compelling needs---in a lot of cases I wouldn't really need to use the ``resource`` module and read its output.

**Comment by grondo** [comment]
> why not have every Flux instance automatically export those variables (removing the TREE part of course)?

Interesting idea! one issue with environment variables is they are always so *leaky*.
However, I wonder if a command like `flux resource setenv` would be helpful here, its output could be something like
```
FLUX_NNODES=4
FLUX_NCORES=16
FLUX_NGPUS=4
```
and could be run via
```
$ $(flux resource setenv)
```

or similar (e.g. how `ssh-agent` is typically started).

Note we will never be able to set "per-node" values of these environment variables since there is no guarantee of homogeneity...

**Comment by jameshcorbett** [comment]
I like that idea for shell scripts. However, I'm not sure how I could use that from Python. I could run ``flux resource setenv`` from my python script and capture its stdout, but that's not very pretty.

**Comment by grondo** [comment]
> I like that idea for shell scripts. However, I'm not sure how I could use that from Python.

Oh yeah, sorry, I didn't mean it would be used from python. For python we'd propose a high level function to get similar information at runtime, with access to full _R_ payload for more detail if needed.

We'll make sure to get your feedback on our initial prototype. Thanks!
