### ISSUE TITLE
flux-sched v0.9.0 release notes are needed

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-sched#671]
The naming conflict with the  `resource` module (at minimum) will prevent the most recent tag of flux-sched (v0.8.0) from working with the upcoming flux-core v0.17.0 tag.  Therefore we will need a flux-sched v0.9.0 tag to go with it.

I'll go ahead and create a milestone and link this issue to it.

**Comment by garlick** [comment]
@dongahn technically we need packages by the end of this week if we want to get in the next TOSS release.  Is that at all feasible?  What is the minimum amount of change we need to current master to end up with a tag you can live with for at least a month?

I had nominated hwloc 2 support but maybe that's not a huge deal - this is more about the TOSS 3 release cycle than TOSS 4 I suppose.

**Comment by dongahn** [comment]
@milroy and I are shooting for this but it is less likely we will get the full resource integration work landed into the current master.

> What is the minimum amount of change we need to current master to end up with a tag you can live with for at least a month?

If @milroy and I have reasonable PRs by the end of Wed, we should plan to put a tag at the current master and release it for TOSS.

**Comment by garlick** [comment]
What would be the downside if we were to tag anyway if the PR's don't make it?

There is a lot of change in flux-core that we'd like to get out to users.

**Comment by dongahn** [comment]
> What would be the downside if we were to tag anyway if the PR's don't make it?

For TOSS3, I don't see much downside. Fluxion should still be functional. It is just that this version will not be the one that will be tested on fluke.

**Comment by grondo** [comment]
To be clear, I read @dongahn's response as "go ahead and tag current master as v0.9.0"

**Comment by grondo** [comment]
Ok, I will push a v0.9.0 tag after doing some sanity checks
