### ISSUE TITLE
FAIL: t1001-qmanager-basic.t 4 - qmanager: basic job runs in simulated mode

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-sched#687]
I got the above failure in the github worflow build of fluxion for a flux-core PR flux-framework/flux-core#2992.  The test is
```
test_expect_success 'qmanager: basic job runs in simulated mode' '
    jobid=$(flux job submit basic.json) &&
    flux job wait-event -t 2 ${jobid} start &&
    flux job wait-event -t 2 ${jobid} finish &&
    flux job wait-event -t 2 ${jobid} release &&
    flux job wait-event -t 2 ${jobid} clean
```
Unfortunately, no other clues were available in the raw logs.  I don't think it would be related to the PR.  Maybe the 2s timeout could be increased?

**Comment by dongahn** [comment]
2s is a pretty decent timeout for this type of operations... You could increase it a bit but I am afraid there might be something else going on... Do you have any idea at what event this gets timed out?

**Comment by garlick** [comment]
Sorry there wasn't any other data available in the raw log.  I'm seeing some other odd timeouts in travis today so maybe it's just another bad day in the cloud!

**Comment by grondo** [comment]
@dongahn, just fyi - we have been increasing these types of timeouts 5-10 fold in flux-core to reduce false failures on busy systems -- e.g. travis-ci where your test container is sharing with who knows how many other test builds on the same system.

Really the timeout should be viewed as a way to detect a hung test, not detecting slowness since we can't control the environment in which test cases execute.

**Comment by chu11** [comment]
I hit in #681 as well, running `make -j16` on a TOSS system.

**Comment by dongahn** [comment]
FYI -- on a very rare occasion, I hit the same error even with `-t 10` change on my Mac running docker

```
FAIL: t1001-qmanager-basic.t 4 - qmanager: basic job runs in simulated mode
#
#           jobid=$(flux job submit basic.json) &&
#           flux job wait-event -t 10 ${jobid} start &&
#           flux job wait-event -t 10 ${jobid} finish &&
#           flux job wait-event -t 10 ${jobid} release &&
#           flux job wait-event -t 10 ${jobid} clean
#
```

I wonder if there is something related to how the jobspec was generated
```
test_expect_success 'qmanager: generate jobspec for a simple test job' '
    flux jobspec srun -n1 -t 0:1 hostname | exec_test > basic.json
'
```
