### ISSUE TITLE
Need better mapping/scheduling between tasks and nodes/cores

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-sched#69]
This was discussed a bit as part of #58, but I wasn't sure if a new issue has been created for this. As is, even if you launch 4 brokers, and then submit each job requiring 2 nodes back to back to back (e.g., my stress case), sched maps these 2-node jobs only to the first two ranks, never using the other two ranks.

This is just to discuss if there are some better mapping/scheduling that sched can do as a short-term improvement? 

@lipari: what is the semantics of `find_resources` and `select_resources` of the `schedplugin1`  plugin? Does it simply treat all of the resources as shared and grab the first available resources regardless they have running jobs? Are there any other scheduler plugins in the works with more smarts? 

Also, if there have been some updates to `wreckrun` with respect to job-to-resource mapping, it seems worthwhile to match that in the `sched-flux` as well. If wreckrun launches jobs back to back what is the current semantics? Anyone has issue numbers that capture some of these questions, mind listing the numbers here?

**Comment by grondo** [comment]
`flux-wreckrun` itself currently ignores actual resources and distributes tasks evenly across *ranks* when running without `sched` (see `alloc_tasks_hack`). This code was only meant as a stand in for actual resources assignment when run with `--immediate`, but when `sched` was removed from core it became the default.

`wrexecd` simply checks `lwj.<id>.rank.<rank>.cores` and launches that many tasks on the current rank. A user of the `wreck` service outside of `flux-wreckrun` could assign those as they see fit.

Thus, if `flux-wreckrun` launches jobs back to back, in the default mode, it will run two identical jobs on the same two ranks. Current thinking is that we shouldn't spend too much time fixing up wreck prototype at this point, but if there is something quick we need to get real work done I am not opposed to that. But clearly, at this point `flux-wreckrun` or any other front-end tool won't be able to reliably tell which resources to pick to avoid overlap. We need some sort of scheduling or resource update/query support for that.

**Comment by dongahn** [comment]
Thanks @grondo. Yeah we need scheduling and sched is supposed to do that, filling the right information into  '...rank.cores'


I think a part o the problem is that I often use a rdl file that doesnt acrurately describe the resources under the bootstrap environment. 

I think we should reinvested this after we have the multiple RDL reader option implemented, which is captured in #33 and #58.

I don't know if anyone is looking at this currently but this seems a pretty interesting item to look at if I can have some spare time.

BTW I recently had a chance to look at hwloc, I tend to like their abstraction and data model.

**Comment by lipari** [comment]
@dongahn, just to complete the picture on the sched side, the code will earmark allocated resources and find/select resources that are not allocated for subsequent jobs.  There is currently no task awareness in flux-sched.  What it searches for and selects are the aggregate resources, i.e., the product of task count and shard definition.  At this point, it expects wreck to launch the tasks across those resources, and as @grondo explained, this ability is not yet implemented.
A future enhancement to sched (or at least a specific sched implementation) will be to support the task mapping request as discussed in [Issue 54](https://github.com/flux-framework/flux-core/issues/354) and the future RFC 10.  It would select the resources and then pass the instructions to the task launcher:  launch rank 0 on resource set x0,y0,z0, rank 1 on set x1,y1,z1, etc.

**Comment by dongahn** [comment]
@lipari, thank. This sounds all good. I agree the task mapping is a future enhancement. But the issue I hit in #58 is a bit different. 

Say, you have a 2-node flux instance. Say, you schedule two jobs each with 1 node back to back and our plugin selects and assigns 1 district node through RDL to each job. But these jobs are currently launched only into the first node. So in a sense, the RDL selection is ignored. 

As mentioned above, I believe the multi-reader option will improve ways to make RDL consistent with the Flux instance resources under the bootstrapping environment. But then, I believe there is some modifications we need to make to the scheduler framework service to assign jobs to the right broker rank(s). I think I understand the path forward so I will take a look at these when I come back.

**Comment by lipari** [comment]
Understood.  The existing logic for what you describe is implemented very crudely in schedsrv.c's 'build_contain_req()' and 'build_contain_1node_req()'.  As you can see the 'n' index always starts out at 0.  This will have to be fixed/enhanced at some point.

**Comment by lipari** [comment]
Here is a summary of the scheduler, JSC, and wrexecd processing:
* sched reads its schedule-able resources from its rdl-conf= option which specifies the file that contains a description of the resources using the Lua format.  These resources no longer have to reflect the actual resources of the enclosing instance (i.e., those identified by resource-hwloc module).
* sched reads in jobs submitted by flux-submit and finds and selects nodes and cores to satisfy the job's request.
* sched serializes the selected resources and conveys them to the JSC's using the jsc_update_jcb_obj(JSC_RDL).  However, all that does is record these resources to the KVS job entry.  It doesn't affect where the tasks get launched.
* sched uses a second call to the JSC to convey the nodes and cores:  jsc_update_jcb_obj(JSC_RDL_ALLOC).  This is where everything becomes rank 0 based.  There is no attempt to assign a rank id that correlates to the offset of the allocated node from the first node of the schedule-able resources.
* On receiving this second call, the JSC records to the KVS lwj entry how many tasks to launch on each rank, again starting with rank 0.
* wrexecd reads this value and launches the requested number of tasks on each rank.

So, what needs to change?  Well, we've already identified in [Issue 61](https://github.com/flux-framework/flux-sched/issues/61) a requirement to input the schedule-able resources from alternate sources and validate them against the actual resources of the enclosing instance.  But in addition, I think the following enhancements are needed:
* Modify the JSC's jsc_update_jcb_obj() API to specify the task placement more precisely: task 0 on node x, core y, task 1 on node x core z, etc.  Obviously we'll ultimately need to convey the full breadth of options described in the forthcoming RFC 10.
* Modify the lwj KVS entry to also reflect this task placement, not just the number of tasks on each rank.
* Create a wreck replacement which launches tasks based on this newly expanded, KVS job spec.

Finally, there is the question of the resources the JSC needs to manage.  How should it reconcile the resources it receives from its API against the actual resources of the enclosing instance (resource-hwloc)?  If the scheduler tells it to allocate ipa5 to job 6 and the Flux instance is running on cab, this should be an error, right?  (Let's ignore for the moment how we will support fake resources and job runs across resources that don't physically exist).

**Comment by grondo** [comment]
> sched reads its schedule-able resources from its rdl-conf= option which specifies the file that contains a description of the resources using the Lua format. These resources no longer have to reflect the actual resources of the enclosing instance (i.e., those identified by resource-hwloc module).

It should perhaps be an error if the resources known to sched are not a subset of the resources on which the instance is running, applied to a subset of *types* of resources (configurable, but starting with at least Nodes and Cores). This could be disabled for simulation and testing.

Given that all our near-term milestones deal with launching flux instances under other RMs, I would say that a solution for #61 is probably increasing in priority. There should be an option for a scheduler to forgo the Lua rdl config and instead read directly from resource-hwloc or via a translator to some common syntax. Perhaps this could be *supplemented* with a smaller, site-wide Lua rdl.conf for resources that aren't discoverable via hwloc.

> Create a wreck replacement which launches tasks based on this newly expanded, KVS job spec.

The wreck replacement will have an entirely new kvs schema. For now, we could replace what wreck currently does with something simple that describes generally where to place each task (effectively this would be the task slot description).

Actually it may be that the given the rfc 10 job spec + serialized rdl for a job, the launcher can create the "slot" for any task in the job. This might help cut down on kvs per-program size.

**Comment by dongahn** [comment]
@lipari: thank you for the analysis. This agrees with what I found as well. 

If the rdl Lua file is not consistent with the resources of the enclosing instance, this should be an error. We need to define the right semantics when this happens. One option is, sched perhaps  posts a warning message about this inconsistency and go with the next source, ignoring the Lua description... We can define the right precedence of sources here. 

I agree with @grondo, we should give a good priority for this one. If nothing else, this will help beefing up automating scheduler testing. 

Assuming this problem is solved, we also need a way to map a resource to the broker rank that owns it. For example, given ipa4 allocation, sched needs a way to convert this into the broker rank (which is running on and managing ipa4) and write to the core count to use to the right kvs directory through JSC. Currently, this connection is not made, and that's a source of the issue. 

Now, because we want to be able to handle the multi-broker-per-node case, hostname alone will not give us all the right mapping. So at least for the bootstrap case, we can perhaps describe the resources in terms of the ranks instead of hostnames. And if we in particular pin each broker to a distinct set of cores (or even hardware thread) and also an amount of memory, perhaps such a rank-based description should just work. One exception is when we have more brokers than the number of hardware threads. But will we ever care about this case? 

Now, the actual mapping between a task and a core (or hardware thread) is something we should discuss further.  sched needs to understand how to interpret the job spec and write the mapping information to the remote execution service. Once the mapping information is convey to the remote execution service, all it has to is enforcing/binding them...

I propose you and I  meet and discuss how we divide the works. 

For now, sched can simply write the number of cores per rank to use ignoreing the actual mapping between a task and task slot.

**Comment by dongahn** [comment]
On a second thought, the rank-based resource description won't work for the hierarchical case. It seems  a resource-to-rank mapping service would be a better one.

**Comment by dongahn** [comment]
FYI -- so that you know, I will be working on resource-to-rank mapping techniques etc to tackle the issues described in this ticket. If I need some discussion, I will create a new issue or issues.
