### ISSUE TITLE
build: configure requires python development packages, but build doesn't

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-sched#710]
The flux-sched build does not appear to require python development packages to be installed, but `configure` fails if they are not installed. It seems like we could remove the unnecessary call to `AX_PYTHON_DEVEL` in `configure.ac`, thereby removing the need to install python3-devel when building packages (for example)

**Comment by grondo** [comment]
Also, does flux-sched really require python yaml package?

**Comment by dongahn** [comment]
@SteVwonder can chime in. I have no clue sorry.

**Comment by SteVwonder** [comment]
> The flux-sched build does not appear to require python development packages to be installed

I do not know with certainty, but my guess would be no, we don't need the development packages in flux-sched.

> Also, does flux-sched really require python yaml package?

It does need the python yaml package for [`flux-ion-resource.py`](https://github.com/flux-framework/flux-sched/blob/master/t/scripts/flux-ion-resource.py)
