### ISSUE TITLE
qmanager: let flux module load return before synchronous fluxion resource RPC

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-sched#712]
flux-framework/flux-core#3063 proposes to change the libschedutil API to allow the scheduler to start up asynchronously.  Currently, synchronous calls are made
1) fluxion-resource module to resource.acquire
2) qmanager to fluxion-resource
3) qmanager to job manager

The end goal is to allow `flux module load` of the scheduler module(s) to return before resources are acquired so that we can boot the cluster in an incremental fashion.

There is a small overview of the new API usage in the description of flux-framework/flux-core#3063

Let's focus this issue on qmanager initialization.  It should go something like this:
* call `scheudtil_create()` with `ops->resource_acquire` set to NULL
* send request to `sched-fluxion-resource.notify`
* enter reactor
* on first notify response, call `schedutil_start()`
* `ops->hello()` will be called zero or more times to get _R_ for running jobs
* `ops->ready()` will be called once all of those jobs are processed.  Call `schedutil_ready()`
* `ops->alloc()`, `ops->free()`, and `ops->cancel()` requests will be received as before

The main change is that what used to happen before entering the reactor now happens afterwards, and the sequence is triggered by the first notify response from sched-fluxion-resource.  After that libschedutil takes care of the synchronization in the reactor.

Edit: #700 was a PR (withdrawn) to implement this in qmanager, before #694 was merged.
Note that since then I noticed the `ready_cb()` in that PR had the wrong type for its "context", and I added a `flux_t *` argument to the ready prototype, which makes it look like all the other callbacks, and helps in this situation.

**Comment by garlick** [comment]
Renaming issue to reflect the real goal, which can be achieved much more simply by calling `flux_module_set_running()`, once flux-framework/flux-core#3104 is merged.

**Comment by dongahn** [comment]
Thanks @garlick. Sorry the other proposal didn't work out. 

The first question is the impact of this on the test cases. Presumably there would be test cases that assume fluxion finished up its startup when `flux module load` returned. But even with the initial proposal, we couldn't get around addressing these issues. So this seems far less disruptive.

**Comment by garlick** [comment]
No problem - this is far less disruptive so I'm all for it.

We'll have to see about test fallout.   In general, requests that arrive while the scheduler is still initializing (synchronously) and has not yet entered the reactor should just queue up until initialization completes and the reactor is entered, so I'm hopeful that fallout will be minimal.

**Comment by dongahn** [comment]
> We'll have to see about test fallout. In general, requests that arrive while the scheduler is still initializing (synchronously) and has not yet entered the reactor should just queue up until initialization completes and the reactor is entered, so I'm hopeful that fallout will be minimal.

Yes, that is my hope too!
