### ISSUE TITLE
Ranked JGF

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-sched#717]
Right now, the JGF reader explicitly forbids ranks != -1 in the JGF (thanks @milroy for calling that out).  I presume this is a fail-safe to prevent ranks from a parent instance from leaking into a resource DB and causing issues.

Having rank support in JGF would be nice for testing as well as for an L2 demonstration that I'm working on.

Are we OK with pulling that restriction back?  Maybe we can leave it in place by default, but allow it to be disabled with a flag/configuration option?

**Comment by dongahn** [comment]
Hmmm. I will take a look, but the JGF reader is currently used to reconstruct a job's allocation state and I don't know why it would reject `rank != -1`.

**Comment by SteVwonder** [comment]
Maybe I misunderstood @milroy in his slack message.  This is the particular line that he called out: https://github.com/flux-framework/flux-sched/blob/ae764152f89b2d2763e679a94f5ed8140c5051d8/resource/readers/resource_reader_jgf.cpp#L784

**Comment by dongahn** [comment]
What is not supported in `unpack()`  within our JGF reader is when you want to unpack a subgraph in JGF to a specific rank. If `rank == -1`,  the reader should  unpack the JGF into the resource graph data store ok and the rank encoded in the JGF will be used. 

Given that the `sched_fluxion_resource` will create the graph data store using [reader::load](https://github.com/flux-framework/flux-sched/blob/ae764152f89b2d2763e679a94f5ed8140c5051d8/resource/store/resource_graph_store.cpp#L36) and from [its method declaration](https://github.com/flux-framework/flux-sched/blob/ae764152f89b2d2763e679a94f5ed8140c5051d8/resource/store/resource_graph_store.hpp#L71), rank is implicitly initialized as -1, I think this should work out of box in theory. I would just try a simple case for testing and see what happens.

**Comment by dongahn** [comment]
Is this still a problem?

**Comment by SteVwonder** [comment]
The job-shell staging tests in https://github.com/flux-framework/flux-sched/pull/743 use a ranked jgf for their input, and that works AFAICT.  So I think this issue can be closed.  Thanks @dongahn!
