### ISSUE TITLE
job-shell-plugin: data staging

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-sched#725]
As part of supporting multi-tier storage systems, we will need a job-shell plugin that can initiate a transfer of data from the parallel filesystem to another tier (e.g., node-local SSD).  A strawman proposal for the specification of data staging within jobspec can be found here: https://github.com/flux-framework/rfc/issues/204.

This plugin can be broken up into a few pieces:

1. Storage mountpoint discovery
   - Pre-determined/configured locations (e.g., `/p/lustre1`, `/l/ssd`, `/mnt/ssd/$USER`)
   - Determined by environment variable (e.g., `$BB_PATH`)
   - Determined by Linux device ID (e.g., `249:0` which is mounted at `/l/nvme0`)
2. Data Movement
   - Simple CLI: (e.g., `cp`, `dcp`, `rsync`)
   - Vendor API (e.g., `bbapi`, `dw`)
3. Staging completion notification
   - Run as a blocking pre-job task
   - Run as an async pre-job task, create a job-shell service that responds when movement complete

**Comment by dongahn** [comment]
@SteVwonder: I know the initial work has been landed. I will close this if you need, you can reopen or create a new one w/ a more focused task..
