### ISSUE TITLE
Issues building on linux-rhel7-power9le with Spack (GCC 10.2.0)

### ISSUE THREAD

**Issue by stmobo** [flux-framework/flux-sched#732]
This is a followup to flux-framework/flux-core#3133 ; after resolving that issue (which occurred while building `flux-core`), I immediately ran into further problems building `flux-sched@master+cuda`. As with the prior linked issue, I'm using GCC 10.2.0, installed via Spack, on a `linux-rhel7-power9le` system.

The build errors I'm getting this time seem to be within templated C++ code, so I'm not going to copy the error text in the issue body; instead, I have the Spack build log here: [spack-build-out.txt](https://github.com/flux-framework/flux-sched/files/5106461/spack-build-out.txt)

The exact spec that is failing to build is `flux-sched@master%gcc@10.2.0+cuda`.

**Comment by dongahn** [comment]
@stmobo: I believe this is the same issue as https://github.com/flux-framework/flux-sched/issues/300: the version of GCC you are using doesn't like some of the Boost graph code. 

You should be able to work around this by adding back the lines that were removed from this commit: https://github.com/flux-framework/flux-sched/pull/697/commits/24a9c53c5b842d71bc59be3c0ecb6059b4e645a2
