### ISSUE TITLE
Deserialized id and name not consistent.

### ISSUE THREAD

**Issue by surajpkn** [flux-framework/flux-sched#74]
There seems to two not-so-important issues with serialize/deserialize RDL. 

1. Serialization does not include any of the job's ids. - Easily solved by adding one line to include an id to `resrc_to_json()`. Where this is important is when resources are passed down to child instances, they need to have consistent ids. 

2. The resource name is wrong after deserialization. 
Example:  resrc->name = hype201, id=201. 
Serialization (including id): "name" : hype201, "id" : 201
Deserialzaiton: resrc->name = hype201201, id = 201

The id is concatenated with name. Thats of course because the deserialization code uses the same function that generates resources from the conf file. 

This is not important, but I would just like to point it out. `resrc_new_from_json()` makes that concatenation. It may be a good idea to not do such a concatenation inside `resrc_new_from_json()` so that it stays generic. For the purpose of loading RDL from file, the json object passed to `resrc_new_from_json()` can be modified to already consist of the right name with the concatenation.

**Comment by lipari** [comment]
I need to understand item 1 better.  Currently the serialized resources are stored in the kvs under the job's id.  It seems redundant to add the job ids to the items serialized.  If you are needing to attach the allocated job ids to the serialized resources, can you just adding them to the json object:
```
        if (zhash_size (resrc->allocs)) {
            JSON jallocs = Jnew_ar ();
            size_t *size_ptr = zhash_first (resrc->allocs);
            while (size_ptr) {
                JSON jobo = Jnew ();
                Jadd_int64 (jobo, "job", *size_ptr);
                json_object_array_add (jallocs, jobo);
                size_ptr = zhash_next (resrc->allocs);
            }
            json_object_object_add (o, "allocs", jallocs);
        }
```
I will fix item 2.

**Comment by surajpkn** [comment]
@lipari I am so sorry I messed up item 1. What I actually meant was node's ids and not job's ids.

**Comment by lipari** [comment]
The node id is listed under the "name" key:
```
lwj.1.rdl = [ { "type": "node", "name": "hype201", "size": 1, "children": [ { "type": "socket" ...
```
Where else should the node id be?

**Comment by surajpkn** [comment]
Sure. But I just assumed concatenating id to non-number name was only to create the hostnames right in these configs we use. If thats the very design, it suffices of course. 
Nevertheless, I include the id key in serialization to just ease its extraction.

**Comment by lipari** [comment]
@surajpkn, take a look at the changes present in the PR I just created.  I not only separated the name into the separate name and id components (which fixed the de-serialization), I added the path and uuid components to the items serialized.

**Comment by dongahn** [comment]
@lipari and @surajpkn, should this be closed with merging of #74?

**Comment by lipari** [comment]
yes, if @surajpkn agrees.

**Comment by surajpkn** [comment]
Yes I agree.
