### ISSUE TITLE
Update Rv1 writer to emit execution.nodelist instead of using "node" key in R_lite

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-sched#753]
There is a pending change in flux-framework/rfc#265 that will allow an array of hostnames to be placed at the `.execution.nodelist` key in Rv1 as a more compact alternative to adding the hostname to the `node` key of each rank entry in `R_lite`. The arguments for this approach are discussed in the referenced PR.

The fluxion Rv1 writer should be updated to write the nodelist array instead of `node` key. We can then make this key mandatory which will help tools in displaying hostnames instead of/in addition to ranks.

**Comment by grondo** [comment]
flux-framework/rfc#265 has been updated to change Rv1 such that the `.execution.nodelist` key is now required, and  the `node` key of `R_lite` entry is removed.

**Comment by dongahn** [comment]
@grondo: I will look into this in the next few days... Sorry it has taken so long.

**Comment by grondo** [comment]
No problem. We realized what we really want is to support a [RFC 29 Hostlist](https://flux-framework.readthedocs.io/projects/flux-rfc/en/latest/spec_29.html) under the `nodelist` key, so I've been working to add a `libflux-hostlist` library to flux-core (not quite ready yet)

**Comment by dongahn** [comment]
@grondo:

Is the idea is to create a host list in the current `nodelist` format with no compression and then use functions within `libflux-hostlist` to compress it? Or `libflux-hostlist` should be used for the intermediate steps needed to produce `nodelist`? What is your plan for `sched-simple`?

**Comment by grondo** [comment]
I think the idea is that `nodelist` will be an [RFC 29 Hostlist](https://flux-framework.readthedocs.io/projects/flux-rfc/en/latest/spec_29.html), and therefore any reader will need to be able to parse `nodelist` into a list of hosts (or at least map rank to hostname), and `libflux-hostlist` can *at least* be used for that purpose.

It also makes sense for any emitter of Rv1 to encode `nodelist` in as concise a format as possible, and `libflux-hostlist` could be used to transform a list of hosts into a hostlist with a chance of very good compression. This what we'll use for `sched-simple`.

However, `"foo1,foo2,foo3,foo4,foo5"` conforms to RFC 29 as does `"foo[1-5]"`, so you can emit a simple comma separated list of hostnames and it would still be a valid `nodelist` readable by `hostlist_decode(3)`.

**Comment by dongahn** [comment]
@grondo: 

Yes this really is a good optimization. I was just asking this to see if I want to wait until `libflux-hostlist` is merged or just move ahead and emit the host names in the current uncompressed format and then use `libflux-hostlist` when it becomes available to compress the list as the last step.

This would be a bit different from another scheme whereby I use `libflux-hostlist`  more deeply for each "intermediate merge" of hostnames. Probably not worthy to consider this for now...

**Comment by grondo** [comment]
Either way could work I think. The update to RFC 20 allows `nodelist` to be an array of RFC29 hostlists. An array of hostnames satisfies that so I think either way is ok.

**Comment by dongahn** [comment]
This can be done in 3 steps:
- Introduce `execution.nodelist`, and instead of emitting each "node" key into `execution.R_lite`, emit it into that this district list.
- Have the final condensing step (that is, when all individual keys were emitted into `R_lite` and `nodelist`
1. Compress `R_lite` (this will make `R_lite` same as or similar to one emitted by `sched-simple`)
2. Compress `nodelist` -- when `libflux-hostlist` is merged to flux-core.
