### ISSUE TITLE
Need Rv1 reader for Fluxion

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-sched#754]
In flux-core we're trying to transition "resource discovery" away from the requirement for `flux hwloc reload`, which currently requires all possible ranks to be online.

Our current plan to move forward is to continue to use Rv1 as a stand-in for more fully featured R (Rv2).
The `resource.acquire` protocol will be updated to use an R object instead of the current `resource.hwloc.by_rank` object. 

The current dynamic resource discovery will be replaced with the following for the given scenarios:

 * system instance (boot from config): the core `resource` module will emit _R_ based on configuration (e.g. bootstrap config can be used to map ranks to hostnames, and a simple R_lite like format can be used to describe expected resources on each rank)
 * flux-in-flux: the core `resource` module will fetch Rv1 from the parent instance for its job and use this object in `resource.acquire`
 *  flux under foreign RM: requires fallback to dynamic resource discovery via hwloc

In order for the above to work though, Fluxion will need to be able to initialize via Rv1 instead of directly using
hwloc XML. Therefore, we wanted to get some feedback and discussion from the sched developers first.

Since Fluxion can emit full JGF in Rv1 `scheduling` key, it seems like the flux-in-flux case can be handled easily.

For the system instance case, we may need a tool that can generate a JGF config file that can be embedded in Rv1 emitted by the core `resource` module, so that Fluxion can initialize the first time without waiting for hwloc XML to be populated.

For a job running under a foreign RM, the core `resource` module will not be able to emit the `scheduling` key of Rv1, since it will not have a method to construct JGF from `resource.hwloc.by_rank`. However, since the resource discovery has fallen back to `flux hwloc reload`, all hwloc XML will be available in the KVS and so Fluxion could initialize the same way it does now.

How does this sound as a first step? Would it be feasible to write a Rv1 reader for the Fluxion resource module that could work in the cases listed above?

**Comment by dongahn** [comment]
> Since Fluxion can emit full JGF in Rv1 scheduling key, it seems like the flux-in-flux case can be handled easily.

This is very important to get it right as the nesting is one of the most important feature for Flux as the workflow enabler. I believe this will require some discussion and work. 

There will be some information like the broker ranks that need to be discarded and re-resolved to the child instance execution target name space. If nothing else, we may need a solution to create this "remapping" scalably. 

The other question would be the resource ID space.  @grondo and @SteVwonder: the most straightforward way would be for the nested Fluxion to use the IDs of core and GPU as seen by the parent Fluxion. Will that pose any issues to the remote execution service of the nested instance at all? (e.g., `CUDA_VISIBLE_DEVICE`). 

I will try to come up with a simple example to reason about this space a bit more concretely.

**Comment by dongahn** [comment]
> For the system instance case, we may need a tool that can generate a JGF config file that can be embedded in Rv1 emitted by the core resource module, so that Fluxion can initialize the first time without waiting for hwloc XML to be populated.

@SteVwonder and @grondo: I have had the flood of emails in the last few weeks. But I might have seen some more discussions in or around this topic. I will try to find them, but it will be very helpful if someone can put some links if there we related discussions.

**Comment by dongahn** [comment]
> For a job running under a foreign RM, the core resource module will not be able to emit the scheduling key of Rv1, since it will not have a method to construct JGF from resource.hwloc.by_rank. However, since the resource discovery has fallen back to flux hwloc reload, all hwloc XML will be available in the KVS and so Fluxion could initialize the same way it does now.

This should be okay. This is turtles all the way. If `scheduling` doesn't exist, Fluxion will assume it is the first baseline turtle and get to the raw hwloc data.

**Comment by dongahn** [comment]
We need to make progress for this. My plan is to implement this support and demonstrate this for a nested instance and tackle the generation of the initial RV1 for the system instance using a separate ticket.

**Comment by dongahn** [comment]
PR #787 has the support.
