### ISSUE TITLE
rc1 tries to load sched-simple when it shouldn't

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-sched#761]
Under my docker development environment, I get the following error message:

```console
ahn1@52e3a9734ef1:/usr/src$ flux start -s 2
2020-10-07T18:41:10.416659Z sched-simple.err[0]: resource.acquire failed: Device or resource busy
2020-10-07T18:41:10.417391Z sched-simple.crit[0]: fatal error: Device or resource busy
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.ails.
```

This isn't a fatal error at all because the resulting flux instance is fully functional:

```console
ahn1@52e3a9734ef1:/usr/src$ flux module list
Module                       Size Digest  Idle  S Service
job-exec                  1261336 7ABCCE5    8  S
job-info                  1352408 2596E5F    8  S
aggregator                1092808 9224D7C    8  S
resource                  1179520 E8D0D81    8  S
sched-fluxion-resource   20318216 D7F254E    8  S
kvs-watch                 1259928 7FAD956    8  S
connector-local           1064816 27E907F    0  R
content-sqlite            1086384 D153640    8  S content-backing,kvs-checkpoint
barrier                   1076456 B551D0F    8  S
sched-fluxion-qmanager    4084280 6FF175C    8  S sched
job-manager               1356552 B297E67    8  S
cron                      1159296 5FB1538    0  S
kvs                       1538056 41EBB81    0  S
job-ingest                1191848 AC020E0    8  S
```

Talking with @grondo, this is pointing to rc1:

```bash
# Print module that has registered 'sched' service, if any
lookup_sched_module() {
    flux module list | awk '$6 == "sched" { print $1 }'
}

if test $RANK -eq 0 -a "${FLUX_SCHED_MODULE}" != "none" \
                    -a -z "$(lookup_sched_module)"; then
    flux module load ${FLUX_SCHED_MODULE:-sched-simple}
fi
```

For testing, I printed `flux module list` inside `lookup_sched_module` as well as inside the if statement. And I found that it doesn't report `sched-fluxion-qmanager` in `lookup_sched_module` while it does inside the branch.

So I suspect this is a race condition as we let fluxion return out of its `mod_main` before entering the reactor loop. Indicatively, this only shows up at size=2 or higher.

**Comment by grondo** [comment]
But to avoid a different race, `flux_module_set_running()` must be called after `flux_service_register` completes, and service registration _is_ done in schedutil.

Would it be enough to require that `schedutil_create()` be called before any other blocking work in schedulers?

**Comment by garlick** [comment]
As long as `schedutil_create()` precedes `flux_module_set_running()` AND `flux_reactor_run()`, the `sched` service is guaranteed to be registered upon `flux module load` completion.

The reason `flux_module_set_running()` was added is because `resource.acquire` is made synchronously.  That deadlocks unless we let `flux module load` return before `flux_reactor_run()`, because rc1 on rank 0 has to finish before resources on other ranks are "discovered" by the resource module.

It's not strictly required, but for convenience both schedulers don't call `schedutil_hello()` until resources are acquired, because that begins the onslaught of job requests, which would have to be set aside until resources are acquired.

I think your main point is that this confusing set of dependencies ought not to be exposed to every scheduler implementation.  I agree with that - it was where I was trying to go with #3063 (before the `flux_module_set_running()` complication was added).

**Comment by dongahn** [comment]
Thank you for the discussion. 

> I think your main point is that this confusing set of dependencies ought not to be exposed to every scheduler implementation.

I believe this is a necessary dependency created through the current architectural choice. Related services are implemented across different modules. At some point, we will want to revisit the issue of service dependency management, but I don't think the level of dependency for this is too high to require an immediate action. 

>  I agree with that - it was where I was trying to go with flux-framework/flux-core#3063 (before the flux_module_set_running() complication was added).

`flux_module_set_running()` is required for multiple (2) service modules and I wouldn't put this into a single library. IMHO it will be pretty difficult to satisfy all the requirements of third party modules which may use either or both service modules and managing multi-service dependencies this way feels a bit ad hoc.  

>  I don't think the level of dependency for this is too high to require an immediate action. 

In this particular case, my current trick is to move `schedutil_create()` into `qmanager`'s constructor: strictly speaking this is actually a resource acquisition and the module constructor is actually a better place to acquire the handle for schedutil anyway.

```diff
diff --git a/qmanager/modules/qmanager.cpp b/qmanager/modules/qmanager.cpp
index 218319ff..ac44c5e4 100644
--- a/qmanager/modules/qmanager.cpp
+++ b/qmanager/modules/qmanager.cpp
@@ -231,16 +231,6 @@ static int handshake_jobmanager (std::shared_ptr<qmanager_ctx_t> &ctx)
     int rc = -1;
     int queue_depth = 0;  /* Not implemented in job-manager */

-    if (!(ctx->schedutil = schedutil_create (
-                               ctx->h,
-                               &qmanager_safe_cb_t::jobmanager_alloc_cb,
-                               &qmanager_safe_cb_t::jobmanager_free_cb,
-                               &qmanager_safe_cb_t::jobmanager_cancel_cb,
-                               std::static_pointer_cast<
-                                   qmanager_cb_ctx_t> (ctx).get ()))) {
-        flux_log_error (ctx->h, "%s: schedutil_create", __FUNCTION__);
-        goto out;
-    }
     if (schedutil_hello (ctx->schedutil,
                          &qmanager_safe_cb_t::jobmanager_hello_cb,
                          std::static_pointer_cast<
@@ -425,6 +415,15 @@ static std::shared_ptr<qmanager_ctx_t> qmanager_new (flux_t *h)
         ctx = std::make_shared<qmanager_ctx_t> ();
         ctx->h = h;
         set_default (ctx);
+        if (!(ctx->schedutil = schedutil_create (ctx->h,
+                                   &qmanager_safe_cb_t::jobmanager_alloc_cb,
+                                   &qmanager_safe_cb_t::jobmanager_free_cb,
+                                   &qmanager_safe_cb_t::jobmanager_cancel_cb,
+                                   std::static_pointer_cast<
+                                       qmanager_cb_ctx_t> (ctx).get ()))) {
+            flux_log_error (ctx->h, "%s: schedutil_create", __FUNCTION__);
+            ctx = nullptr;
+        }
     } catch (std::bad_alloc &e) {
         errno = ENOMEM;
     }
```

**Comment by garlick** [comment]
Looks like the right solution @dongahn.
