### ISSUE TITLE
shell: confusing log from data staging plugin 

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-sched#777]
```
flux mini alloc -n1 -N1 -c2 -g2 ~/b.sh
0.093s: flux-shell[0]: Jobspec does not contain data-staging attributes. No staging necessary.
```

This message will be printed out for every job in production since staging is not supported just yet. Probably better not to print this.

**Comment by SteVwonder** [comment]
🤦 , yeah, that's not good or intended.  Sorry about that.  I'll add that to my list.
