### ISSUE TITLE
resource: traverser->run () behavior depends on edge iteration order

### ISSUE THREAD

**Issue by milroy** [flux-framework/flux-sched#783]
While creating CI tests for PR #775, I discovered some unexpected behavior of [`resource_reader_jgf_t::update_tgt_edge`](https://github.com/flux-framework/flux-sched/blob/3d568512c838e7653185a897eb910e6dc192ac31/resource/readers/resource_reader_jgf.cpp#L691).  

I was testing to make sure `update attach` functions as expected for JGF subgraphs with randomized vertex and edge orders.  I compared the behavior of adding a single node with 36 cores represented by a default-ordered JGF with the behavior of a randomized JGF.  Both have `contains` and `in` edges in the containment subsystem.  The default-ordered JGF works as expected, but the randomized JGF exits with an error when trying to update the `in` edge from vertex 1 to vertex 0.  I printed the output to demonstrate:

```bash
resource-query> update attach t/data/resource/jgfs/elastic/node-add-test.json 1 0 3600
<cut for brevity>
364 84
8 84
84 8
1 8
8 1
0 1
1 0
{"graph": {"nodes": [{"id": "329", "metadata": {"type": "core", "basename": "core", "name": "core0", "id": 0, "uniq_id": 329, "rank": -1, "exclusive": true, "unit": "", "size": 1, "paths": {"containment": "/medium0/rack0/node3/socket0/c
<cut for brevity>
```

As compared to the randomized JGF:

```bash
resource-query> update attach t/data/resource/jgfs/elastic/node-add-random-test.json 1 0 3600
<cut for brevity>
349 84
84 362
335 83
1 0
ERROR: traverser run () returned error 
ERROR: update_tgt_edge: an edge into a root detected!
INFO: =============================
INFO: No matching resources found
INFO: JOBID=1
INFO: =============================
```
I can't figure out why the edge iteration order should matter.  @dongahn how should `resource_reader_jgf_t::update_tgt_edge` handle the situation with unordered (or randomized order) bidirectional edges?

**Comment by milroy** [comment]
I should note that in the randomized JGF, the 1->0 edge was reached near the beginning of the iteration, meaning that there were still many edges to update.

**Comment by milroy** [comment]
After further consideration the problem is in the implicit assumption of the sequence of `update_src_edge` followed by `update_tgt_edge` in [`resource_reader_jgf_t::update_edges`](https://github.com/flux-framework/flux-sched/blob/3d568512c838e7653185a897eb910e6dc192ac31/resource/readers/resource_reader_jgf.cpp#L732).  In the randomized JGF case, the edge 1->0 appears before 0->1 in the iteration.  This causes the `is_roots` map not to be cleared before reaching this line in `update_tgt_edge`: https://github.com/flux-framework/flux-sched/blob/3d568512c838e7653185a897eb910e6dc192ac31/resource/readers/resource_reader_jgf.cpp#L718

If this condition is met, is it necessary to throw an error and return -1, or could we just return 0 and skip updating the edge?

**Comment by dongahn** [comment]
Great testing! Let me look into that a bit.

**Comment by milroy** [comment]
I think a more robust solution would be to have a map with a bool value that indicates whether the edge has been added already.  Then the check in line 718 can just skip the edge (i.e. return 0) if it's already been added rather than throwing an error and returning -1.

**Comment by dongahn** [comment]
The JGF reader's `update()` interface detects root vertices (one root per each subsystem) and add so-called "virtual incoming edge" for those roots. This is required so that the traverser's DFV update code can find the starting root vertex for this DFV recursion.

The assume is there is no incoming edge into the root. Otherwise, it is not a tree (or forest of trees if you have multiple subsystems in the graph). 

https://github.com/flux-framework/flux-sched/blob/3d568512c838e7653185a897eb910e6dc192ac31/resource/readers/resource_reader_jgf.cpp#L718

 This code checks this assumption. Now, without testing it, it feels like it would be okay to relax this assumption and remove this check completely.

In any case, for the near-term use cases, the input JGF wouldn't have this condition at all -- no cycle. 

Could you remove this conditional statement and see if Fluxion is still happy?

**Comment by milroy** [comment]
> Could you remove this conditional statement and see if Fluxion is still happy?

I commented out the line and ran the CI tests.  They all passed.

> The assume is there is no incoming edge into the root. Otherwise, it is not a tree (or forest of trees if you have multiple subsystems in the graph).

This makes sense when the JGF only has `contains` edges (which has always been the case in the past), but now the subgraph getting attached and updated has `in` edges as well.  In the future we could create a new check that takes bidirectional edges into account, or we could make sure the `update ()` step only operates on a JGF with `contains` edges.

**Comment by dongahn** [comment]
> This makes sense when the JGF only has contains edges (which has always been the case in the past), but now the subgraph getting attached and updated has in edges as well. In the future we could create a new check that takes bidirectional edges into account, or we could make sure the update () step only operates on a JGF with contains edges.

Yeah. 

For now, though, it looks like you should proceed with the conditional removed.

**Comment by milroy** [comment]
> For now, though, it looks like you should proceed with the conditional removed.

Will do!  Should I also remove the code related to `is_roots` since this appears to be the only use for that map?

**Comment by dongahn** [comment]
It is used in `update_src_edge`, I think.

**Comment by milroy** [comment]
Ah, yes.  I'll just get rid of the check we discussed then.  Thanks!
