### ISSUE TITLE
docs: add breathe/exhale sphinx extensions for auto-gen C++ API docs

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-sched#789]
Once #772 is closed, we should add [breathe](https://breathe.readthedocs.io/en/latest/) and [exhale](https://exhale.readthedocs.io/en/latest/), which are two sphinx extensions that leverage doxygen to produce Sphinx/RTD compatible documentation.

**Comment by dongahn** [comment]
Hobbs plans to take a look at this per our today discussion with him and @jameshcorbett and @JaeseungYeom.

**Comment by wihobbs** [comment]
@jameshcorbett and I are discussing which subfolders should be included in the RTD documentation and plan to bring this up at coffee hour today. Currently, I plan to use the Doxyfile in `/resource` and add breathe/exhale under the `conf.py` file in `/doc`.

**Comment by wihobbs** [comment]
As a note to anyone trying this: flux-framework/flux-docs#51 describes in more detail what is needed here.
