### ISSUE TITLE
config changes for sched module

### ISSUE THREAD

**Issue by lipari** [flux-framework/flux-sched#8]
Many flux path variables need to be extended in order to run flux outside of flux-core.  The "start" and "load" Makefile targets in the flux-sched/sched directory automate path extensions so that the resulting "flux start" and "flux module load" commands work as expected.
Running straight flux commands out of flux-sched/sched require a mechanism similar to what is done with the makefile to augment path parameters.  Whatever we do to address this need should be applicable to future projects that will be built against flux-core.

**Comment by grondo** [comment]
closed by #440
