### ISSUE TITLE
sched module should set errno when exiting mod_main()

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-sched#81]
If the sched module is loaded without an rdl-conf option, it returns -1 from mod_main.  The broker code then does this
```C
if (p->main(p->h, ac, av) < 0) {
    err ("%s: mod_main returned error", p->name);
    goto done;
}
```
the `err()` function tries to decode errno and print it, but since it's not ever set by the sched module a residual one is picked up, e.g.
```
lt-flux-broker: sched: mod_main returned error: Bad file descriptor
```
I would just set errno = EINVAL in the !path case of `load_rdl()` so users don't see an error that throws them off course.

**Comment by lipari** [comment]
This advice was adopted in commit:  https://github.com/flux-framework/flux-sched/commit/93cbec8e95295b199182e8258b4a36dfa7ec6970
