### ISSUE TITLE
Reported rank does not necessarily match the host a job is running on

### ISSUE THREAD

**Issue by FrankD412** [flux-framework/flux-sched#816]
The `flux-sched` repo seemed like the right place for this, but we can move this elsewhere if that's not the case.

We found an issue where `flux jobs` was reporting an incorrect rank number for an associated job. During a recent run on Summit, we found that the hostname reported when executing a command via `flux exec` mapped to the incorrect rank when compared to the host that our workflow manager's log reported. What clued us in initially was that our workflow manager's logging was 14 minutes ahead of the current time.

Where Flux reported that the job was running:
```
(mummi_20201210) [fdinatal@login3]/gpfs/alpine/lrn005/proj-shared/Campaign3/roots/mummi_c3_20201223% flux jobs -a -c 1000000 | grep wfmanager
  fAsP8XSsBD fdinatal wfmanager.  R      1      1   1.843h 597
  f4HBYpnv47 fdinatal wfmanager. CA      1      1   13.65h 597
  f3uSHekfno fdinatal wfmanager. CA      1      1    30.1m 597
  f3QLCi8v4P fdinatal wfmanager. CA      1      1   46.91m 597
   fCUbGsr4o fdinatal wfmanager. CA      1      1   4.399h 597
   f2jwSgvKH fdinatal wfmanager. CA      1      1     2.4m 597
(mummi_20201210) [fdinatal@login3]/gpfs/alpine/lrn005/proj-shared/Campaign3/roots/mummi_c3_20201223% flux exec -r 1 hostname
a04n14
```

So we logged into `a04n14` and check the time which appeared correct (~11:22AM), nor could we find workflow manager processes on the node. If we check our workflow manager's log:
```
login1:mummi_c3_20201223/workspace $ grep hostname wfmanager.log
hostname = d30n07.summit.olcf.ornl.gov
```

So we `ssh` into `d30n07` and check the date:
```
[fdinatal@d30n07]~% date
Thu Mar 11 14:32:09 EST 2021
[fdinatal@d30n07]~% hostname --long
d30n07.summit.olcf.ornl.gov
```

End of the workflow manager log to find that it matches:
```
2021-03-11 14:32:32,211 - mummi.transformations.patch_creator.patchCreator:init:66 - INFO - Initialized PatchCreator: macro = p:[1000. 1000.] g:[2400 2400], patch = p:[30 30] g:[73 73]
2021-03-11 14:32:36,179 - mummi.ml.dynim.sampler_binned:compute_histograms_3d:67 - INFO - Computing bin indices for data = (9522321, 3)
```

and we found our missing processes (only a snippet):
```
fdinatal  94010  42667  4 14:27 ?        00:00:13 python /gpfs/alpine/proj-shared/lrn005/pilot2/mummi/mummi/scripts/run.wfmanager.py
fdinatal  94013  42667  4 14:27 ?        00:00:13 python /gpfs/alpine/proj-shared/lrn005/pilot2/mummi/mummi/scripts/run.wfmanager.py
fdinatal  94016  42667  4 14:27 ?        00:00:13 python /gpfs/alpine/proj-shared/lrn005/pilot2/mummi/mummi/scripts/run.wfmanager.py
fdinatal  94019  42667  4 14:27 ?        00:00:13 python /gpfs/alpine/proj-shared/lrn005/pilot2/mummi/mummi/scripts/run.wfmanager.py
```

So now, if rank 1 isn't `d30n07` where the workflow is actually running, then what rank are we actually on? A small manual binary search with `flux jobs` based on the fact the nodes are assigned in host alphabetical order:
```
(mummi_20201210) [fdinatal@login3]/gpfs/alpine/lrn005/proj-shared/Campaign3/roots/mummi_c3_20201223% flux exec -r 597 hostname --long
d30n07.summit.olcf.ornl.gov
```

The workflow manager is actually on rank 597 -- but `flux jobs` doesn't reflect that. The high level details:
- Running on 1000 nodes of Summit for 24 hours
- Using the Spectrum option
- Using the following version (unable to get a full print out because allocation ended):
```
(mummi_20201210) [fdinatal@login3]/gpfs/alpine/lrn005/proj-shared/Campaign3/roots/mummi_c3_20201223% flux version
commands:               0.19.0
libflux-core:           0.19.0
```

Please let me know if I can provide you any other information.

**Comment by SteVwonder** [comment]
> The workflow manager is actually on rank 597 -- but flux jobs doesn't reflect that.

For v0.19.0, the last column of `flux jobs` output shows the rank(s) that the job was run on:
```
lƒ(s=1,d=0) fluxuser@6aeeee72cf2e:~$ flux jobs -a
       JOBID USER     NAME       ST NTASKS NNODES  RUNTIME RANKS
    ƒ3mKXLVm fluxuser hostname   CD      1      1   0.058s 0
```

In your quoted output:
```
(mummi_20201210) [fdinatal@login3]/gpfs/alpine/lrn005/proj-shared/Campaign3/roots/mummi_c3_20201223% flux jobs -a -c 1000000 | grep wfmanager
  fAsP8XSsBD fdinatal wfmanager.  R      1      1   1.843h 597
  f4HBYpnv47 fdinatal wfmanager. CA      1      1   13.65h 597
  f3uSHekfno fdinatal wfmanager. CA      1      1    30.1m 597
  f3QLCi8v4P fdinatal wfmanager. CA      1      1   46.91m 597
   fCUbGsr4o fdinatal wfmanager. CA      1      1   4.399h 597
   f2jwSgvKH fdinatal wfmanager. CA      1      1     2.4m 597
```

The last column contains `597` for the rank.  Maybe you were looking at the other columns which represent the number of nodes and cores (both `1`)?  Or maybe I'm just misunderstanding what you are asking.

**Comment by FrankD412** [comment]
You're totally correct... wow, silly issue on my part.. haha

**Comment by SteVwonder** [comment]
No worries! Glad it was an easy fix :)
