### ISSUE TITLE
sched might need to work around zhashx resize bug

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-sched#821]
@chu11 found a bug in `zhashx_t` that causes it to be resized every time there is a hash collision and linked this to job throughput degradation over time (flux-framework/flux-core#3591).  We are exploring pulling in the class as a local library while the upstream fix percolates out to distro packages.

Since sched uses `zhashx_t` in the planner code, this might need to be addressed here too.

**Comment by chu11** [comment]
oh crap, i don't think I can fix this the same way we did in `flux-core`.  `flux-sched` is still GPL, not LGPL.

**Comment by chu11** [comment]
Ok, re-reading https://www.mozilla.org/en-US/MPL/2.0/combining-mpl-and-gpl/, I think we are safe as long as we don't combine code.  The MPL code has to stay isolated.  Is that other people's reading?

**Comment by garlick** [comment]
Yeah, that page doesn't seem to distinguish between LGPL and GPL, so I think we're alright.

Maybe we'll just want to go ahead with pulling in zhashx here too, but I have to ask - since sched is C++, and its use of zhashx is fairly minimal, would this be a good opportunity to convert to a "native" hash implementation (google search turns up`std::hash` and `boost::hash`)?

**Comment by dongahn** [comment]
Most of sched codes are c++ but planner and some other important subsystems are written in c. Still some TODOs to convert the whole thing to wean off of GPLs. All we need is to wean off of rbtree. Hard to find a good replacement. std::map uses a good RB tree underneath but I am not at all sure if we can bend it to use as our efficient search trees.

**Comment by chu11** [comment]
It appears to me that the code in flux-sched that uses zhashx is C so I elected to bring in zhashx in PR #822
