### ISSUE TITLE
Change default queue-depth to 32

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-sched#830]
Per https://github.com/flux-framework/flux-sched/pull/826#discussion_r625917462 with the new `delay scheduling` semantics and match-multi, we should consider changing the default queue depth small. It is currently 8192.

**Comment by garlick** [comment]
Just curious, what is the difference between setting the fluxion queue-depth to 32 and setting the job manager scheduler mode to limited=32?  In the latter case, the scheduler is only presented with alloc requests for the 32 highest priority jobs.

**Comment by dongahn** [comment]
Yeah this would primarily for `mode=unlimited`.

**Comment by dongahn** [comment]
It is on my TODO list to evaluate the queue-depth support provided by `job-manager`. My guess is this can help with this problem: https://github.com/flux-framework/flux-core/issues/3630. 

I vaguely remember there could be some potential implication of this when we hook in multi-factor priority plugin. Somehow I can't find the discussion thread...
