### ISSUE TITLE
Resource reading enhancements

### ISSUE THREAD

**Issue by lipari** [flux-framework/flux-sched#84]
This issue captures residual enhancements to the resource reader that were proposed in comments to [PR 79](https://github.com/flux-framework/flux-sched/pull/79) and [Issue 58](https://github.com/flux-framework/flux-sched/issues/58), but have yet to be implemented.
- read resources from a file specified in the kvs config directory (config.sched.rld-conf) instead of arguments to the sched module load command (https://github.com/flux-framework/flux-sched/issues/58#issuecomment-137787948)
- create a hwloc topology object from custom defined resources for testing instead of using the resources of the build system (https://github.com/flux-framework/flux-sched/pull/79#issuecomment-146197408)
- add consistency checking of the valid arguments ("rdl-conf", "in-sim", etc.) the sched module load command to ensure compatibility.
- find a reliable source for the cluster's name instead of peeling away the id from the first node [Issue 442](https://github.com/flux-framework/flux-core/issues/442)

**Comment by lipari** [comment]
The fourth bullet above has been addressed with an update to https://github.com/flux-framework/flux-sched/pull/79.  https://github.com/flux-framework/flux-core/issues/442 was also closed.

**Comment by dongahn** [comment]
I believe a bulk of the work is done by now. I know at least item 2 and 3 are done. @lipari, is 1 and 4 done? or If not, are they worth doing?

**Comment by lipari** [comment]
Item 4 was addressed and item 1 is no longer needed at this point.
