### ISSUE TITLE
CI fails for merge pull request

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-sched#847]
<img width="1177" alt="Screen Shot 2021-06-23 at 10 12 31 AM" src="https://user-images.githubusercontent.com/862123/123019532-9be2e880-d40b-11eb-913b-beee0b7d9de8.png">

**Comment by grondo** [comment]
Ah, this is my fault @dongahn. I forgot to add a similar fix to https://github.com/flux-framework/flux-core/pull/3717 to flux-sched (we need to skip the annotated tags step on master)
