### ISSUE TITLE
Compilation error from unsigned int to signed int comparison

### ISSUE THREAD

**Issue by ksuarez1423** [flux-framework/flux-sched#856]
Installing flux-sched version 0.16.0 via Spack with GCC 9.2.0 results in failure, due to an unsigned int and signed int comparison. While this would normally just be a warning, -Werror being in use in the compilation options of flux-sched when using GCC ensures it is taken as an error. 

While 0.16.0 is an past version, the lines of code and relevant datatypes causing the issue are identical in the repository as it currently stands.  The exact error occurs in a couple of the readers, with links here for the instances I get. Do I need to invoke Spack differently, or is this something that needs to be handled on the Flux side of things?

https://github.com/flux-framework/flux-sched/blob/edea1077c5b539aaf6f8e710265222c24f51dbd6/resource/readers/resource_reader_jgf.cpp#L300

https://github.com/flux-framework/flux-sched/blob/edea1077c5b539aaf6f8e710265222c24f51dbd6/resource/readers/resource_reader_hwloc.cpp#L285

**Comment by dongahn** [comment]
Ugg. Yes this depends on how strictly a C++ compiler and version checks those things.

**Comment by dongahn** [comment]
```c++ 
if ( remap_id > static_cast<uint64_t> (std::numeric_limits<int>::max ())) {
```

If you can patch the code as part of your Spack deployment, could you try the following?

**Comment by ksuarez1423** [comment]
> 
> 
> ```c++
> if ( remap_id > static_cast<uint64_t> (std::numeric_limits<int>::max ())) {
> ```
> 
> If you can patch the code as part of your Spack deployment, could you try the following?

I apologize for taking so long to respond -- after applying a patch like this, I was able to install flux-sched! Thank you!

**Comment by dongahn** [comment]
Great! Just out of curious, would it be possible to do a quick PR with this patch?

**Comment by ksuarez1423** [comment]
@dongahn I cannot compile master right now, but I've got a PR at #858 which should fix the issue if I wrote it correctly. A similar change definitely handled things on 0.16.0.
