### ISSUE TITLE
flux-sched: minor changes required for clang-12 and gcc-11

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-sched#877]
From my PR to update spack packages I got the following feedback: See https://github.com/spack/spack/pull/26840#issuecomment-949995031

> flux-sched needed a few changes to build with clang and gcc@11. I pushed this commit to this PR, ok for you?
> flux-sched: Fix build with clang and gcc-11
>
> clang doesn't have `-Wno-maybe-uninitialized`:
> use `-Wno-uninitialized` instead
> clang@12: needs `-Wno-defaulted-function-deleted`
> gcc@11: and clang@13 need changes which are good in general:
>   - resource/schema/sched_data.hpp: Need to use `nullptr` instead of `NULL`
>   - resource/planner/planner.h: Need to use `std::size_t`, not `size_t`

as reported by @bernhardkaindl

**Comment by grondo** [comment]
Not fixing this is causing issues getting spack packages accepted, we should try to get these simple changes into the next release perhaps.

**Comment by dongahn** [comment]
Ah... I will put this into our Nov milestone target. Should be straightforward to fix (though I haven't looked into details just yet).

**Comment by dongahn** [comment]
> resource/planner/planner.h: Need to use std::size_t, not size_t

Hmmmm. This doesn't seem to make sense since `planner.h` should be C.

**Comment by bernhardkaindl** [comment]
No, it should be C++:

It's a header file, only included from C++.

Just in case: The extension `.h` doesn't make the C++ to become a C compiler magically.
(BTW, there is only one .c file in flux-sched.)

Therefore it should be named `planner.hpp` and it should `#include <stdef>`, see below.

I'm guessing that you might have one or two computers around which will happily confirm it when you give them the job to verify:

This would even build a gcc-11.2.0 and then build the flux-sched master branch internal to spack, so can use the latest GNU or LLVM compilers without any side effects on your systems:
```
bin/spack install -v flux-sched@master %gcc@11.2.0

     426    In file included from /mnt/data/.bk/spack/.var/stage/kaindlb/spack-stage-flux-sched-0.19.0-wg6nd7xahjc5adcj4rdxeimmhabjvuyn/spack-src/resource/schema/sched_data.hpp:16,
     427                     from /mnt/data/.bk/spack/.var/stage/kaindlb/spack-stage-flux-sched-0.19.0-wg6nd7xahjc5adcj4rdxeimmhabjvuyn/spack-src/resource/schema/sched_data.cpp:11:
  >> 428    /mnt/data/.bk/spack/.var/stage/kaindlb/spack-stage-flux-sched-0.19.0-wg6nd7xahjc5adcj4rdxeimmhabjvuyn/spack-src/resource/planner/planner.h:186:1: error: 'size_t' does not name
             a type
     429      186 | size_t planner_span_size (planner_t *ctx);
     430          | ^~~~~~
     431    /mnt/data/.bk/spack/.var/stage/kaindlb/spack-stage-flux-sched-0.19.0-wg6nd7xahjc5adcj4rdxeimmhabjvuyn/spack-src/resource/planner/planner.h:16:1: note: 'size_t' is defined in h
            eader '<cstddef>'; did you forget to '#include <cstddef>'?
     432       15 | #include <stdbool.h>
     433      +++ |+#include <cstddef>
     434       16 |
     435    In file included from /mnt/data/.bk/spack/.var/stage/kaindlb/spack-stage-flux-sched-0.19.0-wg6nd7xahjc5adcj4rdxeimmhabjvuyn/spack-src/resource/schema/sched_data.cpp:11:
  >> 436    /mnt/data/.bk/spack/.var/stage/kaindlb/spack-stage-flux-sched-0.19.0-wg6nd7xahjc5adcj4rdxeimmhabjvuyn/spack-src/resource/schema/sched_data.hpp:30:24: error: 'NULL' was not dec
            lared in this scope
     437       30 |     planner_t *plans = NULL;
     438          |                        ^~~~
     439    /mnt/data/.bk/spack/.var/stage/kaindlb/spack-stage-flux-sched-0.19.0-wg6nd7xahjc5adcj4rdxeimmhabjvuyn/spack-src/resource/schema/sched_data.hpp:17:1: note: 'NULL' is defined in
             header '<cstddef>'; did you forget to '#include <cstddef>'?
     440       16 | #include "resource/planner/planner.h"
     441      +++ |+#include <cstddef>
     442       17 |
```

**Comment by bernhardkaindl** [comment]
This installs gcc-11 and LLVM/Clang-13 on Ubuntu:
```py
sudo apt install software-properties-common
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt update && sudo apt install gcc-11 g++-11

wget https://apt.llvm.org/llvm.sh
chmod +x llvm.sh
sudo ./llvm.sh 13
```
See: https://apt.llvm.org/

**Comment by dongahn** [comment]
Thanks @bernhardkaindl for your explanation and suggestions!

The planner is C API with an C++ implementation. I just tested with GCC 11 on ubuntu 20.04 and found it misses `#include <stddef.h>`. Adding this should fix the issue and I am putting together a PR.

**Comment by dongahn** [comment]
> clang@12: needs -Wno-defaulted-function-deleted

This was needed because 

> ../../qmanager/modules/qmanager_opts.hpp:66:22: error: explicitly defaulted copy assignment operator is implicitly deleted [-Werror,-Wdefaulted-function-deleted]

> ../../qmanager/modules/qmanager_opts.hpp:69:22: error: explicitly defaulted move assignment operator is implicitly deleted [-Werror,-Wdefaulted-function-deleted]

This happens because member `const std::string m_default_queue_name` has no copy or move constructor per `const`.

The proper fix should be just drop `const` from this member.
