### ISSUE TITLE
Migrate backfill scheduling support from the sched framework module to its own plugin.

### ISSUE THREAD

**Issue by lipari** [flux-framework/flux-sched#88]
The latest enhancements that added backfill scheduling were helpful and carefully done so as to not impact the existing FCFS operation.  However, the vision for the schedsrv framework service was to provide the foundation for a variety scheduling algorithms.  Backfill is the first such alternative algorithm to be developed.  This issue is to move backfill scheduling out of the sched framework and into its own plugin.

**Comment by dongahn** [comment]
This sounds good, @lipari! I look forward to pushing this ideas forward, along with  @SteVwonder and @surajpkn who actually have hands-on experiences of implementing the backfill algorithms.

**Comment by lipari** [comment]
Closed with the merge of [PR 91](https://github.com/flux-framework/flux-sched/pull/91)
