### ISSUE TITLE
Scheduling multiple jobs on the same node and resource states

### ISSUE THREAD

**Issue by surajpkn** [flux-framework/flux-sched#89]
At the moment, a node cannot be shared between jobs because as soon as a job is scheduled on a node, the state of the node resource is ALLOCATED. the match function looks only for IDLE resources and therefore, the node parent and its children (cores) of the resource tree will not be considered for scheduling. A simple fix would be to keep the state of the node resource as IDLE until all of its cores are ALLOCATED. 
A second solution would be to hold the state of the node resource as something like PARTIALLY_ALLOCATED, when at least one of the cores is busy and not all cores have been allocated. When considering other scheduling aspects, I am not sure if its useful or only adds some complexity. But for the resource movements in dynamic scheduling, it certainly makes some checks a lot easier.

**Comment by dongahn** [comment]
@surajpkn: You are right. `resrc` currently supports only exclusive scheduling at the node level. However, RFC 4 requires that our resource model should ultimately support both shared and exclusive scheduling at any level. So this probably is a good time to think about right mechanisms. 

I am curious about types of optimization that PARTIALLY_ALLOCATED can provide for dynamic scheduling? What would be these faster checks that an intermediate state like this can provide (in comparison to the binary IDLE-ALLOCATED classification)?

Also, in terms of priority, how much is your research blocked or affected by the absence of shared scheduling  support at the moment?

**Comment by surajpkn** [comment]
Basically, if space-shared scheduling is NOT enabled, then the problem and the logic becomes absolutely simple. If a node is ALLOCATED, at least one of its cores are ALLOCATED. If it is IDLE, then all of the cores are available. Therefore, to move the resources around, it is sufficient to only check the state of the node and move the whole branch when it is IDLE. 
If space-shared scheduling is enabled, it is possible that a parent uses some of the cores of a node and dynamically distributes the other cores (or submits as slack). Similarly, during an invalidation, an instance should be able to return some of the cores that are IDLE while and wait till the others are released before returning them. Here, you can get rid of the branch from the main resrc_tree only when the node is IDLE and all of its cores are IDLE as well. Thus, one would have to check the states all the cores of a node. Thus, a PARTIALLY_ALLOCATED state says a lot in one check. 

Due to the absence of a solution in #85, I am using a hash table of (uuid, resrc pointer) to speedup multiple operations (which we discussed in one of the meetings). As a result of this I will be checking resources out of (tree) order in various operations and therefore it is not straightforward to identify there if a resource and its branch is ready to be gotten rid off. A PARTIALLY_ALLOCATED state can help there. I am not saying that PARTIALLY_ALLOCATED is the right way to go. If it can help other aspects as well, then it is worth considering. Probably when we have a solution for #85, it wouldn't be required at all. 

In fact, I am still not sure if space-shared dynamic scheduling makes sense. Resource utilization and processors with large number of cores is a motivation. On the other hand, I am not sure if how much of complexity it will add also the flux-core with having to deal with brokers correctly (which of course we are not considering at this stage). 

Nevertheless, it doesn't affect my progress too much. I am trying to implement operations related to this in ways without unreasonable overhead or code complexity.

**Comment by dongahn** [comment]
@surajpkn: Sorry about not having a solution for #85 in time and having you implement the hash table... 

Though you have already implemented your own solution, could you please make an effort to capture the ideal query abstraction for you in #85 at your convenience? Would an ability to iterate through the flat list of `resrc` objects be giving you satisfying performance? Are there better performant query types? The reason I'm asking this is, as part of working on rudimentary task-mapping logic, I also plan to identify these needed abstractions (e.g., get me all of the resources of the same type) and capture them in #85, and I think it would be best to put as many needed patterns in there as possible. 

As to PARTIALLY_ALLOCATED vs IDLE-ALLOCATED, I have to think we want to use PARTIALLY_ALLOCATED as a short term solution. @lipari @SteVwonder ?

But for the longer term, dynamic scheduling might also be an area where keeping at the parent level some up-to-date aggregates on all of the resources under it can come in handy? Initially, @grondo's RDL has an aggregate method that would allow you to aggregate all of the available resources under a resource. IMO, this is a really cool concept but the performance of doing this every time could dilute its benefit. At one point, we discussed some ways to provide a cheaper and more systematic way to track these aggregates by having the scheduler update the aggregates in a transactional manner. Perhaps we should generate more discussion on this concept?

**Comment by lipari** [comment]
> As to PARTIALLY_ALLOCATED vs IDLE-ALLOCATED, I have to think we want to use PARTIALLY_ALLOCATED as a short term solution. @lipari @SteVwonder ?

The problem stems from the early decision to track the resource's state and use that state to steer the code.  With the enhancements we have made along the way, a single state is no longer adequate to capture a resource's state of allocation.  In the changes I'm working on to extract the backfill scheduling from the sched framework, I'm playing with different alternatives to the using the resource state to convey availability.  This is all in flux so to speak, so I haven't decided on a solution that I can share with you just yet.

**Comment by surajpkn** [comment]
@lipari It just came to my mind that as soon as we enable space-shared scheduling, nodes/sockets can have overlapping reservations, while cores cannot. So the walltime_match() needs to be called in only when considering a core resource. I wanted to mention that just in case you had not thought of it yet.

**Comment by lipari** [comment]
> @lipari It just came to my mind that as soon as we enable space-shared scheduling, nodes/sockets can have overlapping reservations, while cores cannot. So the walltime_match() needs to be called in only when considering a core resource. I wanted to mention that just in case you had not thought of it yet.

I'd like to strive for the goal of having the resrc code not have any type-specific conditions.  The current checks for "node" and "core" types are training wheels in my opinion.  I'd like to see them eliminated once an elegant, generic solution can be designed.

In the end, we may always need to have special treatment for nodes and cores, but at this point, I'm not will to concede that requirement.

In understand your research requires jobs to share node and core resources in order for you to evaluate the merits of the various resource migration scenarios you have proposed.  So, for the time being, we can make the resrc code as versatile as needed to support your work.  But, long term, simplicity and "generic-ness" is the goal.

**Comment by lipari** [comment]
I have expanded on the requirements stated in this PR and created a new [Issue 101](https://github.com/flux-framework/flux-sched/issues/101) which includes the partial allocation requirements discussed above as well as the need to support requests for shared or exclusive access.  Closing this Issue.
