### ISSUE TITLE
Integer overflow in jobspec parsing

### ISSUE THREAD

**Issue by jameshcorbett** [flux-framework/flux-sched#896]
@dongahn and I found that when a jobspec has an integer field with a value too large, it causes an error:

```
2021-12-13T22:10:44.607004Z sched-fluxion-qmanager.err[0]: jobmanager_alloc_cb: ENOSYS: yaml-cpp: error at line 1, column 197: bad conversion: Function not implemented
```

I ran into the error by specifying Rabbit storage sizes in bytes. An easy-enough workaround is to specify storage sizes in some larger unit instead.

**Comment by dongahn** [comment]
Thanks. We should add an range check into our jobspec parser

**Comment by dongahn** [comment]
At least how `qmanager` handles the parse error from Jobspec has been improved by PR #652
