### ISSUE TITLE
R is pretty big

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-sched#898]
Not a bug per se, but our sys admins have expressed concern that R is going to be _huge_ for a big cluster.  I guess it remains to be seen what problems, if any, this causes.

The one for fluke (128-ish nodes) is already pretty big
```
[root@fluke1:flux]# wc /etc/flux/system/R
     1  17215 160563 /etc/flux/system/R
```

I couldn't remember whether we have a plan to relax the requirement for JGF in the scheduling key, such as when it adds no additional information.  Without it, R can quite compact, e.g. 4096 homogeneous nodes in
```json
{
  "version": 1,
  "execution": {
    "R_lite": [
      {
        "rank": "0-4095",
        "children": {
          "gpu": "0-15",
          "core": "0-127"
        }
      }
    ],
    "starttime": 0,
    "expiration": 0,
    "nodelist": [
      "foo[0-4095]"
    ]
  }
}
```

**Comment by dongahn** [comment]
This can be a problem at some point but not immediately. We have tested this at the full scale of Summit with 4K nodes as well as emulated environment. Having said that, I mention this is an area to improve. Also by the time we will have rlite reader, the JGF in the system instance won't be required. (though this may not solve the problem with El Cap).

**Comment by grondo** [comment]
I think the sysadmins are more concerned about maintaining such a large file in their configuration management software. However, we've proposed that perhaps the `R` can be amended at deployment with `flux ion-R`, though I'm sure they'll appreciate when JFG in system instance isn't required (maybe that is the main ask in this issue, when will Rlite reader be available for Fluxion?)

**Comment by dongahn** [comment]
>when will Rlite reader be available for Fluxion?

Subject to my  perennial lack of engineering time. 

I will see if I can recruit someone else to do this -- should be pretty straightforward.

**Comment by dongahn** [comment]
Once the PR mentioned in https://github.com/flux-framework/flux-sched/issues/868#issuecomment-1068669617 lands, this problem will be solved.

**Comment by garlick** [comment]
Thanks for making time for this work @dongahn - I know you are very busy.  I think it means we can get rid of the XML "reduction" in flux-core too, which has always bugged me since we already convert hwloc to Rv1 on each node and reduce that at much lower cost when dynamically discovering resources.

**Comment by dongahn** [comment]
This is a good feature to have and I have meant to tackle that since Nov last year. Thank you for being patient with me!
