### ISSUE TITLE
Need a CI coverage for more recent versions GCC

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-sched#903]
GCC11 would be a good target, for example, per https://github.com/flux-framework/flux-sched/pull/902#issuecomment-1024960275.

**Comment by garlick** [comment]
The flux-core fedora34 builder runs with gcc11.  Maybe we can bring that over.

**Comment by dongahn** [comment]
Oh great point!

**Comment by grondo** [comment]
Fixed by #905

**Comment by dongahn** [comment]
Thank you @grondo !
