### ISSUE TITLE
flux-sched-0.21.0.tar.gz is missing a file

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-sched#914]
The file `doc/man5/flux-config-sched-fluxion-resource.rst` is missing from the `flux-sched-0.21.0.tar.gz` tarball because of a missing line continuation character in `doc/Makefile.am`.

We may need to generate a new tag to be able to build RPMs.

**Comment by dongahn** [comment]
Ugg. Will work on that. Would 0.21.1 work?

**Comment by grondo** [comment]
BTW, I'm not sure why `make distcheck` didn't catch this. (seems like it should  have?)

**Comment by grondo** [comment]
I have a PR ready to go I'll push in a moment. Yeah a `0.21.1` will work fine
