### ISSUE TITLE
Resource discovery on El Cap systems

### ISSUE THREAD

**Issue by jameshcorbett** [flux-framework/flux-sched#919]
On El Cap systems we will need a way to encode resource and scheduling information that also includes DWS rabbit information. From DWS we can get a list of compute nodes and rabbits, and their connectivity (which rabbits are on the same rack as which compute nodes). But we can't get CPU/GPU information about the compute nodes. So we will need to figure out how to reconcile the R from something like `flux ion-R encode` with the R that would be produced by polling DWS.

**Comment by jameshcorbett** [comment]
> I don't know enough to be certain, but it sounds like the DWS resources will have to go in the JGF representation under the Rv1 .scheduling key in Rv1, since R_lite doesn't have the capability to encode resource information for off-node resources at this time.
> 
> If so, then we might want to move this issue over to the flux-sched repo, as it will need a flux ion-R or JGF specific solution (flux-core treats the Rv1 scheduling key as opaque data).

Yeah, you're right. Moved.

[There is a Python script in flux-coral2](https://github.com/flux-framework/flux-coral2/blob/master/src/cmd/flux-dws2jgf.py) that will read DWS and produce R-lite+JGF, so it goes around both `R encode` and `ion-R encode`. But I think it does make sense to take basic R information (compute nodes, cores, gpus), let `ion-R` make its JGF, and then add the rabbit information on top of that. If it could really be done in discrete steps like that, it would be pretty straightforward.

**Comment by dongahn** [comment]
@grondo and @jameshcorbett: 

A first step could be: see what it takes to merge the `flux R encode ...` configured RV1 (no sched) object with the JGF object from DW in the first place.

The info from RV1 nosched object and DW JGF object intersects but one is not a subset of another. The RV1 nosched object has flux rank info which the DW JGF does not have. The DW JGF has richer resource type (multi-tiered storage) info that the RV1 no sched object does not have. 

But the info from either source must be consolidated, and one of the "keys" to make this possible would be the node name. So a potentially first $5 experiment could be have a prototype to 1) verify essentially an RV1 no sched object == DWF JGF object and to 2) merge them into full RV1 object? 

In terms of how this should be done. I would first learn if this can be done with a simplest prototype and then learn gaps. Once a prototype gives us a good level of confidence, I would then map out a "production" solution.

**Comment by jameshcorbett** [comment]
Closing this as I think we have a working solution.
