### ISSUE TITLE
flux-sched does not compile when ENABLE_TIMER_EVENT is switched on

### ISSUE THREAD

**Issue by surajpkn** [flux-framework/flux-sched#93]
When ENABLE_TIMER_EVENT is 1, the code doesn't compile because:

It can't find SCHED_INTERVAL macro which is actually defined in simulator/scheduler.h. Including this file in schedsrv.c or .h introduces too many errors (I guess this is the alternate scheduler implementation of @SteVwonder which must not be mixed with the original scheduler).

After moving SCHED_INTERVAL to simulator/simulator.h, it still breaks because of the following
`error: 'ssrvctx_t' has no member named 'run_schedule_loop'`

**Comment by dongahn** [comment]
@surajpkn: Just as a warning, ENABLE_TIMER_EVENT was a placeholder to enable timer-based scheduler loop in addition to job/resource event-based scheduling.  Now, it seems this particular error can be addressed by using schedule_loops? @SteVwonder can weigh in.

**Comment by dongahn** [comment]
Looking at the code, yes it does seem like `handle_timer_queue ()` needs to be ported.

**Comment by surajpkn** [comment]
I use the timer event for the detecting the slack state. If the could also comment out the simulation-related code and use it only for my purposes for the moment.

**Comment by dongahn** [comment]
@surajpkn and @SteVwonder: from the last concall, this shouldn't be a problem any longer. Should we close this?

**Comment by surajpkn** [comment]
It is not a problem for me anymore since I comment out the whole code there anyway (since I use a separate timer module). If I recall right, I think others don't see it because no one really uses this macro. and the code under it still needs to be ported correctly. But @SteVwonder should confirm this.

**Comment by SteVwonder** [comment]
This might still be an issue, but the solution should be to just remove the code in the ifdef since the simulator doesn't really support timers right now (suraj's version does though).
