### ISSUE TITLE
Q: use of lwj.next-id by flux-sched/simulator

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-sched#94]
It doesn't appear that anything in flux-sched still depends on `lwj.next-id` as it is currently used by wreck's job module as storage for the next identifier to use for a job. I was considering removing this key for a builtin sequence number in job module, but I do notice the simluator at least installs a watch on this key. Since we have wrexec events working now, does any part of sched still depend on this key, and if so could that easily be migrated? If not, it is no big deal to keep next-id up to date.

**Comment by dongahn** [comment]
I believe we migrated to the eventing by incorporating that into JSC. If the simulator installs a watch, that should be replaced with JSC.

**Comment by lipari** [comment]
Closed with the merging of [PR 95](https://github.com/flux-framework/flux-sched/pull/95)
