### ISSUE TITLE
Rename HLAPI to REAPI throughout resource

### ISSUE THREAD

**Issue by tpatki** [flux-framework/flux-sched#977]
(After discussion with @milroy and @JaeseungYeom). 

Currently, there is a `resource/hlapi` folder which probably should be renamed to `resource/reapi`. 

Not sure what the initial motivation of HLAPI vs REAPI was, but in the current codebase, everything seems to be called `reapi`, except the aforementioned directory which is named `hlapi`. @grondo @trws do you recall why the naming scheme was such? It seems confusing.

Note that the `resource/hlapi` directory contains the c/c++ bindings for `reapi`, and all other references in the code, eg in `qmanager` also use `reapi`.

**Comment by trws** [comment]
I do not, but that sounds like a worthwhile refactor, mind making the move and popping up a PR?

**Comment by tpatki** [comment]
Yes, certainly -- wanted to check if there was anything I may have missed here before I make the relevant changes.

**Comment by tpatki** [comment]
Closed with #983
